### PR TITLE
add aws-scala-sbt template for scala lambdas

### PR DESCRIPTION
**Pull request by meagonqz**
## What did you implement:

***Implementing Issue:*** #2217

## How did you implement it:

Utilized the existing code for templates to create a new `aws_scala_sbt` template. 
Added a Hello World example in Scala along with a basic sbt setup. The sbt build is run by the command `sbt assembly`. 
Updated tests and `docker-compose.yml`. 

## How can we verify it:

Updated tests seem to cover this. 
Let me know if I should update the [Create docs](https://github.com/serverless/serverless/blob/master/docs/03-cli-reference/01-create.md) or any others.

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by flomotlik** [comment]
@meagonqz Thanks for contributing this! I just ran this on my local system and the following issue happens:

```
/app/build.sbt:3: error: not found: object sbtrelease
import sbtrelease.Version
       ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? r
/app/build.sbt:3: error: not found: object sbtrelease
import sbtrelease.Version
       ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
[warn] Ignoring load failure: no project loaded.
[error] Not a valid command: assembly
[error] assembly
[error]         ^
```

Any idea why that might happen? Just ran the template integration test script.

**Comment by meagonqz** [comment]
@flomotlik The commit was missing a directory, fixed that. I re-ran the integration tests in a clean repo, you shouldn't have any problems now.

I noticed one of the travis builds hits a timeout error but that seems to be covered by https://github.com/serverless/serverless/issues/2225

**Comment by adrianmaurer** [comment]
Thanks @meagonqz I was starting to do this too. This is great!

**Comment by flomotlik** [comment]
Great Stuff, thanks again @meagonqz for contributing!

**Pull request merged**
