### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by matthieupinte**
Update `tutorial.md` "Adding endpoint" for `createCustomer`.

### CODE REVIEW

**Comment by mnapoli** [comment]
@matthieupinte could you explain the change? I don't see how that would make sense with the text of the tutorial.

**Comment by matthieupinte** [comment]
In the tutorial, the step it's to define the endpoint for the `createCustomer` function:
> _In your `serverless.yml`, paste the following block within the **functions** block:_

but you just copy/pasted the code sample corresponding to the the section "**Setting function permissions**".

This fix it's just the sample to be copy/pasted for the section "**Adding the endpoint**".

---

**_Before_**:

## Setting function permissions

[...]

```yaml
provider:
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - ...
```

## Adding the endpoint

[...]

```yaml
provider:
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - ...
```

---

**_After_**

## Setting function permissions

[...]

```yaml
provider:
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - ...
```

## Adding the endpoint

[...]

```yaml
createCustomer:
  handler: createCustomer.createCustomer
  events:
    - httpApi:
        path: /
        method: post
```

**Comment by mnapoli** [comment]
Ohh my bad, awesome, thanks for fixing that 👍 

I'll merge once the build passes.

**Comment by rallytime** [comment]
@mnapoli Can you merge this PR? I was about to make the same change because I also was confused in the tutorial, but decided to check the PR list first. 😄 

Thanks @matthieupinte for submitting this!

**Pull request merged**
