### PR TITLE
add support for lambda env vars in invoke local

### PR DESCRIPTION
**Pull request by eahefnawy**
## What did you implement:

Add support for lambda env vars in invoke local. Any env vars that you set in `serverless.yml` will be available when you run `sls invoke local` without having to load them manually.

## How did you implement it:
Added a new `loadEnvVars()` method to invoke local that runs before running the function.

#### serverless.yml
```yml
service: serverless-local-env-vars

provider:
  name: aws
  cfLogs: true
  environment:
    hello: world

functions:
  hello:
    environment:
      hello2: world2
      hello: worldOverwritten
    handler: handler.hello
```
#### handler.js:
```js
module.exports.hello = (event, context, callback) => {
  console.log(process.env.hello)
  console.log(process.env.hello2)
  const body = {
    message: 'Go Serverless v1.0! Your function executed successfully!',
    input: event,
  };

  const response = {
    statusCode: 200,
    headers: {
      'custom-header': 'Custom header value',
    },
    body: JSON.stringify(event),
  };

  return  callback(null, event);
};
```

run `serverless invoke local -f hello` and see the env vars values in the console

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by nikgraf** [comment]
Reviewing now …

**Comment by nikgraf** [comment]
@eahefnawy just tested it with new examples and works like a charm

**Comment by jeremydaly** [comment]
I have ARNs from Cloudformation outputs populating my environment variables in my Serverless.yml config. Running `invoke local` loads the environment variable, but populates it with the static JSON instead of the correct output.

```
  environment:
    NOTIFICATION_TOPIC: { "Ref": "notifications" }
```

**Comment by pmuens** [comment]
@jeremydaly thanks for reporting 👍 

Could you open up a new issue for that?

/cc @eahefnawy

**Comment by mrowles** [comment]
Lovely work :)

**Pull request merged**
