### PR TITLE
remove temp var `twoWayPassed`

### PR DESCRIPTION
**Pull request by sleepwithcoffee**
related discussion https://github.com/serverless/serverless/pull/11841#discussion_r1142913677

#8368 
#11841

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
@sleepwithcoffee Thanks for looking into that.

Have you run the tests few times to confirm issue doesn't get back?

**Comment by sleepwithcoffee** [comment]
Hi @medikoo I ran `npm run test` several times in my local and did not get any issues

**Comment by medikoo** [comment]
@sleepwithcoffee this is a change in integration tests which are not run via `npm run test`.

See https://github.com/serverless/serverless/tree/main/test#aws-integration-tests on how to run integration tests

**Comment by sleepwithcoffee** [comment]
I setup a simple bash script to run multiple tests
```
for i in {1..10}; do
    npx mocha test/integration/aws/websocket.test.js > output$i.log &
done
```
all tests are passed

**Review by medikoo — APPROVED** [review]
Thank you 👍

Let's see if we get failures again

**Pull request merged**
