### PR TITLE
Add IoT event source

### LINKED ISSUE #1409: Add support for more AWS events
- [x] SNS (#1476 / #1499)
- [x] Streams (e.g. Kinesis and DynamoDB) (#1608 / #1441)
- [ ] SES (#3401)
- [x] Cognito (#3400)
- [x] CloudWatch logs (#3399)
- [x] CloudWatch events (#3102)
- [x] Alexa Skills Kit (#2875 / #1525)
- [x] Alexa Smart Home (#3955)
- [x] IoT (#2954)

Overview of available events for lambda:
http://docs.aws.amazon.com/lambda/latest/dg/invoking-lambda-function.html

### PR DESCRIPTION
**Pull request by horike37**
## What did you implement:

Refs #1409

## How did you implement it:
A Lambda function  is called by a rule of AWS IoT.

## How can we verify it:
Please setting in serverless.yml as follow, then go `sls deploy`
```yml
events:
  - iot:
      name: 'myIotEvent1' 
      rule:
        sql: "SELECT * FROM 'some_topic'"
        enabled: true
        description: 'my iot event description'
        sqlVersion: 'beta'
```

deployed a rule of AWS IoT and attached a Lambda function

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by pmuens** [comment]
Awesome @horike37!!! 💯 🎉 

Thank you very much for this great addition! We'll look into it the upcoming days!

**Comment by worldsoup** [comment]
hey @horike37 you've been making awesome contributions to the framework and we'd love to invite you to our VIP slack room! It's basically just a place where our most active contributors chat and discuss things serverless. Send me your email and I'll get you the invite! nick@serverless.com

**Comment by ac360** [comment]
@horike37 You are incredible.  We all really appreciate your help :)  Well done!!!

**Comment by horike37** [comment]
@pmuens 
Thank you for reviwing!!!

>can one named iot event have multiple rules?
No.

https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-iot-topicrule.html
one named iot event have one rule!

I think `after ` pattren is best! I will fix, send PR.

@ac360
Thank you! I happy to contribute the greate project very much!!
I love open source!!!

**Comment by pmuens** [comment]
Thanks you for the clarification @horike37 👍 That sounds good.

And thanks in advance for updating the PR. Really happy to have you in the community! 💯

**Comment by nikgraf** [comment]
@pmuens how did you handle it in the past? Should an integration test be part of this PR or fine to have it in a separate PR?

**Comment by pmuens** [comment]
@nikgraf we tried to add the integration tests to the PR if possible (but most of the time only if @eahefnawy or I did the implementation since it's sometimes too much work for contributors).

IMHO we could totally do this in a separate PR!

**Comment by horike37** [comment]
@pmuens 
Updated hierarical structure of events.
Check please. thx!

**Comment by horike37** [comment]
😄😄😄

**Comment by horike37** [comment]
How is reviewing?

**Comment by pmuens** [comment]
@horike37 thanks for pinging. Reviewing should be finished soon.

This will definitely make it in the v1.5 release 🎉

**Comment by nikgraf** [comment]
Soo good. Just reviewed and looks good to me 👍

**Comment by horike37** [comment]
@nikgraf @pmuens 
Thank you for the merge!

I think that it is necessary to implement the integration test as well, like the following, is it correct?
Https://github.com/serverless/serverless/tree/master/tests/integration/aws

If the correct, I will implement and send PR.

**Comment by pmuens** [comment]
Right! That would be really awesome @horike37 🙌 !

**Pull request merged**
