### PR TITLE
Stage variables

### PR DESCRIPTION
**Pull request by svdgraaf**
As discussed in https://github.com/serverless/serverless/issues/1455, we need some way to insert environment variables into the lambda functions.

This PR solves that by adding a `variables` section to `provider` in `serverless.yml`. I'm not sure if we want it in that location, but I'm open for suggestions :)

This will end up like so atm:

```yaml
provider:
  name: aws
  runtime: python2.7
  variables:
    foo: bar
    bar: foo
    Bucket: { "Ref": "ThumbnailBucket" }
```

This will then end up in the stage variables in ApiGateway:

screenshot 2016-09-07 14 28 25

Which will then be added to the event which is pushed to Lambda in `stageVariables`, eg: `event.stageVariables.foo` or `event.stageVariables.Bucket`.

### CODE REVIEW

**Comment by svdgraaf** [comment]
Come to think of it, perhaps we should move the `variables` to somewhere in the event, because it only applies to ApiG at the moment? So, something like:

```yaml
functions:
  screenshot:
    variables:
      foo: bar
      bar: foo
      Bucket: { "Ref": "ThumbnailBucket" }
    handler: handler.screenshot
    ...
```

**Comment by svdgraaf** [comment]
Hmmm, I've run into an issue with CF updates, let me investigate.

**Comment by svdgraaf** [comment]
Got it, working on a fix

**Comment by rowanu** [comment]
Yeah, probably don't want this to be API GW based implementation - how would functions without a HTTP event source use them? I think [Apex](http://apex.run/) does it in the function as well, so that feels like the right way to do it.

**Comment by svdgraaf** [comment]
@rowanu well, ofcourse you would always be able to inject your variables in that way. Serverless could even automate that for you.

ApiGateway just gives you the option of setting variables per Stage, which are very nice if you're using the gateway :) We could also move the variables into the http event, which would make a bit more sense:

```yaml
functions
  screenshot:
    handler: handler.screenshot
    events:
      - http:
        variables:
          foo: bar
          bar: foo
          bucket: { "Ref": "ThumbnailBucket" }
```

Which would put all the variables in the method variables for the stage.

**Comment by flomotlik** [comment]
@rowanu @svdgraaf we've got some plans on how to make data available inside of your functions. One of the most important features here is imho service discovery, so if you create a dynamoDB, or an RDS database as a custom resource you should be able to provide data about where it is to the function easily. More info on that coming in the future.

With that said I'm not sure if we need the APIG variables, are they a often used feature (aside from getting environment variables in functions to work)?

**Comment by svdgraaf** [comment]
@flomotlik allrighty. I use it mainly for discovery, so then we can close this PR.

Any idea on a timeline for the feature?

**Comment by flomotlik** [comment]
Not yet, but its a super important feature and preferably I'd like to release it yesterday :D

**Comment by svdgraaf** [comment]
@flomotlik if I can help out, let me know 👍

**Comment by rowanu** [comment]
FWIW APIGW variables are not often used (that I've seen) - they're too niche, I had forgotten they existed until this discussion.

Your example use-case (creating DDB tables and sharing the table name, etc) is exactly what I'm interested in. +1 for having it released yesterday 😜

**Comment by j0rd** [comment]
So I'm not crazy? 

Current behavior is to not pass my vars from serverless.env.yml to event.stageVariables  in my lambda functions?

Trying to port from v0.5 to v1, but seems to be missing said code to do so.

**Comment by flomotlik** [comment]
@j0rd no that functionality is currently not available. At the moment, if you want to hardcode something like keys its best to put them in a config file for now and push that configuration with your deployed artefact (and load it through some language library). I'll update the documentation to make this clear.

As soon as we can share updates on the next steps with Environment variable handling I'll update you guys!

**Comment by nicka** [comment]
@flomotlik Thanks for the update! As @svdgraaf already mentioned, I would love to help out and discuss about this topic. Don't want to add extra pressure here, but out team won't be able to move forward with `v1.x` until this is doable 😊

**Comment by flomotlik** [comment]
@nicka yup definitely super important feature. A workaround for the time until this is available would be using something like dotenv: https://www.npmjs.com/package/dotenv

Not ideal, but it should work for now until we've got something up and running.

**Pull request closed without merging**
