### PR TITLE
Command realignment

### PR DESCRIPTION
**Pull request by jwulf**
I rewrote the command line client using commop. I think it's a better match for JAWS than commander. It separates the code and configuration into JS and JSON - just like JAWS!

Also, more sophisticated commands and nesting of commands.

### CODE REVIEW

**Comment by jwulf** [comment]
Also fixes https://github.com/jaws-framework/JAWS/issues/204

**Comment by jwulf** [comment]
https://gist.github.com/ee7edc009d0681e0e5bf

**Comment by jwulf** [comment]
```
sitapati@MacBook-Air [~/workspace/BGL-JAWS/jaws-bgl/aws_modules] $ jaws help create
jaws create

Subcommands:
   endpoint   Create a new API Gateway endpoint.
   lambda  Create a new AWSM Lambda. Optionally create an API Gateway endpoint for it at the same time.
   project Create a new JAWS Project
   region  Create a new AWS Region configuration in this JAWS Project.
   stage   Create a new stage in this JAWS Project.
```
https://gist.github.com/0ac56d126729aaa2cf97

```
sitapati@MacBook-Air [~/workspace/BGL-JAWS/jaws-bgl/aws_modules] $ jaws help create endpoint
jaws create endpoint

Options:
   --endpoint, -e [string]          Create an API Gateway endpoint for this AWSM Lambda
   --name [string]                  Name for the newly created resource
   --package-manager, -p [string]   Specify a package manager to scaffold for publishing this AWSM Lambda
   --runtime, -R [string]           Runtime for this AWSM Lambda. Defaults to nodejs
```
https://gist.github.com/0937289dc6e85741c682

**Comment by jwulf** [comment]
```
sitapati@MacBook-Air [~/workspace/BGL-JAWS/jaws-bgl/aws_modules] $ jaws help create lambda
jaws create lambda

Options:
   --endpoint, -e [string]          Create an API Gateway endpoint for this AWSM Lambda
   --name [string]                  Name for the newly created resource
   --package-manager, -p [string]   Specify a package manager to scaffold for publishing this AWSM Lambda
   --runtime, -R [string]           Runtime for this AWSM Lambda. Defaults to nodejs
```
https://gist.github.com/33a7134db3fa5c76a02c

**Comment by jwulf** [comment]
Now with support for templates for your lambda function: 

```
sitapati@MacBook-Air [~/workspace/JAWS-Framework/JAWS] $ jaws help create lambda
jaws create lambda

Options:
   --endpoint, -e [string]          Create an API Gateway endpoint for this AWSM Lambda
   --name [string]                  Name for the newly created resource
   --package-manager, -p [string]   Specify a package manager to scaffold for publishing this AWSM Lambda
   --runtime, -R [string]           Runtime for this AWSM Lambda. Defaults to nodejs
   --template, -T [string]          The template to use for your new AWSM Lambda function
```

**Comment by ac360** [comment]
@jwulf Lots of interesting stuff here :)  Going to review it in the next 1-2 days while merging some of the smaller PRs first.  Thanks for your help, as always.  Really grateful to have you helping out.

**Comment by slajax** [comment]
I checked this out and tested it and it seems to work really well. I like the minimalist and clean cli output and definitely the addition of templates. Don't forget to update the PR after running `npm install --save commop && npm uninstall --save commander` so that dependencies are updated and checked in. This PR closes #221.

**Comment by jmpage** [comment]
@jwulf I really like this PR. Unfortunately, master diverged pretty significantly from it.

The contract of the CLI is changed with this PR. If something like this were to be merged, I think that it would make sense to increment the major revision of serverless with it; We wouldn't want to unexpectedly break anyone's buildscripts.

@ac360 I recommend closing this for now since master has diverged significantly, including the CLI. I think a discussion about using commop might be useful as well sometime in the future. If it makes sense to switch over, it could be added to the roadmap and @jwulf could reimplement if he feels up to it.

**Comment by ac360** [comment]
Thanks for the great work @jwulf.  But we have settled on our current pattern :)

**Pull request closed without merging**
