### PR TITLE
fix(Packaging): ensure that .env files are excluded from package

### PR DESCRIPTION
**Pull request by pgrzesik**
Ensures that all `.env` and `.env.{stage}` files are excluded from the packaged artficat.

Addresses: #8566

### CODE REVIEW

**Review by medikoo — APPROVED** [review]
Thank you @pgrzesik, looks great!

**Comment by mnapoli** [comment]
Hi, this change seem to have broken some projects deployed to Lambda: the `.env` file is no longer deployed.

See https://github.com/brefphp/bref/issues/826

Is a change like this breaking backward compatibility?

**Comment by pgrzesik** [comment]
Hello @mnapoli, thank you so much for reporting this. The intention of this PR was to address potential security issue when `.env` files with sensitive data are uploaded as a part of the package by a mistake, but I didn't realize that at the moment, it might be the expected behavior and some of the projects/use cases are relying on that, so it's definitely breaking backward compatibility. I will be addressing it shortly, sorry for inconvenience

**Comment by mnapoli** [comment]
@pgrzesik thanks a lot for the quick response!

**Pull request merged**
