### PR TITLE
Add tags to AWS APIGateway Stage

### LINKED ISSUE #4644: Support for tags in Amazon API Gateway
# This is a Feature Proposal

## Description

On AWS tags are commonly used for logically associating resources with each other and simplifying billing. Amazon's API Gateway stages support tags now 🎉 . However, those don't seem to be populated by Serverless yet:

image

Serverless already supports tags for Lambda functions as well as a stack-wide tags (`stackTags`). As an API Gateway stage can only have one set of tags I suggest to automatically assign the `stackTags` to the API Gateway stages during deployment.

### PR DESCRIPTION
**Pull request by exoego**
## What did you implement:

Closes #4644 

## How did you implement it:
Added a [`AWS::ApiGateway::Stage`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html) resource that add `Tags` to stage.

This also allow us to configure `TracingEnabled` (XRay for API Gateway), `CacheCluster***` and other properties in subsequent PRs.

## How can we verify it:

1. `npm install -g exoego/serverless#tagging-apigw`
1. `sls deploy` over
```yaml
provider:
  name: aws
  runtime: nodejs8.10
  stackTags:
    foo: bar
functions:
  hello:
    handler: handler.hello
    events:
      - http: GET /user
```
1. Verify that new stage `dev` is created and it has tags `foo: bar`.

## Todos:

- [x] Write tests
- [x] Write documentation (N/A ?)
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** COULD BE (API GW stage name is updated every deployment)

### CODE REVIEW

**Comment by exoego** [comment]
I was strugging with adding`StageDescription` to `Deployment`, since it seems that `StageDescription` cannot be attached to existing stage.

So I switched strategy to introduce `Stage` resouce.
As far as I tested, it can deploy and re-deploy finely if `service` are deployed from zero (a fresh stack).

However, it can not re-deploy over existing API Gateway deployed with older severless framework.
A following error occurs.
```
  Serverless Error ---------------------------------------
 
  An error occurred: ApiGatewayStage - dev already exists.
```
Once `sls remove`, then a deployment success.

Unless this fixed, new deployment after this PR will fail, which means breaking change.
Does anyone have idea to fix `STAGE already exists` error?

I will investigate recently-added `APIGatewayV2` resource to overcome this error.

**Comment by exoego** [comment]
@pmuens 
Understood 👍 
I will wait #5692 merge and then follow the design.

**Comment by pmuens** [comment]
> @pmuens
> Understood 👍
> I will wait #5692 merge and then follow the design.

Great! Thank you very much @exoego! 👍

**Comment by pmuens** [comment]
Hey @exoego just a quick update that we're facing the same issues you described in https://github.com/serverless/serverless/pull/5851#issuecomment-465377681 in https://github.com/serverless/serverless/pull/5692#issuecomment-470090311.

I just read the following you wrote:
> I will investigate recently-added APIGatewayV2 resource to overcome this error.

Have you already looked into this? This sounds like a good idea... Currently I'm trying to figure out what the actual difference between `APIGatewayV2` and `APIGateway` is 🤔.

**Comment by exoego** [comment]
@pmuens
Sorry, I did not give it a try yet.
I am super busy this and coming weeks, so hope you or someone research.

**Comment by pmuens** [comment]
> @pmuens
> Sorry, I did not give it a try yet.
> I am super busy this and coming weeks, so hope you or someone research.

Sounds good. No hurry here, just thought that you might've already gathered some data about this. I'll do some more research on this one in the upcoming days...

**Comment by pmuens** [comment]
Hey @exoego 👋

I just looked into this today and unfortunately no advanced settings are supported for `v2` resources right now. I wrote down my findings in https://github.com/serverless/serverless/pull/5692#issuecomment-472408394.

**Comment by exoego** [comment]
@pmuens 
I got an advice from AWS support.

Accroding to AWS, we can add a stage description to `AWS::ApiGateway::Deployment` only if the logical ID of the `AWS::ApiGateway::Deployment` is same as previous deployment.
To maintain logical ID between deployments, it is required to remove timestamp from `ApiGatewayDeploymentLogicalId`.
However, such fixed `ApiGatewayDeploymentLogicalId` will conflict with an existing one with timestamp suffix throwing `ApiGatewayDeployment - StageDescription cannot be specified when stage referenced by StageName already exists.` error,  which means a breaking change.

**Comment by exoego** [comment]
@pmuens 
I got an advice from AWS support.

CloudFormation does not allow to deploy `AWS::ApiGateway::Stage` which name is already used in other stages.
So we should create fresh stage name everytime if we use `AWS::ApiGateway::Stage` to configure API gateway.

Another option is to add `StageDescription` field to `AWS::ApiGateway::Deployment`.
However, to use `StageDescription`, the logical id of `AWS::ApiGateway::Deployment` should be same between deployments. (I was [working on this concept in this branch](https://github.com/exoego/serverless/blob/7fa3d683aa41d2df4225b728c8ee59e0f57deaa8/lib/plugins/aws/package/compile/events/apiGateway/lib/stageDescription.js))
Currently the logica id have a timestamp suffix.
Changing the logical id causes a breaking change.
So this option cannot be an alternative until serverless framework `v2`.

**Comment by pmuens** [comment]
Great! Thanks for getting back @exoego 👍

Yes, I'd also vote for a consistent stage name. So the only option is to use the `StageDescription` resource which I'd prefer. The only problem is that we need to add a random id to force AWS to re-deploy the API Gateway. We faced some serious issues back then when we implemented the initial version of the `http` event source and AWS said that appending a random id to the `Deployment` resource should mitigate this problem.

This was 3 years ago. Maybe it has been fixed in the meantime? We could try that our and if so we could get rid of the random id in the `Deployment` resource logical id which would make this feature and x-ray tracing for API Gateway possible.

I'll try some tests and remove the random id to see if this issue has been fixed on AWS end. I'll comment here once I know more...

/cc @eahefnawy

**Comment by exoego** [comment]
Updated the PR based on #5692 (X-Ray supprot)

**Pull request merged**
