### PR TITLE
Updates tests to run on Windows, plus Appveyor CI

### PR DESCRIPTION
**Pull request by lorengordon**
## What did you implement:

* Updates the tests to pass on Windows
* Includes a config file for running CI tests on Windows, via [Appveyor](https://www.appveyor.com/)

## How did you implement it:

* Adjusted the test command in `package.json` to use double quotes rather than single quotes, as single quotes result in an error on Windows
* Created an `.appveyor.yml` config file that runs `npm test` in nodejs 4 and 6
* Ran the tests and corrected the failures until the tests passed

## How can we verify it:

- https://ci.appveyor.com/project/plus3it/serverless

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by lorengordon** [comment]
So, any thoughts here? I have to keep cherry-picking this work into other branches to get tests to run. :(

**Comment by pmuens** [comment]
> So, any thoughts here? I have to keep cherry-picking this work into other branches to get tests to run. :(

Sorry for not following up here @lorengordon. That you very much for working on this PR! We got in on our radar and will review it ASAP!

Generally speaking it's a super valuable addition and we should merge and set this up ASAP 💪 👍

**Comment by lorengordon** [comment]
@pmuens Ok, sounds good, thanks!

**Comment by lorengordon** [comment]
@pmuens Ahhh, so that last edit to the test command fails on Windows. Can't set the env like that... 😢

**Comment by lorengordon** [comment]
Oh wait, it seems to have ignored that. It's just new tests that are failing on Windows. Lol

**Comment by lorengordon** [comment]
https://ci.appveyor.com/project/plus3it/serverless/build/1.0.19

**Comment by lorengordon** [comment]
Ahh, I see, using `os.EOL` in emit/index.js, but just `\n` in the tests. I'll see if I can get that working.

**Comment by pmuens** [comment]
Shoot. Thanks for jumping in and fixing @lorengordon 👍

**Pull request merged**
