### PR TITLE
feat(Templates): Switch from serverless-webpack to serverless-esbuild in `aws-nodejs-typescript`

### PR DESCRIPTION
**Pull request by adriencaccia**
This PR switched from `serverless-webpack` to [`serverless-esbuild`](https://github.com/floydspace/serverless-esbuild) to handle lambdas packaging.

The gains are:
- blazing fast packaging time
- much less configuration

### CODE REVIEW

**Review by mnapoli — DISMISSED** [review]
Looks simpler as well!

**Review by medikoo — CHANGES_REQUESTED** [review]
@adriencaccia Great thanks for this improvement! 

We'll be happy to take it, still, it seems to require an update in tests (I believe it's due to changes to generated result) - see CI fail

**Comment by adriencaccia** [comment]
> @adriencaccia Great thanks for this improvement!
> 
> We'll be happy to take it, still, it seems to require an update in tests (I believe it's due to changes to generated result) - see CI fail

I fixed the failing test :slightly_smiling_face:

**Review by medikoo — APPROVED** [review]
Thank you @adriencaccia !

**Comment by doodlemoonch** [comment]
Thanks @adriencaccia

**Pull request merged**
