### PR TITLE
refactor: Use `async` in `lib/plugins/plugin`

### PR DESCRIPTION
**Pull request by nyamba**
configuring functions as async, folder `lib/plugins/plugin`

issue: #8368

### CODE REVIEW

**Comment by pgrzesik** [comment]
Thanks a lot @nyamba :bow: It looks like one of the tests is failing - could you please look into that?

**Comment by nyamba** [comment]
Hello @pgrzesik,  it looks that test is tailing for validate function `lib/plugins/plugin/utils.js #validate()`, because made it async then test couldn't catch the error.  Do we need to refactor test of it as well?

Screen Shot 2021-07-05 at 14 47 48

**Comment by pgrzesik** [comment]
Hello @nyamba - yes, it looks like in this situation the test will have to be refactored as well. One tricky part is that whenever adjusting old tests, we should instead replace them with the ones that are based on `runServerless` utility: https://github.com/serverless/serverless/blob/master/test/README.md

Please let me know if you'd like to tackle this - I'm also happy to provide more details on how it might look like.

**Comment by nyamba** [comment]
thanks @pgrzesik, let me try to refactor this test using the `runServerless`.

**Comment by pgrzesik** [comment]
> thanks @pgrzesik, let me try to refactor this test using the `runServerless`.

Thank you @nyamba :bow: Feel free to reach out if you have any questions :raised_hands:

**Comment by nyamba** [comment]
Hello @pgrzesik, I have changed the test as following
Screen Shot 2021-07-09 at 15 38 57

However it throws another exceptions which is made by `PluginManager` when there is no service director.
Screen Shot 2021-07-09 at 15 42 05

How to skip the PluginManager's exception to run the validate function? and I wonder is it really necessary to check the service directory in the validate function, since the PluginManager checks that?

**Comment by pgrzesik** [comment]
Hello @nyamba - `plugin install` command has to be executed in context of service, but in the mentioned example the `runServerless` is executed outside of service context. Instead of specifying `noService` option, let's use some basic `fixture` such as `function` for example.

**Comment by nyamba** [comment]
> Hello @nyamba - `plugin install` command has to be executed in context of service, but in the mentioned example the `runServerless` is executed outside of service context. Instead of specifying `noService` option, let's use some basic `fixture` such as `function` for example - it will ensure that the run will be executed in context of such service fixture

Sorry for misunderstanding, I'm trying to  refactor  the test which is  checking behavior of throwing an exception in  `validate` function using the `runServerless`. This function throws a `ServerlessError` when there is no service directory.

Screen Shot 2021-07-13 at 14 11 51

I think that if I use the fixture, the exception never will be raised. So I wonder how to refactor the test using runServerless?

**Comment by pgrzesik** [comment]
Hello @nyamba - could you maybe share the specific problematic piece of code? I'm struggling to understand the problem here so it's harder for me to help out, sorry about that. If we're testing succesfull run of `plugin install` then it has to be executed in context of service. In the other case, when running not in context of service, we should expected the error to be thrown - it might be a different one that is currently being assesed in tests. Maybe you could push the current code? It will allow me to better understand what is problematic here.

**Comment by nyamba** [comment]
Thank you @pgrzesik  for coordination. I've changed the code as you suggested. However the validate function doesn't running as expected, because before going into it, another function(PluginManager) throwing exception. Please see code in PR.

 I think that there is no chance to test the validate function with runserverless. If you know a way, please guide me to it. However without the Runserverless, I can extend the old test for async function.

**Comment by pgrzesik** [comment]
Hello @nyamba - I see what the problem is. The old `validate` test is very fragile and to be honest, I feel like at the moment it's testing a scenario that cannot really happen in real-world scenario as the validation already happens earlier (as you've experienced with different error). As it's only about `async` change, let's remove this test altogether and I'll make sure to check if we can drop whole `validate` util from plugin utils.

**Comment by nyamba** [comment]
I have removed the test case. @pgrzesik

**Review by pgrzesik — APPROVED** [review]
Thank you @nyamba :bow:

**Pull request merged**
