### PR TITLE
Added request cache and queue to AWS provider and use it from variable resolution

### LINKED ISSUE #3821: Rate exceeded
## Description

I have 8 times ${cf:..} in my serverless.yaml and I get 3 out of 5 times "Rate exceeded" while running serverless. I suppose I've reached a limit for cloudformation's API calls (DescribeStack for instance). Is there any chance to avoid this error except of increase my limits? Why doesn't serverless calls the api only once for all stacks? Or at least only once per stack? 

Last but not least: Which limit do I reach? I don't know which one mentiond on [aws limits](http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html)

For bug reports:
* What went wrong?
I run "serverless deploy -v" and I get an error "Rate exceeded"
* What did you expect should have happened?
deploying without that error
* What was the config you used?
```
custom:
  stage: ${cf:StackA.StagePrefix}
  vpcStackName: ${cf:StackA.VpcStackName}
  topicGeneral: ${cf:StackB.In}
  topicBs: ${cf:StackC.In}
  dnsName: ${cf:StackD.LoadBalancerDNSName}
  securityGroupIds: ${cf:StackD.AlbSecurityGroup}
  privateSubnet1: ${cf:StackE.PrivateSubnet1}
  privateSubnet2: ${cf:StackE.PrivateSubnet2}
```
* What stacktrace or error message from your provider did you see?
```
> sls package
 
  Serverless Error ---------------------------------------
 
     Rate exceeded
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       6.9.1
     Serverless Version: 1.14.0
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #3339

## Additional Data

* ***Serverless Framework Version you're using***: 1.14.0
* ***Operating System***: Fedora / Linux
* ***Stack Trace***: Rate exceeded
* ***Provider Error messages***:

### LINKED ISSUE #4466: Included file is parsed and its variables resolved on each variable reference
# This is a (Bug Report)

## Description
* What went wrong?
I use and include a file (conf.yml) to declares common variables.
One of those is resolved from CloudFormation ```(${cf:otherstack.ArtifactsBucket}```).

This file is referenced in a custom.conf variable.
```
custom:
  conf: ${file(conf.yml)}
```

When deploying, Cloudformation returns a "Rate exceeded" message.
Debugging the code, I can see that serverless is executing the lib/class/Variables.js.getValueFromCf on each reference to a ${self:custom.conf....} variable even if not the one using the CF reference.

For example
     - if my conf file contains 2 variables and only 1 variable ${cf:...}
     - if I reference those 2 vars in my serverless.yml, using the ${self:custom.conf.var} syntax
     - serverless will make 3 calls to the getValueFromCf function (always for the same variable) (1 call when referencing the file + 1 call for each variable ${self:custom.conf.var} resolution)
     - resulting in 3 calls to AWS describe-stacks.
     - In my real case, I use much more references to the conf file and so I reach a "Rate Exceeded" as the calls to describe-stacks are not cached and not serialized.

* What did you expect should have happened?
  1. Only one call to the getValueFromCf function.
  2. No "Rate Exceeded" error.

* What was the config you used?

serverless.yml :
```
service: prototype-sls-cfn-rate

custom:
  conf: ${file(conf.yml)}
  deploymentBucket: ${self:custom.conf.deploymentBucket}
  # following declarations might look stupid but just for showing the issue when referencing conf var
  var1: ${self:custom.conf.appBucket}1
  var2: ${self:custom.conf.appBucket}2
  ....
  # repeat until 'Rate Exceeded' limit is reached on deploy

provider:
  name: aws
  region: eu-west-1
  deploymentBucket: ${self:custom.conf.deploymentBucket}

resources:
  Resources:
    AppBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:custom.conf.appBucket}
```

conf.yml :
```
deploymentBucket: ${cf:otherstack.ArtifactsBucket}
appBucket: application-used-bucket
```
=> with this configuration getValueFromCf('cf:otherstack.ArtifactsBucket') is called 5 times.

* What stacktrace or error message from your provider did you see?
```
Serverless: Packaging service...
Serverless: Service files not changed. Skipping deployment...

  Serverless Error ---------------------------------------

  Rate exceeded

  Get Support --------------------------------------------
...
```

Similar or dependent issues:
* #3821
* #4136 (same symptom but maybe different cause)

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0 and 1.24.1
* ***Operating System***: Windows 7
* ***Stack Trace***: see above
* ***Provider Error messages***: see above

## Workaround
Never use ${cf:...} variable resolution in an included file.

## Potential Solutions
* Avoid included file resolution on each referenced variable 
* Use caching as proposed by @stevearoonie in : https://github.com/serverless/serverless/issues/3821#issuecomment-331022279
* Serializing calls won't be enough as too much calls would be done to CloudFormation

### PR DESCRIPTION
**Pull request by HyperBrain**
## What did you implement:

Closes #3821 
Closes #4466 

## How did you implement it:

Added an on-demand request cache to the AWS provider. The cache can be utilized and activated by adding a new last parameter to the `provider.request` method. It defaults to false to keep the current behavior and has to be enabled explicitly for locations that can use cached results.

The requests intiated from the variable system will set the cached flag to let the variable resolution request static info like the stack descriptions only once.

This PR complements #4499 which added the generic cache for the variable system. Together the fixes will eliminate the rate exceeded errors.

## How can we verify it:

Add lots of external variable references (e.g. `cf`, `ssm`, etc) to your serverless configuration that led to a rate exceeded error with 1.24.1. The deployment should now succeed when using this branch.

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by HyperBrain** [comment]
Have to adjust the unit tests. They fail, because they test for several invokes of the SSM API which is now cached.

**Comment by HyperBrain** [comment]
@e-e-e I changed the cache to the same semantics as used for the variable cache now (implicit promise queue). Now it should be safe against excessive request calls. Please double check.

**Comment by HyperBrain** [comment]
I added a specific unit tests to the provider tests, that does 1000 request calls in parallel and checks that all callers get the expected correct result, but the request is only sent out once. This works and proves that the implicit promise caching works.

**Comment by HyperBrain** [comment]
@e-e-e Now it uses a queue for all requests sent (and restricts the maximum parallel requests to 2 at a time) in combination with the result caching. So subsequent duplicate requests are cached, and all different requests eventually submitted are queued.

**Comment by HyperBrain** [comment]
Additionally did a dependency security check (to test for the new dependencies). No security issues have been found:
https://www.bithound.io/github/serverless/serverless/cache-AWS-requests/dependencies/npm#filter-insecure-dep

**Comment by e-e-e** [comment]
@HyperBrain nice work - this should solve the issue. 👍

**Comment by horike37** [comment]
Thank you for implementing @HyperBrain and following up @e-e-e :+1: :tada: 
For doing this test, I created serverless.yml has a lot of `S3:` variable references and tried the rate limit error occurs with sls current version at first, but I was not able to do that...

How did you guys use the yml file looks like?

**Comment by horike37** [comment]
FYI: @RafalWilinski 

Here is the yml file which the rate exceeded error occurs.
You might want to use if you were not able to reproduce it with your yml file.

serverless.yml
```
service: prototype-sls-cfn-rate

custom:
  conf: ${file(conf.yml)}
  deploymentBucket: ${self:custom.conf.deploymentBucket}
  var1: ${self:custom.conf.appBucket}1
  var2: ${self:custom.conf.appBucket}2
  var3: ${self:custom.conf.appBucket}3
  var4: ${self:custom.conf.appBucket}4
  var5: ${self:custom.conf.appBucket}5
  var6: ${self:custom.conf.appBucket}6
  var7: ${self:custom.conf.appBucket}7
  var8: ${self:custom.conf.appBucket}8
  var9: ${self:custom.conf.appBucket}9

provider:
  name: aws
  region: us-east-1
  deploymentBucket: ${self:custom.conf.deploymentBucket}

resources:
  Resources:
    AppBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:custom.conf.appBucket}
```

conf.yml
```
deploymentBucket: ${cf:anotherstack.ServerlessDeploymentBucketName}
appBucket: slsAppBucket
testtest: ${cf:anotherstack.HelloLambdaFunctionArn}
aa: ${cf:anotherstack.ServiceEndpoint}
```

**Comment by HyperBrain** [comment]
I'll squash the commits now, so that it does not pollute master with 8 commits :)

**Comment by RafalWilinski** [comment]
Thanks for providing steps to reproduce @horike37. I'll test it locally later today. From the code perspective, everything seems fine to me.

**Comment by HyperBrain** [comment]
I'll merge it now, so that I can rebase the circular vars branch again.

**Pull request merged**
