### PR TITLE
Don't load config for `config`

### PR DESCRIPTION
**Pull request by erikerikson**
## What did you implement:

Change the config command to not require loading of the `serverless.*` configuration file.

## Todos:

- [ ] Write tests
- [n/a] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by erikerikson** [comment]
This doesn't resolve the problem of #4597, though it is correct.

**Comment by erikerikson** [comment]
Happy to remove package lock.  Can do that in a bit.

I'm really unsure what tests would look like against this declaration or, really,  how much value it would provide.  Such tests seem more likely to be part of the [original addition]( https://github.com/serverless/serverless/pull/5298) of this flag.

**Comment by pmuens** [comment]
> Happy to remove package lock. Can do that in a bit.

> I'm really unsure what tests would look like against this declaration or, really, how much value it would provide. Such tests seem more likely to be part of the [original addition](https://github.com/serverless/serverless/pull/5298) of this flag.

Thanks for getting back @erikerikson 👍

I agree, that testing this doesn't really make sense here. I was not familiar with the overall functionality so I thought that I'll just bring this up. I jumped in real quick and removed the `package-lock.json` changes. Will merge once the build is green :shipit:

Thanks again for working on this 👌

**Comment by erikerikson** [comment]
Thanks for covering me on that!

**Pull request merged**
