### PR TITLE
Update stats to support CI systems

### PR DESCRIPTION
**Pull request by pmuens**
## What did you implement:

CI System support for stats.

***Implementing Issue:*** #2259 

## How did you implement it:

Add a check if the CI environment variable is set.

## How can we verify it:

Run the tests.

## Todos:

- [x] Provide verification config/commands/resources
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by pmuens** [comment]
Tested it with a simple `console.log` to see if the variable is set to `true` on Travis 😬 . Works as expected.

**Comment by flomotlik** [comment]
@pmuens we don't have tests for this right? In that case GTM, don't think we need to do super complicated testing here.

**Comment by pmuens** [comment]
Yes. I was also thinking about adding a test. But the tricky thing is `local test` vs. `CI test` which will make it complicated (as you mentioned).

**Pull request merged**
