### PR TITLE
Java runtime

### PR DESCRIPTION
**Pull request by hakandilek**
Please check out this PR for the basic Java support mentioned on #682.

With this PR it is possible to use 
 * Scaffold Java handlers
 * compile Java source code using Gradle
 * Perform local runs.

Building and uploading is still in progress.

### CODE REVIEW

**Comment by eahefnawy** [comment]
awesome @hakandilek! Thanks a lot! I think it's best if we keep it open for now and merge all once you finish up everything WIP.

Again, thanks for the efforts 😊

**Comment by flomotlik** [comment]
Thanks for this PR. If you'd be interested to spend some more time on this could we have a quick call next week to chat about ways we could implement Java support in Serverless, especially our upcoming Version 1.

One of the main issues is with setting it up in a way that is independent of any build tools. This PR combines Gradle deeply into the system, which we can't really do as we have to be tool agnostic. I'm also not too sure if we want integrate building the Java Assets into the framework, I'd rather have maven, gradle, ... build those artifacts and we just pick them up for you.

**Comment by hakandilek** [comment]
@eahefnawy sure, keep it open. I'm just putting commits here so that others can review and discuss.

@flomotlik yes a call next week would be good. I also have some points to clarify.

The problem is Java Runtime is different than JS or Python because you have to compile and (optionally) package (jar) sources before you can run them locally or deploy on Lambda. Easiest and simplest way is to use some build tool like Gradle, Maven etc. I used the Gradle Wrapper which does not need any local Gradle installation. It just needs a Java/JDK installation (which is essential) and pulls the rest from the net. Practically it is no different than npm.

IMHO as a user, biggest advantage of the Servless Framework is making AWS-Lambda simpler. As simple as  typing a single command for scaffolding, running or deploying a function. Introducing another build step, which is only specific to the Java Runtime, will just take away this advantage.

**Comment by flomotlik** [comment]
>IMHO as a user, biggest advantage of the Servless Framework is making AWS-Lambda simpler. As simple as typing a single command for scaffolding, running or deploying a function. Introducing another build step, which is only specific to the Java Runtime, will just take away this advantage.

Agreed, though in the Java world that is mostly only applicable to simple projects. Most companies are very well trained in their respective tools and we can't just it for them. And most java shops would be fine (in my assumption and talking to a few companies like that) with building and providing their assets for us to deploy. Sending you an email to chat next week.

**Comment by license2e** [comment]
@flomotlik I would be interested in setting up a call with you regarding on how to get Java implemented without exterior tool dependencies. I was able to get @hakandilek PR merged into my own repo (https://github.com/license2e/serverless/commits/master), but had to change the paths where the generator script created the Java files (we wanted them inside each function) as well as tweak the gradle build command to gather the relevant jars into the dist directory before the rest of the scripts zipped it up. 

The project I am currently working on depends on Java working correctly, and my task is to get Java working on Mac, Linux and most importantly Windows 7 at this point. 

I would like to get involved in helping push this forward, would you have some time?

**Comment by flomotlik** [comment]
@license2e absolutely. We've been working on our new V1 of the framework for a while and we're now starting to get to a point where this would be great to get started. Can you send me an email to florian@serverless.com?

**Comment by flomotlik** [comment]
@hakandilek we're currently working on Java support in #1553 and through our new template system it should be relatively easy to add Maven and Gradle tooling. #1246 also has more info on that. Would love to get your help on it if you're still up to it. I will close this PR in the meantime as its targeting 0.5

**Comment by hakandilek** [comment]
@flomotlik that sounds great. I'd love to help on that. How's the timeline? I might not be able to put my hands on it till end of next week.

**Comment by flomotlik** [comment]
We want to have it on by end of the month basically. Don't think its going to be that much work in general as we can stay pretty close to the AWS documentation examples.

**Pull request closed without merging**
