### PR TITLE
Fix: use normalized maps in zipService.js

### LINKED ISSUE #6704: zipService does not set executable flag correctly for golang binaries on Win32
# This is a Bug Report

## Description

- What went wrong?
The zipService on win32 does not correctly set the executable flag for golang binaries
- What did you expect should have happened?
executable flag is set

## Possible fix

Normalize both maps of files before comparison inside function `zipFiles`

Similar or dependent issues:

- #6482

### PR DESCRIPTION
**Pull request by noreabu**
The comparison inside zipFiles normalizes both maps before comparison

## What did you implement:

fix for executable flag for golang binaries on win32

Fixes #6704 

## How did you implement it:

Normalization of two maps of files before comparison

## How can we verify it:

Probably difficult as i suspect the culprits could be different shells on windows, using different path separators. Mostly git bash was used in our setup.

## Todos:

_**Note: Run `npm run test-ci` to run all validation checks on proposed changes**_

- [ ] Write tests and confirm existing functionality is not broken.  
       **Validate via `npm test`**
- [ ] Write documentation
- [ ] Ensure there are no lint errors.  
       **Validate via `npm run lint-updated`**  
       _Note: Some reported issues can be automatically fixed by running `npm run lint:fix`_
- [ ] Ensure introduced changes match Prettier formatting.  
       **Validate via `npm run prettier-check-updated`**  
       _Note: All reported issues can be automatically fixed by running `npm run prettify-updated`_
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

**_Is this ready for review?:_** NO  
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by noreabu** [comment]
Thanks! I need some time to work through the todos, but i'll be there eventually

**Comment by pmuens** [comment]
> Thanks! I need some time to work through the todos, but i'll be there eventually

Great! Let us know if you need any help here :+1:

**Comment by pmuens** [comment]
Hey @noreabu 👋

Just following-up if you have any update on this? Do you need any help here?

**Comment by pmuens** [comment]
Hey @noreabu I just wanted to check-in again and see if you've found some time to look into this PR.

I think we're pretty close and it would be nice if we could ship this fix with the upcoming release.

Let us know if we can assist you with anything here.

**Pull request merged**
