### PR TITLE
Preparation for multi provider support

### PR DESCRIPTION
**Pull request by pmuens**
## What did you implement:

Adds the `AwsProvider` plugin / class which wraps the SDK and makes it available for other plugins to use.

Furthermore a new `*.test.js` structure for tests is introduces (right now only the tests for the classes).

## How did you implement it:

Add the new `AwsProvider` plugin / class. Update the test names.

## Todos:

- [x] Add documentation
- [x] Write tests
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by flomotlik** [comment]
Cool, imho @eahefnawy should take a look and give feedback on this, but looks good

**Comment by pmuens** [comment]
@flomotlik @eahefnawy Two additional things about this PR:

1. The `awsProvider` plugin is in the main `plugins` directory as the next step would've been to flatten out the structure in plugins so that they`re all in the main `plugins` (like it's done here https://github.com/serverless/serverless/tree/fd1194f13e16a9ffe64987551a7adedd9ed6e16c/lib/plugins). This makes it easier to navigate around and easier to understand for external contributors
2. The PR introduces a new `<filename>.test.js` structure for tests (I started this for the main classes). This makes it easier to find the test at it lives near the file and we can use globs in our `package.json` command so that all the `*.test.js` files are automatically included to run the tests. This way we won't miss any tests in the future and can get rid of the `all.js` file.

**Comment by flomotlik** [comment]
Love the `*.test.js` stuff, not so sure about the flattening of the structure, because imho with more plugins it just makes the list a lot longer. Imho people who really want to contribute to such core items won't have that hard of a time finding things so I don't think it pushes back contributions, but it makes it a lot more crowded and the naming of the folders isn't nice any more because they contain multiple points of data (e.g. they are prefixed with the provider instead of putting it into a provider subfolder)

**Comment by pmuens** [comment]
For me a plugin is a directory with a descriptive name and the content related to that plugin inside of it. This directory should be moved around easily or even removed if not necessary.

Our current structure is way too nested. Before I start to write a line if code I have to rethink where I can find the corresponding file. One problem the current structure also enforces (and has already introduced) is that plugins are no longer independent but rather share code from other directories locations which is IMHO a no-go.

**Comment by eahefnawy** [comment]
👍  for the `*.test.js` convention. While I like the nested organization, one major fallback that I didnt think about initially is navigating on the repo Github. Because if I want to go deep I have to jump through multiple http requests and it takes forever. So I'm willing to switch to flat structure just for that since I tend to navigate on Github a lot.

Currently reviewing...

**Comment by flomotlik** [comment]
Imho when we add more events for example for each provider that we support it becomes a really long list again. We can certainly discuss about how many levels we're nesting, but I imho even adding prefixes into folder names already shows that things should be more nested to make it easier to find. Prefixes duplicate information that could be easily had circumstantial because its in the same subfolders.

**Comment by flomotlik** [comment]
Also @eahefnawy have you ever used the `t` shortcut. Much easier way to navigate by simply finding files or folders in the path (similar to Atom)

**Comment by eahefnawy** [comment]
@flomotlik I have, and it certainly helps. but I sometimes I simply want to navigate without specific thing to search for, especially during PR reviews.

**Comment by pmuens** [comment]
@eahefnawy thanks for the review. Yes, It's a class but in some way it's also a plugin. That's why it lives in the `plugins` directory. :-D (but mainly a class).

I get that the name / list might get long but IMHO that way you can directly see what plugins are available. Furthermore you can see that `invoke` is a core plugin and `awsInvoke` is the implementation for the invoke functionality for AWS.

Although I would vote for a structure with `aws` in the beginning of the file we could e.g. also introduce directories with the provider name (like we already have with `aws`) and then put all the plugins inside of those directories. But don't nest it any further.
So `aws/invoke` or `google/invoke`. But then we might also introduce `core` so that we have `code/invoke` and everything has the same level of dir-deepness and it's easy to navigate around / find the corresponding plugins.

**Comment by flomotlik** [comment]
@pmuens yup the provider->plugin makes sense imho. Easy to find and not a lot of duplicated info

**Comment by pmuens** [comment]
Alright. I'll do the refactoring of the structure in an upcoming PR so this PR is Ready to be merged from my side.

**Comment by flomotlik** [comment]
Cool, GTM

**Comment by eahefnawy** [comment]
this is simple but big change and it touches all files, need some more time to test just in case

**Comment by pmuens** [comment]
@eahefnawy alright 👍 . Let me know when it's GTM from your side

**Comment by eahefnawy** [comment]
@pmuens couldn't break it ... feel free to merge 😊

**Comment by pmuens** [comment]
Awesome! 🎉

**Pull request merged**
