### PR TITLE
Refactor for the CLI endpoints outputs

### PR DESCRIPTION
**Pull request by nicka**
##### Status:

Ready

##### Description:

**The CLI output behaviour is still the same.**  Difference is that this PR exposes only one single API gateway endpoint through the CloudFormation outputs named `ServiceEndpoint`. It loops through the functions array to setup the paths(with the `ServiceEndpoint`) for the CLI output.

**Why?** CloudFormation has a limit of 60 outputs per stack, less outputs by the framework is more outputs for the user. It's also common to expose one single endpoint for a service. 

My personal believe is that the existing outputs where only formatted this way to nicely display all your paths from the CLI output. But the Output value's itself weren't very usable because of the value `> GET - https://foo`. Our common use case is to use the `ServiceEndpoint` output to connect stacks together. Example: A CloudFormation stack which only contains a CloudFront distribution with multiple origins to each `ServiceEndpoint`.

##### Todos:

- [x] Write tests

### CODE REVIEW

**Comment by pmuens** [comment]
Nice one @nicka 🎉 
Really like this PR as it prevents problems if one has too many outputs.

Could you maybe look through the docs and update them (e.g. the example in the `README.md` file in `lib/plugins/info`).

Great work! 👍

**Comment by nicka** [comment]
@pmuens Thanks! Updated the `README.md`'s 🎉

**Comment by pmuens** [comment]
@nicka awesome! Love your eye for the details!

GTM from my side :shipit: . @eahefnawy @flomotlik could you guys take a look into this as well

**Comment by nicka** [comment]
@pmuens Fixing some small typos in the `README.md `.

**Comment by flomotlik** [comment]
@pmuens please review with various http configs just to make sure this works with string and object notation. Other than that it looks REALLY good :D

**Comment by pmuens** [comment]
@flomotlik Yep will review it in detail! Will report back once I'm done!

**Comment by pmuens** [comment]
Just tested this PR locally with some different HTTP event definitions.

Works without a single problem. Great job @nicka 🎉 💃  Love this refactoring as it produces the exact same output but with less usage of CloudFormation output variables 👍 

Just noticed the the function ARN outputs are separated like the endpoints before this PR. Maybe worth to refactor this as well (but in another PR). What do you think @nicka ?

GTM from my side :shipit: 

/cc @eahefnawy @flomotlik

**Pull request merged**
