### PR TITLE
Python3.6 support is coming to Lambda!

### LINKED ISSUE #3482: New Python 3 support on AWS
# Feature Proposal

## Description

Amazon just launched Python 3 support on AWS: https://aws.amazon.com/releasenotes/5198208415517126

What are the steps towards `serverless` support Python 3?

### PR DESCRIPTION
**Pull request by dschep**
## What did you implement:

Closes  #3482

[AWS Lambda has Python3.6 support now](https://aws.amazon.com/releasenotes/5198208415517126
), serverless should support it too! 

## How did you implement it:
Added python3.6 to the checks for invoke local and pass the interpreter rather than relying on the shebang line and added a template.

## How can we verify it:
Seems to only be on `us-east-2` when I tested it, but just do:
```bash
sls create -t aws-python3  # then change region in config
sls deploy
sls invoke -f hello
sls invoke local -f hello
```

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by Cretezy** [comment]
> Seems to only be on us-east-2 when I tested it, but just do:

Will be available to all regions within 24h.

**Comment by dschep** [comment]
Note that you don't actually need any of these changes to deploy a Python3.6 service, you can just change your runtime. This is just a template and an `invoke local` fix.

**Comment by pmuens** [comment]
This is super cool! 👍 

Thanks for the updates @dschep will review it today 🤘

**Comment by eahefnawy** [comment]
@dschep thanks for jumping into this. Just missing updates to the docs.

**Comment by dschep** [comment]
@pmuens Ah. yeah i didn't try to use the template. The "allow edits from maintainers" box is ticked already. Or do I need to add a setting to my fork?

Regarding having a new template instead of changing the existing one, you're exactly correct about the reasoning. Python 2 vs 3 is much more different than node 4 vs 6.

**Comment by pmuens** [comment]
@dschep thanks for the response. In that case having a separate template makes sense 👍 

> Ah. yeah i didn't try to use the template. The "allow edits from maintainers" box is ticked already. Or do I need to add a setting to my fork?

🤔 Checking the box should be sufficient as described [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)... I get an authentication error whenever I try to push to your remote. Furthermore I'm not even able to PR something against your fork. Not sure what's off there.

Could you check the settings of your repo real quick. Maybe something is restriced there... 
Otherwise I can create a gist with the changes 😄 or we can merge this one and PR an update with the changes afterwards.

**Comment by dschep** [comment]
Weird. I've added you as a collaborator to dschep/serverless so that might help. Otherwise, yeah I'm happy to apply a patch file.

**Comment by pmuens** [comment]
@dschep thanks for adding me!

I figured out what's wrong. I added your remote with the `https` URL instead of the `git@github.com` one. This fails because I use 2FA. Anyway. I updated the remote and pushed successfully.

Thanks for all the effort 👍

**Pull request merged**
