### PR TITLE
Add ap-southeast-2 region

### PR DESCRIPTION
**Pull request by tobyhede**
Adds the new Sydney Region.

Addresses issue #1387

### CODE REVIEW

**Comment by pmuens** [comment]
Thank you! /cc @eahefnawy

**Comment by tengis** [comment]
Please merge this PR

**Comment by rojotek** [comment]
(including the code in #1423)

**Comment by flomotlik** [comment]
Hey guys, thanks for the contribution, but we've stopped working on 0.5 of Serverless at this point to fully focus on the next release with V1 that we're currently working on. Therefore we're not taking any commits for 0.5 and do not plan any future releases at this point and I'm closing this PR. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Pull request closed without merging**
