### PR TITLE
Ignore the check whether deploymentBuket exists or not when running sls package

### LINKED ISSUE #4040: "serverless package" requires AWS access if deploymentBucket provider config is used
# This is a (Bug Report)

## Description

The ```serverless package``` command requires AWS access if and only if deploymentBucket provider configuration is used. 

#### What went wrong?
When calling `serverless package` where the serverless.yml file contains the configuration `deploymentBucket` serverless will go and check if that bucket exists using the aws api and will fail if that bucket doesn't exist or if there is no access or if there are no aws access credentials are available.

However the same command when combined with a serverless.yml file that doesn't have deploymentBucket set, will work correctly and package. This also applies there are no aws credentials available on the machine performing the package. 

####  What did you expect should have happened?
The package function should behave exactly as without the configuration value of deploymentBucket and package the code assuming the bucket exists and will be accessible when deployed. 
Then serverless deploy should be the command that would fail when supplied with a package that attempts to use a deploymentBucket that doesn't exist or is unavailable. 

####  What was the config you used?
Example serverless.yml file using deploymentBucket

```
service: my-awesome-service

provider:
  name: aws
  runtime: nodejs6.10
  deploymentBucket: serverless-deployment-bucket-001

functions:
  engine:
    handler: awesome.handlerequest

```

####  What stacktrace or error message from your provider did you see?
```
 serverless package --verbose

  Serverless Error ---------------------------------------

  Could not locate deployment bucket. Error: The specified bucket does not exist
```

## Additional Data

* ***Serverless Framework Version you're using***:
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.1.2
     Serverless Version:     1.19.0

* ***Operating System***:
Linux and OS X

### PR DESCRIPTION
**Pull request by horike37**
## What did you implement:
Closes #4040

I have updated to run the existence check for `deploymentBucket` only when running sls deploy. When running sls package, the check is ignored. Off course, If you don't specify the bucket, the check don't run with both of two commands

## How did you implement it:
I have removed existence check for deploymentBucket from `generateCoreTemplate.js`, and newly have created `existsDeploymentBucket.js` under the directory for deploy command.
Then the existence check run in it when `deploymentBucket` was specified

## How can we verify it:
Please specify a nonexistent bucket name as deploymentbucket, and run `sls package` and `sls deploy`

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by RafalWilinski** [comment]
Thanks for fixing that, it was a real pain for me 👍

**Comment by horike37** [comment]
Thank you for getting back @eahefnawy!
imo, even if `deploymentbuket` does not exist or is not authoritative, syntax errors will not occur in the deployment package generated by `sls package`. (It is correct as a syntax), so I think that this check is only the timing of the deploy.

Perhaps, there may be several use cases that this check is an impediment. we may need to get others opinions.

**Comment by pmuens** [comment]
My gut feeling says that I should be able to run the `package` command w/o having access to the internet or an AWS account at all.

I agree with @horike37 that the `deploymentBucket` check can be skipped during packaging since the bucket is not created and directly managed by Serverless and can be modified / changed between the `package` and `deploy` steps.

**Comment by HyperBrain** [comment]
@pmuens Fully agree. The `package` phase is most likely executed on a build server that has no access to outside resources. Everything accessing these externals is normally executed on a different deployment server in a CI/CD system which has the appropriate rights and IAM role definitions (actually executing `sls deploy` on a previously packaged artifact).
Imo even the bucket name generation should be delayed to the deploy phase (together with adding the acutal name to the template).

**Comment by eahefnawy** [comment]
the package command by default doesn't need internet access, unless a custom bucket is defined. So internet access isn't strictly required. It can still work offline. I just don't feel right to output an invalid package by default.

I do understand your concerns though, how about this:

- on package command, validate the bucket and error out if invalid, **unless a request to AWS fails**, in that case just ignore the connection error and move on. This way we validate early for users who do have internet connection while making users without connection a little happy (they won't be happy when they deploy anyway though)
- deploy command should work the same way

**Comment by HyperBrain** [comment]
@eahefnawy Sounds like a solid approach 👍

**Comment by horike37** [comment]
@eahefnawy Sounds reasonable way!

**Comment by pmuens** [comment]
Yes, that sounds good 👍

**Comment by eahefnawy** [comment]
Awesome! let me know if there's any help you need @horike37 😊

**Comment by pmuens** [comment]
Any update on this PR? Do you need any help here @horike37 😬?

**Comment by horike37** [comment]
@pmuens 
Thank you for pinging! I have not started to work on this yet 😊
Please give me a little time 😬

**Comment by pmuens** [comment]
> @pmuens Thank you for pinging! I have not started to work on this yet 😊 Please give me a little time 😬

Thanks for following-up @horike37 👍 Sure thing! No time pressure here. I was just looking through our Issues and PRs to determine what to review / merge next.

**Comment by horike37** [comment]
It may be hard to take a time for working on that for a while, so if someone wants to do that instead of me,  I will leave it to the person. just re-added `help-wanted` tag.

## Here is the final spec
- on `sls package`, the check is ignored **unless a request to AWS fails**(If you can connect AWS within the environment, the check is done)
- on `sls deploy`, the check is done everytime

**Comment by vijayky2009** [comment]
Any update on this PR? By when this “Ignore deploymentBuket check”  will be available in serverless framework.

**Comment by RafalWilinski** [comment]
@horike37 This PR originates from `unknown repository`. Looks like it was made of fork that you've possibly deleted. Is there any chance to fix that? Thanks 💪

**Comment by horike37** [comment]
Thanks @RafalWilinski :+1: 

>Looks like it was made of fork that you've possibly deleted.

Ahh, yup I deleted my working branch :sweat_smile: 

>Is there any chance to fix that?

Of course!! However, the code I wrote can't recycle.
You might want to create a fresh branch for that and create a new another PR.
We should restart this PR from the beginning.

**Comment by williamdenton** [comment]
I would love to see this issue solved.
My use case is CI/CD generating the packages for later deployment. The CI/CD server does not have aws credentials.

**Comment by jake-lambert-volusion** [comment]
what exactly does *unless a request to AWS fails*, mean? i want to run lambdas locally, with full access to the internet, using credentials which do not have privileges to actually deploy my app (or, perhaps, do anything at all, TBD). So, if failure means "cannot reach AWS" that would not satisfy my use case, and if it means something more broad then I'm not sure what the point of the check is.

I certainly appreciate the argument to do the check on `package` in some contexts. Would y'all be open to adding a flag to control this behavior?

**Comment by horike37** [comment]
Already merged.

**Pull request closed without merging**
