### PR TITLE
AWS HTTP API: Support `timeout` setting

### PR DESCRIPTION
**Pull request by medikoo**
Addresses #7052

### CODE REVIEW

**Comment by Nemo64** [comment]
I'm a bit late but: why would I want to set the api gateway timeout to something different than the lambda function timeout? And wouldn't it make more sense that the default is the lamda function timeout instead of the arbitrary 5s? Or at least be the old default of 29 seconds so that it matches the rest api timeout?

In my test project I have set the timeout for a function to 28 seconds because the apiGateway did previously timeout after 29 seconds. This is no longer true if I understand correctly. Now I'll have to do this:

```
  website:
    handler: public/index.php
    timeout: 28 # seconds (API Gateway has a timeout of 29 seconds, so 28 is the maximum that makes sense)
    layers:
      - ${bref:layer.php-73-fpm}
    events:
      - httpApi:
          path: '*'
          timeout: ${self:functions.website.timeout, 29} # transfer the timeout to the http api too
          # alternatively: timeout: 29 # seconds
```

**Comment by medikoo** [comment]
> Or at least be the old default of 29 seconds so that it matches the rest api default? And actually the normal default of the http api too?

In case of HTTP API [deafult is 5s](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-timeoutinmillis), and it was maintained with that update (note that only if `timeout` is specifically set, we add this property to template)

> wouldn't it make more sense that the default is the lamda function timeout

That definitely makes sense. Also timeout for HTTP API should be slightly larger, otherwise there's a risk that lambda will manage to finish while HTTP API will timeout.

I think it's worth to set timeout of endpoint to value of lambda plus 200ms (and warn if it exceeds 29s). I'll follow up with a PR

**Comment by ac360** [comment]
👍  We ran into this recently on another project.  If you use the "simple" integration (lambda + HTTP API) it didn't seem like we could set the timeout to greater than 5s.  So we had to refactor our CF templates to use  the "non-simple" way to set up the integration.

**Comment by medikoo** [comment]
@Nemo64 function timeout handling will be ensured with: https://github.com/serverless/serverless/pull/7420

**Pull request merged**
