### PR TITLE
Fix python invoke local on Windows

### LINKED ISSUE #3167: Invoke local Python Error: spawn UNKNOWN
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
Unable to run `sls invoke local --function hello`

Steps to reproduce this bug are:

1. serverless create --template aws-python --path first-test --name first-test
2. cd first-test
3. sls invoke local --function hello

* What did you expect should have happened?
stdout to return:
```
{
        "message": "Go Serverless v1.0! Your function executed successfully!",
        "input": event
}
```

* What was the config you used?
     OS:                 win32
     Node Version:       6.9.4
     Serverless Version: 1.6.0
     Python Version: 2.7

* What stacktrace or error message from your provider did you see?
```
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at resolve (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:125:22)
    at AwsInvokeLocal.invokeLocalPython (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:124:12)
    at AwsInvokeLocal.invokeLocal (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:113:19)
From previous event:
    at invoke:local:invoke (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:24:10)
    at BbPromise.reduce (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:160:50)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at PluginManager.run (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:160:22)
    at Serverless.run (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:91:31)
    at serverless.init.then (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\bin\serverless:23:50)
```
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.6
* ***Operating System***: Windows 10
* ***Stack Trace***: 

```
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at resolve (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:125:22)
    at AwsInvokeLocal.invokeLocalPython (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:124:12)
    at AwsInvokeLocal.invokeLocal (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:113:19)
From previous event:
    at invoke:local:invoke (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:24:10)
    at BbPromise.reduce (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:160:50)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at PluginManager.run (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:160:22)
    at Serverless.run (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:91:31)
    at serverless.init.then (C:\Users\jdiaz\AppData\Roaming\npm\node_modules\serverless\bin\serverless:23:50)
```
* ***Provider Error messages***:
spawn UNKNOWN

### LINKED ISSUE #3710: Local invoke error on Windows 10 using Python 3.6
I have created my first serverless function in Python using

* Windows 10 (with NodeJS 8.0)
* Python 3.6

and try to run it locally with

> sls invoke local -f hello

but getting following error

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn python3.6 ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

I am no expert in NodeJS, but it looks like Windows 10 does not allow to run "pyhon3.6" command without (a) full path and (b) executable .exe file in the end.

Workaround:

1. Create environment variable PYTHON, which points directly to your python.exe file (by default %USERPROFILE%\AppData\Local\Programs\Python\Python36-32\python.exe)

2. Patch serverless\lib\plugins\aws\invokeLocal\index.js (function invokeLocalPython, just before return) with

```
    if (process.platform == 'win32') {
      runtime = process.env.PYTHON || runtime;
    }
```
and voilà!

### PR DESCRIPTION
**Pull request by dschep**
## What did you implement:

Closes #3167 
Closes #3710 

by allowing `sls invoke local` to be used on windows

## How did you implement it:
Windows Python distros don't install `pythonX.Y` binaries, so just call `python.exe` with no version. This requires you to have the version of python on the `PATH` env var to match your runtime to work correctly. You also need to check the box on install time of python to add it to `PATH`:
screenshot from 2017-06-22 14-57-46

## How can we verify it:
Install python on widows (checking the add to `PATH`) box and create a python project and use invoke local.

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [X] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by dschep** [comment]
I was looking into adding tests, but `process.platform` is read only so this can only be tested on windows. Does serverless have a windows CI? I only see Travis. Serverless might consider setting up an Appveyor project to ensure high quality for windows users (and macOS builds on travis as well for that matter).

**Comment by pmuens** [comment]
> I was looking into adding tests, but process.platform is read only so this can only be tested on windows.

Thanks for getting back @dschep 👍 Can't we use smth. like this: https://stackoverflow.com/questions/30405397/how-do-you-mock-process-platform-in-jasmine-tests?

> Does serverless have a windows CI? I only see Travis. Serverless might consider setting up an Appveyor project to ensure high quality for windows users (and macOS builds on travis as well for that matter).

Yes, we should definitely set this up since more and more Windows users are using the Framework. We already created an issue for this here: https://github.com/serverless/serverless/issues/3389

**Comment by dschep** [comment]
Updated per discussion in #3346 to support python installations outside(such as pyenv, and in this case, windows too) of the `PATH` override simply by not overriding it.

**Comment by dschep** [comment]
Is emulator what event-gateway & serverless use when you call `sls run`?

**Comment by pmuens** [comment]
@dschep yes, exactly. Here's what's happening behind the scenes when you run `serverless run`:

1. It checks if the [`Event Gateway`](https://github.com/serverless/event-gateway) is already running and downloads the binary if it's not already running or installed
2. It does the same for the [`Emulator`](https://github.com/serverless/emulator)
3. It spins up the [`Event Gateway`](https://github.com/serverless/event-gateway) and the `Emulator`
4. The functions are deployed to the [`Emulator`](https://github.com/serverless/emulator)
5. The functions are registered in the [`Event Gateway`](https://github.com/serverless/event-gateway) with the help of the [FDK](https://github.com/serverless/fdk)
6. You're ready to emit events...

**Comment by dschep** [comment]
Cool cool. I suspected so. It looks like python support is planned for it too, but not currently implemented. Is that correct? Looks like it just needs a `python.py` to match the `node.js` in the `runtimes`. Should be a simple modification of the `invoke.py` in this repo, right?

**Comment by pmuens** [comment]
> Cool cool. I suspected so. It looks like python support is planned for it too, but not currently implemented. Is that correct? Looks like it just needs a python.py to match the node.js in the runtimes. Should be a simple modification of the invoke.py in this repo, right?

Yes, exactly! Shouldn't be too hard to implement 👍

**Pull request merged**
