### PR TITLE
Refs #593 - Add plugin create functionality

### PR DESCRIPTION
**Pull request by pmuens**
Add a basic 'plugin create' functionality so that users can create plugins from within the
command line. Templates for the plugin are included in the templates folder.

### CODE REVIEW

**Comment by ac360** [comment]
Hi @pmuens, you rule :)  This is fantastic.  Could you Submit this PR to `v0.5`?  All new features should go there.

**Comment by pmuens** [comment]
@ac360 thanks. I'll do it ASAP

**Comment by ac360** [comment]
Merged into V0.5.  Thanks @pmuens!!

**Comment by pmuens** [comment]
Thank you very much :+1: . I'll now track the upstream branches and branch from there.

**Pull request closed without merging**
