### PR TITLE
Fixed #4188 - Package generating incorrect package artifact path in serverless-state.json

### LINKED ISSUE #4188: Package generating incorrect package artifact path in serverless-state.json
# This is a (Bug Report )

## Description
When I run `serverless package --stage dit --package build` the `serverless-state.json` still generates absolute path pointing to artifact inside of `.serverless` dir instead of the `build`. When I try to deploy the generated package using `serverless deploy --stage dit --package build -vv` I get an error complaining that the `No function1.zip file found in the package path you provided.`
If I manually go and edit the `serverless-state.json` inside the `build` dir with correct path pointing to the `build` dir instead of the `.serverless` dir then the deployment works fine.

For bug reports:
* What went wrong?
The `serverless deploy --stage dit --package build -vv` did not work.

* What did you expect should have happened?
It should have deployed artifacts from the specified package dir.

* What stacktrace or error message from your provider did you see?
```
  Serverless Error ---------------------------------------

  No function1.zip file found in the package path you provided.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.4.0
     Serverless Version:     1.20.2
```

## Additional Data
* I have multiple functions
* I am using `package.individually` as `true`
* My use case is for build machine to perform the `package` step and upload generated artifacts to some shared location (such as S3) and then another deployment machine to download from S3 and perform the `deploy`. The directory paths on the build machine performing the `package` and the deployment machine performing the `deploy` are different.

* ***Serverless Framework Version you're using***:
```
serverless -version
1.20.2
```
* ***Operating System***:
```
OS X El Capitan
Version: 10.11.6
```
* ***Stack Trace***:
```
  Serverless Error ---------------------------------------

  No function1.zip file found in the package path you provided.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.4.0
     Serverless Version:     1.20.2
```

### PR DESCRIPTION
**Pull request by fruffin**
## What did you implement:

Closes #4188 - Package generating incorrect package artifact path in serverless-state.json

## How did you implement it:

Because artifacts are generated in the `.serverless` directory first, even if a package path was provided, the reference to the artefact zip file was incorrectly pointing at the `.serverless` directory.
This only needs to be changed at the time the service state is saved, so I have added a few lines to the `saveServiceState.js` file of the AWS package plugin to fix the paths in the service configuration before saving.

## How can we verify it:

* In your `serverless.yml` file, specify a package path like so:
```
package:
  path: ../dist
```
* Run the `sls package` command
* Verify that the `serverless-state.json` file in the `dist` directory references the `dist` directory for the package path of each function

## Todos:

- [X] Write tests
- [X] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by fruffin** [comment]
I just haven't got around to adding the extra tests and remove the coverage warnings yet. I'll try to look into it this week

**Comment by ahmed-abdulmoniem** [comment]
Waiting for this PR because the issue is happening with me as well.

**Comment by Idanatcox** [comment]
I had the same issue see https://github.com/serverless/serverless/issues/3525#issuecomment-453307252 for a workaround

**Comment by ahmed-abdulmoniem** [comment]
Any progress on this PR?

**Pull request merged**
