### PR TITLE
Stop hard-coding Public AWS partition in ARN's.

### LINKED ISSUE #4102: "region: us-gov-west-1" generates ARNs for standard region "arn:aws:..." not arn:aws-us-gov:...
# This is a Bug Report

## Description

We are deploying in GovCloud, so we specify that in the provider.region. However, the template generated creates PolicyDocument referencing logs with non-govcloud ARNs.
 
For bug reports:
* What went wrong?

In serverless.yml:
```
provider:
  name: aws
  region: us-gov-west-1    # need ARNs arn:aws-us-gov:...
  deploymentBucket:
    name: eva-ocr-deployment-${self:custom.stage}
```

If I do a "sls package" and see the cloudformation-template-update-stack.json has reference to standard region ARN like "arn:aws:...":
```
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogStream"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/eva-ocr-izdev-DocPdfSplit:*"
                    },
```

* What did you expect should have happened?

The generated ARNs for GovCloud should start with "arn:aws-us-gov:... " like:
```
                      "Fn::Sub": "arn:aws-us-gov:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/eva-ocr-izdev-PagePdfOcr:*"
```

* What was the config you used?

(I don't understand the question)

* What stacktrace or error message from your provider did you see?

When I try to deploy, I see it complain about using "aws" instead of "aws-us-gov":
```
CREATE_FAILED 
AWS::IAM::Role
IamRoleLambdaExecution
Partition "aws" is not valid for resource "arn:aws:logs:us-gov-west-1:644832730935:log-group:/aws/lambda/eva-ocr-dev-DocPdfSplit:*".
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #4040 
* #4048
* #3748
## Additional Data

* ***Serverless Framework Version you're using***: 1.9.0 patched with fix for #4040 #4048 because I don't yet have access to GC for SLS to access the bucket.
* ***Operating System***: OSX El Capitan
* ***Stack Trace***: none
* ***Provider Error messages***: Partition "aws" is not valid for resource "arn:aws:logs:us-gov-west-1:644832730935:log-group:/aws/lambda/eva-ocr-dev-DocPdfSplit:*".

If the ARNs aren't being tweaked for GC, then SLS may not be handling other non-standard regions; sorry, I don't know the code well enough yet.

FYI AWS GC ARNs: http://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html

### PR DESCRIPTION
**Pull request by charlescbeebe**
## What did you implement:

Closes #4102 

## How did you implement it:

Use the new "AWS::Partition" CFN Pseudo Parameter instead of hard-coding ":aws:" (the Public partition) whenever ARN's are constructed by hand in the code.

## How can we verify it:

Compare the `.serverless/cloudformation-template-update-stack.json` file output by `bin/serverless package` on master to the one output from this branch for the following serverless.yml file:

```
service: gc-test

frameworkVersion: ">=1.17.0 <= 2"

stage: dev
region: us-gov-west-1

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:", { "Ref" : "AWS::Partition" }, ":s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:"
            - "Ref" : "AWS::Partition"
            - ":s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"

package:
  include:
    - hello_world.py

functions:
  hello:
    handler: handler.hello
```

In particular, look at the Lambda's IAM Role's PolicyDocument. The biggest payoff comes if you deploy a CFN template created by this branch in GovCloud (and, when Lambda is added to it in the future, the China partition), but that option might not be available to whoever reviews this.

## Todos:

- [x] Write tests
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by charlescbeebe** [comment]
@pmuens FYI at the time I opened this PR, AWS hadn't finished deploying a version of CloudFormation new enough to support it in GovCloud. They have now done so, so it should actually be usable now.

**Comment by pmuens** [comment]
> @pmuens FYI at the time I opened this PR, AWS hadn't finished deploying a version of CloudFormation new enough to support it in GovCloud. They have now done so, so it should actually be usable now.

Great to hear that! Thanks for the update @charlescbeebe 👍

**Comment by tommedema** [comment]
@charlescbeebe why go through the trouble of constructing an ARN manually at all? I would recommend changing

```
- Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:"
            - "Ref" : "AWS::Partition"
            - ":s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"
```

to

```
- Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join: ['', [Fn::GetAtt: [ServerlessDeploymentBucket, Arn]]]
```

**Comment by horike37** [comment]
Closing this issue for now since it took for a long time without any activity.
Feel free to re-open if you want to restart working on this.

**Pull request closed without merging**
