### PR TITLE
fix(Variables): Fix handling of parallel resolution of same variable in v2

### PR DESCRIPTION
**Pull request by nimesh-jethwa**
Changes as per https://github.com/serverless/serverless/pull/11299, but for target branch v2

### CODE REVIEW

**Comment by medikoo** [comment]
@nimesh-jethwa please upgrade to v3. We do not take any improvements to v2, this version is no longer maintained

**Comment by nimesh-jethwa** [comment]
> @nimesh-jethwa please upgrade to v3. We do not take any improvements to v2, this version is no longer maintained

@medikoo Apologies, I should've included some text around the motivation behind this change. We have all our projects (~100+) at v2 and cannot upgrade to v3 at the moment since we use a custom deployment tool that does not yet support v3. Due to the complexity of that custom tool, it might take months before we see the support added in, although projects have switched to the new variables resolver as a first step but are hitting the issue that this PR intends to fix almost everyday.

I understand your comment about v2 no longer being maintained, but is there a remote chance that this fix could be merged?

**Comment by medikoo** [comment]
@nimesh-jethwa unfortunately, we do not have any resources to invest in v2 maintenance. 

Upgrade to v3 should be pretty seamless, what's exactly stopping you?

**Comment by nimesh-jethwa** [comment]
@medikoo As I mentioned, the custom deployment tool (built in-house by the platform teams) that our teams use only supports v2 currently. That tool consists of a lot of JS, TS and custom plugins that needs to support v3 first before our teams can upgrade our repos to v3.

Anyway, I suppose the other option for us in the interim is to publish a custom version of v2 with this fix and use that instead.

**Comment by nimesh-jethwa** [comment]
Found a short term workaround using plugin https://github.com/ds300/patch-package

**Pull request closed without merging**
