### PR TITLE
Websockets: Support more route characters

### LINKED ISSUE #5858: Allow non-alphanumeric characters for websocket routes
# Allow non-alphanumeric characters for websocket routes

## Description

When deploying a websocket route, you will get an error, if you use a non-alphanumeric name for the route. This is more restrictive than what APIGateway allows.

I couldn't find a documentation from AWS regarding the allowed characters. By trial&error I found out, that at least the following characters are allowed in route names:
* `/`
* `-`
* `_`
* `.`

Serverless framework should allow the use of these characters too.

## Additional Data

In the past, we have solved similar issues by simply sanitizing the names for the Cloudformation Stack entries:

`
orgName => orgName.replace(/_/g, 'Underscore').replace(/-/g, 'Dash').replace(/\./g, 'Point').replace(/\//g, 'Slash')
`

### PR DESCRIPTION
**Pull request by eahefnawy**
## What did you implement:

Closes #5858

## How did you implement it:

Replace special characters with alphanumeric ones, as we've done with other logical IDs

## How can we verify it:

```yml
functions:
  hello:
    handler: handler.hello
    events:
      - websocket: 'echo'
      - websocket: 'echo/echo'
      - websocket: 'echo-echo'
      - websocket: 'echo_echo'
      - websocket: 'echo.echo'
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by eahefnawy** [comment]
@dschep I used `Dash` at first, but thought it'd be better to use single/double characters like `D` to keep the logical ID short, especially if there are multiple dashes and slashes, which I think would be common for websockets specially

**Comment by dschep** [comment]
unless there's a size limit to contend with, at this point I'd rather not have a new scheme.

**Comment by eahefnawy** [comment]
@dschep I did some research and couldn't find any particular size limit on logicalIds, so I've pushed your requested changes. Thanks for the feedback 👍

**Comment by eahefnawy** [comment]
@pmuens yep, no need. It is the expected behavior.

**Comment by pmuens** [comment]
FWIW here's that I found today, so we should stick to that pattern in the future https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/resources.md#override-aws-cloudformation-resource

**Comment by kaybee99** [comment]
I can't get this to work with route names containing multiple non-alphanumeric characters.

`echo-echo` works as expected.

`echo-echo-echo` returns 

    Error: The CloudFormation template is invalid: Template format error: Resource name echoDashecho-echoWebsocketsRoute is non alphanumeric.

Is this expected behaviour?

**Comment by cristianrgreco** [comment]
Just encountered the exact same issue as @kaybee99 with multiple underscores.

**Pull request merged**
