### PR TITLE
docs: Add `invoke local` doc for `google` provider

### PR DESCRIPTION
**Pull request by CorentinDoue**
Documentation of the invoke local feature of [serverless-google-cloudfunctions](https://github.com/serverless/serverless-google-cloudfunctions) implemented in https://github.com/serverless/serverless-google-cloudfunctions/pull/258 and https://github.com/serverless/serverless-google-cloudfunctions/pull/264 released in https://github.com/serverless/serverless-google-cloudfunctions/releases/tag/v4.2.0

### CODE REVIEW

**Comment by pgrzesik** [comment]
Hey @CorentinDoue - do you think you could rebase this one so we could merge it? I think it's safe now since the original PR has been merged and released a while back

**Comment by CorentinDoue** [comment]
@pgrzesik I'm on vacation this week, I will rebase it next week 🙂

**Comment by pgrzesik** [comment]
Thank you and have great vacations @CorentinDoue :raised_hands:

**Comment by CorentinDoue** [comment]
@pgrzesik It should be ok :)

**Review by pgrzesik — APPROVED** [review]
Thank you @CorentinDoue :bow:

**Pull request merged**
