### PR TITLE
Add virtualenv support to Python invokeLocal

### PR DESCRIPTION
**Pull request by dschep**
## What did you implement:

Virtualenv support for python invoke local 

## How did you implement it:
Since the invoke local functionality overrides `process.env.PATH`, only the
system python is found, not the python provided by an active virtualenv. This
checks for the `VIRTUAL_ENV` environment variable and if present, adds it's bin
dir to `PATH`.

## How can we verify it:
1. create a python serverless project
2. create & activate a virtualenv
3. install a dependency and import it in `handlers.py`
4. invoke the handler locally, you shouldn't get an error about the import.

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by gmetzker** [comment]
I'll be curious to see if this fixes my issue #3166 as well.

Do you think this will respect packages and packages_dir items in setup.py files.  For my case I use an activated virtual environment and my source files are in `./src/*.py` (with the yaml in the root at `./serverless.yml`

```
packages = find_packages('src'),
package_dir={'':'src'},
```

**Comment by dschep** [comment]
Yes, I think it would.

**Comment by HUSSTECH** [comment]
Hey, just a heads up I ran up against this problem for a long time before I found this issue ticket and guessed that maybe the fix only implemented support when you use `virtualenv`. I switched to that, and it worked. 

So basically, virtual environment support is still not there for either `pyenv` virtual environments, or the new native Python 3.6 `venv` functionality.

**Comment by pmuens** [comment]
> So basically, virtual environment support is still not there for either pyenv virtual environments, or the new native Python 3.6 venv functionality.

Thanks for the heads up @HUSSTECH 👍 

Maybe we can add issues for the other virtual environments so that we can track the progress on that.

**Comment by dschep** [comment]
@HUSSTECH works fine with `python3.6 -m venv` AFAICT:
```
s[:example] master+ ± sls invoke local -f hello
{
    "args": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "close",
        "Host": "httpbin.org",
        "User-Agent": "python-requests/2.10.0"
    },
    "origin": "208.253.70.146",
    "url": "https://httpbin.org/get"
}
[:example] master+ ± python3.6 -m venv test-venv
[:example] master+ ± . ./test-venv/bin/activate 
[:example] [test-venv] master+ ± sls invoke local -f hello
Traceback (most recent call last):
  File "/home/dschep/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 54, in <module>
    module = import_module(args.handler_path.replace('/', '.'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "./handler.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

[:example] [test-venv] master+ ± pip install requests
Collecting requests
  Using cached requests-2.18.1-py2.py3-none-any.whl
Collecting urllib3<1.22,>=1.21.1 (from requests)
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests)
  Using cached idna-2.5-py2.py3-none-any.whl
Installing collected packages: urllib3, chardet, certifi, idna, requests
Successfully installed certifi-2017.4.17 chardet-3.0.4 idna-2.5 requests-2.18.1 urllib3-1.21.1
[:example] [test-venv] master+ ± sls invoke local -f hello
{
    "args": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "close",
        "Host": "httpbin.org",
        "User-Agent": "python-requests/2.18.1"
    },
    "origin": "208.253.70.146",
    "url": "https://httpbin.org/get"
}
```

**Comment by dschep** [comment]
And pyenv (and in general, different locations for python installations) could be supported if we just get rid of the `PATH` override (like I am enabling windows support in #3832).

**Comment by HUSSTECH** [comment]
@dschep, I'll get my colleague to check venv again with those steps, as he was the one who reported that to me. But I had the issue with pyenv. Are you doing anything special for it? when I activate my pyenv virtualenv with a 3.6 environment I still get the following error:
```
Error: spawn python3.6 ENOENT
    at exports._errnoException (util.js:1014:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```
which has already been documented as being a caused by not having python3.6 visible on the path somewhere.

**Comment by HUSSTECH** [comment]
PS. I'm happy to use virtualenv anyway, as it's what I prefer. So it's not a massive issue for our team, the only reason I spotted it was because we happened to use venv and pyenv. As you say, not overriding the path seems like the best long term solution.

**Comment by dschep** [comment]
Nope, this checks for the `VIRTUAL_ENV` environment variable. Pyenv isn't really a virtualenv, it's a totally separate python installation, so as I mentioned, just not overriding `PATH` in invoke local would fix this in the same way that it fixes windows, since that's not installed to `/bin` or `/usr/bin` either. And thinking about it, if you create&activate a virtualenv (either with `virtualenv` or `-m venv`) with your pyenv python installation, it should work actually, i think (since then there is a `VIRTUAL_ENV` var)

**Comment by dschep** [comment]
@pmuens thoughts about just altering #3832 to just never set `process.env.PATH` instead of just deleting it on Windows?

**Comment by pmuens** [comment]
> @pmuens thoughts about just altering #3832 to just never set process.env.PATH instead of just deleting it on Windows?

Sounds like a good alternative to the removal. But TBH I'm not too familiar with the matter, so I'd say it's your call 👍

**Pull request merged**
