### PR TITLE
Knative support

### LINKED ISSUE #5212: Is Knative in your roadmap?
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

I know that as of today you support kubeless which is also basically archiving the same goal. Although I would like to ask if you are planning to support Knative in Serverless.

Reason is that is currently baked by Google, Pivotal, Red Hat and many other organizations which are trying to converge on the serverless approach doing it in one way on Kubernetes.

I would really like to see this adopted as it would vastly open the doors to an easy serverless experience ( I love Serverless CLI! ) and smooth migration, doesn't matter if you use Google Cloud, AWS EKS, Pivotal PKS and so on.

Similar or dependent issues:
* N/A

## Resources
* https://cloud.google.com/knative/

Thank you in advance for any reply given.

Best regards.

### PR DESCRIPTION
**Pull request by pmuens**
## What did you implement

Add `knative` support.

Closes #5212

## How can we verify it

```yaml
# TBD
```

## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test-ci` --> Run all validation checks on proposed changes
- `npm run lint-updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check-updated` --> Check if updated files adhere to Prettier config
- `npm run prettify-updated` --> Prettify all the updated files

</details>

- [ ] Write and run all tests
- [ ] Write documentation
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

**_Is this ready for review?:_** NO
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by pmuens** [comment]
Closing this PR since the implementation which was done here moved to a dedicated provider plugin implementation and several [Serverless Components](https://github.com/serverless-components).

**Comment by mjschmidt** [comment]
Sorry I am very interested in this, would you mind providing some links?

**Comment by mjschmidt** [comment]
Nvm, for those interested

https://github.com/serverless-components/knative-eventing?files=1

**Comment by billfine** [comment]
@mjschmidt here a few others:

[knative-build](https://github.com/serverless-components/knative-build)
[knative-serving](https://github.com/serverless-components/knative-serving)
[knative-eventing](https://github.com/serverless-components/knative-eventing)
[docker](https://github.com/serverless-components/docker)

Plan is to flesh out each of these and provide them in the context of a Serverless Framework, Knative provider.

**Comment by mjschmidt** [comment]
so cool! thank you!

**Pull request closed without merging**
