### PR TITLE
set lint-staged to 12, as 13 drops support for node 12

### PR DESCRIPTION
**Pull request by pjmattingly**
Closes: #11249

Attempting a commit with lint-staged resulted in an error, as the current version of lint-staged dropped support for node 12. Changing to lint-staged@12 resolved the issue.

### CODE REVIEW

**Review by pjmattingly — COMMENTED** [review]
edit: remove spurious commend from vscode.

**Comment by pjmattingly** [comment]
This issue also implies that the CI checks may not be checking for issues like this; That is, errors that might crop up during development.

**Comment by pjmattingly** [comment]
Added small notice in CONTRIBUTING.md about recommended dev environment.

**Comment by pgrzesik** [comment]
Hey @pjmattingly - there seems to be a small conflict, could you look into that?

**Pull request closed without merging**
