### PR TITLE
Ensure to have secure dependencies (decompress & download)

### LINKED ISSUE #7402: Vulnerable dependancy
# Bug Report

## Description

If a yarn or npm audit is part of the CI/CD builds will fail.
Raising the issue here because there has been no action on the issue in the library.

1. What did you do?
npm audit or yarn audit
1. What happened?
serverless fails because of this https://www.npmjs.com/advisories/1217
1. What should've happened?
serverless passes
1. What's the content of your `serverless.yml` file?
N/A
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
N/A

Similar or dependent issues:

- https://github.com/kevva/decompress/issues/71

### PR DESCRIPTION
**Pull request by preshetin**
## What did you implement
Update to secure versions of `decompress` & `download` dependencies.

Closes #7402 

## How can we verify it
Run `npm audit` and you'll get this in the end (no high severity):
```
found 25 vulnerabilities (24 low, 1 moderate) in 8084 scanned packages
  run `npm audit fix` to fix 24 of them.

```

## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test:ci` --> Run all validation checks on proposed changes
- `npm run lint:updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check:updated` --> Check if updated files adhere to Prettier config
- `npm run prettify:updated` --> Prettify all the updated files

</details>

- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by neverendingqs** [comment]
FYI it sounds like this is done as part of every release: https://github.com/serverless/serverless/pull/7531#issuecomment-607514672

**Comment by preshetin** [comment]
@neverendingqs thanks Mark for letting me know. So should I better close this PR?

**Comment by neverendingqs** [comment]
@preshetin yes I believe so.

**Comment by Besiara** [comment]
Why you closed this PR, looks like the issue still persists. A version of download should be updated to 8.0.0

**Pull request closed without merging**
