### PR TITLE
add hello-world template

### PR DESCRIPTION
**Pull request by DavidWells**
Adding a `hello-world` template to be used on the homepage of the site and in the docs.

This will give a better experience to people coming into the framework.

```bash
# Install serverless globally
npm install serverless -g

# Create an AWS Lambda function in Node.js
serverless create --template hello-world

# Deploy to live AWS account
serverless deploy

# Function deployed!
http://api.amazon.com/users/update
```

Output provides the actual desired result of a live http endpoint

```
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (404 B)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..................................
Serverless: Stack update finished...
Service Information
service: serverless-hello-world
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  GET - https://10e0anxke4.execute-api.us-east-1.amazonaws.com/dev/hello
functions:
  helloWorld: serverless-hello-world-dev-helloWorld
```

### CODE REVIEW

**Comment by DavidWells** [comment]
Kudos to @rupakg for the idea

**Comment by pmuens** [comment]
Yes, I agree that's a good idea. Right now we've followed the pattern `<provider>-<runtime>` so that you know where it's deployed and what runtime is used under the hood.

I'm fine to merge this w/o changing it since it's basically a throwaway template to get to the "magic moment" faster.

TBH I would love to see this in another repo so that we have the core as clean as possible.
This way one could run `serverless create -t <theURL>` but unfortunately unfortunately this is not possible since we don't have GitHub URL support for the create command.

What do you think @eahefnawy ?

**Comment by eahefnawy** [comment]
@pmuens while I agree with your concerns about keeping the repo clean, I think this particular case should be in this repo because it's for onboarding purposes, not just another example.

Leaving the merge to you 😊

**Comment by eahefnawy** [comment]
hmm actually, @DavidWells ... the only difference between this template and the ones we already have is CORS, maybe we should just include CORS by default in the core template instead of adding an "example template"? Imo all the templates we have are "example templates" in different runtimes. Imo we should also remove all the tedious comments in `serverless.yml` for onboarding.

**Comment by pmuens** [comment]
@eahefnawy yes, that sounds like a good plan.

We could leave a comment with a link to the docs about the `serverless.yml` file in there (this one: https://serverless.com/framework/docs/providers/openwhisk/guide/serverless.yml/#serverlessyml-reference). But should remove everything else and enable CORS by default.

**Comment by pmuens** [comment]
Just created an issue to cover that: https://github.com/serverless/serverless/issues/3481

**Comment by pmuens** [comment]
Just adding @DavidWells comment about the "need" for this PR here:

> The hello world template gets people to live endpoint with minimal effort (aka no manual editing of serverless.yml)

**Comment by rupakg** [comment]
"Output provides the actual desired result of a live http endpoint" is the key to this PR.

**Comment by DavidWells** [comment]
What @rupakg it's the **zero configuration** solution to getting a working endpoint.

This does 2 things:

1. Gets me to the wow moment faster
2. Demonstrates how functions are triggered by events (in this case http)

```bash
# This is too verbose 
serverless create -t https://github.com/my-organization/my-repo/master/template/hello-world

# So much cleaner and easier to type
serverless create -t hello-world
```

Maintenance on this tiny template should not be an issue.

Let's make this happen. We can always remove it on the next major release if no one uses it.

**Comment by buggy** [comment]
@rupakg and @DavidWells I think the point being made earlier in the comments is that this is a minor modification to the existing template and it's actually desirable to have CORS support there anyway. Instead of creating a `hello-world` template just add CORS support and the endpoint configuration to the current `aws-nodejs` template and call it done.

It's not really going to impact anyone who knows what they're doing but it will help people who don't.

**Comment by pmuens** [comment]
Thanks for the feedback @buggy 👍 

We've discussed this PR yesterday again and came to the conclusion that while this is an outlier (in regards to the naming schema, etc.) it provides a nice improvement regarding the onboarding process. This template will reduce the "time-to-ah-moment".

I've updated the PR with tests and fixed some bugs so that the `create` command can be used. Will merge once the build passes. :shipit:

**Pull request merged**
