### PR TITLE
docs: Fix typos in docs

### PR DESCRIPTION
**Pull request by saintmalik**
Q1: Provide a link to the corresponding issue

• made corrections to the typos i have found in the documentations.

### CODE REVIEW

**Review by mnapoli — APPROVED** [review]
Thank you!

**Comment by saintmalik** [comment]
> Thank you!

You are welcome 🙂

**Review by pgrzesik — APPROVED** [review]
Thank you @saintmalik :bow:

**Comment by saintmalik** [comment]
> Thank you @saintmalik 🙇

You are welcome 🧎🏾

**Pull request merged**
