### PR TITLE
Avoid null error of package

### PR DESCRIPTION
**Pull request by shogohida**
Closes: #11491

### CODE REVIEW

**Review by medikoo — CHANGES_REQUESTED** [review]
@shogohida thanks for giving that a spin, Note that CI failed

**Comment by shogohida** [comment]
@medikoo 
I thought adding `?` is a way to avoid an error so I don't know how I should fix test failures (they are based on the change I made in this PR)....

**Comment by medikoo** [comment]
@shogohida you've used syntax that's not supported in Node.js v12, which we need to support.

**Comment by shogohida** [comment]
@medikoo 
Oh, understood. How about this change?

https://github.com/serverless/serverless/pull/11506/commits/3445cadb2d56edf5543aaaaa64b97a61f6116820

**Review by medikoo — CHANGES_REQUESTED** [review]
@shogohida that looks better. Still CI continues to fail. This time issue is that proposed change doesn't match Prettier formatting

**Comment by shogohida** [comment]
@medikoo 
Sorry for not running prettier and lint locally. I fixed the code again by running them so please check the change I made

https://github.com/serverless/serverless/pull/11506/commits/b6ca394249e0f363a0a291b4dfbd5941bf23517b

**Review by medikoo — APPROVED** [review]
Thank you @shogohida 👍

**Comment by shogohida** [comment]
Thanks for your quick review! Hope contribute more

**Pull request merged**
