### PR TITLE
include stage reference in body mapping template

### PR DESCRIPTION
**Pull request by patrickbrandt**
##### Status:

Ready

##### Description:

I've included a stage reference in the body template so that I can determine the run-time environment of the lambda function; see issue #1849. This provides a quick work around until issue #1455 is resolved.

### CODE REVIEW

**Comment by pmuens** [comment]
@patrickbrandt thank you for this PR! 🎉 

Just one minor thing. Could you add documentation for the new `stage` retrieval:

It should be added to the following places (we're about to update the whole documentation soon so that we'll have a single source of truth):

https://github.com/serverless/serverless/tree/master/lib/plugins/aws/deploy/compile/events/apiGateway#universal-json-request-template

https://github.com/serverless/serverless/blob/master/docs/guide/overview-of-event-sources.md#extended-event-definition-2

and

https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js#L89

Thank you 👍

**Comment by patrickbrandt** [comment]
@pmuens happy to help!

I've updated the 3 doc sources per your request.

**Comment by patrickbrandt** [comment]
Grumble: lint test failed for https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js#L89

89:1  error  Line 89 exceeds the maximum line length of 100  max-len

@pmuens I could reformat the comment as such:
```
// universal velocity template
          // provides
          // `{ body, 
          //    method, 
          //    principalId, 
          //    stage, 
          //    headers, 
          //    query, 
          //    path, 
          //    identity, 
          //    stageVariables} = event`
          // as js objects
```
Let me know your thoughts.

**Comment by pmuens** [comment]
Awesome! Thank you 🎉 

Just one tiny linting error and then we're ready to go!

**Comment by pmuens** [comment]
@patrickbrandt Yep looks good!

Would be great if you could indent it like this:

```
// universal velocity template
// provides
// `{ body, 
//    method, 
//    principalId, 
//    stage, 
//    headers, 
//    query, 
//    path, 
//    identity, 
//    stageVariables} = event`
// as js objects
```

Thanks a lot!

**Comment by pmuens** [comment]
Awesome! Will merge once the build succeeds!

**Comment by patrickbrandt** [comment]
@pmuens all checks passing + I rebased my fork to get rid of a couple of intermediate commits.

**Comment by pmuens** [comment]
Merged! Thanks a lot @patrickbrandt 🎉

**Pull request merged**
