### PR TITLE
refactor: Remove `legacy` logs

### PR DESCRIPTION
**Pull request by pgrzesik**
Reported internally, remove legacy logs

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
@pgrzesik It looks it needs rebase against v3

**Review by medikoo — CHANGES_REQUESTED** [review]
Thanks @pgrzesik in general it looks very well, but it appears that removal was missed in some parts.

To well confirm on that, I've created https://github.com/serverless/utils/pull/154 and when tests here are run against version from PR, some failures occur

**Comment by pgrzesik** [comment]
Ready for a review, merging needs to wait for corresponding PRs in `dashboard-plugin` repository

**Review by medikoo — APPROVED** [review]
Great job 👍

**Pull request merged**
