### PR TITLE
Set IoT permission without creating new rule

### LINKED ISSUE #5541: Set IoT permission without creating new rule
# This is a Feature Proposal

## Description

* Current support for creating IoT rules with a lambda action works great, but lambda can also be invoked by rules without being the direct action of the rule.  [See the docs](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sql-functions.html#iot-func-aws-lambda) for more details.
* I would envision the only necessary configuration to be the ARN of an existing IoT rule, with the behavior changing to only create the `AWS::Lambda::Permission` and omit the `AWS::IoT::TopicRule`
* Potential config example:
  ```yaml
  functions:
    myfunc:
      handler: bin/handler
      events:
        - iot:
            arn: arn:aws:iot:us-east-1:11223344:rule/my-rule
  ```

Similar or dependent issues:

### PR DESCRIPTION
**Pull request by swhite24**
## What did you implement:

Closes #5541 

Added support for additional `iot` event property, `arn`.  When provided, an IoT Rule is not created.  Rather, only a lambda permission is created referencing the property.

## How can we verify it:

Example event configuration:

```yml
functions:
  myIoT:
    handler: myIoT.handler
    events:
      - iot:
          arn: "arn:aws:iot:us-east-1:account_id:rule/rule_name"
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by swhite24** [comment]
Hey @pmuens .  Thanks for getting back to me.

The use case is essentially being able to set a `AWS::Lambda::Permission` on a function without generating an IoT rule and requiring the function to be the action of the rule.

An example scenario:

I have an IoT rule which I want to pipe directly to Kinesis Firehose, without a lambda action.  Part of my rule, however, requires some custom data which I WOULD like to facilitate with a lambda function.  This change would allow me to use the serverless schema directly and not have to manage the permissions on my own.

Here's an example from the docs on invoking a lambda function in the rule definition.

https://docs.aws.amazon.com/iot/latest/developerguide/iot-sql-functions.html#iot-func-aws-lambda

```
SELECT
aws_lambda("arn:aws:lambda:us-east-1:account_id:function:lambda_function", payload.inner.element).some.value as output FROM 'a/b'
```

**Comment by pmuens** [comment]
Hey @swhite24 thanks for getting back and providing the explanation.

Do you have a `serverless.yml` file I can deploy and use for testing? Alternatively can you provide a step-by-step guide how I can validate the functionality?

I messed around with IoT permissions, but apparently I have to select a sink (e.g. which Lamdba should be triggered) when setting them up which defeats the purpose of this PR.

Thanks in advance! 👍

**Comment by pmuens** [comment]
Hey @swhite24 thanks again for working on this. Would love to get this merged soon.

Do you have any easy to follow-along example? I tried to create what you described above but my lack of in-depth AWS IoT service experience prevents me from making process...

**Comment by pmuens** [comment]
Thanks again for working on this @swhite24 :+1:

Unfortunately I was not able to test this thoroughly. I'll close this PR for now. Feel free to re-open it once you have some details on how we can test this change.

**Pull request closed without merging**
