### PR TITLE
Release v3.19.0

### PR DESCRIPTION
**Pull request by medikoo**
Additionally upgraded few dev dependencies to latest majors

### CODE REVIEW

**Comment by pgrzesik** [comment]
@medikoo There seems to be a failing test - should I still review?

**Comment by pgrzesik** [comment]
No problem, just ask for re-review whenever ready 👍

**Comment by medikoo** [comment]
@pgrzesik I've sorted it out. It appears that upgrading `@commitlint/cli` from v12 to v17 introduced a `typescript` and `ts-node` dependencies, and that broke some of our `serverless.ts` tests. I've reverted that upgrade

Putting aside that it introduced side effects to our tests, it's surprising to see a pretty simple linter taking `typescript` as a mandatory dependency, I've reported that issue here: https://github.com/conventional-changelog/commitlint/issues/3218

**Review by pgrzesik — APPROVED** [review]
👍

**Pull request merged**
