### PR TITLE
Integrating Serverless Components

### PR DESCRIPTION
**Pull request by eahefnawy**
## What did you implement:

Integrated with Serverless Components by simply depending on the components cli as a dependency and using its methods (I've kept all the required logic over there to keep things separate). It currently only support `serverless.js` files as declarative usage still requires major updates after the recent changes.

This will likely require Node 8 even to check for the existence of a components project, because we'll need to require the component JS file to check it's actually a component, which will likely include Node 8 features.

The other conflicting issue I've found is: what happens when there's an empty directory? I know @medikoo is working on an interactive `serverless` command, but the components project also ships with such a functionality. I think what we'll need to do is add support for components templates in @medikoo implementation, although I wish we could separate concerns.

## Todos:

_**Note: Run `npm run test-ci` to run all validation checks on proposed changes**_

- [x] Write tests and confirm existing functionality is not broken.  
       **Validate via `npm test`**
- [ ] Write documentation
- [x] Ensure there are no lint errors.  
       **Validate via `npm run lint-updated`**  
       _Note: Some reported issues can be automatically fixed by running `npm run lint:fix`_
- [x] Ensure introduced changes match Prettier formatting.  
       **Validate via `npm run prettier-check-updated`**  
       _Note: All reported issues can be automatically fixed by running `npm run prettify-updated`_
- [x] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

**_Is this ready for review?:_** NO  
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by medikoo** [comment]
> This will likely require Node 8 even to check for the existence of a components project, because we'll need to require the component JS file to check it's actually a component, which will likely include Node 8 features.

@eahefnawy Shouldn't this be marked as breaking change then?

**Comment by eahefnawy** [comment]
@medikoo I have no idea! I personally believe we should drop support for Node 6 in the framework. We've been debating this for quite some time now but I'm not sure where we landed.

Another hacky solution is to read the components JS file as string, and sort of analyse that string to figure out if it's a component or not. Will likely be a slow operation though which would run on every invocation of the serverless cli.

**Comment by eahefnawy** [comment]
As expected, the Node 6 build failed with the following error:

```
/home/travis/build/serverless/serverless/node_modules/@serverless/cli/src/index.js:20
const runComponents = async () => {
                            ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/serverless/serverless/bin/serverless.js:5:23)
      1) should print general --help to stdout
```

**Comment by medikoo** [comment]
> @medikoo I have no idea! I personally believe we should drop support for Node 6 in the framework. We've been debating this for quite some time now but I'm not sure where we landed.

I'm totally after this as well, and I'd love to do it even today :) But it's a breaking change, so formally it means we need to bump SLS version to v2. 

And currently as this integration is proposed as breaking, on formal side I think it should also be reported as such

**Comment by eahefnawy** [comment]
@pmuens sorry for the lack of the verification steps. As mentioned in the description it currently only supports `serverless.js` cause the components CLI only supports that. I'm currently working on updating the declarative usage.

**Comment by eahefnawy** [comment]
Closing this in favor of #6350 ... it's cleaner and more updated.

**Pull request closed without merging**
