### PR TITLE
Add `buildOptions` to ECR config

### PR DESCRIPTION
**Pull request by martinezpl**
Adds a `buildOptions` parameter to ECR config block in order to enable passing arbitrary flags to the `docker build` command, which builds the image that is sent to ECR.

e.g.

```yaml
provider:
  ecr:
    scanOnPush: true
    images:
      image:
        path: ./image/
        file: Dockerfile.dev
        buildArgs:
          STAGE: ${sls:stage}
        buildOptions:
          [
            '--tag',
            'v1.0.0',
            '--add-host',
            'example.com:0.0.0.0',
            '--ssh',
            'default=/path/to/private/key/id_rsa',
          ]
```

Closes: https://github.com/serverless/serverless/issues/11255, https://github.com/serverless/serverless/issues/10712

### CODE REVIEW

**Comment by CoderSpinoza** [comment]
@martinezpl  Is there a plan to merge this? I think this could be beneficial to many users.

**Comment by martinezpl** [comment]
@CoderSpinoza I agree, but it's a question for the maintainers. Issues and PRs coming from outsiders used to be actively reviewed and merged in here, but something seems to have changed this year and the current maintainers ignore those completely.

**Comment by austencollins** [comment]
I think we can get this in shortly. Adding it to our list..

**Comment by austencollins** [comment]
This functionality has been added in: https://github.com/serverless/serverless/releases/tag/v4.1.4 cc @CoderSpinoza

**Pull request closed without merging**
