### PR TITLE
refactor: Remove `bluebird` from `lib/plugins/aws/customResources`

### PR DESCRIPTION
**Pull request by juanjoDiaz**
Addresses: #7171

### CODE REVIEW

**Comment by pgrzesik** [comment]
Hello @juanjoDiaz, with a heavy heart, due to a few regressions introduced with recent Bluebird refactorings(we've noticed way slower packaging, broken `print` command, and just today the issue with EMFILE error #9073 which suggests that we might be opening way more files than previously), we've decided to revert a few of the recent PRs with such refactorings and put on pause bigger changes related to `Bluebird` migration. Unfortunately, it's very easy to miss things during the review process of such refactors, some of the changes are also not caught by our test suite and we want to be more careful moving forward. We'd like to follow the process outlined in https://github.com/serverless/serverless/issues/7171 to limit the potential impacts and unexpected regressions for Framework users. We really appreciate all your efforts in pushing that refactoring forward, but we have to slow down a bit and introduce the changes in smaller chunks and we'd be thrilled to accept your contributions.

**Comment by juanjoDiaz** [comment]
Too bad.
But totally understandable.

I guess that a lesson learned from all this is that test coverage is high but not totally effective.

**Comment by pgrzesik** [comment]
Sorry, I've clicked "close" by mistake

> I guess that a lesson learned from all this is that test coverage is high but not totally effective.

Unfortunately, some of the things are really hard to test, such as detecting the number of open files when packaging bigger service. But we also managed to improve our coverage a bit thanks to these findings e.g. by adding a sanity test for `print` command` that previous test cases didn't catch. Moving forward, we will dedicate more time to thoughful and detailed reviews to avoid such situations, but in order to do that, we want to keep the scope of the changes as small as possible to reduce the possibility of a bug sneaking in. Thanks for understanding and for all your efforts so far :bow:

**Comment by pgrzesik** [comment]
Thanks once again @juanjoDiaz - as mentioned in discussion above, we'd like to follow more iterative, small-steps path - I'm going to close this PR for now.

**Pull request closed without merging**
