### PR TITLE
Exclude ApiGatewayDeployment in CF Template normalization

### PR DESCRIPTION
**Pull request by RafalWilinski**
## What did you implement:

Followup to https://github.com/serverless/serverless/pull/4299
Fixes https://github.com/serverless/serverless/issues/4289

## How did you implement it:

Excludes ApiGatewayDeployment<timestamp_here> from

## How can we verify it:

```bash
serverless deploy
serverless deploy    # This deployment should be skipped

# Perform a change in serverless.yml

serverless deploy    # This should succeed
serverless deploy    # This should be skipped
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by horike37** [comment]
whoops, I made a mistake in the review status..

**Comment by RafalWilinski** [comment]
That's weird behavior. I'll investigate that and hopefully come back soon with results.

**Comment by RafalWilinski** [comment]
@horike37 How many files/functions were in your test package? If more than one, then it might be caused by https://github.com/serverless/serverless/pull/4299

**Comment by horike37** [comment]
@RafalWilinski 
I used only one function and one hander file. The tested package has attached here.
Let me know if you need more info other than this.
[sls-test.zip](https://github.com/serverless/serverless/files/1348548/sls-test.zip)

**Comment by RafalWilinski** [comment]
@horike37 

I've tried reproducing issue, however, I wasn't able to, here's my log:
```
➜  sls-test ../serverless/bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: aws-nodejs
stage: dev
region: us-east-1
stack: aws-nodejs-dev
api keys:
  None
endpoints:
  GET - https://kojv1kg009.execute-api.us-east-1.amazonaws.com/dev/
functions:
  hello: aws-nodejs-dev-hello
➜  sls-test ../serverless/bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: aws-nodejs
stage: dev
region: us-east-1
stack: aws-nodejs-dev
api keys:
  None
endpoints:
  GET - https://kojv1kg009.execute-api.us-east-1.amazonaws.com/dev/
functions:
  hello: aws-nodejs-dev-hello
➜  sls-test ../serverless/bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: aws-nodejs
stage: dev
region: us-east-1
stack: aws-nodejs-dev
api keys:
  None
endpoints:
  GET - https://kojv1kg009.execute-api.us-east-1.amazonaws.com/dev/
functions:
  hello: aws-nodejs-dev-hello
➜  sls-test ../serverless/bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: aws-nodejs
stage: dev
region: us-east-1
stack: aws-nodejs-dev
api keys:
  None
endpoints:
  GET - https://kojv1kg009.execute-api.us-east-1.amazonaws.com/dev/
functions:
  hello: aws-nodejs-dev-hello                                                                      
➜  sls-test ../serverless/bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: aws-nodejs
stage: dev
region: us-east-1
stack: aws-nodejs-dev
api keys:
  None
endpoints:
  GET - https://kojv1kg009.execute-api.us-east-1.amazonaws.com/dev/
functions:
  hello: aws-nodejs-dev-hello
➜  sls-test ../serverless/bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: aws-nodejs
stage: dev
region: us-east-1
stack: aws-nodejs-dev
api keys:
  None
endpoints:
  GET - https://kojv1kg009.execute-api.us-east-1.amazonaws.com/dev/
functions:
  hello: aws-nodejs-dev-hello
➜  sls-test ../serverless/bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: aws-nodejs
stage: dev
region: us-east-1
stack: aws-nodejs-dev
api keys:
  None
endpoints:
  GET - https://kojv1kg009.execute-api.us-east-1.amazonaws.com/dev/
functions:
  hello: aws-nodejs-dev-hello
➜  sls-test ../serverless/bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: aws-nodejs
stage: dev
region: us-east-1
stack: aws-nodejs-dev
api keys:
  None
endpoints:
  GET - https://kojv1kg009.execute-api.us-east-1.amazonaws.com/dev/
functions:
  hello: aws-nodejs-dev-hello
➜  sls-test ../serverless/bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: aws-nodejs
stage: dev
region: us-east-1
stack: aws-nodejs-dev
api keys:
  None
endpoints:
  GET - https://kojv1kg009.execute-api.us-east-1.amazonaws.com/dev/
functions:
  hello: aws-nodejs-dev-hello
➜  sls-test ../serverless/bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: aws-nodejs
stage: dev
region: us-east-1
stack: aws-nodejs-dev
api keys:
  None
endpoints:
  GET - https://kojv1kg009.execute-api.us-east-1.amazonaws.com/dev/
functions:
  hello: aws-nodejs-dev-hello
```

(10 consequent deploy operations)

**Comment by horike37** [comment]
:thinking: :thinking: Ummm..

@RafalWilinski 
Anyway, I have another concern while taking a look at #4379.
If excluding the random number from the end of ApiGatewayDeployment, it would introduce regression which is #2233 issue. What do you think?

**Comment by horike37** [comment]
This PR is closing for now, since there hasn't been any activity for a long time

**Pull request closed without merging**
