### PR TITLE
Allow programmatic use of Serverless*

### PR DESCRIPTION
**Pull request by erikerikson**
## What did you implement:

**_Implementing Issue:**_ #1678

*without unspeakably violating process.argv
## How did you implement it:

Accept "command" array of input to the `init` method of Serverless, pass this through as the second argument of CLI for use instead of argv.  This results in some weird requirements but it's programmatic use without violating your argv so deal with it.  Example:

```
Serverless.init(['invoke', '-f', 'yourFunction', '-d', '-p', 'yourScript.yml'])
  .then(...)
  .catch(...);
```

This would execute Serverless as though the following command was entered at the CLI:
`sls invoke -f yourFunction -d -p yourScript.yml`
## How can we verify it:

Confirm that the following works rather than reporting an error:

```
let sls = null;

try {
    sls = require('serverless');
} catch (ex) {
    const execSync = require('child_process').execSync,
          path = require('path'),
          npmGlobalRoot = execSync('npm -g root', { encoding: 'utf-8' }).trim();

    sls = require(path.join(npmGlobalRoot, 'serverless/lib/Serverless'));
    sls.init(['invoke', '-f', 'yourFunction', '-d', '-p', 'yourScript.yml'])
      .then(() => {
            return serverless.run();
        })
        .then((result) => {
        })
        .catch((ex) => {
            console.error(ex);
        });
}
```
## Todos:
- [N/A?] Write tests
- [N/A?] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Change ready for review message below

**_Is this ready for review?:**_ YES

### CODE REVIEW

**Comment by pmuens** [comment]
Thank you very much @erikerikson! Interesting / great addition!
Is there any way we can add a test case for that?

/cc @flomotlik @eahefnawy

**Comment by ac360** [comment]
Thx @erikerikson for getting this started.  Looking at the above code, there must be a more elegant way to do this. 

I architected V.0 to be programatic first, optionally detect CLI usage and log if detected.  That way you could call something like `serverless.actions.functionDeploy()`.  I'm still in favor of that approach, as it returns values or errors like any function.  Do you think we should follow the V.0 approach here instead?  It would take some work, but we're not too far from it.

**Comment by erikerikson** [comment]
@pmuens Your asking stimulated me to think on it.  I suppose I could write one that stored current argv, set argv, and then sent in an array conflicting with the argv to detect that the right source was used.  That said, I'll put that on pause re:@ac360's comment.

@ac360 I haven't thought too deeply on this, so apologies up front on that.  From the improved perspective of reading your words, a look at init presents a mixing of the initialization of Serverless with the assumption and processing of CLI usage.  Ideally, the CLI processing will be integrated with a transform component that redirects commands into the programmatic entry mechanisms.

From my point of relative ignorance, one of the core concerns here is that due to the plugin architecture the available commands and their proper use/interpretation are dynamic in nature.  This seems increasingly the case as users gain the option to select a subset of the available providers for installation and subsequent use.  A pattern that facilitates such an interaction and its failure modes relatively gracefully seems important.

Surely other will have deeper, more useful thoughts.

**Comment by flomotlik** [comment]
I think we should discuss what the use case here is first, because @erikerikson and @ac360 are talking about 2 different use cases imho.

# What Erik is talking about

Being able to call a Serverless command through Code instead of through the CLI. It would follow the same plugins and do exactly the same thing, just the thing that is calling is different. Imho that can be implemented as a relatively small change. While I don't think we'll have a ton of use cases for it I do see it as an option to refactor the code slightly to make this work as it shouldn't be a lot of work (and can be done as a contribution, I don't think we'll do it ourselves).

# What Austen proposed

Making all the different Plugins and parts of the system available as an API (and please correct me if I'm wrong on that). This is imho a larger project and refactoring and the main issue there is that it might lead to unexpected outcomes for users if you don't go through the whole lifecycle. As this would need more work and isn't as well defined I would create a separate issue to discuss it in more detail so we have a better understanding what we're actually trying to achieve with this (and what potential use cases are)

# Conclusion

I think we can accept a contribution to what @erikerikson brought up and can open a discussion about what @ac360 talks about. @ac360 could you open that issue and describe what the goal would be you want to achieve there? Should it give access to all the functionality we provide in Serverless and what would the use cases for that be (compared to e.g. people simply requiring the code files and calling the functions directly)

**Comment by ac360** [comment]
@flomotlik Thanks for striving for clarity :)  Two follow-up thoughts:

• Yes, using the commands programmatically as an API would be useful and is definitely a bigger project which we should investigate at some point.
• In the interim, I agree something like @erikerikson's solution is a good middle-ground until the above can be addressed.  Additionally, though I am @erikerikson's #1 fan, I believe with a small bit of effort we can create a version of his approach that will require less code on behalf of users who seek to do this, improving the DX.  Give me just a couple of days to look into this and draft up a proposal.

**Comment by flomotlik** [comment]
@ac360 could you post your thoughts in this Issue: https://github.com/serverless/serverless/issues/1678

For now I'll close this PR and #2426 as they both kind of target this issue.

**Pull request closed without merging**
