### PR TITLE
fix(AWS Local Invocation): Remove log4j dependency from java wrapper

### LINKED ISSUE #10831: Java invoke-bridge build failed
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I can't build the Java invoke-bridge as below.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

mvn package

### Command output

```shell
% pwd
/Users/yyamano/work/serverless/lib/plugins/aws/invoke-local/runtime-wrappers/java
% mvn package
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< com.serverless:invoke-bridge >--------------------
[INFO] Building invoke-bridge 1.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.amazonaws:aws-lambda-java-log4j:jar:1.5.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.254 s
[INFO] Finished at: 2022-03-10T15:49:38+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project invoke-bridge: Could not resolve dependencies for project com.serverless:invoke-bridge:jar:1.0.1: Failure to find com.amazonaws:aws-lambda-java-log4j:jar:1.5.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

### Environment information

```shell
v3.7.3 from github.

% node ~/work/serverless/bin/serverless.js -v
Framework Core: 3.7.3
Plugin: 6.1.5
SDK: 4.3.2
```

### PR DESCRIPTION
**Pull request by yyamano**
Closes: #10831

### CODE REVIEW

**Review by pgrzesik — APPROVED** [review]
Thanks @yyamano - great call 👍

**Comment by Jalle19** [comment]
Can this be backported to the 2.x branch? Took me 2 days of debugging to find this issue.

**Comment by mnapoli** [comment]
@Jalle19 we only backport critical fixes to v2. Are there blockers that prevent you from upgrading to v3?

**Comment by Jalle19** [comment]
Not sure, I haven't tried. I stuck with 2.x. because I had it installed globally and it wasn't possible to use 3.x locally with 2.x globally installed. Either way, without this change it's impossible use `sls invoke local` with Java projects.

**Comment by pgrzesik** [comment]
Hey @Jalle19 - as @mnapoli mentioned, unless there's a really good motivation we don't backport fixes to previous major releases. The best approach here would be to consider migration to 3.x

**Pull request merged**
