### PR TITLE
switch to jszip, closes #1621

### LINKED ISSUE #1621: Replace node-zip package with plain js-zip package
Right now we use `node-zip` as our zipping package. However `node-zip` is "outdated" and uses `js-zip` under the hood. We should switch to plain `js-zip` so that we always get the latest features and have more functionality of zipping.

### PR DESCRIPTION
**Pull request by chris-olszewski**
##### Status:

Ready

##### Description:
Switch out `node-zip` for `jszip` resolving #1621.

### CODE REVIEW

**Comment by pmuens** [comment]
Thank you for that! Really appreciate it 🎉 

Just one question: Isn't the package `js-zip` missing in the `package.json` file?

One other thing which might be different with the recent `js-zip` library is that it has a slightly different API (new sync and async methods).

**Comment by chris-olszewski** [comment]
@pmuens Oops, you're right `jszip` should be in `package.json`. Upgraded to 3.1.0, but `npm install` downgrades to 2.5.0. Currently looking into this.

**Comment by pmuens** [comment]
Thank you! Strange. Maybe it has something todo with the `shrinkwrap` which also needs an update once the package was added.

Let me know if you need any help there!

(some methods where zipping is used might need some updates...)

**Comment by chris-olszewski** [comment]
@pmuens Yup, it was `shrinkwrap`. Thanks for the tip.

**Comment by mthenw** [comment]
Great PR.

One suggestion. Can we make some benchmark before merging just to make sure that there is no perf downgrade?

**Comment by flomotlik** [comment]
@pmuens can you take care of the performance test and also do some more manual testing to make sure this works fine. Then we can imho merge this today

**Comment by pmuens** [comment]
Yes. will look into it.

**Comment by pmuens** [comment]
@flomotlik @mthenw tested it on my local machine multiple times. Blazing fast... GTM from my side :shipit: 

Great job @chris-olszewski 🎉 👍

**Comment by flomotlik** [comment]
Tested it locally as well. Good to merge

**Pull request merged**
