### PR TITLE
Cleanup Serverless.js file from unused code

### PR DESCRIPTION
**Pull request by PaulShestakov**
## What did you implement:

Just an unused code cleanup

## How can we verify it:
CI check is not failing:)

## Todos:

- [ ] _Write tests - **NOT NEEDED**_
- [ ] _Write documentation - **NOT NEEDED**_
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by eahefnawy** [comment]
Thanks for pitching in @PaulShestakov ... what makes you super sure this code is unused? :)

> CI check is not failing:)

CI is great, but there are certain edge cases that it doesn't catch. All PRs must be tested manually.

**Comment by dschep** [comment]
@eahefnawy, looking at it, it makes sense that it be deleted. The code is probably used, but it does nothing. regardless of conditions, it just resolves.

**Comment by PaulShestakov** [comment]
> CI is great, but there are certain edge cases that it doesn't catch. All PRs must be tested manually.
Hi, @eahefnawy this line does not sound good at all;)
U can never rely on local tests of some shady person. 

I've just removed a code block like:
```
if (a) {
 return b;
}
return b;
```
(Guess, that was just a dirty merge)

**Comment by eahefnawy** [comment]
ah right, I didn't notice that. Thanks for contributing and clarifying @PaulShestakov & @dschep

**Pull request merged**
