### PR TITLE
ci: Upload standalone to na-siliconvalley region for users in China

### PR DESCRIPTION
**Pull request by timqian**
Resolve network issue we met while uploading standalone files to `sp-shanghai` region from GitHub action: https://github.com/serverless/serverless/runs/1576133295?check_suite_focus=true

Tested in my local machine, Tencent SV region is accessible from China.

### CODE REVIEW

**Review by pgrzesik — APPROVED** [review]
Thanks @timqian for tackling it :raised_hands:

As I'm not aware of how these standalone binaries are being made available for end-users, I have a small question - after changing the upload targets, should we also somehow communicate to users that the download locations for these binaries are changing or it's transparent to our users?

**Review by medikoo — COMMENTED** [review]
@timqian thanks for that.

Can we use the same `dev` platform stage access key and id to upload to new region?

> after changing the upload targets, should we also somehow communicate to users that the download locations for these binaries are changing or it's transparent to our users?

@pgrzesik those url's are not presented to users. It's just urls that are used behind the scends to install or update installation. So I think we do not need to follow with any additional communication

**Comment by timqian** [comment]
@medikoo I think so, we are using the same access key for dev and prod environment

**Comment by medikoo** [comment]
@timqian one additional question. Can you confirm that changing to `na-siliconvalley` guarantees proper access to all users in China?

We've discussed it yesterday with @ac360, and what was pointed is that Tencent network has guaranteed access to it, do o special network configuration, but it doesn't ensure general access to resources in that region from China.

**Comment by timqian** [comment]
Sorry for the late reply, here is a speed test for `na-siliconvalley` region, It is accessible from all the cities in China but a bit slower: 
Screen Shot 2021-01-04 at 10 12 38 AM



## Ref:
https://www.boce.com/http/sls-standalone-1300963013.cos.ap-shanghai.myqcloud.com/vs/sls-standalone-sv-1300963013.cos.na-siliconvalley.myqcloud.com/bff0e64d27c62f9df22e1fbadb9ee002.html

**Review by medikoo — APPROVED** [review]
Thank you @timqian ! 

I've confirmed that upload works as expected with existing creds, and uploaded latest version with our scripts

**Pull request merged**
