### PR TITLE
Fix #1823 - S3 event compile creates an extra bucket with the event configuration

### LINKED ISSUE #1823: S3 event compile creates an extra bucket with the event configuration
* Check if an Issue already exists for this
* Add the relevant label(s)
* Be kind :)

Bug Report Template -----------------------------------------------

##### Serverless Framework Version: 
v1.0-beta
##### Operating System: 
Mac OS X (10.11.6)
##### Expected Behavior:
S3 event should add an event on the configured bucket. 
For example, given the following `serverless.yml`:
```
functions:
  first:
      handler: handler.first
      events:
        - s3: mybucket

resources:
  Resources:
    newCoolResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mybucket
```
Should create the following in the CLF template:
```
"newCoolResource": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "mybucket",
        "NotificationConfiguration": {
          "LambdaConfigurations": [{
            "Event": "s3:ObjectCreated:*",
            "Function": {
              "Fn::GetAtt": ["first", "Arn"]
            }
          }]
        }
      }
    },
```

##### Actual Behavior:
The generated CLF template has the following:
```
  "newCoolResource": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "mybucket"
      }
    },

   "mybucket0S3Event": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "mybucket0",
        "NotificationConfiguration": {
          "LambdaConfigurations": [{
            "Event": "s3:ObjectCreated:*",
            "Function": {
              "Fn::GetAtt": ["first", "Arn"]
            }
          }]
        }
      }
    },
```

The incorrect behaviors are: 
1. Two buckets were created: `mybucket` and `mybucket0` instead of only the first one.
2. The event was configured for `mybucket0` instead of the configured bucket.

### PR DESCRIPTION
**Pull request by bennybauer**
Pull Request Template ------------------------
* Check out our Pull Request Guidelines here: https://github.com/serverless/serverless/blob/v1.0/CONTRIBUTING.md

##### Status:

Ready

##### Description:
Fixing issue #1823:
1. Not creating additional buckets 
2. Verifying whether bucket already exists as a custom resource. In this case, the s3 event (`NotificationConfiguration`) will be added to that bucket.

Notice that even after this PR, we still don't support multiple events per bucket.

##### Todos:

- [x] Write tests

### CODE REVIEW

**Comment by pmuens** [comment]
@bennybauer thank you for this one! I'll look into it ASAP.

**Comment by bennybauer** [comment]
@pmuens just noticed that i had some duplications in the test, not it's cleaned.

**Comment by flomotlik** [comment]
@bennybauer it looks like something went wrong with a rebase here? It looks like additional commits are in here as well

**Comment by bennybauer** [comment]
@flomotlik my bad, I forget to squash the other commits... I've created PR #1837 instead of this one. **You can close it.**

**Pull request closed without merging**
