### PR TITLE
fix #1854 - update npm devDependencies packages

### LINKED ISSUE #1854: shrinkwrap includes a few devDependencies, causing unnecessary warnings for users
##### Serverless Framework Version: 

`npm ls -g serverless`: serverless@1.0.0-beta.1.1

##### Operating System: 

macOS Sierra public beta

##### Expected Behavior:

- `npm install -g serverless@beta` should not generate any warnings

- ideally, only dependencies should be installed, not devDependencies

##### Actual Behavior:

`npm install -g serverless@beta` (as directed by quick start instructions) results in the following warnings:

> npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint@^2.9.0 but none was installed.
> npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint-plugin-import@^1.7.0 but none was installed.

### PR DESCRIPTION
**Pull request by nickchisiu**
##### Description:

added latest version of eslint-config-airbnb-base package

### CODE REVIEW

**Comment by pmuens** [comment]
@nickchisiu awesome! 🎉 

Would be great if you could include an npm shrinkwrap in this PR 💯

**Comment by flomotlik** [comment]
@nickchisiu could you look into the build and why its failing? I tried restarting but it still fails for some reason in `npm install`. This is weird as it works in the other parts of the build

**Comment by nickchisiu** [comment]
sure @flomotlik , the issue it's on node 4.4 and npm 2.15.8 , I'm gonna push a new fix ASAP

**Comment by nickchisiu** [comment]
@flomotlik it seems that my local repo it's not updated with the latest master branch , merging that right now and updating tests where it's needed with the latest micha and eslint npm packages standards

**Comment by nickchisiu** [comment]
@flomotlik @pmuens travis build and corverage succeeded && npm install works nice && latest dev tools packages added

**Comment by flomotlik** [comment]
Looks good to me. @pmuens can you look over it as well. I'll also create two issues so we replace the whole random string creation for a tmpdir with something better. Having to update the code in 50 different places is pretty much overkill and massive code duplication. Same for random string in the main application (it should also be fully random and not the current time as time isn't random)

**Comment by nickchisiu** [comment]
agree, and now that you mentioned maybe a CI code duplication evaluation feature would be welcomed , or maybe it's something that exists and i'm not aware of it .

**Comment by flomotlik** [comment]
Yup we discussed adding CodeClimate in the past. We'll do it at some point, its just not high priority right now

**Comment by pmuens** [comment]
@nickchisiu thank you very much for raking the lead on this one!

Looks good to me. @eahefnawy could you also take a look (not sure about some removed `returns` when dealing with promises).

**Comment by nickchisiu** [comment]
@pmuens latest mocha version doesn't support both returning `BbPromises` and `return` on the same event , so where you are having that `done` object you shouldn't have the `return`  because `done` already contains the return

**Comment by eahefnawy** [comment]
@nickchisiu yep that's what I had in mind.

There's a lot of style changes in this PR though, is that because of the updated linter?

**Comment by pmuens** [comment]
@nickchisiu thanks for clarifying that! Promises and `returns` are sometimes an explosive combination 💥

**Comment by nickchisiu** [comment]
@eahefnawy yes, I added latest eslint version in order to get rid of all deprecated and dependency errors on `npm install` so this eslint package got new coding standards implement and  any modifications that I made was errors fixing caused from these newly added standards ( which I think it's good )

**Comment by nickchisiu** [comment]
@flomotlik quick question , any idea of why my commits are seen as one on contributors page ? thanks !

"nickchisiu
1 commit / 303 ++ / 281 --"

**Comment by flomotlik** [comment]
@nickchisiu I squashed them. We're probably going to do more of that in the future, but 50 commits would be a lot in the history at once, so we squashed it into one merge commit

**Comment by nickchisiu** [comment]
so 5 hours of works squashed into one poor commit maybe like a simple README change, I really don't want to be rude but if somebody manage to implement Google Cloud Functions for eg. you will squash all his work just for the simple fact that you see too many commits ? I think this type of actions creates precedents, and a contributor can work for example on 6 great huge features 2-3 months and have 6 squashed commits for that and be an average contributor with 6 commits which maybe not get listed ( as I know only the top 100 contributors are shown )

**Comment by flomotlik** [comment]
Our policy is that we're squashing or combining commits depending on the scale of changes that are happening in a specific PR. I generally prefer splitting PRs into separate commits that deal with separate things. When the Pull Request gets larger then it obviously makes sense to have separate commits as it turns it into easier to deal with and separate pieces.

 I did not feel that this PR needed 50 separate commits so we squashed it to keep our History small and because it would portray the history of contributions to Serverless wrongly by pushing way too many commits into the contribution history for this PR. We value your and everybody elses contributions very highly, but we will always regard technical questions, commit history or other things above contribution statistics. This is a right that I reserve for myself as the person responsible for the progress on Serverless and is honestly also not debatable for me.

**Pull request merged**
