### PR TITLE
Implement awsCompileApigEvents

### PR DESCRIPTION
**Pull request by pmuens**
Implementation of the API Gateway event source.

- [x] implement PR #894

- [x] Write documentation
- [ ] Remove linting issues
- [x] Good test coverage

### CODE REVIEW

**Comment by pmuens** [comment]
@ac360 pointed be to this great PR by @rma4ok which we should implement in this PR:
https://github.com/serverless/serverless/pull/894

It would make working with APIG as an end user way easier

**Comment by pmuens** [comment]
Still some problems when you add an additional endpoint.
Here's the error log:

```
Thu Jun 16 08:51:45 UTC 2016 : Endpoint response body before transformations: <AccessDeniedException>
  <Message>Unable to determine service/operation name to be authorized</Message>
</AccessDeniedException>

Thu Jun 16 08:51:45 UTC 2016 : Endpoint response headers: {x-amzn-RequestId=8dc0385a-339f-11e6-9397-a76da9cf5e10, Connection=keep-alive, Content-Length=130, Date=Thu, 16 Jun 2016 08:51:44 GMT}
Thu Jun 16 08:51:45 UTC 2016 : Lambda invocation failed with status: 403
Thu Jun 16 08:51:45 UTC 2016 : Execution failed due to configuration error: 
Thu Jun 16 08:51:45 UTC 2016 : Method completed with status: 500
```

**Comment by flomotlik** [comment]
@pmuens got the same error on a get request

**Comment by pmuens** [comment]
Really strange. POST is working. Here's a discussion about this error. The last user says that lambda is not supposed to be called with GET requests. That sounds strange...

https://forums.aws.amazon.com/thread.jspa?threadID=209420

**Comment by pmuens** [comment]
@eahefnawy @flomotlik The commit https://github.com/serverless/serverless/pull/1312/commits/a57126f38a4b687d12fe0064aea860c6ee851a84 should solve the problem.

**Comment by pmuens** [comment]
GTM from my side! Great job guys! 🎉

**Pull request merged**
