### PR TITLE
feat: Do not retry AWS requests if the token has expired

### PR DESCRIPTION
**Pull request by mars-lan**
Closes: #9913

### CODE REVIEW

**Review by pgrzesik — APPROVED** [review]
Thank you @mars-lan - great call :+1:

**Review by pgrzesik — CHANGES_REQUESTED** [review]
Sorry, I've missed the fact that there's `yarn.lock` added to this PR - could you please make sure to remove it?

**Comment by mars-lan** [comment]
> Sorry, I've missed the fact that there's `yarn.lock` added to this PR - could you please make sure to remove it?

Done. Also added the file to `.gitignore`.

**Review by pgrzesik — APPROVED** [review]
Great call, thank you @mars-lan :bow:

**Pull request merged**
