### PR TITLE
build(dependency): upgrade to boxen@v4.2.0

### PR DESCRIPTION
**Pull request by crash7**
Validated the breaking changes introduced in https://github.com/sindresorhus/boxen/releases/tag/v4.0.0 and they don't affect `serverless@v2`.

Addresses: #7486

### CODE REVIEW

**Comment by crash7** [comment]
@medikoo not sure about this test error:
```
1) HttpApiEvents
       Should not configure HTTP when events are not configured:
     ServerlessError: The Serverless version (2.0.0-pre) does not satisfy the "frameworkVersion" (*) in serverless.json
      at Service.loadServiceFileParam (lib/classes/Service.js:76:13)
      at /home/runner/work/serverless/serverless/lib/classes/Service.js:53:26
  From previous event:
      at Service.load (lib/classes/Service.js:53:8)
      at /home/runner/work/serverless/serverless/lib/Serverless.js:98:29
      at processImmediate (internal/timers.js:456:21)
  From previous event:
      at Serverless.init (lib/Serverless.js:77:8)
      at /home/runner/work/serverless/serverless/node_modules/@serverless/test/run-serverless.js:179:43
```

Not sure if it's something already in v2 or that boxed updated a transitive dependency that triggered this. 
Any idea? I will keep digging.

**Comment by rkj1980** [comment]
no I have no idea I have a lawyer working on it I've been gang stalked and my intellectual property was stolen and Mendel experiments and patents were made with my intellectual property

Sent from ProtonMail mobile

-------- Original Message --------

**Review by medikoo — COMMENTED** [review]
Thank you, that looks good!

Unfortunately CI got broken by issue that was exposed by dependency update.
It was fixed with https://github.com/serverless/serverless/pull/8166 and already propagated to v2

Can you update your branch so it's picked?

**Review by medikoo — APPROVED** [review]
Thank you @crash7 !

**Pull request merged**
