### PR TITLE
Provide the reserved variable 'name' to Endpoints

### PR DESCRIPTION
**Pull request by erikerikson**
Provide the reserved variable 'name' to Endpoints from their containing Function.  This enables the name variable to be used in endpoint sections of the s-function declaration as is intuitively possible.

This resolves issue https://github.com/serverless/serverless/issues/819.

### CODE REVIEW

**Comment by erikerikson** [comment]
@ac360 please confirm that the reserved "name" variable should **always** refer to the name of the function that is context to the entity being populated.

This "always the context function's name" policy gets trickier in the context of events.  Events already have a name attribute as per Events.js, line 26.  It may be that people believe the function name is being referred to by the name variable but that they are in fact getting the event variable.  Which value is appropriate for the reserved variable "name"?  Maybe there's room for a reserved "eventName" and "endpointName"?

Please advise.

**Comment by ac360** [comment]
@erikerikson Thanks for noticing this.  We do have a name convention for endpoints.  It is:  `users/show~GET` aka `path~method`.  Could you update this PR to add a `getName()` method to the `Endpoint` class, which returns and endpoint name in the above format?  That is what we should use here, instead of function name.  We're trying to not have endpoints so closely tied to functions, since `V0.6` will introduce endpoints that are proxies to AWS resources and outside services.  That's a feature of API Gateway that people like @joostfarla and others have been requesting forever.

I think your suggestion of `eventName` and `endpointName` is great, and likely the only way to handle those nuances.  We should implement it.

P.S.  You are fantastic @erikerikson.  Really, you are a tremendous help.  Every day, I am grateful to have you as part of the community.  Thank you :)

**Comment by erikerikson** [comment]
Will do.  This is a good shift in the strategy and an important capability to provide.

Is there a naming standard for Events too?  If so, I can try my hand at offering an impl for those as well.

@ac360 You're welcome.  Thank **you** for establishing the community that I get to participate in!  You know... not to mention my thanks for creating this tool that makes using ApiG/Lambda not taxing on my sanity.  Certainly not mentioning that.

**Comment by erikerikson** [comment]
You already had the getName method in Endpoints, providing exactly the format you described :)

Please consider the latest commit.  This seems a much cleaner impl.  I'm tempted to reverse the attribute additions in the two fromObject methods but I don't know where those are used and what the impact might be.  Advice?

**Comment by erikerikson** [comment]
Oh wait.  I can avoid the wider impact by moving that logic into the populate method.  One sec...

**Comment by erikerikson** [comment]
Okay, now the addition of the reserved variables has a very focused target.  I think that should be good to go.

**Comment by ac360** [comment]
Nice work @erikerikson Thank you!

**Pull request merged**
