### PR TITLE
Grammatically updated the tech-doc CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jhonsnow456**
Gramatical errors

Closes: #{ISSUE_NUMBER}

### CODE REVIEW

**Comment by jhonsnow456** [comment]
Sir, how to know whether it will get merged to the master repository or what I have to do.

**Review by medikoo — APPROVED** [review]
Thank you @jhonsnow456 That looks great!

**Comment by jhonsnow456** [comment]
Thank you sir I will really like to work more in this project.

**Comment by medikoo** [comment]
> Thank you sir I will really like to work more in this project.

That's very welcome! 👍 If you need any guidance let me know

**Pull request merged**
