### PR TITLE
Add integration test for cloudwatchevent

### PR DESCRIPTION
**Pull request by horike37**
## What did you implement:

Closes #3102

## How did you implement it:
I've implemented it as the following
- Deploy EC2 instance as the CloudFromation resource.
- Be fired the cloudwatchevent by starting and stoping the EC2 instance.
- Check to run the Lambda functions with the CloudWatch logs.

## How can we verify it:
Please run the integration test

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by pmuens** [comment]
Thanks @horike37 👍 🥇 

Will look into it ASAP.

**Comment by pmuens** [comment]
@horike37 super cool! 🎉 

Thank you so much! 👍 Just tested it and it works great! I fixed some minor typos and switched to a `t2.nano` instance.

Just curious if you know if there are other CloudWatch Events we can use in the test to replace the EC2 instances?

My concern right now is that the EC2 instances take too long to spin up and make Travis timeout again (we had that with the old integration tests before running them in parallel with the help of Jest).

But this is just another, not necessary improvement. If this is the best solution to test it right now, then I'm all in for merging this!

**Comment by horike37** [comment]
@pmuens 
Thank you for the review!!

>Just curious if you know if there are other CloudWatch Events we can use in the test to replace the >EC2 instances?
You might be able to use the API calls. It won't take very long since it is only called API
http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/WhatIsCloudWatchEvents.html

If it make Travis timeout, I'll try to replace that.

**Comment by pmuens** [comment]
Hey @horike37 thanks for the response!

How would this exactly look like? Do you mean this: http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/logging_cw_api_calls_cwe.html

Or calling the events directly through the SDK / API?

**Comment by horike37** [comment]
Hey @pmuens 
>Do you mean calling the events directly through the SDK / API?
It means that CloudWatch Event is fired through calling some AWS SDK / API

It can be fired by calling AWS API (SDK) via CloudTrail.
Example the following rule

```
{
  "source": [
    "aws.dynamodb"
  ],
  "detail-type": [
    "AWS API Call via CloudTrail"
  ],
  "detail": {
    "eventSource": [
      "dynamodb.amazonaws.com"
    ]
  }
}
```

it look like this to do the integration test:
- Activate CloudTrail
- Call some AWS API(CloudWatch Event should be fired)

**Comment by pmuens** [comment]
Thanks @horike37 👍 

Sorry for the ping-pong. So I understand this in the following way:

CloudTrail can be used to e.g. monitor API calls. So we setup CloudTrail and issue an API request. This should trigger the CloudWatch Event which is used to react to CloudTrail events. Correct?

Can we make it in a way that we don't need any external resources? In your example you're using a `dynamodb` table. Would be great if we only have CloudTrial and nothing else to setup beforehand. Otherwise we might end up in the same situation with the EC2 instances.

Just wanted to make sure that everything is thought through so that we don't waste your time here as you already did a great job with this PR and the integration test(s) in general!

**Comment by horike37** [comment]
Hey @pmuens!

>Sorry for the ping-pong. 
No problem! Welcome to the deep dive into the discusstion!

>Can we set it up in a way that we don't need any external resources?
Umm. If you use `putevent`, you might be able to trigger the CloudWatch Event without using external resources as far as reading document. 
http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/AddEventsPutEvents.html

Shall I try this?
So if the implementation gets simpler, that is better.

**Comment by pmuens** [comment]
@horike37 thanks for the proposal!

That sounds like a really good solution since it doesn't involve any external resources 👍 

Would be really nice if you could give it a shot! Let us know if you need any help!

**Comment by horike37** [comment]
@pmuens 
OK! will try to use `putevent `. If it would be OK, update this integration test.
Please give me a little time.

**Comment by pmuens** [comment]
Sounds great! Thanks for the effort @horike37 💯 🥇

**Comment by horike37** [comment]
@pmuens
>Would be nice if you could push commits on top of the current status / no history rewrite so that we still got access to your previous work with EC2.

Got it!

**Comment by horike37** [comment]
Hey! @pmuens. Updated the code.
It has succeeded this test without external resources by using `putevent`.
This test has became very simple. Please check it.

**Comment by pmuens** [comment]
Awesome! Thank you very much @horike37 🎉 🥇 

Will review it ASAP so that we can merge it...

**Comment by horike37** [comment]
@pmuens 
Thanks! 🎉

**Pull request merged**
