### PR TITLE
refactor PluginManager and CLI to better support command nesting, cleanup

### PR DESCRIPTION
**Pull request by dougmoscrop**
## What did you implement:

***Implementing Issue:*** #2084
***Implementing Issue:*** #2041
***Implementing Issue:*** #2037
***Implementing Issue:*** #1570
***Implementing Issue:*** #2041

I made PluginManager support arbitrarily nested commands by using loops/recursion instead of explicit checks (firstLevel -> secondLevel)

This made a bunch of stuff simpler and fixed a number of bugs. I also restricted plugin loading to just relevant ones (i.e match provider).

## How did you implement it:

One of the key changes was to make the pluginManager deal with the command object itself, vs. just an array of strings pointing to the command. (Exception: run and getCommand).

I think most PluginManager actions are now fairly straight forward, self-contained functions.

## How can we verify it:

N/A as it mostly just fixes up what people expected / what was documented already?
(integration tests pass)

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Leave a comment that this is ready for review once you've finished the implementation

### CODE REVIEW

**Comment by dougmoscrop** [comment]
This is ready to have some review, I think using Split view is better than Unified.

**Comment by dougmoscrop** [comment]
So one thing that is unclear to me is: should plugins be able to extend other commands? If so, I would probably do some kind of `_.merge()` operation instead of just setting key=value when loading commands. Right now a plugin that defines a new 'deploy' command overwrites.

**Comment by pmuens** [comment]
Wow! Thank you very much @dougmoscrop 🎉 
This is a huge refactoring / changeset and I love it as it closes so many different issues / bugs. Just briefly looked over it and will test it out in detail today!

Will report back once I've done the review.

But thank you very much for working on this to make the PluginManager more flexible / extendible! 👯

**Comment by dougmoscrop** [comment]
Cool! I think it would be good to decide what should happen when plugins have commands that already exist. For example, if someone wanted to add a 'deploy xyz' command, deploy already exists from another plugin, but it has to be expressed as:

```
commands: {
  deploy: {
    commands: {
      xyz: ... 
    }
}
```

This already is a bug (one of the referenced issues), but I don't know what you all want the defined behaviour to be. It could overwrite, it could silently not change the existing command, it could try to 'merge' the hooks and what have you, or it could throw an error. I can/will add tests for whatever the desired outcome is.

**Comment by pmuens** [comment]
Alright. I just gave it a spin!

Here's what I tested so far:
- [x] Check if provider plugins are only loaded when running inside a service
- [x] Check more than 2 level deep command support
- [x] Test custom validation for deeply nested commands
- [ ] Check if help is still displayed if Serverless variable is not set

Works really great. But I ran into those minor issues:
- [ ] The `usage` value is not displayed when having more than 2 level deep commands
- [ ] The help won't be displayed when a Serverless variable is not set (see: #2041)

Anyway I love this PR @dougmoscrop as it's way more clean and solves so many issues alongside.

Regarding the "same command name" issue: I love the merging of both commands as this makes the extendability so much better than throwing an error. What would you say @flomotlik @eahefnawy ?

@dougmoscrop could you please rebase the PR and resolve the conflict?

Thanks for this! Really great addition!

**Comment by dougmoscrop** [comment]
Okay, I fixed the conflicts, and fixed https://github.com/serverless/serverless/issues/2041 (I put it in a separate commit for visibility)

**Comment by dougmoscrop** [comment]
In the same spirit as #2041, if you enter a command that is not found, with a variable expansion that is not available, it will fail to do the variable expansion. This isn't due to my changes or anything, but I could fix it with this refactoring.

If a user has a ${opt:xyz} in serverless.yml, but enters `sls barf`, they have two errors: xyz is not specified, and barf does not exist. Which error would you think is more important?

(right now the xyz one happens, but I could use this refactoring to make 'barb' is not a valid command print first.)

**Comment by dougmoscrop** [comment]
with regard to: ` The usage value is not displayed when having more than 2 level deep commands` can you help me reproduce? I added a subcommand to 'deploy function' (I called it 'deploy function quickly') and I get:

```
dmoscrop$ sls help

Commands
* Serverless documentation: http://docs.serverless.com
* You can run commands with "serverless" or the shortcut "sls"
* Pass "--help" after any <command> for contextual help

create ........................ Create new Serverless Service.
deploy ........................ Deploy Service.
deploy function ............... Deploys a single function from the service
deploy function quickly ....... Instantly deploys the function with no regard for space-time continuum
invoke ........................ Invokes a deployed function.
info .......................... Displays information about the service.
logs .......................... Outputs the logs of a deployed function.
remove ........................ Remove resources.
tracking ...................... Enable or disable usage tracking.

Plugins
AwsCompileApigEvents, AwsCompileFunctions, AwsCompileS3Events, AwsCompileSNSEvents, AwsCompileScheduledEvents, AwsDeploy, AwsDeployFunction, AwsInfo, AwsInvoke, AwsLogs, AwsRemove, Create, Deploy, Info, Invoke, Logs, Package, Remove, Tracking
klm3-dmoscrop:search dmoscrop$
```

```
dmoscrop$ sls deploy function quickly --help
Plugin: Deploy
deploy function quickly ....... Instantly deploys the function with no regard for space-time continuum
    --function / -f (required) ......... Name of the function
    --stage / -s ....................... Stage of the function
    --region / -r ...................... Region of the function
```

I think maybe the problem is I have not implemented the 'merge' so if the subcommand was defined in a separate location it might have stomped on another command.

**Comment by pmuens** [comment]
Yep. Nevermind. I failed to add the `usage` on the command level. Works like a charm!

Would also vote to display that the "command was not found" rather than the "variable is not given"  error message is shown!

Great work! Love it to have it in separate commits as it's easier to review!

**Comment by dougmoscrop** [comment]
Okay so now entering an invalid command will short circuit before getting to variable substitution.

**Comment by dougmoscrop** [comment]
Alright, command merging is done and tested with a separate commit so you can see. I think this is "good to go" pending any further requests.

**Comment by pmuens** [comment]
Ok. So reviewed everything in detail today! Everything works like a charm 🎉 

I love the stuff you've done here @dougmoscrop (especially your 👀  for the details and tests)! Great job!

@flomotlik GTM from my side. Would be great if you could take another look at it!

**Comment by dougmoscrop** [comment]
Np @pmuens! I have another one of these for compile/events/apiGateway coming -  sorry not sorry :)

I got methods.js down to like 70 lines.

**Comment by pmuens** [comment]
Damn @dougmoscrop you really rock and roll!

Yes, the `methods.js` file became a little bit messy from time to time. Great that you've worked on it and refactored it! 💯 

Just note that we're a few days away from merging the new API Gateway Proxy which also touches code in the `method.js` file (see: https://github.com/serverless/serverless/pull/2185).

Would love to see the refactoring as it reduces lots of pains while working with it ("scrollzilla"). So bit 👍  for that... 🎉

**Pull request merged**
