### PR TITLE
Adding Content Handling for API Gateway

### PR DESCRIPTION
**Pull request by ryanmurakami**
## What did you implement:

Providing a fix for #2797 
Still some work on optimization and tweaking, but looking for feedback on approach.

## How did you implement it:

Created an API Gateway configuration plugin to set the content-handling property for Integration Responses during the `aws:deploy:finalize:cleanup` phase.

I liberally adopted a plugin that @jonsharratt wrote [here](https://github.com/craftship/codebox-npm/blob/master/.serverless_plugins/content-handling/index.js).

CloudFormation still doesn't support the ContentHandling property on an IntegrationResponse resource, so I'm even questioning whether it's worth putting this in yet.

## How can we verify it:

Add the property:
`contentHandling: CONVERT_TO_BINARY`
to an `http` event with the `integration: lambda` property. 
Deploy the service and observe it setting the correct content-handling property on the `200` integration response.

## Todos:

- [x] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by jonsharratt** [comment]
Awesome you are looking to get this into the Serverless framework, the main things I had in my notes were:

* Get details of the `integrationResponse` so that if already set and you re-deploy it does not have to do the step.
* Support removal of the `integrationResponse` setting if removed then re-deployed, related to first point.
* Test if the 1 minute wait is still needed, the plugin was written back on a fair few versions back of the Serverless framework so not sure if the process has improved around the amount of executions when deploying the API.  This could be CloudFormation doing the API publishes under the hood, I never really dug deep enough to trace the flow.

As you mention it is a bit of nasty one having to take this approach in regards to  "CloudFormation still doesn't support the ContentHandling property".

Let's see what the wider community things 👍

**Comment by ryanmurakami** [comment]
@jonsharratt Awesome, thanks for sharing those notes. Very good points. I added a bit to optimize function array traversal, but definitely wanted to get more thoughts before I went hard on it. 

Also, thanks a ton for the original code!

**Comment by pmuens** [comment]
Thanks a ton for this PR @ryanmurakami 👍 💪 

And thanks @jonsharratt for the initial codebase 💯 

We were also looking into binary support for API Gateway but the `content_handling` property is not supported in CloudFormation yet.

So this code used the AWS SDK behind the scenes, right?

I'm not sure if it's worth the technical debt to introduce SDK calls alongside the CloudFormation usage. With `v2` we've decided to primarily provision all the infrastructure components and updates through CloudFormation.

What are your thoughts @brianneisler @eahefnawy 

My vote would be to wait for the CloudFormation team to catch up and introduce the `content_handling` support (not sure what the ETA (if any) is there).

**Comment by HyperBrain** [comment]
Imo the cleanup event is semantically not the right place to do a resource change.
The correct place would be `after:aws:deploy:updateStack` as this is the first place where it is guaranteed that the resources are deployed.

Additionally I think using the REST API to change the setting can and must be only a temporary solution. You cannot guarantee the integrity of the resources because the resource creation and mofification are unrelated and can get out of sync. Especially as soon as the user tries to use other operations like rollback.

**Comment by eahefnawy** [comment]
Thanks tons for this @ryanmurakami :1st_place_medal: ... But I agree with @pmuens on this one. I'm hesitent to put hacky solutions into the core. Super happy about the plugin though 👍

**Comment by jonsharratt** [comment]
@ryanmurakami if you fancy extracting it out into a proper plugin / repo go for it, would be awesome.  I can then switch mine out to use it 💃 .  If you need a hand let me know or add me to the repo as a contributor and I will chip in when I have time.

👍

**Comment by ryanmurakami** [comment]
@pmuens @eahefnawy Sounds good! I'll take @jonsharratt's suggestion and create a plugin out of this. Also, it looks like #2797 is in the 1.14 milestone. If the plan is to hold off, you'd probably want to drop that out.

@HyperBrain, great suggestion! I'll move it to that event for the plugin. Thanks!

Closing. Thanks for the feedback!

**Comment by pmuens** [comment]
@ryanmurakami thanks for the reply and your PR in the first place! 👍 

Great to see that this functionality will be moved into a plugin! Let us know if you need any help with that.

**Comment by ryanmurakami** [comment]
Hi guys, I pushed the plugin out: https://www.npmjs.com/package/serverless-apigwy-binary
Still a lot to do, but this accomplishes the baseline configuration required. Thanks for the comments!

**Comment by pmuens** [comment]
Awesome! Thanks for publishing @ryanmurakami 👍 💪 

Would be nice if you could add it to our plugin repo (https://github.com/serverless/plugins/edit/master/plugins.json) so that it's easier to discover (I haven't done it yet so that I don't steal your contribution 😄 )

**Pull request closed without merging**
