### PR TITLE
Python rebuild

### PR DESCRIPTION
**Pull request by ryansb**
This is a rebuild of the Python branch that exists on top of new changes to master. 

Supported:

```
sls module create -r python2.7
sls function create -r python2.7
```

Unsupported:

```
sls function run
sls function deploy
```

### CODE REVIEW

**Comment by ac360** [comment]
:+1: Nice work :)

**Comment by ryansb** [comment]
Now with `function run` support.

**Comment by ac360** [comment]
:100:

**Comment by cscetbon** [comment]
Hey @ryansb, I'm trying to understand what you did and how we could use it to create/run/deploy lambda written in Python. Can you describe what currently works and how to use it ? Would be great to also update the documentation if it supposed to be merged.

**Comment by ryansb** [comment]
@cscetbon Yeah, so right now the checklist looks like this:

- [x] Create a new module using `sls module create -r python2.7`
- [ ] Download Python dependencies to the `dist` directory
- [ ] Zip Python code and dependencies into deployable file
- [x] Use `sls function run` to run a Python function locally

You can check this branch out locally to try out what I have so far. Right now I'm working on the deployable zip file so you can actually deploy Python functions.

**Comment by cscetbon** [comment]
@ryansb Ok cool. I'll follow your progress ! Is there any reason when I try your command I get an error on your branch as on the serverless:python ?
```
> sls module create -r python2.7 -m m1 -f f1
{ [ServerlessError: Unsupported runtime python2.7] name: 'ServerlessError', messageId: 1 }
> python -V
Python 2.7.10
> python2.7 -V
Python 2.7.10
```

**Comment by ryansb** [comment]
@cscetbon can you hop into the serverless/serverless channel on [gitter.im](https://gitter.im)? You can log in with your github account and we can work on it real-time.

**Comment by cscetbon** [comment]
@ryansb I logged in but can't find that channel. Have you already created it ? Do I need special access ? I see other channels though

**Comment by JamieCressey** [comment]
Hey @ryansb how are you getting on? It would be awesome to get this merged, let me know if I can help with any of the remaining tasks!

**Pull request closed without merging**
