### PR TITLE
Reduce memory consumption on deploy by at least 50%

### PR DESCRIPTION
**Pull request by ryansb**
## What did you implement:

I've been having an issue with a particularly large project that's been eating 8+ gigabytes of memory at deploytime (15+ functions, individual deploy zips). 

## How did you implement it:

I switched to using a stream to read artifacts at upload, because it was being read into a `const` that the AWS SDK had to then copy to a bytearray that was wrapped in a TLSStream object, duplicating the artifact several times. 

## How can we verify it:

Create a new template project (I used `aws-python`). Edit serverless.yml to package individually & have 4 functions.

```
service: aws-python # NOTE: update this with your service name
provider:
  name: aws
  runtime: python2.7
  cfLogs: true
  versionFunctions: false

package:
  artifact: ./deployable.zip

functions:
  hello1:
    handler: handler.hello
    package: {artifact: ./deployable.zip}
  hello2:
    handler: handler.hello
    package: {artifact: ./deployable.zip}
  hello3:
    handler: handler.hello
    package: {artifact: ./deployable.zip}
  hello4:
    handler: handler.hello
    package: {artifact: ./deployable.zip}
```

Run a deploy, using the `time` command to show the total CPU time, total wallclock time, and max memory used. 

```
$ time -f 'CPU: %U user/%S kernel\nMax Memory: %M Kbytes' sls deploy
... deploy stuff ...
CPU: 1.27 user/0.08 kernel
Max Memory: 96760 Kbytes
```

_Assume all `sls` commands are prefixed with that same `time` command for brevity_

Reasonable. The deploy zip size is 387 bytes here, which is totally fine. This will be our baseline. Now, I'll add a 49MB file of random data so that the artifacts are bigger (but still always under 50MB).

```
$ dd if=/dev/urandom of=random.bytes bs=1M count=49
49+0 records in
49+0 records out
51380224 bytes (51 MB, 49 MiB) copied, 0.267294 s, 192 MB/s
$ du -h random.bytes
49M     random.bytes
```

Redeploy time!

```
# this is *without* this patch
$ sls deploy
CPU: 1.85 user/0.29 kernel
Max Memory: 384004 Kbytes
# again, with the patch
$ sls deploy
CPU: 2.05 user/0.27 kernel
Max Memory: 238988 Kbytes
```

So the total memory usage is way more than the collective artifact size. The artifacts are 50192K, so and the difference between the two runs is `586036-96760`, and dividing by the artifact size gets us `(384004-96760)/50192 = 5.7` so our artifact is getting 5x bigger in RAM. 

The patched version `(238988-96760)/50192 = 2.8` which is half the increase (same artifact and such).

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by ryansb** [comment]
Also, with this patch, my previous 8+ GB usage is down to about 230MB of max memory on deploy, so for me it's more than a 10x reduction in RAM usage.

**Comment by pmuens** [comment]
Wow 🎉 ! Thanks @ryansb that's astonishing 💯 

Love this "One weird trick" 😸

**Comment by nikgraf** [comment]
This is sooo awesome @ryansb!

**Comment by ryansb** [comment]
Tests are fixed now - I didn't update the `sinon` stub matcher for uploading artifacts. Now the test checks that the readstream sent to the S3 uploader is pointing to the path the artifact comes from.

**Comment by ryansb** [comment]
Hrm, I'm not sure how much that would speed up large files. It makes sense that uploading while reading from disk would be faster than reading from disk, storing in the `const`, then uploading.

**Comment by pmuens** [comment]
I deployed the service above with this branch and after that with the master (which uses the storing in `const`) The deployment with this branch was significantly faster than with the master branch. 

Haven't benchmarked it though as I was looking for memory consumption via `docker stats`...

**Pull request merged**
