### PR TITLE
docs: Add `Sub` function example to pseudo parameters doc.

### PR DESCRIPTION
**Pull request by walery**
Update documentation for change added in serverless/serverless#8279

### CODE REVIEW

**Review by pgrzesik — CHANGES_REQUESTED** [review]
Thank you @walery, unfortunately I think the proposed example is misleading, as it's not going to be a valid part of `serverless.yml` if that was the intention. Maybe it would be better to use something like

```
functions:
  hello:
    handler: my-function.handler
    environment:
      var: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*:*'

```

**Comment by walery** [comment]
Yes, I thought about it as well. Then I decided to use the same example as above.

Let me fix both examples 👍

**Comment by pgrzesik** [comment]
Oh, I didn't notice that the example above is also wrong - if you could adjust them both that would be perfect. Thank you :bow:

**Comment by walery** [comment]
I've now adjusted both examples. Thank you @pgrzesik

**Review by pgrzesik — APPROVED** [review]
Awesome job @walery - thanks for not only expanding docs but also improving old misleading example :bow:

**Pull request merged**
