### PR TITLE
Add S3 Event support for Prefix and Suffix parameters.

### PR DESCRIPTION
**Pull request by philltomlinson**
Added support for suffix and prefix values when creating an S3 event source for a lambda.

### CODE REVIEW

**Comment by jonathannaguin** [comment]
Would be great to be included in 0.5 :+1:

**Comment by JamieCressey** [comment]
I think this is covered by: https://github.com/serverless/serverless/commit/8be459513169d88ecec1014930a256fc280d4ada

And should be in 0.5

**Comment by ac360** [comment]
Thanks @philltomlinson!  @eahefnawy Could you review this one and see if there is a duplication?

**Comment by philltomlinson** [comment]
This feature is already available so ignore this pull request.

**Pull request closed without merging**
