### PR TITLE
Create CloudFormation::WaitCondition that depends on Deployment

### PR DESCRIPTION
**Pull request by alexanderbh**
## What did you implement:

Fixes issue: https://github.com/serverless/serverless/issues/2233

## How did you implement it:

I have created a CloudFormation::WaitCondition that depends on the uniquely named ApiGateway::Deployment. It is called `ApiGatewayDeploymentWait` and it is then possible to depend on this in for example ApiGateway::BasePathMapping resources.

## How can we verify it:

Create a resource that depends on `ApiGatewayDeploymentWait` and see that they are updated after the ApiGateway::Deployment in CloudFormation.

## Todos:
- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Change ready for review message below

**_Is this ready for review?:**_ YES

### CODE REVIEW

**Comment by flomotlik** [comment]
thanks for bringing this up @alexanderbh , but I don't think this change works. The main issue is it doesn't actually deploy changes to the APIG. If you start with the following example for your functions and deploy it:

```
functions:
  hello:
    handler: handler.hello
    events:
      - http: get whatever
```

and then deploy the following after that you won't be able to call the endpoint with `something` because it doesn't exist (wasn't deployed). 

```
functions:
  hello:
    handler: handler.hello
    events:
      - http: get whatever
      - http: get something
```

**Comment by alexanderbh** [comment]
@flomotlik Ahh I see. You are correct. Seems the only way is to deploy a new Deployment.

I have solved this another way then. I create a CloudFormation::WaitCondition called ApiGatewayDeployment that depends on the ApiGateway::Deployment that has a random name.

It is then possible to DependsOn: "ApiGatewayDeployment". Even though that is not a ApiGateway::Deployment. Maybe it should have another name to indicate that the type is not a Deployment.

I will update this PR and you can see if that is too weird a solution.

**Comment by dougmoscrop** [comment]
I'd like to propose a potentially different way to think about this: I suggest that serverless-core create a WaitCondition that DependsOn nothing (or some initial set of things that makes sense). Then, plugins should add things to this wait condition - for example, the aws plugin would add the api gateway wait condition TO the 'all done' wait condition. Then, custom resources and things added via external plugins can use this "vanilla" wait condition as a sort of common interface.

Or is this over engineering?

**Comment by polvoazul** [comment]
This seems great! Is it going to be merged?

**Comment by pmuens** [comment]
@alexanderbh thanks for submitting the PR!

We should definitely get something like this in place.

I like the approach @dougmoscrop mentioned as many other event sources might also wait on something. Not sure how this might look like exactly though. Definitely needs some more discussion (maybe we can open up a new issue for that).

**Comment by eahefnawy** [comment]
@alexanderbh thanks for putting the effort into this. We discussed this change internally and concluded that it adds more overhead and complexity than the solution it intends to solve. We want to try to keep the CloudFormation template at a minimum to avoid hitting the limits.

Now I do realize that you still need to depend on deployment resource somehow; the good news is that we're currently discussing [integrating the newly announced AWS SAM standard](https://github.com/serverless/serverless/issues/2867) which wouldn't have a deployment resource at all. We believe this would make the CloudFormation template much simpler.

I'm gonna close this PR for now, but feel free to reopen if you feel that you have a stronger argument on this change.

Thanks again! 🙌 ... and sorry for dragging this for quite some time 😊

**Pull request closed without merging**
