### PR TITLE
support any AWS nodejs runtime, not just 4.3

### PR DESCRIPTION
**Pull request by assaflavie**
## What did you implement:

Supporting local invokes for AWS lambda runtimes for node.js that are not 4.3

Refs #3397 

## How did you implement it:

Currently it checks for an exact match string for 'node43' in order to allow local invokes. I changed it to a prefix match for 'nodejs'.

## How can we verify it:

Change the runtime to node6.10 and try to invoke a function locally.

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by eahefnawy** [comment]
Thanks @assaflavie for jumping into this! Could you add a unit test for Node 6 in the config? Just to make sure your changes won't get lost in the future 😊

**Comment by assaflavie** [comment]
@eahefnawy done. the test fails before introducing my change, and passes afterwards. But kindly have a look and tell me it's sufficient.

**Comment by assaflavie** [comment]
it goes without saying, this will allow local invokes with runtime versions that aren't actually supported by AWS. I'm allowing anything that starts with `nodejs`... that's why I'm asking if this is cool with you. The way I see it, if the user chooses an unsupported AWS runtime, he/she will figure this out pretty quickly when trying to deploy, so there's no huge risk added here.

**Comment by lteacher** [comment]
@assaflavie just a note, the build is running against your changes. The fail is because of linting errors, you just got to `npm run lint` and fix up the two errors there. :1st_place_medal:

**Pull request merged**
