### PR TITLE
fix(invoke): use processed options

### PR DESCRIPTION
**Pull request by CorentinDoue**
this allow non-AWS providers to use `-e` to declare their environment variables for local invocation

Closes: #9452

### CODE REVIEW

**Comment by pgrzesik** [comment]
Thanks @CorentinDoue :bow: @medikoo could you take a look at this? I'm not sure I fully understand the original issue

**Review by medikoo — DISMISSED** [review]
Thank you @CorentinDoue!

Ideally would be to back it with some regression test, but writing reliable one is not that trivial. So let's take it as it is

**Comment by medikoo** [comment]
@CorentinDoue sorry, I have a second thought. 

If I see correctly all options are passed as expected at initialization. Why do you assume proposed patch fixes any issue?

**Comment by CorentinDoue** [comment]
@medikoo 
If I compare the behavior between AWS and GCP of the following command:
```bash
yarn sls invoke local -f <my-function-name> -e MY_VAR=value
```

**AWS**
1. The schema of command `invoke local` is resolved in `scripts/serverless.js:252` before the instantiation of `serverless` and the options are parsed
2.  `serverless = new Serverless()` is instantiated with the parsed options `{function: "<my-function-name>", env: "MY_VAR=value"}`
3. The plugin `invoke` is instantiated with the parsed options
4. In `loadEnvVarsForLocal`, `this.options.env` is defined 
5. `process.env.MY_VAR` is setup to `value`

**GCP**
1. The schema of command `invoke local` is not resolved before the instantiation of `serverless` because the provider is not `'aws'` (`scripts/serverless.js:252`)
2.  `serverless = new Serverless()` is instantiated with the raw options `{f: "<my-function-name>", e: "MY_VAR=value"}`
3. The plugin `invoke` is instantiated with the raw options
4. In `loadEnvVarsForLocal`, `this.options.env` is undefined 
5. `process.env.MY_VAR` is never setup

Adding hook
```js
'initialize': () => {        
    this.options = this.serverless.processedInput.options;     
 },
```
override raw options with parsed options. `this.options.env` is defined and the variable is defined

**Review by medikoo — APPROVED** [review]
@CorentinDoue thanks for clarifications. Indeed it's a problem when aliases are used. All clear now, merging

**Pull request merged**
