### PR TITLE
Expose plugin hooks

### PR DESCRIPTION
**Pull request by dougmoscrop**
## What did you implement:

This is the same as https://github.com/serverless/serverless/pull/2821 but without the actual visualization code, which will go in a separate plugin.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by dougmoscrop** [comment]
Rebased for posterity; cc @pmuens

**Comment by pmuens** [comment]
Thanks @dougmoscrop 👍 

/cc @eahefnawy

**Comment by dougmoscrop** [comment]
Hmm I don't think it's breaking since it's just storing the variable in an object. Before this change plugins had to represent their hooks either as `fn.bind(plugin)` or `() => fn()`

`const x = 1;`
vs
`const obj = { x: 1 }`

**Comment by dougmoscrop** [comment]
Let me see if there's a test that can cover this to ensure it's not breaking. I'll write it, merge this in to it, then rerun the test.

**Comment by pmuens** [comment]
Thanks for the feedback and jumping into a test to show that this should be not breaking @dougmoscrop 👍

**Pull request merged**
