### PR TITLE
Python support

### PR DESCRIPTION
**Pull request by ryansb**
Python support, now based on v0.1.4

- [x] `function run`
- [x] `component create -r python2.7`
- [x] CodeDeploy
- [x] CodePackage
- [x] Example on using component-level code in handler function
- [x] Dependency management with prefixed `pip`

### CODE REVIEW

**Comment by ac360** [comment]
:+1:

**Comment by ac360** [comment]
:+1: :+1:

**Comment by ryansb** [comment]
@ac360 Python support is ready to rock (and rebased to current master).

**Comment by kevinold** [comment]
Nice!!!

**Comment by ryansb** [comment]
:ship:

**Pull request merged**
