### PR TITLE
🚀 OpenWhisk Provider Support 🚀

### PR DESCRIPTION
**Pull request by jthomas**
Status:

Ready 😎

Description:

This PR provides the provider implementation for the OpenWhisk platform. I've implemented the entire suite of plugins for create, deploy, invoke and remove, with full unit test coverage and documentation. See the lib/plugins/openwhisk directory for the source code.

I have tested this implementation against the OpenWhisk platform deployed on IBM Bluemix.

Enjoy!

_See https://github.com/serverless/serverless/pull/1700 for the original PR and discussion_

### CODE REVIEW

**Comment by pmuens** [comment]
@jthomas Thank you for the update and for reopening it! 🎉

**Comment by mbehrendt** [comment]
this PR hasn't been updated for a while - is there sth we could do to help moving the ball forward?

**Comment by jthomas** [comment]
We were hoping to talk about using serverless framework with Openwhisk at our upcoming workshop at Serverless Conf London. 
Let's us know if there's anything you need to help with getting this in.

**Comment by csantanapr** [comment]
ping @ac360 @jthomas What's the latest on this PR?

Can we continue the conversation here on the issue on what's required.

**Comment by jthomas** [comment]
I started work last week on updating this PR to merge all the changes since I dropped it.
I'm off work for two weeks but will continue on my return. 
I didn't spot any major issues.

OpenWhisk has also continued to add new features so there's things I'd like to add like zip file support.

Could someone from the serverless team estimate how likely they are to merge this once I update the PR?

**Comment by ac360** [comment]
Hi @jthomas, sending you an email about next steps tomorrow when I'm back in the office.  Thanks for your work keeping this up to date and enjoy your vacation :)

**Comment by mthenw** [comment]
OpenWhisk provide support development has been moved to separate repo: https://github.com/serverless/serverless-ibm-openwhisk.

**Pull request closed without merging**
