### PR TITLE
Improve variables test

### PR DESCRIPTION
**Pull request by horike37**
## What did you implement:

Closes #4448 

I have improved the variables test as what @HyperBrain stated, which is using `sinon-chai` syntax so that this leads to much better error messages in case of failures

https://github.com/serverless/serverless/pull/4448#pullrequestreview-74467610

## How did you implement it:

Updated syntax with `sinon-chai`.

## How can we verify it:
Run `npm run test`

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by HyperBrain** [comment]
@horike37 I'll update the PR with a few other improvements/changes in a minute.

**Comment by HyperBrain** [comment]
@horike37 I still found one problem here: https://github.com/serverless/serverless/pull/4450/files#diff-85861fc5b449ff23241d0cd3ad5a137eR600

It seems that the `#getValueFromFile():should work for absolute paths with ~` is not compatible with Windows and it fails on my local system. On Windows you do not have a `~` semantics for your home dir. We should change the test to NOT use the actual os library module but fake the results.

**Comment by HyperBrain** [comment]
@horike37 Found the issue: `os.homedir` is a function, so the string has to be composed as `${os.homedir()}/somedir/config.yml`

**Comment by HyperBrain** [comment]
@horike37 I have fixed the non functional test and chenged it to expect exactly what the code is expected to do. Finally, we're good 😄

**Comment by horike37** [comment]
Thanks @HyperBrain :+1: 

>If you have a closer look, you see, that it does not test anything in the first 3 expects (there is no >"to.equal(true)". So this test is broken and we must not release the realPathsync changes, because >they are not tested properly. We do not know if they'll work.

Whoops, I missed it... Certainly, it had not `to.equal(true)`.
Then personally good to know how to use `finally` functionality :tada:
I thought it hard to use `afterEach` to reset any stubs on each tests
I just get some new experience! Thanks!

**Comment by HyperBrain** [comment]
A better approach would be to initialize a `sinon.sandbox` in `beforeEach()` and use `sandbox.stub()` to create the stubs in the tests. Then you can just do `sandbox.restore()` in `afterEach()` to remove all stubs a test has created.

That is better than `finally` but I did not want to reqrite the complete file :-D

**Comment by horike37** [comment]
>A better approach would be to initialize a sinon.sandbox in before() and use sandbox.stub() to >create the stubs in the tests. Then you can just do sandbox.restore() in afterEach() to remove all >stubs a test has created.

That makes sense! thanks :smile:

**Pull request merged**
