### PR TITLE
Enable Setting Amazon API Gateway API Key Value

### LINKED ISSUE #5935: Enable Setting Amazon API Gateway API Key Value
# This is a Feature Proposal

## Description

Finally, AWS added support for defining API Key value using CloudFront. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html#cfn-apigateway-apikey-value

This will help in the cases if you need to retain the same API key value and remove the stack and deploy it again, and with multi-region deployments where you need to define same API key for multiple API gateways.

### PR DESCRIPTION
**Pull request by laardee**
## What did you implement:

Closes #5935

## How can we verify it:

```yaml
provider:
  name: aws
  runtime: nodejs8.10
  apiKeys:
    - original # original format
    - name: new-key-and-value # name and value
      value: apikeyvalueapikeyvalue
    - name: only-name # only name
    - value: onlyvalueonlyvalueonlyvalue # only value
      description: description for the api key
```
or with usage plan
```yaml
provider:
  name: aws
  runtime: nodejs8.10
  apiKeys:
    - free:
      - original # original format
      - name: new-key-and-value # name and value
        value: apikeyvalueapikeyvalue
      - name: only-name # only name
      - value: onlyvalueonlyvalueonlyvalue # only value
        description: Api key for ${self:provider.stage} stage
    - paid:
      - original-paid
  usagePlan:
    - free:
        quota:
          limit: 1
          offset: 2
          period: MONTH
        throttle:
          burstLimit: 100
          rateLimit: 200
    - paid:
        quota:
          limit: 1
          offset: 2
          period: MONTH
        throttle:
          burstLimit: 100
          rateLimit: 200
```
## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by laardee** [comment]
Thanks for the heads up, the conflicts which #5970 introduces should be quite trivial.

**Comment by pmuens** [comment]
> Thanks for the heads up, the conflicts which #5970 introduces should be quite trivial.

Great! That's good to hear :+1:

We'll merge #5970 soon so we can tackle this right PR after doing that.

**Comment by pmuens** [comment]
Quick update that https://github.com/serverless/serverless/pull/5970 was merged recently...

**Comment by laardee** [comment]
@pmuens now the conflicts should be fixed

**Pull request merged**
