### PR TITLE
Add AWS x-ray support for Lambda

### LINKED ISSUE #3495: Add support for AWS x-ray on AWS Lambda
AWS has added support for `X-ray` on `Lambda`: https://aws.amazon.com/blogs/aws/aws-x-ray-update-general-availability-including-lambda-integration/

would be a nice feature the enable that support from within the `serverless.yml` file by allowing to set the required `enable active tracing` option for the `lambda function`:

image

### PR DESCRIPTION
**Pull request by pmuens**
## What did you implement:

This PR implements AWS x-ray support for Lambda. It's a refactored and updated version of https://github.com/serverless/serverless/pull/3742, so shout-outs to @e-r-w whi implemented the first pass in #3742.

**Aside:** We'll tackle AWS x-ray support for API Gateway separately (as per #5564)

Closes #3495

## How did you implement it:

Added the CloudFormation config to the function and Lambda IAM role level.

## How can we verify it:

```yml
service:
  name: test

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
  tracing:
    lambda: true # this will result in `Active`, you can change it to true, `Active` or `PassThrough`

functions:
  hello:
    handler: handler.hello
  world:
    handler: handler.world
    tracing: PassThrough
```

## Todos:

- [x] Figure out the generic `provider`-wide config definition
- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by pmuens** [comment]
> LGTM. Haven't had a chance to test it yet tho. Quick question tho, since it seems `mode` is the only option for `tracingConfig`, why not simplify the config to `tracingConfig: active`?

Thanks for reviewing 👍

Hmm. Good question. I kept it an object because I thought that maybe there's more config to come. But after thinking about this again I think we can start with a simple syntax and extend it later on.

Will update the PR according to that...

**Comment by dschep** [comment]
Provider seems like the right place to put it. That's where everything else goes. TBH... the only(afaik) thing other than name (aws kms key) that's in `service` would make more sense under `provider`

**Comment by eahefnawy** [comment]
@pmuens I believe we have tons of properties in the provider object that are not prefixed with aws, I don't see a reason to change that pattern now, especially that aws is the default provider.

**Comment by exoego** [comment]
I dont't think prefix is not necessary in field of `provider` since it already have a *scope* defined by `provider.name`.

**Comment by pmuens** [comment]
Thanks for the review and feedback @exoego @dschep and @eahefnawy 👍

I agree, that prefixing this and putting it into `service` would be odd. We had some reasons to do it back then, but in this case, let's keep it in provider 👍

I just rebased and updated that PR so that you don't have to specify the config as an object like

```yml
tracingConfig:
  mode: Active
```

but could provide the mode inline as a string like

```
tracingConfig: Active
```

@dschep came up with this idea and I really like it. We can expand to an object later on if we see more config for Tracing coming in...

Would be nice if I can get another review and after that we shold be able to merge this :shipit:

**Comment by exoego** [comment]
From ease-of-use point of view, in-line syntax is welcome.
There are many mixed-type property that can accept string for shorthand, and object for complex configuration, e.g. `service` itself and `http` event.

**Comment by pmuens** [comment]
Quick update here. Maybe we should look into https://github.com/serverless/serverless/pull/5692 and figure out a pattern for tracing configs.

In that PR we enable tracing for API Gateway like this:

```yml
provider:
  apiGateway:
    stageDescription:
       enableTracing: true
```

Maybe we should re-visit this PR and update it to look like this:

```yml
provider:
  lambda:
    tracingConfig: Active
```

This way we would avoid confusion when people are using both.

The `lambda` nesting wouldn't apply for the case when the tracing config is defined on a per-function basis though. Here's a full example with the proposed syntax:

```yml
service:
  name: test

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
  lambda:
    tracingConfig: Active

functions:
  hello:
    handler: handler.hello
  world:
    handler: handler.world
    tracingConfig: PassThrough
```

Any thoughts @exoego @eahefnawy @dschep ?

**Comment by exoego** [comment]
Hm, it is sad there is inconsistency regarding X-Ray config between Lambda and API GW...
Maybe AWS initially intended to add new mode for tracing, so chosed enum `Active` and `PassThrough`, but simplified it as boolean for API GW.

I think it is easy for users if serverless framework abstracts CF and provide unified field for both Lambda and APIGW.
e.g. `tracing: true`.
No need to copy design inconsistency in AWS.

If AWS add more granular option to tracing in the future, then we can add object support like

```yml
tracing:
  foo: xyz
  bar: 123
```

**Comment by dschep** [comment]
Agreed with @exoego that abstracting the differences away and just having a Boolean in the yaml would be really nice. There's still 2 options needed tho. Maybe this:
```yaml
lambdaTracing: true # for this PR
apigatewayTracing: true # for the other PR
```

**Comment by russell-dot-js** [comment]
Dig it!!!

**Comment by pmuens** [comment]
@exoego and @dschep thanks for chiming in 👍

I just updated the configuration so that it's easier to enable tracing for Lambda and API Gateway with the help of the `tracing` config on the provider level.

You can now basically say:

```yml
provider:
  tracing:
    lambda: true
    apiGateway: true
```

to enable tracing for Lambda and API Gateway. Note that API Gateway is done via https://github.com/serverless/serverless/pull/5692 (I updated it today so that the interface matches with the Lambda one we're implementing here).

This way it's pretty simple to enable tracing for every function while keeping it extensible in the future. You could still define tracing on a per-function basis (see the example in the PR description / the doc updates in this PR).

This is ready for another review.

**Comment by jeffbski** [comment]
How is this different from serverless-plugin-tracing ? 

Using that plugin, you can set 
```yml
  tracing: true
```
at provider or function level. This enables tracing for lambdas.

**Comment by dschep** [comment]
@jeffbski, it's the same, but built in!

**Comment by pinkerton** [comment]
This is awesome @pmuens! I just set up a project with the plugin over the weekend.

When can we expect this in a release of the CLI tool?

**Pull request merged**
