### PR TITLE
NodeJS updated to 16.x

### PR DESCRIPTION
**Pull request by cagriatalay**
Closes: #{#11359}

### CODE REVIEW

**Review by medikoo — CHANGES_REQUESTED** [review]
@cagriatalay great thanks for addressing that. Still unfortunately unit tests also have to be updated, check CI fails

**Comment by 300LiterPropofol** [comment]
Great to see this is being fixed. I wonder when this patch will be merged and released?

**Comment by medikoo** [comment]
@300LiterPropofol we were not notified that this PR is ready for re-review, so it got stale.

Nonetheless, we'll check it now.

**Review by medikoo — APPROVED** [review]
Thank you @cagriatalay !

**Comment by cagriatalay** [comment]
@medikoo You're welcome sir, thanks for the opportunity.

**Comment by 300LiterPropofol** [comment]
Super cool to see this is merged to main, I wonder whether this update, i.e., nodejs using 16.x, will be included in `npm i serverless` package. Will it be included in the next release?

**Comment by medikoo** [comment]
@300LiterPropofol It was already published

**Pull request merged**
