### PR TITLE
Fixes #5188 "Failed to fetch the event types list due the error: API …

### LINKED ISSUE #5188: {"errorMessage":"invalid_request"} when running deploy
# This is a Bug Report

## Description
Following the getting started guide at https://github.com/serverless/platform/blob/master/docs/event-gateway/getting-started.md, running `serverless deploy` with v1.29.2 results in the error 
```{"errorMessage":"invalid_request"}```. 
If i rollback serverless cli to v1.28.0, the following error results instead 
``` Failed to fetch the event types list due the error: API key not set.```.

For convenience, I've reproduced the serverless.yml here:
```
service: my-service

app: <your-app-name>
tenant: <your-tenant-name>

provider:
  name: aws
  runtime: nodejs8.10

functions:
  main:
    handler: handler.main
    events:
      - eventgateway:
          type: sync
          eventType: http.request
          path: /
          method: GET

custom:
  eventTypes:
    http.request:
          
plugins:
  - "@serverless/serverless-event-gateway-plugin"
```
## Additional Data
v1.28.0
```
Event Gateway Plugin
 
  Error --------------------------------------------------
 
  Failed to fetch the event types list due the error: API key not set.
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.3
     Serverless Version:     1.28.0
```
v1.29.2
```
 Error --------------------------------------------------
 
  {"errorMessage":"invalid_request"}
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.3
     Serverless Version:     1.29.2
```

### PR DESCRIPTION
**Pull request by johnlim**
…key not set" error when event gateway plugin is used.

## What did you implement:
Updated logic to retrieve access keys from new `.serverlessrc` schema similar to commit 32ed6776c5538a7b6ef051930c193b7a6ae1a404. With this fix, `serverless.yml` does however still need to include 
```
custom
  eventgateway:
    url: tenant-app.slsgateway.com
```
I was unable to figure out why the http call to update deployment fails without the eventgateway url specified. Presumably, something to do with computedData which the backend verifies? Would appreciate it if someone could explain it to me. 
Closes #5188 

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by dschep** [comment]
tagging @sebito91 too

**Comment by pmuens** [comment]
Any update on this one @eahefnawy @sebito91?

Is this still relevant or is this part of the enterprise plugin?

**Comment by pmuens** [comment]
Alright. Just merged `master` into this PR since https://github.com/serverless/serverless/pull/5948 was merged. Let's see what Travis thinks about this...

**Comment by pmuens** [comment]
Makes sens. Thanks for revieweing @dschep 👍

**Pull request merged**
