### PR TITLE
Fixed apiKeys string issue due to no proper parsing from .yaml file

### LINKED ISSUE #6651: API Keys must be strings
# This is a Bug Report

## Description

- What went wrong?
  API Keys were not created.

- What did you expect should have happened?
  API Keys with assigned usage plan were created.

- What was the config you used?

```
  apiKeys:
    - buenos:
        - ${self:service}:${self:provider.stage}-BuenosPotatos
    - pomidoros:
        - ${self:service}:${self:provider.stage}-PomidorosMark
        - ${self:service}:${self:provider.stage}-PomidorosTom
  usagePlan:
    - buenos:
        quota:
          limit: 100000
          period: MONTH
          offset: 2
        throttle:
          burstLimit: 200
          rateLimit: 100
    - pomidoros:
        quota:
          limit: 100000
          period: MONTH
          offset: 2
        throttle:
          burstLimit: 200
          rateLimit: 100
```
 
- What stacktrace or error message from your provider did you see?
```
Serverless: [serverless-plugin-epsagon] Wrapping your functions with Epsagon...
Serverless: [serverless-plugin-epsagon] You have some Python Lambda functions. Please make sure Epsagon's Python library is installed.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: [serverless-plugin-epsagon] Cleaning up Epsagon's handlers
 
  Serverless Error ---------------------------------------
 
  API Keys must be strings
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              8.10.0
     Framework Version:         1.51.0
     Plugin Version:            1.3.11
     SDK Version:               2.1.0
 

```
Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**:  1.51.0
- **_Operating System_**: VERSION="19.2 (Tina)"
- **_Stack Trace_**:
- **_Provider Error messages_**:

### PR DESCRIPTION
**Pull request by tharun208**
## What did you implement
     I fixed an issue with the current apiKey parsing from the YAML file.

   The current apiKey parsing is having an issue while parsing it from the .yaml file if it is an apiKey is a map of multiple key lists. This PR has the fixed version of the apiKey parser.

Closes #6651 

## How can we verify it

See #6651 issue description.

## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test-ci` --> Run all validation checks on proposed changes
- `npm run lint-updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check-updated` --> Check if updated files adhere to Prettier config
- `npm run prettify-updated` --> Prettify all the updated files

</details>

- [x] Write and run all tests
- [x] Write documentation
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by tharun208** [comment]
Hi @pmuens, I actually re-executed all the tests and everything is fine. Would you want me to add more test cases?

**Comment by tharun208** [comment]
Hi @pmuens, Can we go with the merge request, as it is passing all the tests

**Comment by tharun208** [comment]
Hi @pmuens, Added test cases

**Comment by tharun208** [comment]
Hi @pmuens, Actually I was trying to debug the code and I found this issue within info plugin which I thought which we are using in the actual deployment side. This is the `serverless.yml` which I used to test -

`
apiKeys:
    - buenos:
        - ${self:service}:${self:provider.stage}-BuenosPotatos
    - pomidoros:
        - ${self:service}:${self:provider.stage}-PomidorosMark
        - ${self:service}:${self:provider.stage}-PomidorosTom
  usagePlan:
    - buenos:
        quota:
          limit: 100000
          period: MONTH
          offset: 2
        throttle:
          burstLimit: 200
          rateLimit: 100
    - pomidoros:
        quota:
          limit: 100000
          period: MONTH
          offset: 2
        throttle:
          burstLimit: 200
          rateLimit: 100
`

**Comment by tharun208** [comment]
Maybe , The issue is not well addressed i think so

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pmuens** [comment]
Hey @tharun208 thanks for getting back.

I just used your snipped and tested a deployment with the recent `master` (not this PR). (Un)fortunately I couldn't reproduce the linked issue. Everything is working without any errors on my end.

Here's the full service I've deployed:

```yaml
service: test-${self:custom.idx}

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  region: eu-central-1
  stage: dev
  apiKeys:
    - buenos:
        - ${self:service}:${self:provider.stage}-BuenosPotatos
    - pomidoros:
        - ${self:service}:${self:provider.stage}-PomidorosMark
        - ${self:service}:${self:provider.stage}-PomidorosTom
  usagePlan:
    - buenos:
        quota:
          limit: 100000
          period: MONTH
          offset: 2
        throttle:
          burstLimit: 200
          rateLimit: 100
    - pomidoros:
        quota:
          limit: 100000
          period: MONTH
          offset: 2
        throttle:
          burstLimit: 200
          rateLimit: 100

custom:
  idx: 0

functions:
  greeter:
    handler: functions/handler.greeter
    events:
      - http:
          method: GET
          path: world
          private: true
```

Did you do something different? What caused your service to fail on `master`?

**Comment by pmuens** [comment]
Thanks again for working on this @tharun208 👍:100:

I'll close this PR for now since we were not able to reproduce the problem with the current `master`. Maybe it was already fixed or it's another problem. Feel free to re-open this PR if you've found a way to reproduce the problem.

**Pull request closed without merging**
