### PR TITLE
Updated csharp template to latest tooling

### PR DESCRIPTION
**Pull request by slang25**
## What did you implement:

While implementing the FSharp serverless template I've noticed that AWS have a fix for the packaging issue that was worked around in the build and test scripts. The issue was that relative paths didn't work with the package command.

This PR also has ported to the latest tooling, both the new csproj-based dotnet core, and the latest aws-lambda-tools following the new template more closely (while still fitting the existing template to a certain extent).

This is another attempt #3097

## How can we verify it:

Create new from aws-csharp template and deploy for both Windows and Linux.

## Todos:

- [x] Update tests
- [x] Update documentation
- ~~Check for linting errors~~ (non-functional changes)
- ~~Make sure code coverage hasn't dropped~~ (non-functional changes)
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [ ] Change ready for review message below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by pmuens** [comment]
Thanks @slang25 👍 

I'll check it out. So https://github.com/serverless/serverless/pull/3097 is replaced with this one?

**Comment by slang25** [comment]
@pmuens Yes 😃 And this time I have docker working on my laptop (had some nasty Windows Hyper-V issue, should just use a mac I guess) so I should be able to carry out a proper test using the instructions in the previous PR.

**Comment by pmuens** [comment]
Nice! Let us know if you need any help 👍

**Comment by eahefnawy** [comment]
@slang25 thanks for your work here. I'm closing this PR as it seems that it's now dead without any activity/updates from your side.

I've updated our contribution guidelines to highlight this

Thanks again 😊

**Pull request closed without merging**
