### PR TITLE
Release v3.29.0

### PR DESCRIPTION
**Pull request by medikoo**

### CODE REVIEW

**Review by Danwakeem — COMMENTED** [review]
I think it is alright  to ship this :shipit: I am not sure if Austen or Maciej wanted to take a look first though 🤔

**Comment by medikoo** [comment]
> I think it is alright to ship this :shipit: I am not sure if Austen or Maciej wanted to take a look first though 🤔

Can you confirm with them? If it's not supposed to be shipped, then it shouldn't be merged into `main`, as otherwise it becomes the blocker for other things

**Comment by fbnfgc** [comment]
Hello, do you know when you'll be able to release a 3.29.0 version? Thanks 🙏

**Comment by fbnfgc** [comment]
Thanks a lot 💯

**Pull request merged**
