### PR TITLE
Support for (unix) file permissions

### PR DESCRIPTION
**Pull request by perhallstroem**
We needed to bundle up a couple of executables together with our lambda and noticed that we got a "permission denied" when trying to execute them. An issue ( #504 ) exists for this problem already. This solution entails using JSZip directly instead of using "node-zip". We are currently using this fork, and it works as expected when deploying from a Mac; it appears that this change would not work on a Windows ("DOS") machine, of which I have very limited experience and not much love for.

### CODE REVIEW

**Comment by ilkovich** [comment]
Works for me also, +1 for a merge

**Comment by krzysu** [comment]
could you include it in 0.5 release?

**Comment by HyperBrain** [comment]
In my opinion any change should be platform agnostic as there are lots of users using WIndows for development. I, for example, use both, Linux, Windows and Mac with serverless and all work great.
As zipping binaries with the executable bit set can and will only be done on a UNIX like system it should do it there as expected, but if run on a system, not supporting the permissions like Windows, it should *not fail* but emit at least a warning in case any binary files are detected.
@ac360 What's your point on that?

**Comment by perhallstroem** [comment]
@HyperBrain – I'd be happy to look into that, but I am the first to admit I am not very familiar with Windows. If it is run on Windows, there will be no files with the executable bit set since the concept doesn't exist there (unless I am mistaken). Under what circumstances should a warning be emitted? 

My understanding is that the zip file would be created as expected on Windows: if JSZip is told that the platform is Windows, it will use _dosPermissions_, if any; if it is some flavour of Unix, it will use _unixPermissions_, if any (https://stuk.github.io/jszip/documentation/api_jszip/file_data.html). Hence, if run on Windows, no particular permissions would be set. That should be fine, since a file being executable is determined based on the file extension instead of an executable bit, and it would continue working as it always has for zip files created on Windows.

**Comment by HyperBrain** [comment]
With "warning on Windows" I mean if you have a project that deploys some shell scripts or binaries with your lambda that need the executable bit be set, the Windows based deploy would silently deploy non-usable scripts/binaries as it has no knowledge about that, wheras the same deploy on Linux based systems would yield the expected results.
So if you'd checkout and try to deploy on WIndows and the package contains shell scripts or binaries, at least a warning should be emitted that the results could be unusable.
I think it would even be different if you use interactive mode and silent mode. IMHO silent mode should fail whilst interactive mode could show some kind of "I do not care. Just Do it." prompt to let the user finally decide what happens.

**Comment by perhallstroem** [comment]
Closing this pull request for now, since this can no longer be merged cleanly with master. 

We are currently relying on a plugin that does not work with 0.5, which means that we will not be upgrading at this time, and so will continue to relying on my unofficial 0.4 fork until we are in a position to upgrade; at that time, I might open a new pull request + address the concerns raised here.

**Comment by krzysu** [comment]
It's a pitty this pull request was closed. And honestly I don't get the point of the discussion here.
I agree that solution needs to work for all operating systems, but as we see, no Windows user complained so far. So why do you block fix for affected linux users?
That permissions bug forces me to zip and upload my lambda function manually instead of using build in serverless deploy functionality.

**Comment by perhallstroem** [comment]
@krzysu – if you do not need to be at the absolute bleeding edge all the time, please feel free to use my fork (https://github.com/perhallstroem/serverless) – the master branch is at v0.4.2 and the v0.5 branch is up-to-date as of today. It comes with absolutely no warranties :) We are currently using what is in master in our CD pipeline to production, but the v0.5 branch is not yet exercised since we currently rely on a plugin that works only on 0.4.

**Comment by eahefnawy** [comment]
@perhallstroem really sorry we delayed this PR :disappointed: . Could you please update it for master so we can merge it asap?

**Comment by arabold** [comment]
From what I've seen this is part of Serverless 0.5.3 already. The fix causes another problem for my setup now (which is a bit non-standard, I have to admit): 

I'm mounting a Windows file system with all my code into a Ubuntu VM. All tools including `sls` and `node` run inside of this VM. So now that Serverless 0.5.3 sets the Unix permissions (which are "`-rwxrwx--- 1 root vboxsf`" due to the VM and Windows), Lambda cannot load my scripts anymore :-1: 
```
EACCES, permission denied '/var/task/lambda/get-artist-details/_serverless_handler.js'
```

Is there any case in which it's preferable to have Lambda *not* being able to read the file system? So why are we copying the original Linux file system permissions instead of forcing them to something meaningful such as 0664 or 0777?

For example, if I change the relevant code in CodeDeployLambda.js to
```
119:    let permissions = 0o777;
```

then the deployed Lambda function works as it did in sls 0.5.2. But with this change in 0.5.3 I cannot deploy working code anymore.

**Comment by arabold** [comment]
I've created https://github.com/serverless/serverless/pull/975 to address this issue

**Comment by eahefnawy** [comment]
@arabold thanks for your reply. So PR #975 should replace this PR and this PR should be closed?

**Comment by arabold** [comment]
Sorry for not being clear. #646 can be closed as the same code was already merged a few days ago by @ac360 in PR #960 -- it's just the exact same code but created by @nicka instead of @perhallstroem . Therefore this PR as well as the related issue report #504 can be closed as resolved now.

However, these code changes now introduced a new issue on systems running inside of a VirtualBox - in my case Ubuntu running on top of Windows with a shared file system. If the file permissions are something like 0770 (not world-readable) then packaging the ZIP file will prevent these files from being accessible by AWS Lambda. Executing the Lambda will result in the error above.

My PR #975 enhanced the original PR (which was already merged) to consider this scenario and ensure all files are always world-readable. Thus ensuring that whatever is packaged and uploaded is readable by Lambda. Other flags such as executable are still copied and retained. It's a very simple change as you can see.

Hope that clears things up.

**Comment by eahefnawy** [comment]
Awesome! Thanks a lot @arabold

**Pull request closed without merging**
