### PR TITLE
Fix postinstall error

### LINKED ISSUE #3757: Latest Version Fails Post install when permissions are tight
# This is a Bug Report

## Description

For bug reports:
* What went wrong? 
Post install for serverless fails

* What did you expect should have happened?
Post install to complete

* What was the config you used?
N/A

* What stacktrace or error message from your provider did you see?
```
> serverless@1.15.1 postinstall /usr/local/lib/node_modules/serverless
> node ./scripts/postinstall.js

/usr/local/lib/node_modules/serverless/node_modules/write-file-atomic/index.js:132
    throw err
    ^

Error: EACCES: permission denied, open '/root/.serverlessrc.3405600948'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/serverless/node_modules/write-file-atomic/index.js:117:17)
    at createConfig (/usr/local/lib/node_modules/serverless/lib/utils/config/index.js:30:19)
    at getConfig (/usr/local/lib/node_modules/serverless/lib/utils/config/index.js:44:5)
    at Object.get (/usr/local/lib/node_modules/serverless/lib/utils/config/index.js:90:18)
    at isTrackingDisabled (/usr/local/lib/node_modules/serverless/lib/utils/isTrackingDisabled.js:6:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/utils/segment.js:9:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/classes/Utils.js:14:17)

```

Similar or dependent issues:
* #3753
* Specifically: https://github.com/serverless/serverless/pull/3753#discussion_r120884591

## Additional Data
This is failing on circleci 2.0 where permission are apparently too strict.

* ***Serverless Framework Version you're using***: 1.15
* ***Operating System***: Debian

### LINKED ISSUE #3760: Postinstall script installation of tabtab fails
# This is a Bug Report

## Description

When installing `serverless` the `postinstall` script throws when attempting to run `tabtab install` because `tabtab` does not exist. If I run the `tamtam install` command separately after installation, it succeeds. There seems to be a type of race condition with the creation of that binary and the execution of the postinstall script.

Repro steps:
1. Run `npm install serverless`
2. Observer error message on completion

Node.js version: 6.10.3 (also tried with 8.0.0)
npm version: 5.0.3

## Additional Data

* ***Serverless Framework Version you're using***: 1.15.1
* ***Operating System***: MacOS 10.12.4
* ***Stack Trace***: 
```sh
> serverless@1.15.1 postinstall /Users/rylewis/Documents/Dev/Repo/deploy/node_modules/serverless
> node ./scripts/postinstall.js

/bin/sh: ./node_modules/tabtab/bin/tabtab: No such file or directory
/bin/sh: ./node_modules/tabtab/bin/tabtab: No such file or directory
Unhandled rejection Error: Command failed: ./node_modules/tabtab/bin/tabtab install --name serverless --stdout
/bin/sh: ./node_modules/tabtab/bin/tabtab: No such file or directory

    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at serverless.init.then.e (/Users/rylewis/Documents/Dev/Repo/deploy/node_modules/serverless/scripts/postinstall.js:15:7)
    at tryCatcher (/Users/rylewis/Documents/Dev/Repo/deploy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/rylewis/Documents/Dev/Repo/deploy/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/rylewis/Documents/Dev/Repo/deploy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/rylewis/Documents/Dev/Repo/deploy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/rylewis/Documents/Dev/Repo/deploy/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/rylewis/Documents/Dev/Repo/deploy/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/rylewis/Documents/Dev/Repo/deploy/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/Users/rylewis/Documents/Dev/Repo/deploy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/rylewis/Documents/Dev/Repo/deploy/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/rylewis/Documents/Dev/Repo/deploy/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/rylewis/Documents/Dev/Repo/deploy/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/rylewis/Documents/Dev/Repo/deploy/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/rylewis/Documents/Dev/Repo/deploy/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### PR DESCRIPTION
**Pull request by pmuens**
Fixes the postinstall error which breaks installation with tight permissions.

Closes #3757 
Closes #3760

### CODE REVIEW

**Comment by HyperBrain** [comment]
Just did an `npm install` within the serverless directory which also triggers the `postinstall.js`.

```
$ npm install

> serverless@1.15.0 postinstall C:\Projects\serverless\serverless
> node ./scripts/postinstall.js

- buffer-shims@1.0.0 node_modules\buffer-shims
serverless@1.15.0 C:\Projects\serverless\serverless
`-- aws-sdk@2.66.0
```

Now the script executes and does not exit with a rejection anymore. Also looking at the source code it seems to befixed now (at least on my Windows system) 👍

**Comment by pmuens** [comment]
Nice. Thanks for the check @HyperBrain 👍 

Could you check if the autocompletion still works? I'm currently having a hard time getting this up and running in my Docker container.

**Comment by HyperBrain** [comment]
Ok. It's Windows 10 ;-) but I'll try to set it up in the integrated Ubuntu shell.

**Comment by pmuens** [comment]
> Ok. It's Windows 10 ;-) but I'll try to set it up in the integrated Ubuntu shell.

Great! Thank you very much! 👍

**Comment by HyperBrain** [comment]
```
[tabtab] Adding source line to load /mnt/c/Projects/serverless/serverless/node_modules/tabtab/.completions/serverless.bash
in /home/frank/.bashrc
```
After restarting the shell it worked:
```
frank@DESKTOP-E70VN2N:/mnt/c/Projects/serverless/serverless$ ./bin/serverless
config    deploy    install   login     logs      package   rollback
create    info      invoke    logout    metrics   remove    slstats
```

**Comment by pmuens** [comment]
Nifty! Thanks for confirming @HyperBrain 👍 

I'll update the PR since I think I've found the real root cause.

**Comment by horike37** [comment]
Hey @pmuens @brianneisler,
When will you release this PR? Will you release this as v1.5.4?

**Comment by horike37** [comment]
oooh, sorry. this have already been released.

**Comment by pmuens** [comment]
@horike37 so you still see this error on `v1.15.3`?

**Pull request merged**
