### PR TITLE
Fix for missing artifact of layers with prebuilt artifacts

### PR DESCRIPTION
**Pull request by dortega3000**
Problem: When a layer defines an artifact using 
```
layers:
   <LayerName>:
       package:
            artifact: <Artifact File|i.e: xyz.zip>
```

These artifacts dont get copied to the < WorkingDir>/.serverless directory as a result of the package or deploy command line executions. This causes the package to be incomplete or for the deployment to fail as the file cannot be found to upload it to S3.

## What did you implement:

Closes #XXXXX

## How did you implement it:

When a layer is being packaged, if the layer contains an artifact file, its copied from the path provided on layers.< layername>.package.artifact property,  to < WorkingDir>/.serverless/< BaseName>.  The property layers.< LayerName>.package.artifact gets updated to < BaseName>, where basename is the basename of the original path provided for the artifact.

## How can we verify it:

Add a layer with an artifact before the patch at the file will not be copied, after the patch the file will be as expected in the <WorkingDir>/.serverless directory.

Use following.Yaml snippet

```
layers:
   testlayer:
       package:
            artifact: ./artifacts/test.zip
```

Make sure <WorkingDir>/artifacts.test.zip exists.

## Todos:

- [ ] Write tests
- [x] Write documentation
- [X] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by dschep** [comment]
Agreed with the need for tests & clearer description @pmuens. AFAICT the issue is if you use `package.artifact` with a layer, it doesn't get properly copied. Is that correct @dortega3000?

**Comment by pmuens** [comment]
Hey @dortega3000 thanks for pushing the lint fixes 👍

Any update on the awaiting PR / Issue description and tests? Do you need any help here?

**Comment by pmuens** [comment]
Hey @dortega3000 any updates on this one? Can we help you with anything here?

**Comment by dortega3000** [comment]
Working on it over The Weeknd 😉

**Comment by pmuens** [comment]
> Working on it over The Weeknd 😉

Great! Thanks for following-up @dortega3000 👍

**Comment by dortega3000** [comment]
Updated documentation and how to test

**Comment by dschep** [comment]
@pmuens layers are effectively always packaged individually. there should be a separate zip file for your layer that gets uploaded to s3

**Comment by pmuens** [comment]
> @pmuens layers are effectively always packaged individually. there should be a separate zip file for your layer that gets uploaded to s3

@dschep I see. So the layer `.zip` file should be in the `.serverless` directory.

Just to make it clear. This is my `serverless.yml`:

```yml
service:
  name: test-philipp

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10

layers:
  testLayer:
    package:
      artifact: ../foo/bar.zip

functions:
  hello:
    handler: handler.hello
  world:
    handler: handler.world
```

Here's what `master` currently does:

bildschirmfoto 2019-02-22 um 13 23 18

and here's what this PR does:

bildschirmfoto 2019-02-22 um 13 22 40

So copying the file over is the expected bahvior, correct?

**Comment by pmuens** [comment]
Ok, another update real quick. I just used `master` and deployed the aforementioned service 🔝.

While Serverless doesn't copy the file into the `.serverless` directory it figures where the file is and uploads it to S3 nevertheless.

@dortega3000 could you use the recent `master` and check if the problem you're addressing with this PR has already been resolved? When using the setup I shared above you should see the `bar.zip` file in your S3 bucket.

**Comment by dschep** [comment]
Yup, that's the behaviour i'd expect.

**Comment by pmuens** [comment]
Hey @dortega3000 thanks again for taking the time to work on this 👍

I just tried to reproduce this bug running `master`. (Un)fortunately I cannot reproduce the behavior you're describing based on the setup I shared above. The `.zip` artifact is correctly uploaded to the deployment S3 bucket and the layer gets successfully created.

I'll close this PR for now since it seems like it's fixed. Feel free to re-open if this is not the case.

**Pull request closed without merging**
