### PR TITLE
fix(AWS API Gateway): Ensure proper `apiId` resolution

### PR DESCRIPTION
**Pull request by pgrzesik**
Closes: https://github.com/serverless/serverless/issues/10220

related: https://github.com/serverless/serverless/pull/10177

cc @vicary

### CODE REVIEW

**Comment by vicary** [comment]
@pgrzesik Thanks heaps!

**Review by medikoo — COMMENTED** [review]
Why this was not picked by test, which is supposed to test that case?

**Comment by pgrzesik** [comment]
> Why this was not picked by test, which is supposed to test that case?

When investigating, I've realized that it's not really possible to test it with unit tests, as the use case where the `apiName` has to be generated and is not available in compiled CloudFormation does not happen if no plugins are involved so the test wasn't really covering that case. I've changed the test to be more generic and left it as we don't have too many `runServerless` tests that cover that part of logic.

**Review by medikoo — APPROVED** [review]
Thanks for explanations, makes sense

**Pull request merged**
