### PR TITLE
Dockerfile layer path invalid on win32

### PR DESCRIPTION
**Pull request by leogono**
Related issue: https://github.com/serverless/serverless/issues/7489

I had the same issue on Windows 10. I saw that no one created a PR yet. But credits should go to @stevebaldwinelectroneum

Closes: #7489

### CODE REVIEW

**Comment by leogono** [comment]
yep, will do. :)

**Comment by leogono** [comment]
weird, still getting formatting issue on check. But it work out well locally.
image

**Comment by medikoo** [comment]
@leogono for `prettier-check:updated`, your master needs to be in sync with this repo. Maybe there's some issue with that.

You may also confirm by checking all files (not just updated) via `npm run prettier-check`.

Still, CI clearly says:

```
ib/plugins/aws/invokeLocal/index.js
Code style issues found in the above file(s). Forgot to run Prettier?
`prettier -c lib/plugins/aws/invokeLocal/index.js`
```

**Comment by medikoo** [comment]
Closing, as it was addressed with https://github.com/serverless/serverless/pull/8273

**Pull request closed without merging**
