### PR TITLE
docs(markdown) : lint updates

### PR DESCRIPTION
**Pull request by SachinKSingh28**
Just thought to contribute by fixing some lint warnings I saw when going through contributing guidelines.

### CODE REVIEW

**Review by medikoo — CHANGES_REQUESTED** [review]
@SachinKSingh28 great thanks for all improvements! They look good. Still for consistency we also expect all markdown documents to follow Prettier rules. Can you ensure that Prettier style is respected (currently CI fails because it doesn't)

**Comment by SachinKSingh28** [comment]
@medikoo thanks and sorry for my ignorance! I just noticed a lot of other markdown files so was just wondering if it would be better to add something like [markdownlint](https://www.npmjs.com/package/markdownlint) to the PR flow. I can try to create a separate pull request for that.

**Comment by medikoo** [comment]
> @medikoo thanks and sorry for my ignorance! I just noticed a lot of other markdown files so was just wondering if it would be better to add something like markdownlint to the PR flow. I can try to create a separate pull request for that.

@SachinKSingh28 that sounds as a great idea. Still I wonder how Prettier rules work with it. We need to ensure those do not contradict each other.

Let us know

**Comment by SachinKSingh28** [comment]
@medikoo I'll try to run both locally to see if they contradict. I'll post the result on this PR, I'm sure we can figure out a markdown config with which both can co-exist.

**Comment by medikoo** [comment]
@SachinKSingh28 Do you have any update on that?

**Comment by medikoo** [comment]
@SachinKSingh28 Thanks for the so far effort, still due to lack of updates I'm going to close it. If you feel like revisiting the subject, do not hesitate, I'll happily reopen the PR.

**Pull request closed without merging**
