### PR TITLE
[V3] Add NodeJS 22 to supported AWS Lambda Runtime

### PR DESCRIPTION
**Pull request by vipomage**
- Update `awsLambdaRuntime` 
  - Add `nodejs22.x`

Closes: #12922

### CODE REVIEW

**Comment by evan1715** [comment]
why wasn't this merged?

addresses 
https://github.com/serverless/serverless/issues/12914#issuecomment-2494054948 
https://github.com/serverless/serverless/issues/12916#issuecomment-2494056788 
#12922 
#12963 

helps maintain brand loyalty to switch to and pay for v4 later instead of just going to [sst](https://sst.dev/), [cdk](https://docs.aws.amazon.com/cdk/v2/guide/home.html), [amplify v2](https://docs.amplify.aws/), and protects legally for easily arguable "[critical security and bug fixes](https://www.serverless.com/blog/serverless-framework-v4-a-new-model)" under a major runtime update. notice of node 22 in v3, its release, this pull request, and multiple comments were created in 2024.

https://github.com/serverless/serverless/issues/12922#issuecomment-2526886276 
https://github.com/serverless/serverless/issues/12922#issuecomment-2563870220 
it is not a feature, it's categorized as "security and bug" 

{F81C460B-2311-4350-8BC0-3C57858B855F}


_temporary_ alternative:
1. yarn patch serverless
2. add nodejs22.x after searching for nodejs20
3. yarn patch-commit -s "the folder"
4. yarn

**Comment by domdomegg** [comment]
@evan1715 it looks like the PR wasn't closed by the serverless team, but by the community submitter. I've recreated the PR here: https://github.com/serverless/serverless/pull/13013

**Comment by evan1715** [comment]
@domdomegg you are correct. i did not clearly distinguish that in my response. i apologize, and i appreciate you making another PR to solve it.
i see your PR was immediately closed after you submitted it without any response from the serverless team. https://github.com/serverless/serverless/pull/13013#event-16154070077

the handling of this from serverless is quite poor. after consideration, i've decided that our company will not continue into v4 even though we had planned to. if they can't handle something like this, then how could we entrust them into v4. quite a loss of potential revenue for them.

**Comment by austencollins** [comment]
As mentioned in the other PRs doing this, we are no longer maintaining V3 and have moved on V4. If you don't feel V4 is right for you, we understand, and wish you the best of luck.

**Pull request closed without merging**
