### PR TITLE
chore: lodash get method replaced with pure javascript

### PR DESCRIPTION
**Pull request by PunitSoniME**
Replace _.get with pure javascript code in order to reduce dependency on lodash

Addresses: #7747

### CODE REVIEW

**Review by medikoo — CHANGES_REQUESTED** [review]
@PunitSoniME great thanks for this work. Yet intention of #7747 was to replace `_.get` only in straightforward cases e.g. `if (_.get(definitelyExistingObject, 'foo'))` can be replaced with `if (definitelyExistingObject.foo)` 

We should not introduce any `_.get` counterpart for that.

With next major, when we will drop support for Node.js v12, we would be able remove `_.get` completely by replacing it with [Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

**Comment by GrahamCampbell** [comment]
Could we could go ahead and remove node 12 support in a PR right now (I am happy to provide a first attempt at such a PR - though I am not familiar with all places in the codebase that are due to be refactored/cleaned up a little)? Node 12 has been EOL for some time, and GitHub Actions are running stuff that asks for node 12 on node 16 (https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/), effective May 18th.

**Comment by medikoo** [comment]
> Could we could go ahead and remove node 12 support in a PR right now

We will do that with the next major release (so v4), as removing support for any Node.js release (even EOL'd) is a breaking change

**Comment by GrahamCampbell** [comment]
> as removing support for any Node.js release (even EOL'd) is a breaking change

I don't agree here, actually. Correctly specified version constraints on the node version don't make changing supported versions breaking.

**Comment by medikoo** [comment]
@GrahamCampbell it is breaking. In general, if something that worked before upgrading to a new release stopped working, it means there's a breaking change in the release
For users (or CIs) still working with Node.js v12, it'll be breaking to drop support for this version suddenly.

**Pull request closed without merging**
