### PR TITLE
Fix deploy function command at quick start.

### PR DESCRIPTION
**Pull request by n-ina**
## What did you implement:

I proceeded according to the procedure, but there was a part that failed.

1. run `serverless create --template aws-nodejs --path my-service` referring [Create a Service](https://github.com/serverless/serverless#create-a-service)
2. run `serverless deploy -v` referring [Deploy a Service](https://github.com/serverless/serverless#deploy-a-service)
3. run `serverless deploy function -f myfunction` referring [Deploy Function](https://github.com/serverless/serverless#deploy-function)

Following error occured.
```
$ serverless deploy function -f myfunction
Serverless: Deploying function: myfunction...
 
  Serverless Error ---------------------------------------
 
     Function "myfunction" doesn't exist in this Service
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.4.3
     Serverless Version: 1.2.1
``` 

## How did you implement it:

I fixed deploy function command at [README.md](https://github.com/serverless/serverless#deploy-function).

## How can we verify it:

This line runs without failure.
https://github.com/serverless/serverless/commit/31fdb80fac724b4fdb4f70094f86e60d04ada3b7#diff-04c6e90faac2675aa89e2176d2eec7d8R60

## Todos:

- [x] Write documentation

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by pmuens** [comment]
Nice catch! 👍 

Could you quickly rebase (we've merged a fix for the linting issue recently) so that we can merge this?

**Comment by n-ina** [comment]
Thank you for reply. Now I've merged some recently issues. Can you merge this request?

**Comment by dougmoscrop** [comment]
Rather than merge you should `git pull --rebase`

**Comment by n-ina** [comment]
Sorry for bothering 🙇  I understand 💡 
Now I fixed my branch. Please review this branch status again.

**Comment by pmuens** [comment]
Great! Thank you for rebasing @n-ina 👍 

And thank you for the explanation @dougmoscrop 💯

**Pull request merged**
