### PR TITLE
dep: add eslint plugin dependency

### PR DESCRIPTION
**Pull request by jalateras**
Before submitting a PR, please note the following:

[] Make sure that there's an issue opened that discuss this fix/feature. This is not required for simple PRs (ie. fixing a typo in README), but we just want to make sure you don't waste your time on a feature that we don't intend to support/maintain.
[] Make sure that you've tested your changes thoroughly.
[] If there are some side effects to your changes (whether positive or negative), please mention them in your PR so that we can discuss how to avoid them.

Above all, we thank you so much for your contribution! :)

### CODE REVIEW

**Comment by jalateras** [comment]
Are you folks committed to complying to the eslint rules. Currently, there are over 5K issues...and that's just in the `lib` directory. Happy to lend a hand here though.

```
✖ 5982 problems (5931 errors, 51 warnings)
```

**Comment by flomotlik** [comment]
@jalateras the new code in the v1.0 branch is fully fixed with eslint, thanks for your proposal. Closing this for now as this is fixed on the separate branch. Would love to keep you as a contributor if you're open to that!

**Comment by jalateras** [comment]
@flomotlik certainly

**Comment by flomotlik** [comment]
Great, we'll be sharing more info about the future of Serverless over the next weeks, please feel free to jump in anywhere you like and where it makes sense for you in terms of feedback or code. Happy to have you!

**Pull request closed without merging**
