### PR TITLE
fix(AWS sqs): Ensure only `ARN` in plain string form is allowed as direct `sqs` event assignment

### PR DESCRIPTION
**Pull request by sdas13**
Closes: #9723

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
@sdas13 thanks for contribution! Please mark PR as ready for review, once it's finalized.

**Review by medikoo — CHANGES_REQUESTED** [review]
@sdas13 thanks for picking this up. Still proposed implementation doesn't reflect the agreed solution (as outlined here: https://github.com/serverless/serverless/issues/9723#issuecomment-878849456)

If for some reason you do not agree with that, best if you elaborate in the issue first

**Comment by sdas13** [comment]
Hey @medikoo 
Thanks for the feedback. I will use `awsArnString` at the top level. 
https://github.com/serverless/serverless/blob/317cfe1e91eb7ba58fdb2a151a7cb4224ed21a37/lib/plugins/aws/package/compile/events/sqs.js#L17


But in case of passing CF intrinsic functions directly to sqs input, there will be a configuration warning that `should have required property 'arn'` but the `Type Error` will be still there, since `EventSourceArn` will become undefined
https://github.com/serverless/serverless/blob/317cfe1e91eb7ba58fdb2a151a7cb4224ed21a37/lib/plugins/aws/package/compile/events/sqs.js#L62

Should it be handled as well or we just fix the schema?

**Comment by medikoo** [comment]
> But in case of passing CF intrinsic functions directly to sqs input, there will be a configuration warning that should have required property 'arn' but the Type Error will be still there, since EventSourceArn will become undefined

@sdas13 Can you provide an example of a configuration that will raise this problem? Sorry, from description it's not perfectly to me

**Comment by sdas13** [comment]
```
functions:
    eventHandler:
       handler: handler.test
       events:
          - sqs: !ImportValue MyExportedQueueArnId               
```

@medikoo this configuration would throw a `Type Error`

**Comment by medikoo** [comment]
> @medikoo this configuration would throw a Type Error

And that's ok, as that'll become invalid by schema (Solution is to update schema so only ARN in plain string form is allowed as direct `sqs` event assignment, and CF intrinsic functions are supported only in object configuration form (so when `arn` is defined as a property on object assigned to `sqs`)

**Comment by sdas13** [comment]
thanks @medikoo I will update the PR

**Review by medikoo — APPROVED** [review]
Thank you @sdas13 ! That looks great :)

**Comment by sdas13** [comment]
Thank you for your guidance @medikoo

**Pull request merged**
