### PR TITLE
InvokeLocal/Java: support POJO input and different handler names

### LINKED ISSUE #4526: can't invoke scala locally
# This is a Bug Report

## Description

* What went wrong? Function was not invoked
* What did you expect should have happened? Function was invoked
* What was the config you used? newly generated project from aws-scala-sbt template
* What stacktrace or error message from your provider did you see? n/a

Similar or dependent issues:
#2864 

## Additional Data

This happens because the handler takes an object as input, but InvokeBridge is trying to call it with a `Map<String,Object>` (AWS supports [other types](http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-req-resp.html) too).
I'm working on a patch that will instantiate the object and set its properties via reflection using java beans.

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: macOS 10.13.1 (17B1003)
* ***Stack Trace***:
```
~/D/I/s/aws-scala-sbt ❯ sls invoke local -f hello
Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.
java.lang.IllegalArgumentException: argument type mismatch

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.serverless.InvokeBridge.invoke(InvokeBridge.java:61)
	at com.serverless.InvokeBridge.<init>(InvokeBridge.java:32)
	at com.serverless.InvokeBridge.main(InvokeBridge.java:86)
```

### PR DESCRIPTION
**Pull request by zydeco**
## What did you implement:

InvokeLocal/Java:
* Add support for [handlers with POJO input type](http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-req-resp.html)
* Support different handler names (`package.class::method-reference`)
* Fixes #4526

## How did you implement it:

The Java bridge for InvokeLocal will resolve the handler method using [the same rules as AWS](http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-handler-types.html):
* Use the method name specified on the handler (`package.class::method-reference`), or `handleRequest` by default.
* Select the method with the largest number of parameters.
* If two or more methods have the same number of parameters, AWS Lambda selects the method that has the Context as the last parameter.
* If none or all of these methods have the Context parameter, then the behavior is undefined.

Then, if the resolved handler's first argument isn't assignable from `HashMap<String,Object>`, it will be assumed to be a POJO, and InvokeBridge will instantiate it and set its properties with Java beans. This is used in the scala template.

There are still input types that remain unsupported:
 * String
 * Integer
 * Boolean
 * List
 * Streams

The AWS documentation says it will linvoke the method with most parameters, but we only support two variants (it wasn't clear what the extra parameters should be):
 * One parameter: input
 * Two parameters: input and Context

## How can we verify it:

1. Scala template can now be invoked locally (uses POJO input):

```
sls create --template aws-scala-sbt
sbt assembly
sls invoke local -f hello
```

2. Invoking correct function when changing name:
* set handler to `hello.Handler::handleHello` in `serverless.yml`
* rename `handleRequest` to `handleHello` in `Handler.scala`

```
sbt assembly
sls invoke local -f hello
```

3. Example based on the aws-java-maven template, with a POJO input and a differently named handler: 
https://gist.github.com/zydeco/a2499a4995d14a3801a654e3fac044b6

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by zydeco** [comment]
It seems travis hasn't picked up this PR yet, is there anything I can do about it?

**Comment by horike37** [comment]
Thank you for sending the PR @zydeco :+1: 
Umm, I'm not really sure why missed kicking the Travis check :thinking: 
Cloud you please push an empty commit on top of this branch so that Travis can pick up the PR again?

**Comment by HyperBrain** [comment]
@zydeco You could also squash your commits and push them again to trigger a new Travis run. Somehow the current build is not accessible at all. It seems to be screwed somehow.

**Comment by zydeco** [comment]
It didn't seem to help, shall I close it and do a new PR?

**Comment by HyperBrain** [comment]
@zydeco I think this is the only way out 😄 as even a new commit did not change it.

**Pull request closed without merging**
