### PR TITLE
MD5 hash service name

### PR DESCRIPTION
**Pull request by ervin210**
## What did you implement:

Closes #XXXXX

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by lorengordon** [comment]
Can we use something stronger than md5? Like at least sha256? Usage of md5 will not work on systems where FIPS-mode is enabled.

**Comment by ervin210** [comment]
yes

**Comment by pmuens** [comment]
Thanks for opening @ervin210 and thanks for the feedback @lorengordon 👍

Yes, we could use something from the node core `crypto` package. This way we could save another dependency we need to introduce.

@ervin210 could you update the PR template when you're done? Thanks in advance and let us know if you need any help here!

**Comment by ervin210** [comment]
Hello,
 Thanks  and me for  help  appreciate  lot . I’m  little lost    where   i  can install   PR templet ?
any link   please?
Thanks

**Comment by pmuens** [comment]
Hey @ervin210 thanks for getting back 👍

The [PR template](https://github.com/serverless/serverless/blob/master/.github/PULL_REQUEST_TEMPLATE.md) is basically the PR description (https://github.com/serverless/serverless/pull/4271#issue-258106763). It has different sections which help us to triage, test and validate a PR. It would be nice if you could update the description so that we can see which issue this PR refers to and what the current state is.

Let us know if you need any help here 💯

**Comment by horike37** [comment]
Closing this issue for now since it took for a long time without any activity.
Feel free to re-open if you want to restart working on this.

**Pull request closed without merging**
