### PR TITLE
Removing selfReferences

### PR DESCRIPTION
**Pull request by pjmattingly**
Addresses #11273

### CODE REVIEW

**Comment by pjmattingly** [comment]
Removing instances of `selfReferences` as per #11273.

**Comment by pjmattingly** [comment]
Also, do we want to remove `lib/plugins/aws/utils/find-references.js`?

With these removals, this function is called nowhere else in the code. Also, removing this would remove a function that depends on lodash.

**Review by medikoo — COMMENTED** [review]
> Also, do we want to remove lib/plugins/aws/utils/find-references.js?

@pjmattingly yes, if it's not used anywhere else, it definitely should be removed.

Thank you!

**Comment by pjmattingly** [comment]
Okay, I made the change and removed find-references.js, as well as its tests. Then testing and other checks look good.

**Review by medikoo — APPROVED** [review]
Thanks @pjmattingly looks great 👍

**Pull request merged**
