### PR TITLE
Populate objects if default syntax targets an object

### LINKED ISSUE #4509: "Fallback/Overwrite" variable technique doesn't recurse into objects
# This is a Bug Report

## Description

When the serverless configuration is resolving a variable that is the overwrite/default value technique, when resolving any of the options that refer to an object, it does not resolve the variables within that object.

So given a configuration:
 ```
provider:
  name: aws
  stage: dev

custom:
  test: ${env:I_DONT_EXIST, self:custom.nested}
  nested:
    child: ${self:provider.stage}
```
In my plugin I expect `serverless.service.custom.test` to be
```
{
  child: "dev"
}
```
But what I get is 
```
{
  child: "${self:provider.stage}"
}
```

Similar or dependent issues:
 * #3604

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: Windows 10
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

### PR DESCRIPTION
**Pull request by HyperBrain**
## What did you implement:

Closes #4509 

## How did you implement it:

Centralized object population in `getValueFromSource` as proposed by @dsole in https://github.com/serverless/serverless/issues/4509#issuecomment-348369084. Now default variables will be resolved correctly and are populated in case they target objects. Also changed/moved the populateObject unit test to match the new situation and implementation.

As only populateProperty and overwrite called the getValueFromSource method, this should not have any side effects. However it should be tested thoroughly.

## How can we verify it:

Use the variable syntax with default values, where the default value resolves to an object that itself contains variable references again.

Example:
```
provider:
 name: aws
 stage: dev

custom:
 test: ${env:I_DONT_EXIST, self:custom.nested}
 nested:
   child: ${self:provider.stage}
```

Test should now be resolved to:
```
{
  child: "dev"
}
```

⚠️ The verification should also include tests, that all other variable reference mechanisms are not broken (e.g. the test should include SSM, CF, file, env, etc)!

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by HyperBrain** [comment]
I did a test with a file include as follows:
```yaml
# serverless.yml
custom:
  included: ${file(vars.yml)}
  stage: ${self:custom.included.myVar1.stage}

functions:
  first:
    handler: first.handler
    environment:
      MY_VAR: ${self:custom.stage}
```
and
```yaml
# vars.yml
myVar1:
  stage: ${opt:stage}
```
Result:
`MY_VAR` is correctly set to `dev` if I invoke `serverless package -s dev`, so the population of files seems to work. Double checks appreciated.

**Comment by HyperBrain** [comment]
Thanks for the reviews. I will merge it later (after the other one).

**Comment by erikerikson** [comment]
Taking another look here and I think this proposes improper factoring.  It probably fixes the bug but not by fixing the root issue.  Looking at what that root fix would look like.

**Comment by HyperBrain** [comment]
@erikerikson Would be happy to have some alternative thoughts. The initial scope of this fix was, that the default values were not resolved at all, which is fixed by this PR (both paths now check for objects to resolve).
As you have a more complete picture of the inner resolution after working on the circular vars, please advise how this can be fixed in a better way.

**Pull request merged**
