### PR TITLE
Throw an error if artifact is bigger than 50MB

### PR DESCRIPTION
**Pull request by RafalWilinski**
## What did you implement:

Closes https://github.com/serverless/serverless/issues/4399

## How can we verify it:

```bash
mkfile -n 1500m bigfile.js  
npm install axios aws-sdk puppeteer --save      # Some random big modules
serverless package
```
## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by RafalWilinski** [comment]
Any ideas how to test it? Creating file which after compression will be 50MB doesn't seem like a good option (slow, might timeout on slower systems)

@pmuens @horike37 @HyperBrain

**Comment by vladgolubev** [comment]
@RafalWilinski not sure if this a better idea, but can it be in memory?

https://github.com/webpack/memory-fs
https://github.com/eldargab/node-fake-fs
https://github.com/tschaub/mock-fs

**Comment by jaikdean** [comment]
Bear in mind that the 50MB limit documented by AWS Lambda is not strictly imposed. A 55MB zip will be fine if the unzipped contents are under the their 250MB limit.

I feel this should throw a warning rather than aborting deployment.

**Comment by vladgolubev** [comment]
@jaikdean regarding 50 vs 55 mb limit. I have a feeling AWS uses mebibytes in their limits. Which results in slightly more megabytes

https://blog.codinghorror.com/gigabyte-decimal-vs-binary/

image

**Comment by jaikdean** [comment]
@vladgolubev A good thought, but it’s not the case. [This post](https://hackernoon.com/exploring-the-aws-lambda-deployment-limits-9a8384b0bec3) goes into detail about various experiments, which ultimately showed the 50MB limit to be unenforced when uploading to S3.

This is undocumented behaviour, so AWS could start enforcing the limit any time, but I still believe a warning is the best option at this point.

**Comment by vladgolubev** [comment]
@jaikdean wow, thanks. So then we can provide even better feedback

* Hard stop if folder >=250mb, even before starting zipping
* Warn when zip reaches 50 MB 
* Error when zip reaches 250 MB

**Comment by HyperBrain** [comment]
> Hard stop if folder >=250mb, even before starting zipping

This is quite dangerous. If you are working with plugins like `serverless-webpack` your output size will me much less than your actual source folder. Any kind of these checks should not be made.

**Pull request closed without merging**
