### PR TITLE
update log for easy copy/paste of url

### PR DESCRIPTION
**Pull request by DavidWells**

### CODE REVIEW

**Comment by nikgraf** [comment]
Hmmm, why using console.log? Doesn't this go against the consistency of the whole framework only using serverless.log?

**Comment by pmuens** [comment]
@nikgraf godd question. Yes it does (I'm also not a that happy with the inconsistency right now).

However we're planning to monkey-patch `console` to get rid of `this.serverless.cli.log` (since this is not available in e.g. the `utils` files).

You can read more about it in @DavidWells comment here: https://github.com/serverless/serverless/pull/3844#issuecomment-311140046

**Comment by nikgraf** [comment]
@pmuens hmmm, ok I let you guys decide.

To me personally this inconsistency with color and none-prefix makes the experience a bit worse then better.

**Comment by pmuens** [comment]
> @pmuens hmmm, ok I let you guys decide.
> To me personally this inconsistency with color and none-prefix makes the experience a bit worse then better.

Yes, thanks for the feedback. Yes, we should definitely offer a consistent experience here 🤔  (from a dev and users perspective).

**Pull request merged**
