### PR TITLE
Added proxy handling in the aws util

### LINKED ISSUE #223: Managing corporate proxies
Hey JAWS team!

While this project is reallllyyyy amazing, I'm kind of breaking my teeth with corporate proxies, and ways to deploy via jaws dash. The error I get is:

```
{ [NetworkingError: connect ECONNREFUSED 
...

```
I was used to declare this on my Mac:

```bash
declare -x http_proxy="http://IP:PORT"
declare -x https_proxy="http://IP:PORT"
```

which is fine with NPM, Bower, and all these kind of package managers.

I also tried to add env vars in the .env file (as with HTTP_PROXY and HTTPS_PROXY), but this does nothing, or at least I'm not doing it the right way :smile:.

Do you guys have a hint for me please? :)

### PR DESCRIPTION
**Pull request by Ninir**
This adds proxy configurations checking the environment variables. Even if the name does not matter, I thank @sixlettervariables for the original idea.

Closes #223.

### CODE REVIEW

**Comment by sixlettervariables** [comment]
Looks good.

**Comment by ac360** [comment]
@Ninir Thanks for this :)  Just need  a few more days to finish the ES6 refactor, then I will merge this in!  I appreciate your help very much.  You too @sixlettervariables!

**Comment by Ninir** [comment]
Closing as obsolete. Will open a new one for the new project ;-)

**Comment by eahefnawy** [comment]
:+1:

**Pull request closed without merging**
