### PR TITLE
Pass through aws_session_token to allow temporary security credentials

### PR DESCRIPTION
**Pull request by davidcai**
To make temporary security credentials work, this PR passes the optional `aws_session_token` defined in ~/.aws/credentials to the awsConfig variables used across Serverless code. For more info about `aws_session_token`, please see: https://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs

Additionally, in the `ProjectCreate` action, I added code to save `aws_session_token` as `SERVERLESS_ADMIN_AWS_SESSION_TOKEN` in admin.env for later references.

On a side note, because the aws_session_token will expire, and users have to renew credentials, the saved credentials in `admin.env` will also have to be renewed, it will be nice to have an action (e.g., AdminEnvSync) that will pull the credentials from ~/.aws/credentials and save them in admin.env. You already have the code to do that at the beginning of the _validateAndPrepare function in ProjectCreate.js (around line 286).  But I'm thinking to externalize the code to a separate action. (This PR didn't include this change.)

### CODE REVIEW

**Comment by hauboldj** [comment]
I think that ideally serverless should not pass any credentials to the aws-sdk. This would allow serverless to be run on an ec2 instance using IAM roles as part of a CI job. If needed then serverless could set environment variables to provided credentials to the aws-sdk. This would allow using aws profiles and temporary credentials. I would also like to see support for assuming a role with MFA.

**Comment by davidcai** [comment]
@hauboldj Agree. Would love to see Serverless using credentials provided by environment variables.

**Comment by ac360** [comment]
Thanks all, we will get to this :+1: Sorry for the delay

**Comment by hauboldj** [comment]
Great. I created a pull request to show the way I was starting to work around it.

**Comment by erikerikson** [comment]
This is also implemented in https://github.com/serverless/serverless/pull/536

**Comment by erikerikson** [comment]
Checking differences.

**Comment by erikerikson** [comment]
So, @davidcai you want to replace the duplication of your credentials in admin.env with the following (works today, except for session token):

SERVERLESS_ADMIN_AWS_PROFILE=[YOUR_PROFILE]

Then you won't have to synchronize your credentials at all.  We should just save the profile by default instead of duplicating credentials.  I thought I created an issue on that point but don't see it.

PR https://github.com/serverless/serverless/pull/536:
1. Will also use ~/.aws/credentials defined credentials if SERVERLESS_ADMIN_AWS_PROFILE is set
2. Checks for environmentally defined credentials
3. Reads the duplicated credentials in admin.env.

It also has the advantage of being free from conflicts with master (at the moment).

**Comment by davidcai** [comment]
Thank you. I will definitely check it out. Still hope session token will work just like the other AWS credential values.

**Comment by erikerikson** [comment]
This is implemented in v0.5

**Comment by ac360** [comment]
@davidcai Thanks for this :)  We have added support for this in previous versions, thanks to @erikerikson's help.

**Pull request closed without merging**
