### PR TITLE
Spotinst - adding Java8 template and updating docs

### PR DESCRIPTION
**Pull request by jeffnoehren**
## What did you implement:

Created Java8 template for spotinst
Created docs for new template
Cosmetic update to docs for Spotinst Document Store feature

Closes #XXXXX

## How did you implement it:

Document change
Added template

## How can we verify it:

Docs change in Spotinst Provider
Template in lib/create/templates/spotinst-java8

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by horike37** [comment]
Hi @jeffnoehren thank you for sending the PR as always :+1: 
Currently, we're in a merge freeze until next week, when 1.25 is going to be released.
We will review after that. 

By the way, could you please tell us why is this PR a breaking change?

**Comment by jeffnoehren** [comment]
Hey @horike37 Sorry that was a mistake on my part. This is for sure not a breaking change lol I know you said that you are having a merge freeze before the next release but I was wondering if it would be possible to get our changes in for 1.25? We are introducing a new template and we would like to have it live ASAP :)

**Comment by horike37** [comment]
Sorry, This PR will be shipped in v1.26.
If we break a merge freeze, it would make a muddle of the maintainer team and it would be hard to ensure the quality of the framework.

Thank you for your understanding in advance.

**Comment by jeffnoehren** [comment]
Yea I understand! Are the releases on a regular schedule? I would like to be ahead of it for the next one haha

**Comment by horike37** [comment]
Currently, we don't have a regular cadence, so we release whenever a sufficient number of PRs are merged and feel comfortable with it. 

The release two times before is 07.11.2017, so it may be at 1,2-month intervals.

**Comment by jeffnoehren** [comment]
Yea I just checked the previous releases and saw that as well. Ok thank you for the heads up!! Also do you post somewhere a few days before freezing? Sorry for all the questions I just want to be prepared for next time :)

**Comment by horike37** [comment]
Don't worry :+1: 
We often discuss it with core member at [slack channel](https://join.slack.com/t/serverless-contrib/shared_invite/MjI5NzY1ODM2MTc3LTE1MDM0NDIyOTUtMDgxNTcxMTcxNg)
You might want to join there.

**Comment by jeffnoehren** [comment]
Thanks just joined!!

**Comment by jeffnoehren** [comment]
Hey sorry that is my bad! I just updated the appropriate docs and they should work! let me know if this is correct!

**Comment by jeffnoehren** [comment]
Yay cool! thank you

**Pull request merged**
