### PR TITLE
feat(AWS Lambda): Add support for dotnet8 runtime

### PR DESCRIPTION
**Pull request by martincostello**
Add support for the new .NET 8 runtime.

Closes: #12367

### CODE REVIEW

**Comment by martincostello** [comment]
Hasn't rolled out to all regions yet, but it's visible to me in us-east-1.

image

See also https://github.com/aws/aws-lambda-dotnet/issues/1611#issuecomment-1956588227

**Review by normj — APPROVED** [review]

**Comment by martincostello** [comment]
AWS Lambda now supports .NET 8 in all regions - [_Introducing the .NET 8 runtime for AWS Lambda - AWS Compute Blog_](https://aws.amazon.com/blogs/compute/introducing-the-net-8-runtime-for-aws-lambda/)

**Review by raydav — APPROVED** [review]

**Comment by BassemPolestar** [comment]
any updates on when the .NET 8 runtime will be available ?

**Comment by martincostello** [comment]
The .NET 8 runtime is available in all AWS regions today.

**Comment by BassemPolestar** [comment]
@martincostello yes I know 😊 I mean when can someone merge this pr so we can update the runtime in serverless

**Review by manemarron — APPROVED** [review]

**Review by Monigass — APPROVED** [review]

**Review by cjsanchezb — APPROVED** [review]

**Review by rsl-pseudocode — APPROVED** [review]

**Comment by adam-knights** [comment]
@Mmarzex any chance of a merge and release?

**Review by ryanbell1997 — APPROVED** [review]

**Comment by Mmarzex** [comment]
Hi @adam-knights apologies on this. Our team has been focused on preparing the v4 beta release. This will be available then.

**Comment by vinnie1234** [comment]
@Mmarzex only in V4? Or will you also merge this then to V3?

**Comment by martincostello** [comment]
It would be quite trivial to push a new v3 release with this one change (like was done for `provided.al2023`) rather than make people wait for that release and _also_ tie it in with needing people to use a non-stable version of a future version of serverless?

**Comment by ryanbell1997** [comment]
Also, when could we expect v4 beta to be released?

**Comment by Monigass** [comment]
image

**Comment by andremantaswow** [comment]
we're waiting for this on v3. any news?

**Comment by ryanbell1997** [comment]
@andremantaswow I believe you can start using V3 now. You need set your serverless account up for it, but then I just needed to add a build step to my workflow file to authenticate with serverless, and it then deploys with .NET 8 runtime.

Checkout the readme for v3 branch: https://github.com/serverless/serverless/tree/v3

**Comment by karadjov** [comment]
@Mmarzex your team is blocking multiple products to upgrade to runtime which is already available for 2 months. 
Still V.4 Beta is not released, so who knows when V.4 GA will be released?
It is not professional to block simple PRs this way. You can easily release this runtime with V.3 so we do not have to wait months for simple change.

**Comment by martincostello** [comment]
I'm going to close this - it's 3 months old and the Serverless team appear to have no intention of doing a new v3 release to add this.

**Pull request closed without merging**
