### PR TITLE
remove invalid variable references from the documentation

### PR DESCRIPTION
**Pull request by duytrandev**
Closes: #8306

### CODE REVIEW

**Comment by duytrandev** [comment]
* Remove the mention about `{self:}` -> this was introduced at some point in the past but didn't work as expected and got removed by #8343

* Remove the mention about `{env:}` -> it was supposed to be a lazy way to import all environment variables into serverless according to the previous doc. Checked around but cannot seem to find any related implementation.
Confirmed by `...\test\unit\lib\configuration\variables\sources\env.test.js` that this syntax is not currently supported and should encounter error

**Review by medikoo — APPROVED** [review]
Looks great 👍 Thank you @duytrandev

**Review by medikoo — CHANGES_REQUESTED** [review]
@duytrandev can you ensure that changes follow Prettier formatting. CI failed due to that

**Comment by duytrandev** [comment]
hi @medikoo I updated my code to resolve the prettier issue
maybe it's worth noting in the PR template to run `npm run prettier-check:updated` instead of `npm run prettier`?

**Comment by medikoo** [comment]
> hi @medikoo I updated my code to resolve the prettier issue
maybe it's worth noting in the PR template to run npm run prettier-check:updated instead of npm run prettier?

`npm run prettier-check:updated` depends on a state of `main` in your fork. Did you have problems with `npm run prettier` ?

**Comment by duytrandev** [comment]
@medikoo I got a lot of `warn` notices to a point that I cannot tell any problem with my code even though I only updated 2 blocks of code

image

**Comment by medikoo** [comment]
> @medikoo I got a lot of warn notices to a point that I cannot tell any problem with my code even though I only updated 2 blocks of code

Maybe you have git configured on windows to change the end of line characters?

**Review by medikoo — APPROVED** [review]
Thank you @duytrandev ! Great improvement.

Small hint: To mark PR as ready for re-review, best is to simply re-request review in reviewers box (we receive notification of such action)

**Pull request merged**
