### PR TITLE
Make code coverage great again (return it back to 100% - ref: #3275)

### LINKED ISSUE #3275: Return code coverage back to proud 100%
# This is a tech debt issue

## Description

With time the [code coverage](https://coveralls.io/github/serverless/serverless) has slightly deteriorated, and not all the lines in the code are run during the tests execution. The current coverage is 97% - which is still a great number. But it would be much better to have complete coverage and make each line to be executed at least once.

This issue is open as a formal ticket for the subsequent PR I'm preparing.

## Additional Data

* ***Serverless Framework Version you're using***: latest `master` branch

### PR DESCRIPTION
**Pull request by zerkella**
## What did you implement:

Closes #3275

Implemented missing tests to make each line of code to be executed at least once. That is 100% code coverage. Also a few improvements in the tests and code.

## How did you implement it:

Added the missing tests.

## How can we verify it:

In order to verify - run tests and lint.
Here are the results on the PR code:

* [Travis CI](https://travis-ci.org/zerkella/serverless)
* [Coveralls](https://coveralls.io/github/zerkella/serverless)

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by pmuens** [comment]
Damn @zerkella you rock! Thank you so much for this! 🎉

**Comment by zerkella** [comment]
Sure :) not at all

**Comment by zerkella** [comment]
Hi @pmuens - is it possible to merge this PR?
Thanks!

**Comment by pmuens** [comment]
Hey @zerkella thanks for pining. We've put this PR on our "To be discussed" list (https://github.com/orgs/serverless/projects/1#card-1827109) and will come back once it's discussed.

Thanks again for working on our test suite! 💯

**Comment by zerkella** [comment]
Got it @pmuens - thanks for the update. Curious - what's the thing that the team wanted to discuss there?

**Comment by pmuens** [comment]
Hey @zerkella sure. 

The discussion is if it's necessary to have 100% test coverage or if it might slow the development process down because tests need to be updated frequently (e.g. if the console output is tested too strictly)...

**Comment by zerkella** [comment]
Thank you

**Comment by zerkella** [comment]
BTW @pmuens - testing strings and output was always valuable. It helped to find the bugs, when the functionality stopped working.

In order to make the tests lest fragile - the right tactic is to target not the whole messages ([like here](https://github.com/serverless/serverless/blob/master/lib/classes/CLI.test.js#L358-L363)), but rather key points ([like here](https://github.com/serverless/serverless/blob/master/lib/classes/CLI.test.js#L437-L438)). In such a way the tests indeed verify that the output looks correct, while at the same time they leave enough space to change the strings without breaking the tests.

**Comment by pmuens** [comment]
@zerkella thanks for the notes. 👍 

I agree. checking the whole message gets too cumbersome once it's updated. Doing a `contain` is a nice approach to still check the correctness while not going into too much detail.

**Comment by zerkella** [comment]
All right - from what I see this project is not that fast-pacing, and is not that friendly for contributions. Life's too short to waste it waiting :) You can either accept or not accept this PR, but my presence here is over. 

For your information here is a small list of the blocking issues I experienced with Serverless project contributions (maybe you can react and make it better for future contributors):
- It is 10th day after the current PR has been created, and it is neither accepted, nor rejected. This is so slow...
- I see 20 other PRs in the queue, waiting months. Which tells a lot.
- The communication is non-welcoming. E.g. I had a couple of questions for Eslam, but he just ignored email messages. And that Gitter is a joke - no response there from either Philipp or Eslam.

**Also, a friendly note about some fundamental challenges you might face in the future.** 

When I came here, my intent was to study the code via covering it with tests, then contribute the fixes, and then features (btw  - why I worked here? just for fun, because I had some free time). While I didn't get past phase 1 - because of the reasons mentioned above^^^, but I did study some code and found interesting stuff that the team might need to focus on.
1. The lifecycle event model is not going to work reliably in the long run. First, it needs directives like "put me before/after that plugin", "last/first in the queue" (+topological sorting of such listeners), and probably analog of "stopPropagation()" response from the listeners. Second, there will be numerous issues with plugins compatibility - when a plugin works fine alone, but breaks in real life when there are also other plugins working and changing something (this is a non-solved issue for all event-based frameworks). And third - there will be needed a mechanism to formalize relations/communication among plugins, when they need to share data and results, or when they have dependencies (hard or soft) on each other.
2. There needs to be more abstraction and configuration in the project. Lot of things are hardcoded somewhere deep inside the code, while the external systems actually do not treat such stuff as a contract. For example, when downloading function run logs only the ones with `$LATEST` string in the names are retrieved. But AWS doesn't say that it will always compose such log names. In general - there are many other similar places, where Serverless depends on strings, output, specific keys, non-guaranteed order of items, particular AWS behavior, etc. Serverless developers will  need to clearly expose/mark such stuff - to distinguish (and make easily modifiable) these weak external contracts from a solid non-changing core code.
3. There's a need for code reviews. This will definitely help the project. I've seen quite a big number of commits that had lesser or bigger flaws. A second pair of eyes would be definitely helpful.
4. There's a tech debt being accumulated, which damages reliability. Examples are: not all cases covered in the logic, inconsistency (e.g.: why sometimes {{console.log}} used, sometimes {{process.stdout.write}}, and sometimes Serverless's own wrapper above {{console.log}}), fragile dependency on particular output (as mentioned in 2.), etc. This needs to be accounted for and fixed. If the project is not reliable for businesses working with AWS - it will fail.

That's pretty it. 

I still wish you good luck as to a startup. Hopefully everything will work for you, guys.

Best,
Andrey

**Comment by eahefnawy** [comment]
Hey Andrey

Thanks for your honest feedback. I just wanna clear things out here. Those are my thoughts and don't necessarily represent the Serverless Team.

I 100% agree that we need to respond to PRs more quickly by doing a quick big picture review, which is something we discussed in a team meeting this week. The response doesn't have to either close or merge, but there are actually three options:

- Close - If we decided we don't want to support this feature for any reason.
- Put on hold - If we decided we want to support it, but it's not high priority enough to invest the time to review and test rigorously to keep the quality high.
- Merge - If we decided we want to support it and it's high priority and worth the time to review & test **now**

What we need to be better at imo is to actually communicate one of those statuses.

I hope you understand that we can't possibly keep being pulled by all PR/Issue that gets submitted by our users. This is a full time job and would take all our time away and won't move us forward according to a plan/priorities. We care about the greater good of our community more than a single user in our community. So we have to follow a plan based on priorities.

As for support, we can't possible answer all questions, especially by email, as we get a lot of those! We're not a support team and the framework doesn't come with support built in, which is why we created the Serverless Forum and the Gitter room. It's not for the team to be present, but for the community to help each other.

Also, I know we don't seem fast paced publicly within the framework, but we're actually very fast paced internally 😉 ... We're cooking a lot of stuff in the background that would serve the greater good of the community in the near future.

I hope you don't take all this personally Andrey 😊 ... I'll be doing my best in the future to keep contributors informed about the status of their PRs, hopefully they won't take it personally either.

Thanks for being with us @zerkella 🙌

**Comment by eahefnawy** [comment]
Ok for the spirit of responding quickly, I'm also gonna start and put my two cents on this PR while I'm here ... I personally don't want to merge this PR for something you pointed out which I agree > **We are accumulating great technical debt**. Merging this PR means that from now on we'll have to maintain all those tests you added, which are not necessarily that valuable (sorry 😕 ).

I don't believe we should strive for 100% test coverage. It's really not about the percentage, but more about covering what needs to be covered and maintain that.

**Pull request closed without merging**
