### PR TITLE
Add debug info & upload concurrency control

### PR DESCRIPTION
**Pull request by brianjd**
***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by eahefnawy** [comment]
@brianjd Thanks for interest in contributing. But I don't understand at all what you're trying to do here. There's no issue/discussion about the change you're making and you have no PR description. So I'm closing...

**Comment by brianjd** [comment]
@eahefnawy I thought the title was explanation enough.  It is related to https://github.com/serverless/serverless/issues/2988.  When packaging individually, Serverless attempts to upload all of the functions simultaneously, which doesn't work so well on slower connections, leading to deploy failures. This PR adds all of them to a queue and uploads them 5 at a time by default, or the concurrency can be set using SLS_UPLOAD_CONCURRENCY_LIMIT.

**Comment by brianjd** [comment]
@eahefnawy Also, when debugging is enabled, it will tell you which function is being uploaded.

**Comment by jamiewildehk** [comment]
I still face issues uploading to S3 that this PR could help with.

**Comment by pmuens** [comment]
> I still face issues uploading to S3 that this PR could help with.

Thanks for commenting @jamiewildehk 👍

Could you describe what errors / error messages you see and what service setup you use? Thanks in advance!

**Pull request closed without merging**
