### PR TITLE
fix: Drop an unnecessary newline from deploy output

### PR DESCRIPTION
**Pull request by o5**
Addresses: #9860

### CODE REVIEW

**Comment by pgrzesik** [comment]
Hello @o5 - could you please share the reason behind this change? What is wrong with the current output?

**Comment by o5** [comment]
Hello @pgrzesik - yes of course.

ServerLess 2.72.2
Screenshot 2022-02-04 at 15 07 19

ServerLess 3.0.1
Screenshot 2022-02-04 at 15 09 23

**Comment by pgrzesik** [comment]
What exactly is wrong with the provided screenshot? The additional newlines were added on purpose to make the output a bit more readable and highlight the line that shows the service, stage and region.

**Comment by o5** [comment]
Screenshot 2022-02-04 at 15 09 23

Screenshot 2022-02-04 at 15 18 47

**Comment by pgrzesik** [comment]
As I said - this is intentional for the reasons I've listed in previous comment - why do you think it should be removed?

**Comment by o5** [comment]
Is newline before first readable output also intentional? If yes, I'll close this but I've never met similar in other CLI tool.

**Comment by pgrzesik** [comment]
> Is newline before first readable output also intentional? If yes, I'll close this but I've never met similar in other CLI tool.

Yes, this is intentional to highlight visually the next line with service name, stage and region.

**Comment by o5** [comment]
> to highlight visually the next line with service name, stage and region.

This really not help :)

**Comment by pgrzesik** [comment]
> > to highlight visually the next line with service name, stage and region.
> 
> This really not help :)

Could you explain more what do you mean by that? We're open to feedback 💯

**Comment by o5** [comment]
@pgrzesik I already invested 35min of my time. Sorry, no more.

**Comment by pgrzesik** [comment]
Sure thing, hope you understand we cannot accept PRs without sufficient reasoning and explanation, we're happy to revisit if we get more reports. Have a good day 🙇

**Comment by o5** [comment]
You too.

**Pull request closed without merging**
