### PR TITLE
Fix windows go rework

### PR DESCRIPTION
**Pull request by dschep**
I failed to properly test it after a slight refactor befor emerge

### CODE REVIEW

**Comment by lolcoolkat** [comment]
@dschep I've tested the new code that's been added. However i'm still getting the `{"message": "Internal server error"}` after deploying a hello world function. Any ideas? :/ Here's a screengrab of the zip process with the file name and the new mode on the binaries..

img

**Comment by dschep** [comment]
hmm. odd @lolcoolkat, this is how it worked for me:
```
User@WinDev1811Eval MINGW64 ~
$ npm i serverless/serverless 2> /dev/null

User@WinDev1811Eval MINGW64 ~
$ sls create -t aws-go -p aws-go
Serverless: Generating boilerplate...
Serverless: Generating boilerplate in "C:\Users\User\aws-go"
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.37.0
 -------'

Serverless: Successfully generated boilerplate for template: "aws-go"

User@WinDev1811Eval MINGW64 ~
$ cd aws-go

User@WinDev1811Eval MINGW64 ~/aws-go
$ make
env GOOS=linux go build -ldflags="-s -w" -o bin/hello hello/main.go
env GOOS=linux go build -ldflags="-s -w" -o bin/world world/main.go

User@WinDev1811Eval MINGW64 ~/aws-go
$ sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service aws-go.zip file to S3 (10.8 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....................
Serverless: Stack update finished...
Service Information
service: aws-go
stage: dev
region: us-east-1
stack: aws-go-dev
resources: 16
api keys:
  None
endpoints:
  GET - https://089sn4eo5f.execute-api.us-east-1.amazonaws.com/dev/hello
  GET - https://089sn4eo5f.execute-api.us-east-1.amazonaws.com/dev/world
functions:
  hello: aws-go-dev-hello
  world: aws-go-dev-world
layers:
  None
Serverless: Removing old service artifacts from S3...
```

image

**Comment by lolcoolkat** [comment]
I'm not using MINGW64 @dschep so i'm not sure if the process is different. I'm just using normal Windows10 along with Command Prompt. So that process you have in the make file doesn't work with command prompt. I have the following:

````
build:
    set GOOS=linux
    go build -ldflags="-s -w" -o bin/hello hello/main.go
    go build -ldflags="-s -w" -o bin/world world/main.go
    go build -ldflags="-s -w" -o bin/auth auth/main.go
````

And then I do `sls deploy` and I get an error. Maybe its something to do with the make process not being correct? Do you mind trying your process on a Windows10 machine and just use regular Command Prompt (cmd) to deploy and see if u get the same thing?

**Comment by dschep** [comment]
@lolcoolkat `set GOOS=linux` doesn't seem to be working. I ran that make file in `cmd` and then ran `file bin/world` in my bash shell and it says it's an MSDOS binary.

**Comment by lolcoolkat** [comment]
Oh, okay maybe that’s my issue then. Any ideas for a work around just using cmd? I’m assuming ill need to use MINGW64 like you did?

**Comment by dschep** [comment]
@lolcoolkat I figured out how to get it to work. in `cmd` run:
```
set GOOS=linux
make
```

**Comment by lolcoolkat** [comment]
That worked @dschep thank you!!!!! <3

**Comment by lolcoolkat** [comment]
@dschep figured out how to do it in the Makefile btw :) Just had to add quotes!

````
build:
	set "GOOS=linux" && go build -ldflags="-s -w" -o bin/hello hello/main.go
	set "GOOS=linux" && go build -ldflags="-s -w" -o bin/world world/main.go
````
🎉 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
