### PR TITLE
Add API gateway + Lambda serving static html example

### PR DESCRIPTION
**Pull request by DavidWells**
Implement https://github.com/serverless/serverless/issues/2300

### CODE REVIEW

**Comment by andymac4182** [comment]
Be great to see this implemented with the new proxy support since it should be simpler due to no response template required.

**Comment by DavidWells** [comment]
@flomotlik these are doc changes. Any idea why CI is failing?

**Comment by flomotlik** [comment]
Yes we merged a PR that broke the build, @pmuens is working on a fix in #2294

**Comment by flomotlik** [comment]
@DavidWells this works now. Agreed with @andymac4182 that we should use the new proxy setting (this example won't work because it would use the new proxy but fail)

**Comment by mthenw** [comment]
@DavidWells took care of that example :)

**Pull request merged**
