### PR TITLE
Add ap-southeast-2 (Sydney) region

### PR DESCRIPTION
**Pull request by scotty-p**
##### Status:

Ready

##### Description:

API Gateway and Lambda recently released in ap-southeast-2 region. Updated region lists.

##### Todos:

- [ ] Write tests

### CODE REVIEW

**Comment by kmcgain** [comment]
Is there a timeline for when this could be released?

**Comment by tobyhede** [comment]
@kmcgain The team have no plan to do another release before v1.0. 

For now, on the 0.5 stream, you need to patch this yourself, unfortunately.

**Comment by kmcgain** [comment]
Alright, thanks for the heads up.

**Comment by flomotlik** [comment]
Yup @kmcgain @scotty-p as @tobyhede mentioned at the moment we're not working on V0.5 any more (to fully focus on 1.0). We're going to release our Beta of 1.0 soon and have been releasing several alphas recently and moving fast towards releasing 1.0

**Pull request closed without merging**
