### PR TITLE
Fixing logical resource name link

### PR DESCRIPTION
**Pull request by ryanmurakami**
## What did you implement:

The link to "logical resource name" in the CognitoUserPool documentation was going to a 404. Looks like the pages resolve with an ending slash, so the relative link needed to traverse up two directories instead of one.

## How did you implement it:

Added `../`

## Todos:

- [ ] Write tests
- [x] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by pmuens** [comment]
Thanks for the PR @ryanmurakami 👍 

There seems to be no bug. The problem is that our doc website which uses the `.md` files to build the documentation has URLs without the `.md` suffix.

The links in this `.md` file / documentation for Cognito User Pool triggers point to the generated URLs (and therefore don't contain the `.md` ending).

You could check that by visiting (you should see a 404):
https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/resources#aws-cloudformation-resource-reference

Adding the `.md` ending should resolve this issue (this way we're referencing the actual file in the repo and not he URL for the build documentation):
https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/resources.md#aws-cloudformation-resource-reference

I hope that this was understandable. Anyway. Thanks again for paying attention on the docs (and the PR!) 💪

**Comment by ryanmurakami** [comment]
Hi @pmuens!
Ah, okay, I think I get it. I think there may still be an issue, though, because the docs site (not github) still goes to 404. (see gif) Seems like there might be an issue with how github & the docsite render these urls?

**Comment by ryanmurakami** [comment]
The urls in that gif are:
[Cognito User Pool](https://serverless.com/framework/docs/providers/aws/events/cognito-user-pool/)
[logical resource name](https://serverless.com/framework/docs/providers/aws/events/guide/resources#aws-cloudformation-resource-reference)

**Comment by ryanmurakami** [comment]
Yeah, the fix in this pr definitely won't work.

**Comment by pmuens** [comment]
Ah gotcha! Thanks for the in-depth analysis @ryanmurakami 👍 

Maybe we can just copy the reference from the bottom to where it's used and then remove the reference at the bottom since it's only used once.

https://github.com/serverless/serverless/blame/44630f17dd2d40aae19c5778bb613f56d41adc15/docs/providers/aws/events/cognito-user-pool.md#L92

That should fix it.

Would you open up a new PR to fix this (since you're the one who found the bug)?

Thanks in advance @ryanmurakami 👍

**Comment by ryanmurakami** [comment]
@pmuens Sure! Take a look at #3771. I think that will do it.

**Comment by pmuens** [comment]
Thanks @ryanmurakami 💪

**Pull request closed without merging**
