### PR TITLE
Add Azure docs overview page

### PR DESCRIPTION
**Pull request by pmuens**
Docs overview page for Azure.

### CODE REVIEW

**Comment by dannykingme** [comment]
Added images with Azure logo to those image urls in s3.

**Comment by pmuens** [comment]
Thanks @dannykingme. Works as expected! 👍 💯

**Comment by christopheranderson** [comment]
FYI - I don't see any left nav showing up for Azure https://serverless.com/framework/docs/providers/azure/

**Comment by pmuens** [comment]
Yes, that seems to be resolved once the main docs are merged into master.

@DavidWells built the site so he know more how this works.

**Pull request merged**
