### PR TITLE
Allow use of AWS Web Identify Credentials

### PR DESCRIPTION
**Pull request by thomaschaaf**
Alternative implementation of #7428

- [x] Write and run all tests
- [x] Write documentation
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by thomaschaaf** [comment]
That is true. I have changed the code accordingly.

**Comment by thomaschaaf** [comment]
@medikoo could this be merged or do you have suggestions what I need to change?

**Comment by thomaschaaf** [comment]
@medikoo what can I do to get this merged?

**Comment by medikoo** [comment]
> @medikoo what can I do to get this merged?

@thomaschaaf sorry my priorities where shifted for a while. I'll try to look into it shortly

**Pull request merged**
