### PR TITLE
Use modular aws-sdk to minimize bundle

### PR DESCRIPTION
**Pull request by exoego**
Addresses #5099

### CODE REVIEW

**Comment by medikoo** [comment]
@exoego I think it's great idea to have this modularization on place. Still it appears that those modules are still at alpha version.

Do you know when we can expect stable releases?

**Comment by exoego** [comment]
Honestly, I have no idea when AWS publishes stable version.
But I assume it is very close (within a couple of months or alike), since it is now gamma (a.k.a. RC) version.

**Comment by medikoo** [comment]
@exoego I'm going to close this as it's not active (and pollutes active PR's list). Still do not hesitate to update and ping me when it'll be ready to take. I'll happily reopen then!

**Comment by G-Rath** [comment]
@medikoo the modules have now been released at a stable v3 version 🎉

**Comment by exoego** [comment]
I will revisit this

**Comment by G-Rath** [comment]
@exoego I'm very interested in this too and am somewhat familiar with both the serverless codebase & the aws sdks, so let me know if you want any help or support :)

**Comment by exoego** [comment]
@G-Rath You can take over 😉

**Comment by G-Rath** [comment]
@exoego unfortunately I'm pretty swamped at work currently so don't know when I'll be able to have a crack at it 😓

**Comment by medikoo** [comment]
@G-Rath great thanks for information. It's probably a good opportunity to upgrade to `aws-sdk` v3 in our `v3` branch, which will make v3.0.0 public release in 2-3 weeks.

PR that does that is definitely welcome

**Comment by medikoo** [comment]
@exoego I just saw your work on https://github.com/serverless/serverless/pull/10476.

It's fine to work on it against `master` (so publish it still in scope of v2) assuming it's a really safe replacement and works with Node.js v10. Otherwise, it'll be better to prepare it against [v3](https://github.com/serverless/serverless/tree/v3) branch

**Pull request closed without merging**
