### PR TITLE
chore: Refactor `provider.role` tests

### PR DESCRIPTION
**Pull request by js-cha**
Addresses: #8523 - Provider role variants

### CODE REVIEW

**Comment by js-cha** [comment]
Hi @pgrzesik sorry for the delay. This PR addresses the Provider role variants tests and is ready for review. However I noticed the unit tests are failing: `TypeError: AWS.util.loadConfig is not a function`. I can't figure out what would cause this from refactoring the unit test code? I tried on master branch without my changes and it also failed - any guidance would be great 🙏

**Comment by pgrzesik** [comment]
Hello @js-cha - I've investigated and it seems like the cause of these failing tests is a change introduced to `aws-sdk` internals which causes us to change patching approach a little bit. This PR should address it: https://github.com/serverless/serverless/pull/9872

**Comment by js-cha** [comment]
thanks for that @pgrzesik - this PR is ready for review.

**Review by pgrzesik — APPROVED** [review]
Thank you @js-cha, well done :clap:

**Pull request merged**
