### PR TITLE
Fix environment yaml property name in docs

### PR DESCRIPTION
**Pull request by epeli**
## What did you implement:

Documentation fix.

## How can we verify it:

Setting env variables like this does not work 

image

## Todos:

- [ ] Write tests
- [x] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by jeffnoehren** [comment]
hey @horike37 
No I think this is a change for a different provider. Our Plugin is looking for the **environmentVariables** key in the yml

**Comment by epeli** [comment]
Oh, I was using this with AWS could not get it working without this change.

**Comment by horike37** [comment]
@jeffnoehren Thank you for the response :smile: 

@epeli 
Closing this PR since it already written properly in AWS doc :+1:

**Comment by jeffnoehren** [comment]
thanks @horike37 :)

**Pull request closed without merging**
