### PR TITLE
Implement workaround for the AWS quirk on $input.json()

### PR DESCRIPTION
**Pull request by jordanmack**
This is at attempt at a workaround for the AWS quirk of requiring an invalid JSON string to use the `$input.json()` within a requestTemplate. After an object has been converted to a string within _prepareRequestTemplates(), this adds a regex search which removes the quotes around `$input.json()`. This will allow us to use the quoted string values like `"$input.json('$')"` or `"$input.json('$.pets')"`within our JSON, and eliminate the need for the big ugly stringified version.

### CODE REVIEW

**Comment by jordanmack** [comment]
This should help with issue #537, and possibly others. It's definitely a hack, but this workaround will help a lot until a real solution is found.

**Comment by msteckyefantis** [comment]
I just tried it out. Very cool!! Very easy edit, and worked first time I tried it.

As good as this solution is, I still see a few issues:

1) Inputing the value "$input.json('$')" differs from how you would input the same value in the AWS API Gateway browser console integration request, where you just put in the value like this: $input.json('$'). Maybe not that big of an issue, but this causes ambiguity and potential confusion for users who may be looking at the AWS documentation for mapping templates.

2) This is still a workaround where the user has to find the appropriate file and line of code on their computer and input that line of code.

3) Perhaps there are cases where this code can cause issues/errors for certain template inputs into the requestTemplates value in the s-function.json file, or maybe not and it works perfectly fine.

Regardless, thanks a lot for your help with this issue, your solution is legit.

**Comment by jordanmack** [comment]
@msteckyefantis I'm glad it helped.

1. It could cause some confusion, and we should add some documentation somewhere. I hope that AWS makes changes eventually to allow JSON compliant formatting so this workaround wouldn't be needed. The alternative is some major changes to the Serverless framework. Since this problem affects such a common use case, I see this workaround as an essential lesser evil.

2. I submitted a pull request for this, so it's up to the Serverless team on if they want to merge it into a future release.

3. My regex search and replace is fairly restrictive, so I hope it doesn't cause any additional problems. I have to concede that it is definitely possible that it might affect a use case that I didn't anticipate though.

**Comment by msteckyefantis** [comment]
I see what you're saying, thanks for the info/perspectives.

**Comment by jordanmack** [comment]
I botched the pull request and needed to recreate. The new issue is #546.

**Pull request closed without merging**
