### PR TITLE
Fix/deps of devdeps

### LINKED ISSUE #3972: Dependencies aren't included when they are a dependency of devDependencies
# This is a Bug Report 

## Description
Serverless package doesn't correctly add node_modules when a node module is also a dependency of a devDependency

I have a package.json that contains this : 

```
{
  "name": "myapp",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "bluebird": "^3.5.0",
    "moment": "^2.18.1"
  },
  "devDependencies": {
    "aws-sdk": "*",
    "serverless": "^1.18.0"
  }
}

```

When I run `serverless package` then extract the resulting zip file, the `node_modules` folder only contains a `.bin` folder.

I think that this is due to the way the `excludeDevDependencies` functionality works.

I'm wondering if the issue might be coming from the fact that, as the `serverless` module relies on `moment` and `bluedbird` they are in the list of dependencies when running `npm ls --dev=true` but not added back when running `npm ls --prod=true`.

## Similar or dependent issues:
This is probably related to  #3889

## Additional Data

* Serverless 1.18.0
* MacOS Sierra
* package is created correctly ( but with the devDependencies) if I use `excludeDevDependencies: false`

### PR DESCRIPTION
**Pull request by davidgovea**
## What did you implement:

Closes #3972 

Necessary dependencies of devDependencies are no longer pruned.

## How did you implement it:
The recent `devDependencies` pruning feature uses `npm ls >> tmpfile` to keep track of all devDependencies. With this change, the `--prod=true` dependencies are collected in the same way (npm ls to another temp file).  

Then, `_.difference(devDependencies, prodDependencies)` is used to avoid excluding actually needed dependencies

## How can we verify it:

The first commit (`3e4986c`) implements the change (disabled) and a failing test. Didn't see a way to provide a failing test without changing code also, due to the stubbing strategy.

## Todos:

- [x] Write tests
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by davidgovea** [comment]
@pmuens awesome! Thank you :+1: 

As far as the .map() to .mapSeries(), I'm not sure it's needed in those two places (it's OK for dev/prod actions to happen simultaneously, since they use 2 different files). Definitely needed in the parent where it existed before, when deps are being collected and recorded to the files from different package.json's.

Not a problem though, and definitely simplifies reasoning about what's going on.

We've been using this branch for our efforts -- getting that space saving on the bundle, and not seeing dep issues any more.

**Comment by ryanmurakami** [comment]
@pmuens @davidgovea Just tested this on two of our problem services and it packaged them both up perfectly. Good job!

**Comment by pmuens** [comment]
Thanks for getting back @davidgovea 👍

> As far as the .map() to .mapSeries(), I'm not sure it's needed in those two places (it's OK for dev/prod actions to happen simultaneously, since they use 2 different files). Definitely needed in the parent where it existed before, when deps are being collected and recorded to the files from different package.json's.

Yes, you're right. The final version only uses `mapSeries` when we're fetching the `dev` and `prod` dependencies via array indices from the result. The rest can be computed in parallel (which should speed things up a bit 👍).

> We've been using this branch for our efforts -- getting that space saving on the bundle, and not seeing dep issues any more.

That's great to hear. The more validation that this fixes the problem, the better. There are so many different config setups so it's really hard to test everything (although I spent a long time testing this yesterday 😅).

---

> @pmuens @davidgovea Just tested this on two of our problem services and it packaged them both up perfectly. Good job!

Thanks for testing this @ryanmurakami 👍! Great to hear that it resolves the issues on your end as well.

**Comment by maximede** [comment]
Seems to work for me too using `yarn add serverless/serverless#3975/head`

**Comment by pmuens** [comment]
> Seems to work for me too using yarn add serverless/serverless#3975/head

Awesome! Thanks for testing it out @maximede 👍

**Pull request merged**
