### PR TITLE
Fix issues with PR #5631 causing base64 errors

### LINKED ISSUE #5491: base64 encoding: Serverless command "LS12ZXJib3Nl" not found
# This is a Bug Report

## Description

The following error:

```
Serverless command "ZHluYW1vZGI=" not found. Did you mean "plugin"? Run "serverless help" for a list of all available commands.
```

happens when `serverless --service=foo dynamodb install` is called.

It can also be reproduced with a simpler command like `serverless --no-color --verbose info`, which outputs:
```
Serverless command "LS12ZXJib3Nl" not found. Did you mean "config"? Run "serverless help" for a list of all available commands.
```
## Additional Data

It happens only with the `1.33.0` version, which was released today. It is caused by the changes from https://github.com/serverless/serverless/pull/5361

### PR DESCRIPTION
**Pull request by jkozera**
## What did you implement:

Closes #5491

## How did you implement it:

- Changed the arguments parsing logic to encode all the arguments, which simplifies the decoding later, to avoid errors like the one from #5491.
- Implemented decoding of nested objects, which is required to decode encoded commands.

### Details, why the changes were required:

- Some of values were not converted back from base64, which resulted in spurious errors with base64 strings. (This was caused by nested arrays, like commands, not being converted back, combined with the wrong assumption that commands always occur before options. It is not always true, as the added test case demonstrates.)
- Some other values were converted *from* base64, but they weren't base64 in the first place, which resulted in junk binary data. (This was due to the invalid assumption that only odd-numbered values   need to be converted.)

## How can we verify it:

Try running for instance `serverless --no-color --verbose info` in any project.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by Enase** [comment]
thanks +1

**Comment by jkozera** [comment]
FWIW , it can be worked around by always passing arguments like:

```
sls [command] [subcommand] --arg1 [value] --arg2 [value]
```

Basically, never placing subcommands after other options, and never using booleans without arguments. For the booleans, you can pass `1`, for instance:
```
sls [command] [subcommand] --arg1 [value] --arg2 [value] --no-color 1
```

But yeah, it's a pain, and probably a worse workaround than just downgrading to v1.32. :)

**Comment by medikoo** [comment]
For me following commands as simple as below crash

```
$ npx sls deploy -v -s somestage
 
  Serverless Error ---------------------------------------
 
  Serverless command "deploy somestage" not found. Did you mean "deploy"? Run "serverless help" for a list of all available commands.
```
 
Even if there's a workaround, I wouldn't expect anyone to take effort and learn about it.

It'll be best if v1.33 is just deprecated, as current behavior is pretty nasty.

**Comment by dschep** [comment]
i'm releasing 1.33.1 asap

**Comment by medikoo** [comment]
@dschep Thank you!

**Pull request merged**
