### PR TITLE
Omit referenced values from environment variables in local invocation

### LINKED ISSUE #3080: sls invoke local replaces environment variables with [object Object]
# Bug Report

## Description

For bug reports:
* What went wrong?
Attempted to run my Lambda function locally.

* What did you expect should have happened?
Function runs locally in the same way that it would be invoked in AWS.

* What was the config you used?
Here's the relevant declaration:

functions:
  scrapeProducts:
    handler: 'produce-products.handler'
    environment:
      STREAM_WRITER_ROLE:
        'Fn::ImportValue': 'hello-retail-stream:${self:custom.stage}:RetailStreamWriterArn'
      STREAM_NAME:
        'Fn::ImportValue': 'hello-retail-stream:${self:custom.stage}:RetailStreamName'
    role:
      Fn::GetAtt:
        - ProductStreamProducer
        - Arn

* What stacktrace or error message from your provider did you see?

{ [ValidationError: Missing credentials in config]
 message: 'Missing credentials in config',
 code: 'CredentialsError',
 time: Tue Jan 10 2017 16:16:42 GMT-0800 (PST),
 requestId: '3ad96a44-d793-11e6-8116-834f226c697d',
 statusCode: 400,
 retryable: false,
 retryDelay: 85.4559698374942,
 originalError: 
  { message: 'Could not load credentials from TemporaryCredentials',
    code: 'CredentialsError',
    time: Tue Jan 10 2017 16:16:42 GMT-0800 (PST),
    requestId: '3ad96a44-d793-11e6-8116-834f226c697d',
    statusCode: 400,
    retryable: false,
    retryDelay: 85.4559698374942,
    originalError: 
     { message: '1 validation error detected: Value \'[object Object]\' at \'roleArn\' failed to satisfy constraint: Member must have length greater than or equal to 20',
       code: 'ValidationError',
       time: Tue Jan 10 2017 16:16:42 GMT-0800 (PST),
       requestId: '3ad96a44-d793-11e6-8116-834f226c697d',
       statusCode: 400,
       retryable: false,
       retryDelay: 85.4559698374942 } } }

## Additional Data

Have a look at the project here for a more complete picture:

https://github.com/Nordstrom/hello-retail/tree/scrape-store-products

It makes some sense that SLS may not be able to resolve the CF template values when running locally. But, having the string value "[object Object]" in place of the correct value was very confusing.

* ***Serverless Framework Version you're using***: 1.4
* ***Operating System***: Mac OS El Capitan
* ***Stack Trace***: See above
* ***Provider Error messages***: '1 validation error detected: Value \'[object Object]\' at \'roleArn\' failed to satisfy constraint: Member must have length greater than or equal to 20'

### PR DESCRIPTION
**Pull request by fabsrc**
## What did you implement:

Closes #3080

## How did you implement it:

Used lodash's `omitBy` function to omit all objects from environment variable values.

## How can we verify it:

*serverless.yml*
```yaml
service: testService

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    environment:
      QUEUE:
        Ref: Queue

resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
```

*handler.js*
```js
module.exports.hello = function(event, context, callback) {
    const queue = process.env.QUEUE || 'http://localhost:4576/123456789012/test';
    callback(null, 'QUEUE: ' + queue);
}
```

When invoked with `sls invoke local -f hello` it should return `QUEUE: http://localhost:4576/123456789012/test` instead of `QUEUE: [object Object]`.

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by arabold** [comment]
This PR is dangerous and a *breaking change*.

By deleting these environment variables early in the chain, you prevent plugins to hook into `invokeLocal` and resolve these values dynamically. So this would need to be tested with a wide range of plugins. Personally, I'm against doing any of this in first place and would rather invest the time in properly allowing the use of `Ref:` and `Fn::ImportValue` for environment variables.

There's a plugin that can do this already: https://github.com/arabold/serverless-export-env (full disclosure: I'm the author).

**Comment by fabsrc** [comment]
@arabold 
In my opinion `sls invoke local` should also work without having to deploy first. In this case `Ref:` and `Fn::ImportValue` would not work. Instead I want to use a fallback value for environment variables for local development (see the example above).

And btw: I tested this change with your plugin as well and it still works as expected 😉

**Comment by arabold** [comment]
Does this even work in 1.22+ anymore? #4329 broke this functionality for us.

**Comment by fabsrc** [comment]
I branched out from the current master branch which is v1.23.0, so I guess it works fine.

To me #4329 seems like a bug in the `deployFunction/index.js` file where AWS' [`updateFunctionConfiguration`](http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html) endpoint is called without resolving the environment variables first. `updateFunctionConfiguration` only works with the [`Environment` Data Type](http://docs.aws.amazon.com/lambda/latest/dg/API_Environment.html) which requires key-value pairs of type `String`.

**Comment by HyperBrain** [comment]
@fabsrc BTW: I fixed the function deployment in 1.24.1 and the environment is only updated there if it does not contain CF references. As deploy function is a debug functionality that completely bypasses CF integrity that is ok.

**Comment by horike37** [comment]
Closing this issue for now since it took for a long time without any activity.
Free feel to re-open if you want to restart working on this.

**Pull request closed without merging**
