### PR TITLE
Fix bug when packaging a functions-free service

### LINKED ISSUE #3547: SLS deploy broken for project without function
# This is a Bug Report

## Description

Attempting to deploy a function-free serverless.yml results in a failure.  The failure complains that no package (e.g. foo.zip) is available.

This issue effects 1.12 but not pre-1.11.

For bug reports:
* What went wrong?
Error: `No ingress-stream.zip file found in the package path you provided.`
Deployment did not proceed.

* What did you expect should have happened?
Deployment of [the well-formed and correct] CloudFormation stack would occur.

* What was the config you used?
https://github.com/Nordstrom/hello-retail-workshop/blob/master/Lesson1_HelloRetailStream/ingress-stream/serverless.yml

* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***: 1.12
* ***Operating System***: all
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by eahefnawy**
## What did you implement:

Closes #3547 

Fixed a bug with the package plugin when the service has no functions. A `no package found` error was thrown.

## How did you implement it:
We're now not throwing that error when there are no functions in the service.

## How can we verify it:
run `sls package` on a functions-free service:

```yml
service: serverless-functions-free

provider:
  name: aws
  runtime: nodejs6.10
```
Should package without issues.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by eahefnawy** [comment]
@pmuens yep, I noticed that there are no test coverage at all for the entire `extendedValidate` file. Must've been missed in the massive package/deploy change.

pushing complete test coverage for that file shortly 😊

**Comment by eahefnawy** [comment]
Just pushed!

**Comment by silver2k** [comment]
I can't test this right now, but will it still fail when the deployment is broken into multiple zip files via plugin?

**Comment by eahefnawy** [comment]
@silver2k this is only a change when you don't have functions at all, hence no zip files ... I'm guessing your case is different since you have multiple zips

**Comment by silver2k** [comment]
Correct, I have a zip per function.

On 12/05/2017 17:34, "Eslam λ Hefnawy" <notifications@github.com> wrote:

@silver2k <https://github.com/silver2k> this is only a change when you
don't have functions at all, hence no zip files ... I'm guessing your case
is different since you have multiple zips

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/serverless/serverless/pull/3598#issuecomment-300987947>,
or mute the thread

**Comment by eahefnawy** [comment]
> Correct, I have a zip per function.
then you have functions in your service. So don't worry about this PR at all! 😊 

All the best 💃

**Comment by silver2k** [comment]
Unfortunately - still worried.
Just tested with 13.2 and I now get `servicename.zip not found in the package path you provided.`
As mentioned - I'm using a plugin to split out a zip per function - but the logic is still tied to a specific zip file name

**Comment by connaryscott** [comment]
this does not work for me.  i am on serverless version:  
```
chscott$ serverless --version
1.25.0
```
i have to create a dummy function for me to get a zip.  I want a zip for resources that are being created.  there is no function implementation in this case.   How can i avoid having any functions?

**Pull request merged**
