### PR TITLE
Do not require unique event names for schedules

### PR DESCRIPTION
**Pull request by rifflock**
This is for issue #995

I allowed for both `dash deploy` and `event deploy --all` to use non-unique schedule names.

I'm not sure that I covered all use cases for event deploy as I'm pretty new to the serverless code base.

### CODE REVIEW

**Comment by arabold** [comment]
Thanks for the changes, @rifflock . I'm pretty certain this will fix scheduled events but might not solve it for other event types such as Kinesis and SNS yet.

@ac360 @eahefnawy Do you have any comments or suggestions on this? I definitely would want to see this change in 0.5.4 if possible :+1:

**Comment by rifflock** [comment]
I updated the other 3 event deploy functions to do the same thing that I did in `schedule` one. They now all pull the function first, and then deploy the event for that function.

**Comment by HyperBrain** [comment]
For resource-bound events it is good to have them globally, so the solution should be ok, to have the CW triggers bound to the function (as it actually will trigger the bound function) and keep the resource-bound events global.

**Comment by eahefnawy** [comment]
@rifflock thanks for your great work here. I've read the issue and @arabold for sure have solid points that we didn't consider. So I do think we should make that change.

If I understand this correctly, this PR means that we'll now deploy events with `sls event deploy funcName#eventName`, correct? So the event name now should be unique within a function (which is unique project-wide itself). Is there any checks for that? to make sure event names are unique within a function? (we used to make that check in the Serializer)

**Comment by rifflock** [comment]
That's correct. It seems to make sense to have event names be unique by function. I didn't add any functionality to verify that uniqueness, though. I will take a look in the morning to see if the Serializer still checks for that, and if not I'll see if I can add it.

**Comment by HyperBrain** [comment]
@eahefnawy Would it be possible to change the event UUID entry's name that is generated in the variables files automatically when upgrading from 0.5.3 to the fixed version? Otherwise you would have to remove the event and the entry manually because the serializer would not find the old ones. That would generate lots of effort (if the event names change, the UUID property will change its name too).

**Comment by arabold** [comment]
Scheduled events can trigger more than one function. Therefore an alternative to having per-function scheduled events would be to define them globally (in a `s-events.json` in the project root) and only define the _binding_ in `s-function.json`. This would solve the problem in an elegant way as well and would be more in sync with how resource events (SNS, Kinesis) work.

In that case we (for our project) would define 3 global scheduled events, each with a unique name per project:
* schedule-daily
* schedule-hourly
* schedule-5min

This would be defined in an `s-events.json` (or as part of the `s-project.json`) like this:
```
  "events": [
    {
      "name": "schedule-5min",
      "type": "schedule",
      "config": {
        "schedule": "rate(5 min)",
        "enabled": true
      }
    },
    {
      "name": "schedule-1hour",
      "type": "schedule",
      "config": {
        "schedule": "rate(1 hour)",
        "enabled": true
      }
    },
    {
      "name": "schedule-1day",
      "type": "schedule",
      "config": {
        "schedule": "rate(1 day)",
        "enabled": true
      }
    },
  ]
```

Then, in the `s-function.json` it would look something like this:
```
{
  "name": "my-function",
  "runtime": "nodejs4.3",
  ...
  "events": [
    {
      "name": "schedule-1day",
      "type": "schedule",
    }
  ]
  ...
}
```


Any thoughts?

**Comment by HyperBrain** [comment]
I would even use a new type `scheduleref` for event references to (1) explicitly show that it's a reference and no definition and (2) to not break existing configurations that are in use.
```
{
  "name": "my-function",
  "runtime": "nodejs4.3",
  ...
  "events": [
    {
      "name": "schedule-1day",
      "type": "scheduleref",
    }
  ]
  ...
}
```

**Comment by rifflock** [comment]
I like the idea of having it be a different type as @HyperBrain suggests. That way if you want to have a separate schedule for 6 different lambdas, and you _want_ it to be separate rules in CW then you do that by having it be a `schedule` instead of a `scheduleref`

I also like that by doing it that way it is _technically_ out of scope for this issue, so I don't feel obligated to do it ;)

We can support both!

**Comment by rifflock** [comment]
I don't see anything specific to events in the `Serializer` class or the `serializeFunction` method, so I don't think there's anything explicitly enforcing uniqueness in event names. I'm also not sure exactly how one might go about adding that.

**Comment by flomotlik** [comment]
Hi, thanks for the contribution, but we've stopped working on 0.5 of Serverless at this point to fully focus on the next release with V1 that we're currently working on. Therefore we're not taking any commits for 0.5 and do not plan any future releases at this point and I'm closing this PR. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Pull request closed without merging**
