### PR TITLE
Suppress AWS SDK v2 deprecation message

### PR DESCRIPTION
**Pull request by medikoo**
Prevent deprecation message by following suggestion from [comment by @kuhe](https://github.com/serverless/serverless/issues/11753#issuecomment-1435134813)

Closes: #11753

### CODE REVIEW

**Comment by obrcnh** [comment]
How do I fix this problem? Upgrade the serverless package to the latest? I try the version 3.28.0 and it doesn't work out.

**Comment by herebebogans** [comment]
@obrcnh wait for next release

**Comment by obrcnh** [comment]
> @obrcnh wait for next release

Thanks!

**Comment by andresmoschini** [comment]
Why removing the warning is a good thing? The pending update to SDK v3 is still pending. Am I missing something?

**Comment by vividn** [comment]
We've upgraded to serverless `3.28.1`, but are still getting this warning on every call. Why? It is disrupting our deployed environments and our tests

**Pull request merged**
