### PR TITLE
Logical IDs Centralization Missed Details

### PR DESCRIPTION
**Pull request by erikerikson**
## What did you implement:

Completes (?) #2679

@eahefnawy Sorry.  The merges I was doing and trying to get in prior to my ditching on account of my honeymoon ended up turning up a few interesting missed cases.  This PR attempts to amend those.

Commit Notes:
A few places where names had been hard coded were missed in #2679.  This pull request attempts to get the rest of these (although I fear a few more exist).
The hard coding of the logical ids for the role and policy were removed from the json files defining those values.
Additionally, the path and name of the default role and policy were extrapolated as were log group and api gateway names.
The new role path, role name, and policy name values were used to amend the static role and policy.
Commentary in the centralization file was re-added for future 'us'es.

Tests were updated
No function or documentation changes occurred by these changes

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by erikerikson** [comment]
Perhaps @pmuens, you will have interest in this too as reviewer of #2679.  Been thinking about how fine grained naming controls can best be introduced...

**Comment by pmuens** [comment]
@erikerikson thank you very much for this PR and the effort you put into this!
Really appreciate it!

I'll look into it ASAP and provide feedback.
Curious what feedback @eahefnawy and @flomotlik got about this.

**Comment by erikerikson** [comment]
Sorry @pmuens, just noticing these conflicts.  Will get them sorted.

**Comment by erikerikson** [comment]
@pmuens sorted.

**Comment by eahefnawy** [comment]
@erikerikson thanks for that! These changes makes sense! been testing it for a while and couldn't break it. G2M! 👯

**Comment by pmuens** [comment]
@erikerikson thanks fort the update! Will look into it today!

**Comment by erikerikson** [comment]
Thanks for your time gents! @eahefnawy & @pmuens - you guys rock!  🎸

**Pull request merged**
