### PR TITLE
Fix getFileContent encoding

### PR DESCRIPTION
**Pull request by RafalWilinski**
## What did you implement:

Closes https://github.com/serverless/serverless/issues/4182

This line: https://github.com/serverless/serverless/pull/3924/files#diff-0e8817ce3b2d950d2b8d0e47f9fccb2eR107 changed encoding from `null` (default for `fs.readFileSync` according to the [docs](https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options)) to `utf8`. 

## How can we verify it:

```bash
npm install deasync --save
```

```js
require('deasync'); // or any other module that consists of executable binaries or has "weird" characters
```

Deploy & invoke, there should be no errors.

OR
```
git checkout f0b1474f1e49d69c39e27e3c8def929569e20bed # Before PR changing encoding
serverless package

# Check random executable size from node_modules

git pull https://github.com/RafalWilinski/serverless master
serverless package

# Check executable size, should be the same
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by RafalWilinski** [comment]
The only thing that comes to my mind right now is a test, that tries to read a troublesome sequence of bytes, compresses them and then decompresses.

**Comment by pmuens** [comment]
> The only thing that comes to my mind right now is a test, that tries to read a troublesome sequence of bytes, compresses them and then decompresses.

Thanks for commenting @RafalWilinski. That sounds good 👍.

**Comment by pmuens** [comment]
FYI: @RafalWilinski just added a test which checks if the data is returned as is.

Next up I'll test this PR so that we can merge it ASAP.

**Comment by RafalWilinski** [comment]
Great, thanks!

**Comment by pmuens** [comment]
Hey everyone 👋

Just wanted to post a quick update that we've done a path release which includes this fix (see: https://github.com/serverless/serverless/releases/tag/v1.21.1).

**Pull request merged**
