### PR TITLE
Add disable parameter to function package options

### PR DESCRIPTION
**Pull request by jthomas**
## What did you implement:

This will allow functions to be excluded from the service packaging.

Resolves this bug a user found with deploying functions without a package to OpenWhisk.
https://github.com/serverless/serverless/issues/3820

## How did you implement it:

Added trivial change to support the `function.package.ignore` property in the `serverless.yml`.

## How can we verify it:

`npm test` as the PR includes a test case. 

This serverless.yml will deploy without error.

```yaml
service: test

provider:
  name: openwhisk

package:
  individually: true
  exclude:
    - "**/*"

functions:
  foo:
    handler: handler.hello
    package:
      include:
        - handler.js
  bar:
    handler: handler.hello
    package:
      include:
        - handler.js
  seq:
    package:
      disable: true
    sequence:
      - foo
      - bar

plugins:
  - serverless-openwhisk
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by jthomas** [comment]
yo @pmuens!

Can you explain what you would expect to happen from that serverless configuration? 

Looking at the example above, I actually think this error is correct. The packaging service has not created the individual function package, following the configuration directive. AWS' provider plugin does not currently define behaviour for deploying functions without a package and throws the error above.

**Comment by HyperBrain** [comment]
I agree with @jthomas . In the AWS environment a function without code cannot be deployed, so the option must lead to an error. Skipping the function (and thus not generating a CF resource for it) would be wrong, as the function would be undeployed as a consequence on the stack update.

Possible options would be to ignore the setting with AWS but print a warning, or have it as is - throw an error.

**Comment by pmuens** [comment]
@jthomas 🤔 Yes, it makes sense after thinking through this again 👍 

Maybe we can add a quick info on the console that the specific function will be ignored for packaging.

I agree with @HyperBrain. IMHO we should still throw an error, but show an info before it fails. Something like `Function "myFunc" won't be packaged since packaging was disabled for it`. This way the user might know what's going on when seeing the error (which, as you said makes totally sense).

Furthermore we could add another sentence in the docs which explains that this could happen.

**Comment by jthomas** [comment]
@pmuens I've added a log message to tell users when functions are excluded from packaging. 

Unfortunately, I've overwritten your docs changes when I pushed the updates up 🙈. 

Do you have the content stored somewhere? I was going to add the comment you mentioned to explain this to users.

**Comment by pmuens** [comment]
> @pmuens I've added a log message to tell users when functions are excluded from packaging.

Thanks for updating @jthomas 👍!

> Unfortunately, I've overwritten your docs changes when I pushed the updates up 🙈.
> Do you have the content stored somewhere? I was going to add the comment you mentioned to explain this to users.

Hehe 😄. No problem I have the changes locally. Will push them on top of yours and do a final review tomorrow 👍

**Comment by jthomas** [comment]
Thanks for saving me there @pmuens 😃.

LGTM.

**Comment by pmuens** [comment]
> Thanks for saving me there @pmuens 😃.

Sure thing! Thanks for PRing @jthomas 👏

**Comment by eahefnawy** [comment]
@jthomas we've discussed this internally and thought it'd be best to only include docs for this in the OpenWhisk docs. We'd like to make all our example code/config work out of the box. Having it in the aws docs where users can copy/paste and expect it to work wouldn't be great DX, which I'm guessing that's what happened with @pmuens 😊 

Thanks tons @jthomas 🙌

**Pull request merged**
