### PR TITLE
Merge + Fix Bug

### PR DESCRIPTION
**Pull request by erikerikson**
## What did you implement:

1. Merges the latest master
2. Fixes the bug that @amberlion reports

## How did you implement it:

See changes in commits https://github.com/erikerikson/serverless/commit/2fd0f238c2583e703f600303964fd5ebd0ec0700, https://github.com/erikerikson/serverless/commit/48bc0d2f171e58f2bcc3b32c015e693f14cdee95, and https://github.com/erikerikson/serverless/commit/5a8269bb36bb6b2e2407812d87aebaa831037089

!NOTE! this removes the fail package on missing file behavior that was introduced.  This breaks our hello-retail projects when the call to `fse.realpathSync` fails to find the path at https://github.com/erikerikson/serverless/blob/circular-vars/lib/classes/Variables.js#L245.
## How can we verify it:

@eahefnawy it would be wonderful to get some tests catching some of these tests.  Perhaps we need a truly rigorous definition of the requirements constellation around these features.  We have an increasing set of people that are on increasingly old builds because of these issues (to be clear, not just the serverless team).

@pmuens can you help get this moving?  This has been stalled for a long time now.

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by erikerikson** [comment]
Just to be clear, I'm not asking you to work the weekend or anything...  Just would love to get this unstuck

**Comment by pmuens** [comment]
Thanks for PRing the changes @erikerikson 👍

Is there any chance to untangle the PR a little bit since it includes `99 file changes? Maybe we can rebase @eahefnawy PR on top of master and then open up your PR against his so that we only get the small fraction of changes without the changes from `master`.

This would make the review-process a lot easier.

/cc @serverless/framwork-maintainers

**Comment by HyperBrain** [comment]
@pmuens Fully agree. First the `circular-vars`branch should be rebased onto master (or better master merged in because there is a dependent branch), and then the dependent branch can be rebased.

**Comment by erikerikson** [comment]
Yea.  That's why I called out the commits that represented the actual changes.  I don't believe I have rights to do what you ask but would be happy to close this and separate it into two PRs which I can do.

**Comment by erikerikson** [comment]
BTW - congratulations @HyperBrain on being invited to be a maintainer!

**Comment by HyperBrain** [comment]
@erikerikson Thanks 😄

**Comment by erikerikson** [comment]
If anyone can find some time to do this rebase, it would be appreciated.  Thank you!

**Comment by erikerikson** [comment]
i.e. of @eahefnawy 's branch, to be clear.  I'm raring to adjust this one :D

**Comment by erikerikson** [comment]
FWIW, this bug has been in place since `'1.11.0': '2017-04-12T16:05:40.693Z'`

**Comment by erikerikson** [comment]
sorry.  correction: `'1.12.0': '2017-04-26T16:01:23.822Z'` . It still worked in `1.11.0`

**Comment by HyperBrain** [comment]
@erikerikson I can have a look and try if I can get the base `circular-vars` branch rebased or at least how to carefully clean up the mess 😄 . I don't wanna do something that destructs your PR completely.

**Comment by erikerikson** [comment]
ping

**Comment by HyperBrain** [comment]
@erikerikson pong!

Sorry Erik, I was a bit loaded the last days, but I'm sure I can try the rebase tomorrow - promised 😃

**Comment by HyperBrain** [comment]
@erikerikson You don't have to wait anymore - I did a rebase locally onto the current master.

We have to test somehow if your branch / changes can be rebased onto that again.
I'll run the unit tests right now and update package-lock again as it got broken during the rebase.

**Comment by HyperBrain** [comment]
The base branch is rebased onto the current master now.

**Comment by erikerikson** [comment]
Thanks @HyperBrain !
Closing in preference for #4478

**Pull request closed without merging**
