### PR TITLE
handle absolute paths in file()

### LINKED ISSUE #3629: Variable file() fails with absolute path
# This is a Bug Report

### What went wrong?
Could not load `file()` when path given was absolute

### What did you expect should have happened?
`file()` should handle absolute paths

### What was the config you used?
```yaml
...
provider:
  environment: ${file(/Users/damon/development/mindhive/graymont-trucks/deploy/build/dev/cloud/env-local.json)}
```

### What stacktrace or error message from your provider did you see?
```
 Serverless Warning --------------------------------------
 
     A valid file to satisfy the declaration 'file(/Users/damon/development/mindhive/graymont-trucks/deploy/build/dev/cloud/env-local.json)'
     could not be found.
```

## Additional Data

Just to show the file from the example above should work, it does exist: 
```
$ ll /Users/damon/development/mindhive/graymont-trucks/deploy/build/dev/cloud/env-local.json
-rw-r--r--  1 damon  staff  560 16 May 20:52 /Users/damon/development/mindhive/graymont-trucks/deploy/build/dev/cloud/env-local.json
```

And if I change the path in serverless.yaml to be relative it works:
```yaml
...
provider:
  environment: ${file(../deploy/build/dev/cloud/env-local.json)}
```

* ***Serverless Framework Version you're using***:
* ***Operating System***:
```
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.10.0
     Serverless Version: 1.13.2
```

### PR DESCRIPTION
**Pull request by mangas**
## What did you implement:

Closes #3629

## Todos:

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by mangas** [comment]
@pmuens I thought that since this change would allow files with absolute paths it would also make sense to support the ~ syntax to refer to the home directory

Because ~ was part if the command regex I had to change that too. I am not familiarized enough with the code to understand if this change has too much of an impact so I am happy to revert the last commit if you don't agree with it

**Comment by mangas** [comment]
Any chance I can get a review on this PR ?

**Comment by mangas** [comment]
@pmuens great news, when do you think the next release will happen?

**Comment by pmuens** [comment]
> @pmuens great news, when do you think the next release will happen?

The next release (`v1.18`) is scheduled for [July 19, 2017](https://github.com/serverless/serverless/milestone/33). However this feature could potentially be available in an upcoming patch release.

**Comment by mangas** [comment]
next patch release sounds good, thanks !

**Pull request merged**
