### PR TITLE
chore(aws-provider) Remove dependency on aws provider sdk object

### PR DESCRIPTION
**Pull request by AlinoeDoctari**
Removes dependency on aws provider sdk when checking for changes. This should help merge #8850 and move forward with #8445.

### CODE REVIEW

**Comment by AlinoeDoctari** [comment]
No more BBpromises, should be ok to review.

**Review by medikoo — CHANGES_REQUESTED** [review]
@AlinoeDoctari great thanks for that!

I've noticed that this change requires updates in our tests (simply because tests in question are heavily attached to implementation internals).

Currently we try to not update such tests in their form, but instead rewrite them so they're based on more reliable (internals agnostic) `runServerless` variant. e.g. I believe there would be zero changes to tests needed when they are refactored to that.

I've prepared a spec refactor, and pre-configured already most vague parts here: https://github.com/serverless/serverless/issues/8886 This should make refactor relatively easy.

Ideally if we can cover this refactor first, before we take in that cleanup.

**Comment by AlinoeDoctari** [comment]
Thanks a lot for taking a look and taking the time to draft the spec :bowing_man: I will have a look at that new issue and see if I can come up with something there, if that's ok for you.

**Comment by medikoo** [comment]
> I will have a look at that new issue and see if I can come up with something there, if that's ok for you.

Yes, that'll be great. Let us know if anything is not clear

**Comment by AlinoeDoctari** [comment]
Implemented as part of #8913 .

**Pull request closed without merging**
