### PR TITLE
Support Kinesis AT_TIMESTAMP definition

### LINKED ISSUE #3648: Kinesis event does not support AT_TIMESTAMP
# This is a Feature Proposal
## Description

Kinesis stream even source supports LATEST, TRIM_HORIZON, but not AT_TIMESTAMP.

### PR DESCRIPTION
**Pull request by pselle**
This is a new PR for #3649 (where there were issues reopening it)

Support Kinesis AT_TIMESTAMP definition by supporting timestamp fields in event declaration

## What did you implement:

Support Kinesis AT_TIMESTAMP definition by supporting timestamp fields in event declaration

Closes #3648

## What did you implement:

This enables Timestamp for kinesis event fields, such that one can create the event source mapping for timestamp: https://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html

## How did you implement it:

Added this field to the streamTemplate if it is present in the event declaration.

## How can we verify it:

Add `timestamp` to a kinesis event declaration, and verify in the cloudformation JSON.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by eahefnawy** [comment]
Thanks @pselle 😊 ... I've tried packaging it out and the output is as expeted. I wasn't able to verify deployment though as I'm resolving some issues in my aws account.

@pmuens could you try deploying again to see if CF is finally accepting this new property? 😊

**Comment by HyperBrain** [comment]
> Not sure if we should remove the startingPositionTimestamp config, because this would make the AT_TIMESTAMP config useless...

Keeping it would do the same, wouldn't it? 😃 What is the use to have the AT_TIMESTAMP mode without the possibility to set a timestamp?

**Comment by pmuens** [comment]
> Keeping it would do the same, wouldn't it? 😃 What is the use to have the AT_TIMESTAMP mode without the possibility to set a timestamp?

Yes, true story 😄. Maybe it's still not 100% supported through CloudFormation.

**Comment by pselle** [comment]
@pmuens Sounds like CF is missing the same things it was earlier in the year -- we need `StartingPositionTimestamp` to exist for this to work. The docs: https://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html#API_CreateEventSourceMapping_RequestSyntax for CF claim it exists now, but maybe they're ... wrong?

**Comment by pmuens** [comment]
> @pmuens Sounds like CF is missing the same things it was earlier in the year -- we need StartingPositionTimestamp to exist for this to work. The docs: https://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html#SSS-CreateEventSourceMapping-request-StartingPositionTimestamp for CF claim it exists now, but maybe they're ... wrong?

Yes, it looks like the docs are incorrect. I digged deeper into this and it looks like it's still not added yet.

> Edit: It looks as though the like above (and that in the issue), references the Lambda API docs, not CloudFormation. Does this mean that given that sls is working through CloudFormation, it's still not available to sls framework?

Yes, the Framework uses CloudFormation under the hood (no direct SDK / API calls). That's why we always have to wait until certain features are supported in CloudFormation.

Sorry for the inconveniences @pselle. And thanks again for PRing this! We should definitely revisit this once the support actually lands in CloudFormation (Next time I'll do the deep dive before asking you to re-PR). Thanks for all your work on this 💯 🥇.

**Pull request closed without merging**
