### PR TITLE
Add validation to remove command

### LINKED ISSUE #4406: `sls remove` silently exits 0 if serverless.yml is missing
# This is a Bug Report

## Description

`sls deploy` prints a helpful error message if `serverless.yml` is missing:

```
➜ $(npm bin)/sls deploy -v
 
  Error --------------------------------------------------
 
  This command can only be run in a Serverless service directory
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.2
     Serverless Version:     1.23.0
```

`sls remove` does not:

```
➜ $(npm bin)/sls remove -v
(silence; exits 0)
```

In my case, I had forgotten to render a template file to `serverless.yml` (done in a `deploy` wrapper script omitted above, but not done when running plain `sls remove` as above. This was confusing and tricky to troubleshoot; a message like the one above would make it much more obvious in the future.

For bug reports:
* What went wrong?  **`sls remove` exited silently with success**
* What did you expect should have happened? **It should have printed an error and exited nonzero**
* What was the config you used? **n/a; see above**
* What stacktrace or error message from your provider did you see? **n/a; see above**

Similar or dependent issues:
* n/a

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: Alpine Linux (in docker)
* ***Stack Trace***: n/a; see above
* ***Provider Error messages***:  n/a; see above

### PR DESCRIPTION
**Pull request by alexdebrie**
## What did you implement:

Closes #4406.

Serverless now throws an error if `sls remove` is run in a directory without a `serverless.yml`, rather than exiting silently.

## How did you implement it:

Added `validate` to the `before:remove:remove` hook. This mirrors the implementation in the [deploy command](https://github.com/serverless/serverless/blob/master/lib/plugins/deploy/deploy.js).

## How can we verify it:

1. Pull this branch down.
2. Change into a directory without a `serverless.yml` file.
3. Run `<path-to-repo>/bin/serverless remove`. It should throw an error.

## Todos:

- [X] Write tests
- [X] Fix linting errors
- [X] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by alexdebrie** [comment]
Not sure why tests are failing. Looks like it's in the general area of stuff touched by #4390. @horike37 do you have any ideas here?

Also, I see two `beforeEach()` methods -- is that expected? [Link](https://github.com/serverless/serverless/blob/ebcde3b6837a91869b97a407fed6bda8cfceed62/lib/plugins/aws/deploy/lib/createStack.test.js#L28-L44)

**Comment by HyperBrain** [comment]
@alexdebrie The doubled `beforeEach` is an error in any case - if I remember correctly that means undefined behavior when constructing the object (either of the two is run).

The bodies should be consolidated if not on the same level.

**Comment by alexdebrie** [comment]
Thanks, @HyperBrain. Want me to make that fix in this PR or should I put it in a separate PR?

**Comment by HyperBrain** [comment]
Maybe a separate one that can be merged sooner - so that other branches can update too.

**Pull request merged**
