### PR TITLE
Added validation on `sls create` to check for existing files

### PR DESCRIPTION
**Pull request by aysark**
## What did you implement:

Fixes https://github.com/serverless/serverless/issues/2909, https://github.com/serverless/serverless/issues/2388
`sls create` overwrites existing Python/JS files in directory

## How did you implement it:

Added a validation check in create plugin when no boilerplate is given to check if any of the template files already exist in CWD, if so, throws an error.

## How can we verify it:

Added a test in create.test.js.  And you can first create existing template files in your working dir; `serverless create -t aws-nodejs`.

Then if you do the command again in the same dir; `serverless create -t aws-nodejs`.  You will get an error:
screen shot 2016-12-18 at 5 36 05 pm

## Todos:

- [x] Write tests
- [ ] Write documentation - don't think its needed (error message is sufficient)
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [x] Enable ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for this PR
- [x] Change ready for review message below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by PHYSICSINTELCOM2015** [comment]
Execellent!.

**Comment by pmuens** [comment]
Just PRed the addition that serverless also checks if the service directory already exists (if the user uses the `--path` parameter): https://github.com/serverless/serverless/pull/3014

This PR is GTM from my side 👍

**Comment by FLGMwt** [comment]
Would it make sense to check for just explicitly check for `serverless.yml` instead to make this a bit simpler?

**Comment by pmuens** [comment]
Hmm. IMHO I like it that this PR compares every file in the template to the files in the CWD. This way we won't miss anything. The user can still rename the file anyway if he wants to overwrite it.

@FLGMwt What's the intention to only check for `serverless.yml`?

**Comment by eahefnawy** [comment]
@aysark thanks for that. We'll include that into our next release.

However it seems that there's a syntax error in the test file, and travis is failing as a result. Could you provide a quick fix so we can merge this right away? 😊

**Comment by pmuens** [comment]
Damn... I think I introduced this accidentally when I resolved the merge conflict via the browser. Sorry for that 😬

**Comment by pmuens** [comment]
Just created a new PR with the fix (unfortunately was not able to push on top of this one). --> https://github.com/serverless/serverless/pull/3048 /cc @eahefnawy

**Pull request closed without merging**
