### PR TITLE
Monster whitespace commit

### PR DESCRIPTION
**Pull request by ryansb**
Since so many folks have trailing whitespace removal on, we should really get
rid of these all at once to make it easier to deal with the resulting merge
conflicts.

### CODE REVIEW

**Comment by shortjared** [comment]
@ryansb @ac360 Probably time to start thinking about a CI process to enforce linting and tests? Just set them up to auto run on a PR will fix 95% of the problem.

**Comment by ryansb** [comment]
Yeah, that's true - I don't know what the "cool kids" are using for linting these days, but it'd be pretty easy to set up jshint on TravisCI.

**Comment by eahefnawy** [comment]
BOOM! :D @ryansb you're the bomb! :D

**Comment by marklawlor** [comment]
@ryansb @ac360  Jshint is great for syntax errors but most of its functionality has been deprecated in favor of JSCS of stylistic linting. http://editorconfig.org/ is extremely handy for code consistency as well. I've found using all 3 tools works wonders.  Only hard part is agreeing to the linting rules. Maybe people should vote on one of the presets?

**Pull request merged**
