### PR TITLE
Add `sls:stage` and `sls:region` variables

### LINKED ISSUE #6031: Variables: Introduce access to resolved `stage` via `sls:stage`
At the moment to reference the region or stage you have to do:

```
${opt:stage, self:provider.stage, 'dev'}
${opt:region, self:provider.region, 'us-east-1'}
```

Since this is pretty common, it would be awesome to have simple variables that aliase that, e.g.

```
${sls:stage}
${sls:region}
```

--- 

_Maintainer note_

`region` is AWS specific, therefore it's expected to be handled in other proposal: https://github.com/serverless/serverless/issues/9005

### PR DESCRIPTION
**Pull request by mnapoli**
## What did you implement:

Fix #6031 by adding 2 new variables: `sls:stage` and `sls:region`.

Those variables are shortcuts to:

```
${opt:stage, self:provider.stage}
${opt:region, self:provider.region}
```

## How did you implement it:

To be honest I copied existing code, I am not an expert. Feel free to post comments to suggest improvements.

## How can we verify it:

I added automated tests but testing with a real `serverless.yml` would be great (didn't find those in automated tests).

Here is an example:

```yaml
service: aws-nodejs # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs8.10
  stage: customstage
  environment:
    APP_STAGE: ${sls:stage}
functions:
  hello:
    handler: handler.hello
```

The function could be:

```js
module.exports.hello = async (event) => {
  return { stage: process.env.APP_STAGE };
};
```

The result of this function should be `{"stage":"customstage"}`.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by mnapoli** [comment]
👍 I see, thanks for the feedback.

**Comment by pmuens** [comment]
@mnapoli thank you for your understanding.

I'll close this PR for now however we'll revisit it once #5508 has been figured out.

Thanks again for working on this 👍

**Comment by mnapoli** [comment]
Hi @pmuens, would it make sense to reopen this PR now that #5508 has been closed?

**Comment by mnapoli** [comment]
Follow-up: #9296

**Pull request closed without merging**
