### PR TITLE
Allow request parameter configuration with lambda-proxy integration

### LINKED ISSUE #2882: Return error when lambda-proxy and req/res config user
# This is a Feature Proposal

Follow up of https://github.com/serverless/serverless/pull/2799#issuecomment-265400880. We should return error if both lambda-proxy and req/res config is used to reduce confusion.

### PR DESCRIPTION
**Pull request by HeroesDieYoung**
## What did you implement:

Closes #2882 

SDK generation is incomplete with regard to parameters (path, querystring, and headers) for lambda-proxy integration.  Allowing only the request.parameters object in configuration allows for the successful generation of an SDK that supports their use.

## How did you implement it:

Check for keys other than "parameters" on the request object and remove them (showing a warning to the user) if they exist.  Maintained existing behavior for response configurations, they are still removed and a warning is shown.

## How can we verify it:

Examples:

```
service: test

frameworkVersion: ">=1.13.2 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2
  memorySize: 128

functions:
  helloWorld:
    handler: dist/hello.hello
    events:
      - http:
          path: /{name}
          method: GET
          request:
            parameters:
              querystrings:
                foo: true
              paths:
                bar: true
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by HeroesDieYoung** [comment]
I get that it might be somewhat confusing to support only a limited subset of the request options.  However, that's exactly how AWS is designed.  Lambda-proxy integration allows easy development of lambdas as HTTP endpoints, for restful APIs and the like, and supports the request configuration options I'm trying to expose here.  Moving to lambda integration is a _much_ more configuration heavy alternative to get the same behavior that lambda-proxy provides out of the box.  Lambda integration also changes the event object you receive, making it harder or impossible to get the information you'd want as an HTTP endpoint. 
 Since lambda-proxy is specifically for HTTP endpoints, I would go so far as to argue that not allowing configuration of request parameters makes serverless unsuitable for use with lambda-proxy.

I guess my argument boils down to "Amazon supports it, and for good reason.  If serverless wants to claim lambda-proxy support, it too must support these configuration options."

Re-using a subset of the request configurations seems simplest, as that mirrors how AWS behaves, but can you suggest an alternative that you think might be clearer?

**Comment by sammarks** [comment]
Just ran into this issue in one of the projects I'm currently working on. I agree with the sentiment above and think it would be better to find a solution other than just having developers use the Lambda integration instead.

It seems a little clunky, but if we wanted to avoid the confusion with the request object, why not just have the request object be reserved for the traditional Lambda integration (and keep it named to request so we don't break backwards compatibility), and then introduce a proxy object to contain all of the configuration for the Lambda-Proxy based setup.

Then, inside that object we can configure the parameters and any other Lambda-proxy-specific configuration values.

**Comment by HyperBrain** [comment]
I'm also on the same page here. The (for lambda-proxies) restricted configuration set should be fully supported. Lambda proxy does simplify and remove the complex request/response mappings, but offers you the other options as the lambda integration does.

An option would be, to allow them within an http endpoint definition, but bail out with an error, if unsupported options are specified - this might be a result of accidentally using lambda-proxy where you want to use lambda (remember, the default, if nothing is specified in Serverless is proxy).

/cc @pmuens

**Comment by pmuens** [comment]
Thanks for all the feedback @HeroesDieYoung @sammarks and @HyperBrain 👍 

I just thought through this again and I agree, that we should always reflect the current status of support AWS provides. Therefore we should review this PR throughly and merge it so that users can use the `request` config with the `LAMBDA-PROXY` integration type they would expect based on the current AWS support.

**Comment by eahefnawy** [comment]
Just took this PR for a spin for a final confirmation and didn't have any issues. This is G2M! 🎉 

Tons of thanks @HeroesDieYoung for your contribution 🙌 ... hope we see you again 😊

**Pull request merged**
