### PR TITLE
HTTP API: Access logs configuration

### PR DESCRIPTION
**Pull request by medikoo**
Addresses #7052 

It also includes https://github.com/serverless/serverless/pull/7383 which ideally should be approved and merged first

Support access logs configuration

### CODE REVIEW

**Comment by robbiehanson** [comment]
Is this included in v1.64.1 ?

I enabled logging, but it doesn't seem to work. I added logging configuration to my serverless.yml as described in 7052:
```
provider:
  # ...
  logs:
    httpApi: true
```

**Comment by medikoo** [comment]
> Is this included in v1.64.1 ?

Sorry, it'll be published shortly with v1.65.0

**Comment by camhart** [comment]
What IAM permissions are required for this?

`An error occurred: HttpApiStage - Insufficient permissions to enable logging (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: 380bde81-0981-46b4-9a4c-1b1dcd5133e8).`

**Comment by medikoo** [comment]
@camhart it appears that due to recent change on AWS side new IAM permissions are required.
They're outlined here: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-logging.html#http-api-logging.permissions

**Comment by rererecursive** [comment]
@camhart I just ran into this issue as well and had to debug this with AWS support. It's a bug on Amazon's side.

Whenever you create a CW log group, there's another resource created alongside it called a "resource policy". The problem is that every new resource policy is getting appended to a single item, which causes you to hit the character limit on the policy size. 

So, even though you can create new log groups in the console, you have no permissions to actually use them.

You can see this by running `aws logs describe-resource-policies`. It will output a single item called `resourcePolicies` -> `AWSLogDeliveryWrite` containing a list of log group names. You will see that the name of your CloudWatch log group is missing from this list. This is because if you try to update this item by including your log group's name, you will run into the error:
`'policyDocument' failed to satisfy constraint: Member must have length less than or equal to 5120`

This is performed by AWS and we have no control over it, but you can update the policy using the API. The fix is to overwrite the `AWSLogDeliveryWrite` policy with `arn:aws:logs:<region>:<account>:log-group:*` as part of a `aws logs put-resource-policy`. It should then work.

**Comment by medikoo** [comment]
@rererecursive great thanks for sharing that. It definitely can help many users which approach that.

**Comment by stevenj** [comment]
I just hit this issue myself.  What a pain.

**Pull request merged**
