### PR TITLE
WIP: Add Google Cloud Functions support

### LINKED ISSUE #1510: Add support for Google Cloud Functions
Google Cloud Functions work a little differently from AWS. However we'll try to have a common interface across provider whenever we can, which should be easier with the provider-per-service approach. Here's a basic outline of their offering and how we can support it:

**Research:**
- [ ] Google Functions use `triggers` to trigger functions. It's just like our events concept, so we'll call it `events` for consistency.
- [ ] Google Functions support HTTP, Bucket, Pub/Sub topic and direct invoke triggers. They don't yet support schedule events. 
- [ ] Google Functions can support additional triggers by using Pub/Sub topics as a proxy, for example Gmail push notifications and cloud logging.
- [ ] Google Functions can be tested/invoked using the direct trigger event.
- [ ] Google Functions can be deployed from either a Google Storage bucket, or a source control repo. We'll probably go with the bucket approach for consistency.
- [ ] Google Functions are not yet supported in the SDK, and they don't provide a public REST API either. The only way to access Google Functions right now is via the CLI. So we'll have to have this dependency, at least for now.
- [ ] Google Functions are not supported in Google Resource Manager either. So we won't be able to deploy via the resource manager and be consistent in that front.
- [ ] Google Functions logs are accessed via Google StackDriver, the equivalent of AWS CloudWatch. So we'll be able to have logging functionality.
- [ ] The entry point is called `entryPoint` but we should call this `handler` for consistency
- [ ] Right now only Node.js is supported
- [ ] Google thinks in terms of `Projects` we should keep `Service`
- [ ] Two types of functions (`foreground` and `background` --> [docs](https://cloud.google.com/functions/docs/writing/))

**Questions:**
- Should we go full `CLI` since CloudFunctions can only be deployed this way or should we use the Resource Manager to e.g. deploy the `serviceBucket`?
- How do we abstract the `Pub/Sub topic` support as an event source?

**Helpful links:**
- https://github.com/GoogleCloudPlatform/nodejs-docs-samples

### PR DESCRIPTION
**Pull request by pmuens**
## What did you implement:

Closes #1510

This is a WIP PR which adds the Google Cloud functions integration to the Serverless framework.
## How did you implement it:

Wrote integration plugins for the serverless plugins like `deploy`, `invoke`, `remove`, etc.
## How can we verify it:

Read the README at https://github.com/serverless/serverless/tree/add-google-cloud-functions-support/lib/plugins/google

## Implemented features

- [ ] `create` (**Note:** We need to add a template to the core (which is not recommended as this won't be merged into master) or we need a way for plugins to inject templates from their codebase)
- [x] `deploy`
- [x] `remove`
- [x] `info`
- [x] `invoke`
- [x] `info`
- ~`deploy function` (Not yet supported by Google Cloud Functions API)~

## Todos:
- [ ] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources
- [ ] Change ready for review message below
- [x] Run `npm shrinkwrap`

**Is this ready for review?:** NO

### CODE REVIEW

**Comment by pmuens** [comment]
@ac360 @eahefnawy @flomotlik Just updated the PR so that the `info` plugin and the `bucket` event source is in place. Furthermore I've update the README so that you get a full example with all event types and the corresponding handlers.

I looked into `deploy function` support. However the current Google Cloud Functions API don't support direct code pushed to functions.
It only supports the updating of the `.zip` file in the bucket. We could implement that but this means that after 5 `deploy function` calls the other functions won't work anymore as the corresponding `.zip` file (the old one the not updated functions rely on) will be removed. That's why I think the feature is not necessary for this MVP implementation.

Would be great if you could play around with it and share your thoughts.

**Comment by flomotlik** [comment]
@pmuens created a new Repo: https://github.com/serverless/google-cloud-functions-plugin

Could you move the code as a plugin there?

**Comment by pmuens** [comment]
@flomotlik yes, I can do that.

Before moving it there I'll fix the bugs @ac360 mentioned. Furthermore we might want to discuss how this plugin should work.

I would not add a `google-nodejs` template to the core system as it should be in the plugin (see https://github.com/serverless/serverless/issues/2498).

Should the user be able to add a `serverless-provider-google` which encapsulates all the other plugins? What should this name be?

**Comment by pmuens** [comment]
Closing this one as it has been moved to the dedicated plugin repository: --> https://github.com/serverless/google-cloud-functions-plugin

**Pull request closed without merging**
