### PR TITLE
The provider.logs.restApi sub fields do not accept string values of "true" or "false".

### LINKED ISSUE #6782: The always restApi logs enable when using an SSM parameter in the configuration.
# Bug Report

## Description

1. What did you do?

I enable logs depending on the stage using SSM parameters.

1. What happened?

The API Gateway logs enable for every stage. The SSM values for `dev` and `test` stages were `false`, and `staging` and `prod` were `true`.

1. What should've happened?

API Gateway logs should have been disabled for `dev` and `test`, and enabled for `staging` and `prod`.

1. What's the content of your `serverless.yml` file?

```yaml
provider:
  logs:
    restApi:
      accessLogging:     ${ssm:/${self:provider.env}/API_GW_LOGS}
      executionLogging:  ${ssm:/${self:provider.env}/API_GW_LOGS}
      fullExecutionData: ${ssm:/${self:provider.env}/API_GW_LOGS}
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Not captured.

Similar or dependent issues:

- #12345

### PR DESCRIPTION
**Pull request by miguel-a-calles-mba**
## What did you implement

Closes #6782 

## How can we verify it

Logs are disabled with this configuration:

```yaml
provider:
  logs:
    restApi:
      accessLogging:     "false"
      executionLogging:  "false"
      fullExecutionData: "false
```

Logs are enabled with this configuration:

```yaml
provider:
  logs:
    restApi:
      accessLogging:     "true"
      executionLogging:  "true"
      fullExecutionData: "true"
```

## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test-ci` --> Run all validation checks on proposed changes
- `npm run lint-updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check-updated` --> Check if updated files adhere to Prettier config
- `npm run prettify-updated` --> Prettify all the updated files

</details>

- [x] Write and run all tests
- [x] Write documentation
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** YES

### CODE REVIEW

**Comment by exoego** [comment]
I understand it is frustlaed that serverless framework does not accept string "true" or "false".
I also opened a similar PR for other boolean configuration in #6561, but it was closed after design discussion.
There are lots of boolean (or numeric) variables in severless framework, and adding special treat like this PR and #6561 is considered tech debt.

It is recommended to use `$file` variable and use booleans in those files.
https://github.com/serverless/serverless/pull/6561#issuecomment-523006447

**Comment by medikoo** [comment]
@miguel-a-calles-mba https://github.com/serverless/serverless/issues/6782#issuecomment-538399679

**Comment by miguel-a-calles-mba** [comment]
Hi @pmuens, I'm okay closing this PR if it is not the preferred approach.

**Comment by pmuens** [comment]
> Hi @pmuens, I'm okay closing this PR if it is not the preferred approach.

@miguel-a-calles-mba thanks for following-up! Sorry for the misunderstanding. I thought that this PR might be obsolete given that you tackle this problem in #6787. I guess my question is if #6787 fixes the same issue this PR aims to solve.

**Comment by pmuens** [comment]
Closing this PR as #6787 is a follow-up PR which addresses the same problem.

**Pull request closed without merging**
