### PR TITLE
feat: Use nodejs18 in custom-resources and aws-sdk v3

### PR DESCRIPTION
**Pull request by xoapit**
Closes: #12133

Based on changes from #12146 by [svoychik](https://github.com/svoychik). He is not available to resolve the conflicts so I have recreated the PR based on that changes.

### CODE REVIEW

**Comment by tonivdv** [comment]
@xoapit thanks for taking the time and hope it will be merged asap :) 

Just little question, is there a specific reason to not already bump the runtime to nodejs20 ? I see that in the v4 branch it was already set to 20 so I guess it should work?!

**Comment by xoapit** [comment]
@tonivdv  nodejs20 runtime is not available in AWS Cloud (US) https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-lambda.html so I want to keep it as 18.x to make sure it works for all partitions

**Comment by jeffrey1226** [comment]
When will you merge it? Node 16 is deprecated soon. So we need to fix it asap.

**Comment by xoapit** [comment]
No one from the serverless team reviews and merges the PR, no releases from Nov 2023. Hmm, It looks like they do not want to maintain version 3.

**Comment by xoapit** [comment]
V.4 introduces a new pricing model, please refer to https://www.serverless.com/blog/serverless-framework-v4-a-new-model

**Comment by jeffrey1226** [comment]
Hi @xoapit , Thank you for your reply. I see. It's not good for me. Can you please help me how to download your PR to my local project? I can't wait. And it seems like they stopped to support this v3.

**Comment by xoapit** [comment]
@jeffrey1226 It won't work with your local project. Maybe you can apply a patch like this https://github.com/serverless/serverless/issues/12133#issuecomment-1958961198

**Comment by garethmcc** [comment]
Some additional clarity as well regarding AWS timelines; while AWS is marking June, 2024 as when Node 16 is deprecated, this will have no impact on deployments at that stage. AWS will only be blocking function create from February, 2025.

**Comment by maximiliangertz** [comment]
Any update on this?

**Comment by Mmarzex** [comment]
We just released the beta of Framework v4 which contains updating the custom resources runtimes @maximiliangertz

**Comment by xoapit** [comment]
@Mmarzex Does Serverless have a plan to maintain v3? Your team published v4 under `serverless`, not @serverless/v4, so v3 is no longer supported.

**Comment by vSkoryk** [comment]
@Mmarzex can we still get it merged please?

**Comment by j0k3r** [comment]
Job is already done in a previous PR https://github.com/serverless/serverless/pull/12311

**Comment by vSkoryk** [comment]
@j0k3r Hi, PR you mentioned is not merged either. Will it be merged?

**Comment by j0k3r** [comment]
@vSkoryk I've no idea, I don't have the right to merge nor working at Serverless Inc.

**Comment by robinwolny** [comment]
Please prioritize this PR. Thank you

**Comment by mdchrist** [comment]
hi @Mmarzex 
I know you mentioned this is available on serverless v4 beta, but this issue is around the v3 serverless framework.
What is the expectation of merging this PR or resolving this issue?
AWS extending support of lambda node16 as well as this being available on serverless v4 have been mentioned, but these factors do not solve the issue... they just provide extensions and workarounds.

**Comment by jeffrey1226** [comment]
> @jeffrey1226 It won't work with your local project. You can apply a patch like this [#12133 (comment)](https://github.com/serverless/serverless/issues/12133#issuecomment-1958961198)

Thank you @xoapit 
It works perfectly. You saved me.

**Comment by Mmarzex** [comment]
Hi everyone, thank you for your patience, this is now supported in a new v3 release, specifically [v3.39.0](https://www.npmjs.com/package/serverless/v/3.39.0), it is available on NPM now.

**Comment by dave-continuum-media** [comment]
[celebrate]     Dave Boyer reacted to your message:
________________________________

**Pull request closed without merging**
