### PR TITLE
Upgrade aws-csharp to .NET Core 2.0

### PR DESCRIPTION
**Pull request by slang25**
## What did you implement:

Upgrade aws-csharp to .NET Core 2.0

## How did you implement it:

I upgraded the current template and example from inspection.
I've simplified things where possible, including:
- Removing `global.json`, we no longer need to pin the sdk back
- Removed the call to `dotnet restore`, this is implicit
- Removed the apt zip install as this was a workaround required due to a bug in `netcoreapp1.0`

## How can we verify it:

I will run through the tests in the morning (UK time), and do a manual verification by creating an empty project from this template.

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by horike37** [comment]
Awesome! Thank you for working on this @slang25 :100: 
Ping @serverless/framework-maintainers if you need any helps or you are ready for review!

**Comment by horike37** [comment]
Hi @slang25, I have a question.
Currently, your approach is to upgrade from dotnet core 1.0 instead of adding a new template.
Is dotnet core 2.0 compatible with 1.0? If so, it would be good to the current approach but if not, we should add a new template with separating from the existing one.

Cloud you tell us since I'm not csharp expert.

**Comment by slang25** [comment]
Hi @horike37 

I gave this some thought, and I couldn't think of a good reason why someone would target 1.0 today.

Libraries that were compatible with netcoreapp1.0 and netstandard1.0 will work with 2.0, so I see it as a logical superset, or at least practically enough so that we only need to offer 1 template.

**Comment by horike37** [comment]
@slang25 
OK, make sense!
Let's go ahead the upgrading way :+1: 

Ping us if you are ready for review so that we can start to review and test it.

**Comment by yunspace** [comment]
Hi @slang25 I was able to follow your example and get fsharp to work with dotnet 2.0 also. My code is here: https://github.com/yunspace/lambda-platform-perf-comparison

Do you plan to add fsharp support in as part of your PR? Alternatively I can create a support PR for fsharp 2.0 support

**Comment by slang25** [comment]
Hi @yunspace, I was thinking about doing it in the same PR, but then I thought I should try to keep things small. Yeah if you want to jump in with a PR that would be awesome, equally if there's nothing in by the time I have this tested and merged then I'll take on.

**Comment by yunspace** [comment]
Ok I'll try and get it in, since I got the code ready anyway it will probably be easier.

**Comment by yunspace** [comment]
Hi @slang25 do you need a hand with this PR? If you can grant me access to your fork or alternatively I can merge your code into my #4688? Would be nice to get this in for 1.27.0

**Comment by slang25** [comment]
Thanks @yunspace, I would appreciate that 😃 I had some issues running the integration test, I'll have another go over the weekend. I have added you as a collaborator to my repo.

**Comment by yunspace** [comment]
@slang25 integration tests should work now. The issue was missing `zip` in `microsoft/dotnet` docker image, which I've added now into `build.sh`.

So I run:

     tests/templates/integration-test-template aws-csharp './build.sh'

Need to make sure all aws creds are set and all files are in unix format (I'm on windows).

**Comment by yunspace** [comment]
@horike37 I think this is ready to review. However either you or an admin needs to re-trigger than failed travis build due to timeout. Alternatively @slang25 would need to close and re-open this PR to re-trigger it.

**Comment by HyperBrain** [comment]
Retriggered :)

**Comment by horike37** [comment]
@yunspace 
Awesome :+1: :+1: 
We will review it.

@HyperBrain 
Thanks!

**Comment by slang25** [comment]
Brilliant @yunspace, although zip should not be needed, it was added in the 1.0 version to work around a bug in the runtime (the zips were corrupt), bit in dotnet core 2.0 it should work with just `dotnet lambda package`

**Comment by yunspace** [comment]
@slang25 hmm I see, I was getting a zip not found error... will double check

**Comment by yunspace** [comment]
Okay confirmed `zip` is definitely needed:

```
Changed permissions on published dll (chmod +r Newtonsoft.Json.dll).
Zipping publish folder /app/bin/release/netcoreapp2.0/publish to /app/bin/release/netcoreapp2.0/deploy-package.zip
Failed to find the "zip" utility program in path. This program is required to maintain Linux file permissions in the zip archive.
```

I've raised issue https://github.com/dotnet/dotnet-docker/issues/409 I can fix this up when there is a fix. But this PR should be good to go.

**Comment by slang25** [comment]
@yunspace Nice find. I can see what the issue is, the behaviour you are seeing now was added to `Amazon.Lambda.Tools` because it would fail under the .NET 1.0/1.1 runtimes, however it was planned to be changed for 2.0 so that it would use the .NET compression by default on non-Windows.

[See here](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Tools/LambdaPackager.cs#L105-L125)

However it looks like this was forgotten, so I'll PR it up over there, that shouldn't block this PR though.

**Comment by slang25** [comment]
PR here: https://github.com/aws/aws-lambda-dotnet/pull/238

**Pull request merged**
