### PR TITLE
Replace internal inquirer with @serverless/inquirer

### PR DESCRIPTION
**Pull request by AhmedFat7y**
Closes: #7690

### CODE REVIEW

**Comment by AhmedFat7y** [comment]
@medikoo 
Object Destructing is not supported in node v6.x
[@serverless/inquirer](https://github.com/serverless/inquirer) is using a higher version of [chalk ](https://github.com/chalk/chalk) `^3.0.0` which needs a higher version node engine `>= 8`
Other references are using `^2.4.2`, `^2.4.1`, `^2.0.1`

```
/home/travis/build/serverless/serverless/node_modules/@serverless/inquirer/node_modules/chalk/source/index.js:103
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Function.Module._load (/home/travis/build/serverless/serverless/node_modules/mock-require/index.js:30:22)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/serverless/serverless/node_modules/@serverless/inquirer/index.js:8:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
```

**Comment by medikoo** [comment]
@AhmedFat7y indeed, thanks for finding this out. It's a bug in `@serverless/inquirer` which I've just fixed. Bump version to v1.1.1 and it should be good.

**Comment by AhmedFat7y** [comment]
@medikoo one more thing, will this cause a problem? It seems to be path-based resolution
https://github.com/serverless/serverless/blob/2a72b1ab0b98e07972a88937299428587f11f96a/lib/plugins/interactiveCli/tabCompletion.js#L47-L49

**Comment by medikoo** [comment]
> @medikoo one more thing, will this cause a problem? It seems to be path-based resolution

This won't be affected. `require.resolve` resolves absolute path to `inquirer` as used by `tabtab`, and after that all is safe, as we work with correct absolute path.

**Comment by AhmedFat7y** [comment]
@medikoo I'm not sure what's the problem here. I modified the package version to `^1.1.1` and added `npm show @serverless/inquirer` to `travis.yml` to make sure it's the same version I intended, and it's all good.

However, it still throws the same error
```bash
npm show @serverless/inquirer
@serverless/inquirer@1.1.1 | MIT | deps: 3 | versions: 3
An inquirer with enforced Serverless theme
https://github.com/serverless/inquirer#readme
keywords: inquirer, serverless
dist
.tarball: https://registry.npmjs.org/@serverless/inquirer/-/inquirer-1.1.1.tgz
.shasum: bff3d8efac69237f345c835a027b0fbd82b1d8db
.integrity: sha512-kzrFQ6/TV+z6WvMEEfOzMWEorClMrCJy4z+lcdaiEN8xe+VH+TcxT7O9tsgj4pYlHioT3raDPjTBX9jvPbzo3Q==
.unpackedSize: 16.0 kB
dependencies:
chalk: ^2.0.1    inquirer: ^7.1.0 ncjsm: ^4.0.1    
maintainers:
- serverless-main <services@serverless.com>
dist-tags:
latest: 1.1.1  
published yesterday by serverless-main <services@serverless.com>
The command "npm show @serverless/inquirer" exited with 0.
$ npm test -- -b
> serverless@1.71.1 test /home/travis/build/serverless/serverless
> mocha "!(node_modules)/**/*.test.js" "-b"
/home/travis/build/serverless/serverless/node_modules/@serverless/inquirer/node_modules/inquirer/node_modules/chalk/source/index.js:103
	...styles,
	^^^
```

**Comment by medikoo** [comment]
@AhmedFat7y indeed, it appears there's also problem with `inquirer` which with patch release broken support for Node.js v6 (reported that issue: https://github.com/SBoudrias/Inquirer.js/issues/920)

Anyway I've downgraded `inquirer` there to version which is used here, so now there should be no issue. Just change version range to `^1.1.2^

**Comment by AhmedFat7y** [comment]
@medikoo There's no reviewer for this PR, but it's done, what will happen now?

**Comment by medikoo** [comment]
> @medikoo There's no reviewer for this PR, but it's done, what will happen now?

Thanks for info. I'll review it next days (unfortunately in next days my priorities were shifted, so I may respond with delay now)

**Pull request merged**
