### PR TITLE
Add support for Alibaba Cloud Function Compute provider

### PR DESCRIPTION
**Pull request by joyeecheung**
Hi, this PR adds support for the Alibaba Cloud Function Compute provider. Alibaba Cloud Function Compute is the FaaS product developed by [Alibaba Cloud](https://www.alibabacloud.com/), one of the largest cloud provider in China. The serverless plugin is located in [aliyun/serverless-aliyun-function-compute](https://github.com/aliyun/serverless-aliyun-function-compute) and has been published to npm.

I assume the images (http://docs.alibabagroup.com/assets2/images/en/news/library_logos_aliyun_large.png) need to be uploaded to the serverless.com S3 bucket else before this can be merged. Also note that the name `aliyun` and `Alibaba Cloud` are interchangeable, the former is the Chinese spelling of "Alibaba Cloud" and is preferred in code while the latter is preferred in documentations.

## What did you implement:

Add support for Alibaba Cloud Function Compute provider

## How did you implement it:

* Add create template `aliyun-nodejs`
* Add documentations for the Alibaba Cloud Function Compute

## How can we verify it:

Using this fork, do:

```
serverless create --template aliyun-nodejs
npm install
# configure credentails and serverless.yml
serverless deploy
```

screen shot 2017-09-26 at 2 56 25 pm
screen shot 2017-09-26 at 2 56 49 pm copy

## Todos:

- [x] Write tests
- [x] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by ac360** [comment]
Wow :)

**Comment by eahefnawy** [comment]
@joyeecheung Awesome!!!!! We'd love to make this integration more official! I've sent an email to joyeec9h3 [aaat] gmail to discuss more. Please let me know if there's another email I should send to.

Thanks a lot for your contribution 😊

**Comment by joyeecheung** [comment]
@eahefnawy Hi, I'll be happy to make this integration more official. BTW just realized I have used my private email in this PR by mistake, so I force pushed to use the company email instead. I will resend the email using that address, sorry for the confusion.

**Comment by ChenLi0830** [comment]
Finally! A Chinese Cloud Provider that support serverless architecture. I can feel the tears in my eyes

**Comment by hgl** [comment]
Any progress on this one?

**Comment by hgl** [comment]
@joyeecheung any chance you could also add [`aliyun-nodejs` to `validTemplates` here](https://github.com/serverless/serverless/blob/3c058f2cf0046361f2936b680b263dc0284fd9f9/lib/plugins/create/create.js#L12), currently 

```
serverless create --template aliyun-nodejs --path my-service
``` 

fails with 

```
Template "aliyun-nodejs" is not supported.
```

**Comment by hgl** [comment]
@joyeecheung I tried to use this fork, but after running `serverless deploy` I got the `the parent of sub user must be project owner` error. Seems to come from the log service. The account corresponding to `aliyun_account_id` are the one that activated the log service. Any idea?

**Comment by ChenLi0830** [comment]
@joyeecheung Any new updates?

**Comment by joyeecheung** [comment]
Just helped out @hgl last night, the user must make sure they've set up the credentials right before trying the first deploy otherwise there will be a few confusing authorization errors from the remote server (not really something we can do about at the moment..).

@ChenLi0830 The plan is to land this when FC is available in the international regions and have official English documentations ready. That should happen within this year.

**Comment by hgl** [comment]
Very thankful to @joyeecheung for helping me until late night.

The issue was that you need to absolutely make sure you have manually activated on aliyun'website all services this plugin will interact with, before executing `sls deploy`, otherwise the second run will fail even if you have activated them after the first run. The "all" part is very important, you need to activate all mentioned services like log, oss, etc, even if you don't intend to use some of them, otherwise it will fail too.

The provider needs three credential values to interact with all services, make sure you gather them correctly from the site (they're not on the same page).

Do hope the experience will improve over time. Looking forward to embrace serverless architecture on aliyun painlessly.

**Comment by hgl** [comment]
After some investigation I realize the real reason for my encountered error was that the aliyun log service requires a globally unique project name, which means the serverless service name we choose needs to be globally unique on aliyun.

For example, if you follow the quick guide and try to create a service named "my-service", you'll encounter the same error as I did, and it's pretty cryptic.

**Comment by banyudu** [comment]
Any new updates?

**Comment by horike37** [comment]
Hi @banyudu, thank you for pinging :+1: 
The Alibaba Cloud Function Compute provider is supported for only China region. We will be able to merge it and official release after being supported for internal region as well.

@joyeecheung 
Do you know what is the current status that FC release for internal region?

**Comment by joyeecheung** [comment]
@horike37 I can't really answer that because I don't work on the FC team, sorry.

**Comment by horike37** [comment]
@joyeecheung 
Don't worry :+1: 
I closed this once to keep the repo clean. You can re-open and take a step forward if there is any new updates on this :smile:

**Comment by shuaichang** [comment]
@horike37 we plan to launch the first international region in couple of months, we will re-open this PR once it's ready.

**Comment by roura356a** [comment]
Hey @horike37 FYI Function Compute is International now =D

**Pull request closed without merging**
