### PR TITLE
Set default or custom function.name property

### PR DESCRIPTION
**Pull request by eahefnawy**
This PR sets a default `name` property in the function object if it doesn't exist. This includes updating the logs and invoke plugins as they're using the function name. Resolves Issues #1718 & #1697

cc/ @flomotlik @pmuens

### CODE REVIEW

**Comment by pmuens** [comment]
Does this allow the user to overwrite the name of the function?

Additionally we can remove the fallback to the name creation here:
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/functions/index.js#L70-L71

**Comment by eahefnawy** [comment]
@pmuens Nice catch!! and yes it overwrites the default if a `name` is provided by the user

**Comment by flomotlik** [comment]
Did you  validate this works now with Logs and info and custom names?

If you did LGTM, if @pmuens agrees then we can merge.

**Comment by eahefnawy** [comment]
@flomotlik yep, tried it on a real service. No issues. Just updated the tests.

**Comment by pmuens** [comment]
Just one final question. Is there also a test which tests the fallback to the default name when no custom name is given (in the `Service` test)?

LGTM if this is in place.

Good job! 👍

**Comment by eahefnawy** [comment]
@pmuens most of the test cases for the `load()` method use the default lambda name since this is how we set it up initially. [Here's one example](https://github.com/serverless/serverless/blob/master/tests/classes/Service.js#L572)

**Pull request merged**
