### PR TITLE
feat: Add support for python3.12 runtime

### PR DESCRIPTION
**Pull request by LironEr**
Add support for python 3.12 runtime ([announcement](https://aws.amazon.com/about-aws/whats-new/2023/12/aws-lambda-support-python-3-12/))

Closes: #12299

### CODE REVIEW

**Review by adminy — APPROVED** [review]

**Comment by DamianCzajkowski** [comment]
Hello, will work on merging these changes start anytime soon?

**Comment by StuartBertram** [comment]
I know it has been Christmas, but looking at the "blame" info, the Python 3.11 release was [proposed on the 26th July](https://github.com/serverless/serverless/pull/12085) and [merged on the 27th](https://github.com/serverless/serverless/pull/12085#event-9940281591) when [AWS made their announcement](https://aws.amazon.com/about-aws/whats-new/2023/07/aws-lambda-python-3-11/).

Hopefully it's quicker than Python 3.10, which was [proposed on 18th April](https://github.com/serverless/serverless/pull/11922) (the [same day that it was annouonced](https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-python-3-10/)) but [not merged until 11th May](https://github.com/serverless/serverless/pull/11922#event-9224660572) because of vacation time!

**Comment by FinchPowers** [comment]
There has been no activity over the master branch since December 6th. I wonder what will happen with Serverless v3 with the plans for v4.

**Review by r3sdev — APPROVED** [review]
LGTM

**Comment by robgagliano** [comment]
Is there any update on this PR?

**Comment by mgerlach** [comment]
Hi, could this be merged quickly, please?

**Comment by norvalbv** [comment]
Commenting on this to hopefully bump it up. Version 3.12 would be ideal, hopefully can get merged asap.

**Comment by scolebrook** [comment]
Is Serverless still being actively maintained? This (seemingly small and simple PR) has been sitting waiting for attention for a LONG time with many people commenting and no merge, let alone release.

**Comment by Mmarzex** [comment]
Sorry everyone, this will be included in the v4 beta that is targeted for availability within the next week.

**Review by daniel094 — APPROVED** [review]

**Review by max-lobur — APPROVED** [review]

**Comment by max-lobur** [comment]
> Sorry everyone, this will be included in the v4 beta that is targeted for availability within the next week.

Why does this require a mayor release?

**Comment by adminy** [comment]
Simple, Profit 😜 V4 is licensed for profit. V3 isn't. Also I'm guessing the features on V4 are not going to be backwards compatible. since its a reimplementation

**Comment by scolebrook** [comment]
> Sorry everyone, this will be included in the v4 beta that is targeted for availability within the next week.
That "next week" was over 6 weeks ago.

https://www.serverless.com/blog/serverless-framework-v4-a-new-model

This blog post is from October last year so it's not news for many, but it is for me. Seems like Serverless v4 is going to require a paid license for anything but the most modest commercial use. That blog post says that v3 will still be maintained with "critical security and bug fixes through 2024". I guess they don't consider supporting up to date Lambda runtimes as a critical security or bug fix. Many would beg to differ.

But it's kind of moot given that Serverless won't be a true open source project any longer. I hope someone forks from v3 and keeps it alive. Otherwise, time to pin to v3.latest and start migrating projects to SAM and deal with it's limitations.

**Comment by mgerlach** [comment]
> Simple, Profit 😜 V4 is licensed for profit. V3 isn't. Also I'm guessing the features on V4 are not going to be backwards compatible. since its a reimplementation

Yep. We have now decided to abandon serverless in the long run.

**Comment by max-lobur** [comment]
> > Sorry everyone, this will be included in the v4 beta that is targeted for availability within the next week.
> > That "next week" was over 6 weeks ago.
> 
> https://www.serverless.com/blog/serverless-framework-v4-a-new-model
> 
> This blog post is from October last year so it's not news for many, but it is for me. Seems like Serverless v4 is going to require a paid license for anything but the most modest commercial use. That blog post says that v3 will still be maintained with "critical security and bug fixes through 2024". I guess they don't consider supporting up to date Lambda runtimes as a critical security or bug fix. Many would beg to differ.
> 
> But it's kind of moot given that Serverless won't be a true open source project any longer. I hope someone forks from v3 and keeps it alive. Otherwise, time to pin to v3.latest and start migrating projects to SAM and deal with it's limitations.

Oh wow, thanks. Welcome SAM then 😁

**Comment by astuyve** [comment]
Locking a 1 line PR behind v4.x and the licensing change is a bad look. The community should fork this project.

**Comment by jimmyn** [comment]
Anyone forked it already?

**Comment by FinchPowers** [comment]
I just made a super simple plugin that allows to override the awsLambdaRuntime value of the validation schema.

https://www.npmjs.com/package/serverless-v3-aws-lambda-runtime-schema-override

[It's a single file with no external dependencies](https://github.com/FinchPowers/serverless-v3-aws-lambda-runtime-schema-override/blob/main/index.js).

**Comment by manumbs** [comment]
> > Sorry everyone, this will be included in the v4 beta that is targeted for availability within the next week.
> > That "next week" was over 6 weeks ago.
> 
> https://www.serverless.com/blog/serverless-framework-v4-a-new-model
> 
> This blog post is from October last year so it's not news for many, but it is for me. Seems like Serverless v4 is going to require a paid license for anything but the most modest commercial use. That blog post says that v3 will still be maintained with "critical security and bug fixes through 2024". I guess they don't consider supporting up to date Lambda runtimes as a critical security or bug fix. Many would beg to differ.
> 
> But it's kind of moot given that Serverless won't be a true open source project any longer. I hope someone forks from v3 and keeps it alive. Otherwise, time to pin to v3.latest and start migrating projects to SAM and deal with it's limitations.

@scolebrook why `java21` is supported in `v3` in this [PR](https://github.com/serverless/serverless/releases/tag/v3.39.0) and `python3.12` can't be as well?

**Comment by mgerlach** [comment]
Meanwhile adding `configValidationMode: warn` to serverless.yml should work. We use it and are able to set the runtime to Python 3.12.

**Comment by JeffTax** [comment]
meme

**Comment by pkucmus** [comment]
Would anyone care for [Smyth](https://mirumee.github.io/smyth/)? It's not a direct replacement for Serverless but if your looking for a Lambda developer runtime then deploy by hand or with the likes of TF then it might be useful. 

(I hope it won't bother anyone that I'm posting about Smyth here, I apologize if it does - I'm just exited about a tool I made)

**Comment by jimmyn** [comment]
I recently found this fork: https://github.com/oss-serverless/serverless

And it looks legit and it is regularly updated. You can send your PR there

**Comment by pkucmus** [comment]
There's also https://mirumee.github.io/smyth/ and https://mirumee.github.io/lynara/ maybe it'll help someone - those are not direct replacements for Serverless but might be enough to improve one's developer experience when working with Lambdas

**Comment by austencollins** [comment]
Closing this PR as the feature is already available in V.4, along with additional improvements, and this PR is getting spammy.

**Comment by JeffTax** [comment]
LOL, I called out that it was financially motivated not to support this minor change, and they deleted it... all that to try and get people to upgrade to a paid version.

I would like it to stand that even though the community wanted this small and inconsequential change, they didn't want to do it for any reasonable reason other than their benefit. Open source isn't about deleting things because you don't like them.

**Comment by mgerlach** [comment]
+1

**Comment by tibbe** [comment]
We migrated to CDK as a result of handling of this and other similar issues.

**Pull request closed without merging**
