### PR TITLE
Added missing options for parsing of templates

### PR DESCRIPTION
**Pull request by svdgraaf**
See this issue: https://github.com/serverless/serverless/issues/1704, the `${stage}` and `${region}` variables were not available in the template parsing, I added the `options` hash to the variable parsing. I added them as first item, so other vars can override, if needed.

Now, you can dynamically create resources, based on the stage etc, eg:

```yml
resources:
  Resources:
    FoobarBucket:
      Type: AWS::S3::Bucket
      Properties:
       BucketName: ${stage}-foobar-bucket
```

Which would result in a `dev-foobar-bucket` and a `production-foobar-bucket`.

### CODE REVIEW

**Comment by flomotlik** [comment]
looks good to me. @eahefnawy @pmuens could you take a quick look to check if there could be an issue with it?

**Comment by eahefnawy** [comment]
This looks simple but I gotta think it through (I'm not feeling good about it tbh 😄 ) ... The reason being is that if the issue is in the shortcut only as the issue states, then it's probably an issue in the CLI class (or maybe plugin manager) since the Service class should get the options ready to go whether it's a shortcut or not.

Also, what this PR seems to be doing is trying to populate variables **from options rather than serverless.env.yml** file, which is not intended to be done with CLI options. If you want the stage name as a variable you can add a `stageName` variable inside that stage vars object in `serverless.env.yaml`

These are just on top of my head, I'm gonna take a closer look and provide you with more info asap.

Thanks for digging into this @svdgraaf and bringing this up. Our codebase is getting higher in quality thanks to you 😊

**Comment by svdgraaf** [comment]
@eahefnawy well, the idea was to have dynamic variables, based on the stage/environment. So that you can switch resource properties based on those variables, without the need to set a variable in the .env file.

Thinkin further about this, this can actually be done with a `Ref:"AWS::Region"` and `Ref:"AWS::StackName"`. I'll work something out and create a PR for an example in the documentation.

So let's close this PR, I agree that this isn't needed. I'm not sure how this would work with other providers though.

**Comment by eahefnawy** [comment]
@svdgraaf sounds good. This is actually a part of a bigger discussion we're starting in issue #1707 ... Would love to hear your thoughts there. The idea of passing variables via the CLI is definitely interesting as we're thinking to rely less on `serverless.env.yml`

**Comment by wedgybo** [comment]
We were discussing this in gitter the other night. I'm with @svdgraaf and think that some key vars should be made available by default, which could then be overridden by the serverless.evn.yml file.

The variables I see being useful are:

 * stage
 * service
 * provider
 * region
 * runtime

So maybe instead of cloning the options object we could select key parts from the serverlessYml object?

**Comment by flomotlik** [comment]
@wedgybo could you open an issue outlining this?

**Pull request closed without merging**
