### PR TITLE
Continue recursion for #4687

### PR DESCRIPTION
**Pull request by bsdkurt**
## What did you implement:

Additional fix for #4687

## How did you implement it:

Continue recursion for populateValue root case.

## How can we verify it:

The following serverless.yml can be used to reproduce the problem. Adjust cf reference to an existing stack with an export.

```yaml
service: test

custom: ${file(custom-properties-${opt:stage, self:provider.stage}.yml)}

provider:
  name: aws
  region: ${self:custom.region}

  environment:
    TEST: ${cf:resources-v1-dev.UserPoolArn}
```

## Todos:

- [X] Write tests
- [n/a] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by bsdkurt** [comment]
@erikerikson I'm not sure if that is possible. I think this requires that the their be an existing stack that the testing framework as access to. When I had the cf variable pointing to a non-existent stack, the parsing failed before hitting this problem due to the missing stack. Pointers welcome.

Please also see my question on the #4687 bug report. Thanks!

**Comment by erikerikson** [comment]
There is an SSM variable test case that only success if it encounters a specific error.  I think related to identifying the case that the parameter does not exist.

However, here I think the problem was that the pre-population of the service left the region in a bad state.  This means the test could check that the result of `provider.getRegion()` returns the expected result following population (or simply checking the source directly).  I don't think that the provider environment declaration would need to be part of the service. Also, the custom attribute could be populated from the provider or something other than a file to avoid having to write one out.

**Comment by erikerikson** [comment]
But this is why it is important to ensure you get a failure prior to applying the fix and a success after.  To be sure you arranged the circumstance properly.  😄

**Comment by bsdkurt** [comment]
Thanks for the testing pointers. It will take be a week or so before I can find the time to create the test case (crunch time at work). I'm ok with you pushing ahead without me if you prefer.

**Comment by erikerikson** [comment]
Test offered here: https://github.com/bsdkurt/serverless/pull/1

The simplest case of the error was that it had to continue treating the object being populated as the root (and not ignore it - [ignoring it](https://github.com/serverless/serverless/blob/master/lib/classes/Variables.js#L199) is otherwise very important to avoid infinite recursions from self references)

**Comment by erikerikson** [comment]
BTW - go ahead and use `n/a` in place of an `x` in the `Write Documentation` checkbox.  This is a non-use-impacting change and thus no docs are needed.

**Comment by bsdkurt** [comment]
@erikerikson Thank you for providing the test case. I have merged it and updated the todo's as you suggested. Looking forward to 1.27 :-)

**Comment by erikerikson** [comment]
Of course...

Sorry for writing the bug.

Thank **you** for discovering, debugging, and fixing it!

@HyperBrain should be GTM!

**Comment by HyperBrain** [comment]
@erikerikson Good news! I'll merge.

**Pull request merged**
