### PR TITLE
Fixed platform detection for generating zip

### PR DESCRIPTION
**Pull request by miltador**
##### Status:

Ready

##### Description:

On Windows, ```process.platform``` equals ```win32```, therefore ```platformName``` was ```UNIX``` instead of ```DOS```.
This leaded into a strange behavior of resulting zip on UNIX platforms.
According to [jszip docs](http://stuk.github.io/jszip/documentation/api_jszip/generate_async.html), ```platform``` option also accepts ```process.platform``` values.
I simplified the code by passing ```process.platform``` directly.
It fixes the deploy bug on Windows described in #1835.

### CODE REVIEW

**Comment by miltador** [comment]
The tests are currently failing because this PR is also dependent on Stuk/jszip#335.
Once that PR will be merged and new jszip version released, this one can be merged as well.

**Comment by pmuens** [comment]
Thanks @miltador for your fix! There's also another open PR which might implement a fix as well.

Would be great if you could look into it: https://github.com/serverless/serverless/pull/1863

I would suggest to merge #1863 first and then once your PR is available in jszip merge yours as well.

**Comment by miltador** [comment]
Hi @pmuens,
I agree, #1863 can be merged first and then this one, when jszip will merge my PR.

**Comment by pmuens** [comment]
@miltador thanks for the heads up and looking into this!

**Comment by flomotlik** [comment]
@miltador looks like it was merged into master. If you could update this branch we should be able to get this merged once the new jszip release comes out

**Comment by miltador** [comment]
@flomotlik , I synced it with master and resolved conflicts.
Hope that new jszip release will come out before serverless v1.0 :)

**Comment by miltador** [comment]
@pmuens , @flomotlik 
New jszip version is out, I updated the dependencies. Everything seems to be ok now.

**Comment by pmuens** [comment]
@miltador awesome!

Could you shrinkwrap as well so that we fix the version?

Thanks a lot for your effort you've put in both projects! 🎉

**Comment by miltador** [comment]
@pmuens ,
Done.
I am glad to help!

**Comment by pmuens** [comment]
Thanks @miltador 

@flomotlik could you take a final look at it?

**Comment by flomotlik** [comment]
LGTM, worked fine in my tests.

**Pull request merged**
