### PR TITLE
feat(log): Log AWS SDK calls in debug mode

### LINKED ISSUE #5603: Log AWS SDK calls in debug mode
# This is a Feature Proposal

## Description

* It would be useful to log AWS SDK calls in debug mode

The AWS SDK documentation provides the way to do this :
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/logging-sdk-calls.html

Sample Output :
```
$ SLS_DEBUG='true' sls deploy
...
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.653s 0 retries] describeStacks({ StackName: 'aws-nodejs-dev' })
Serverless: [AWS cloudformation 200 0.416s 0 retries] describeStackResource({ StackName: 'aws-nodejs-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.539s 0 retries] putObject({ Body:
   <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 2008 more bytes>,
  Bucket: 'aws-nodejs-dev-serverlessdeploymentbucket-1s0qq1l3xgitw',
  Key:
   'serverless/aws-nodejs/dev/1544952584628-2018-12-16T09:29:44.628Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata:
   { filesha256: 'xZIKLb/bwT/oy2xNWi6mYZmtWIag3ummNB7fzfIiplU=' } })
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (387 B)...
Serverless: [AWS s3 200 0.956s 0 retries] putObject({ Body:
   <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 0a 00 00 00 68 61 6e 64 6c 65 72 2e 6a 73 ad 90 51 4b c3 30 14 85 df fb ... 337 more bytes>,
  Bucket: 'aws-nodejs-dev-serverlessdeploymentbucket-1xxxx1l3xgitw',
  Key:
   'serverless/aws-nodejs/dev/1544952584628-2018-12-16T09:29:44.628Z/aws-nodejs.zip',
  ContentType: 'application/zip',
  Metadata:
   { filesha256: 'SKOn9FE0AXSLvkveYZTnosBh89Gs6BIRaJMF3kqymo0=' } })
Serverless: Validating template...
...
```

### PR DESCRIPTION
**Pull request by jlamande**
## What did you implement:
Logging AWS SDK calls when SLS_DEBUG is activated.

Closes #5603 

## How did you implement it:

Configure the AWS.config.logger when SLS_DEBUG environment is activated.
In that case the AWS.config.logger will simply use the serverless.cli.log function to log AWS SDK calls.

Based on the official AWS documentation for logging :
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/logging-sdk-calls.html

## How can we verify it:

In any serverless projects :
```
SLS_DEBUG=true serverless deploy
```

The console output should show the AWS SDK calls made by serverless :
```
...
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.653s 0 retries] describeStacks({ StackName: 'aws-nodejs-dev' })
Serverless: [AWS cloudformation 200 0.416s 0 retries] describeStackResource({ StackName: 'aws-nodejs-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.539s 0 retries] putObject({ Body:
   <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 2008 more bytes>,
  Bucket: 'aws-nodejs-dev-serverlessdeploymentbucket-1xxxx1l3xgitw',
  Key:
   'serverless/aws-nodejs/dev/1544952584628-2018-12-16T09:29:44.628Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata:
   { filesha256: 'xZIKLb/bwT/oy2xNWi6mYZmtWIag3ummNB7fzfIiplU=' } })
Serverless: Uploading artifacts...
...
```

## Todos:

- [X] Write tests
- [X] Write documentation
- [X] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by jlamande** [comment]
I should have missed something but how adding 2 unit tests on exactly the 3 lines of code I added may have decreased the coverage in coverall :(
I covered exactly the 2 branches of the new code.
Some help to understand why.

**Comment by dschep** [comment]
I like it to! :shipit:

**Comment by kronos317** [comment]
@jlamande 

Can you please take a look at this?

I get this error

`
Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     Cannot read property 'LogicalResourceId' of null
 
  Stack Trace --------------------------------------------
 
ServerlessError: Cannot read property 'LogicalResourceId' of null
    at provider.request.then.catch (/Users/onseen/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:100:26)
    at tryCatcher (/Users/onseen/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/onseen/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/onseen/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/onseen/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/onseen/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/onseen/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/onseen/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/onseen/.nvm/versions/node/v8.9.1/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
`

**Comment by kronos317** [comment]
I am on 
 - serverless: 1.4.0
 - tsc: 2.4.2
 - node: 8.9.1

**Pull request merged**
