### PR TITLE
Solve the problem of principal format in China region

### PR DESCRIPTION
**Pull request by beary**
## What did you implement:

Closes https://github.com/serverless/serverless/issues/5365

The previous PR(https://github.com/serverless/serverless/pull/5366#issuecomment-486528502) could not be reopened due to "The repository that submitted this pull request has been deleted.", so this PR was created. @muja 

## How did you implement it:

Replace `AWS::URLSuffix` with hardcode `<service-name>.amazonaws.com`.

## How can we verify it:

Deploy a restApi in region cn-north-1.

Examples:
* `sls create -t nodejs-aws`
* Modify serverless.yml like this:
```yml
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10
  region: cn-north-1
  endpointType: regional

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get

```
* `sls deploy -v`

Before:
```bash
Serverless: Operation failed!
Serverless Error ---------------------------------------
 
An error occurred: HelloLambdaPermissionApiGateway - The provided principal was invalid. Please check the principal and try again. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException;
```

After:
```bash
Serverless: Stack update finished...
```

## Todos:

- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by medikoo** [comment]
@pmuens @beary shouldn't we also update those places:
https://github.com/serverless/serverless/blob/add5e3ebb5d3d9050e36bf720ab9ab1c3fd8f3d8/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js#L35
https://github.com/serverless/serverless/blob/add5e3ebb5d3d9050e36bf720ab9ab1c3fd8f3d8/lib/plugins/aws/package/compile/events/websockets/lib/deployment.js#L41

I'm not well familiar with the problem, just want to be sure those places were skipped intentionally

**Comment by beary** [comment]
Hi @medikoo,
Those two places should keep using `URLSuffix` pseudo parameter, because [this docs](http://docs.amazonaws.cn/en_us/general/latest/gr/rande.html#cnnorth_region) shows China region endpoints end with `amazonaws.com.cn` and it working correctly from my experience.

And [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html) says:
>A service principal is an identifier that is used to grant permissions to a service. The identifier includes the long version of a service name, and is usually in the following format:
>
>      long_service-name.amazonaws.com
It seems that *principal* is not a URL, but a identifier, so **URL**Suffix is not suitable and only need to hardcode it into `<long_service-name>.amazonaws.com` format in *service principal*.

**Comment by medikoo** [comment]
Great thanks @beary for thorough explanation. LGTM to me.

**Comment by pmuens** [comment]
Thanks for the second review @medikoo :+1:

LGTM :shipit:

**Pull request merged**
