### PR TITLE
Git ignore _meta in project template

### PR DESCRIPTION
**Pull request by rma4ok**

### CODE REVIEW

**Comment by rma4ok** [comment]
According to docs `_meta` should be ignored
```
_meta (meta data that holds stage/regions config and variables - gitignored)
    |__resources (final CF templates for each stage/region)
         |__s-resources-cf-dev-useast1.json
    |__variables (variables specific to stages and regions)
         |__s-variables-common.json
         |__s-variables-dev.json
         |__s-variables-dev-useast1.json
```

**Comment by ryansb** [comment]
:+1:

**Comment by c-knowles** [comment]
#564 changed this so only stages starting with `dev` get ignored.

**Comment by rma4ok** [comment]
@c-knowles but what about `_meta/_tmp`? build dir should be ignored too.
And all `_meta` is still ignored in [`v0.5` branch](https://github.com/serverless/serverless/blob/v0.5/lib/templates/gitignore)

**Comment by c-knowles** [comment]
There's #665 and #607 for the `_tmp` folder. I'm interested to understand whether `_meta` should be ignored or not which is why I filed #564 since the docs and functionality did not match. I think various changes have been made in 0.5 which mean the _meta folder contains less useful information, at least information that is not easy to regenerate. For example, I think there will no longer be any S3 bucket (https://github.com/serverless/serverless/pull/806).

**Comment by rma4ok** [comment]
@c-knowles do you think I just better close this PR ?

**Comment by c-knowles** [comment]
I think it may not be needed, would leave it to someone from the contributors group to check though.

**Pull request closed without merging**
