### PR TITLE
Upgrade aws-fsharp example to .Net Core 2.0

### PR DESCRIPTION
**Pull request by yunspace**
## What did you implement:

Related to #4656, upgraded F# to dotnet 2.0

## How did you implement it:

- removed global.json
- updated netcoreapp1.0 to netcoreapp2.0
- removed reference to FSharp SDK since it is incorporated into .Net SDK
- updated all dependencies to latest versions
- updated unit, integration tests and image used in docker-compose, 

I've also removed the duplicated code in `docs/providers/aws/examples/hello-world/fsharp` folder. As per discussion with @horike37 in #4669 

## How can we verify it:

Unit test: `npm test`

Integration test: `tests/templates/integration-test-template aws-fsharp './build.sh'`

## Todos:

- [X] Write tests
- [X] Write documentation
- [X] Fix linting errors
- [X] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by yunspace** [comment]
integration tests are passing. This PR is ready to review.

**Comment by horike37** [comment]
Thank you for working on this @yunspace :100: 
I have tested locally and it is working fine :+1: Awesome!

Could you also rebase (or merge master into) this branch and update the corresponding docs for the recently updated the two files? After that, we can merge this PR :smile:

**Comment by yunspace** [comment]
Yep will do!

**Comment by horike37** [comment]
@yunspace 
The serverless.yml file still remains under example doc.
Would be good to remove it as well.
https://github.com/yunspace/serverless/blob/fsharp2/docs/providers/aws/examples/hello-world/fsharp/serverless.yml

Ping us if you are ready for review again :smile:

**Comment by yunspace** [comment]
@horike37 all done now.

**Comment by horike37** [comment]
Thanks @yunspace :+1: 
Looks like perfect :100: Just merged.

**Comment by yunspace** [comment]
Thanks @horike37 I will take what was done here and help out with #4656

**Pull request merged**
