### PR TITLE
Saner role names

### PR DESCRIPTION
**Pull request by thomaschaaf**
Prefix the lambda role and policy with the stack name.

This also makes naming the role and policy consistent - before it was <stage>-<service> and <service>-<stage> as prefixes.

Alternatively I could add a roleName serverless setting - but I think this is easier to work with.

I need this because at our company the aws resources need to consistently start with the team name and whitelisted with iam wildcards.

- [x] Write and run all tests
- [x] Write documentation
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by thomaschaaf** [comment]
@medikoo i thought about it but if you are using it from the serverless eco system it should not break anything as everything will be renamed automatically.
If you are manually referring to the role from the outside it could break something though. If you are doing that I would assume you declared your own role though.

What do you suggest I do? I could write a notice for it but I don't know where.

**Comment by xalvarez** [comment]
@thomaschaaf & @medikoo please note that this seems to be a breaking change. After upgrading to serverless 1.65 our stacks can no longer be updated because CloudFormation says that the role already exists.

**Comment by medikoo** [comment]
@xalvarez do you rely setup custom stack name (via `provider.stackName` setting)?

Note that this update affected role name only if you rely on above, otherwise no changes to role name has been made.

**Comment by xalvarez** [comment]
@medikoo that's right, we override stack names and as a consequence new deployments will try to change lambda's execution role.

**Comment by medikoo** [comment]
@xalvarez and why exactly you have collisions? Technically if you use different stack names across services there should be no collision

**Comment by xalvarez** [comment]
I asked myself the same question, all lambdas for which we updated serverless ran into this issue

**Comment by xalvarez** [comment]
In case it's relevant, we obtain stage from a parameter (opt:stage) and use it as part of the stack's name.

**Comment by medikoo** [comment]
And is this stage resolved properly for role name? (can you investigate template as generated by the framework). 
Having resolved role name, do you have understanding why it may collide (which other service could generate same role name?)

**Comment by xalvarez** [comment]
I've written a sample project with the aim of showcasing the issue and I have failed to reproduce the problem so I assume there isn't any problem with this change

**Comment by xalvarez** [comment]
I've been able to reproduce the issue in this project: https://github.com/xalvarez/serverless-version-1-65-breaking-change

In this example stack name and service name are almost the same. The only difference is that the first letter from stack name is upper case and in service name it's lower case.

One could argue this is the corner case, it is a breaking change though. One possibility would be to provide the possibility to specify a role name in `serverless.yml`

**Comment by medikoo** [comment]
@xalvarez thanks for test case. Still it's still not clear to me where role name collision is introduced.

Do you suggest that  there are some role name case sensitivity issues on AWS side, and e.g. renaming the role from `foo` to `Foo` in CF template, will cause the "role already exists" error?

**Comment by xalvarez** [comment]
I'm no serverless super expert but if you deploy the sample project as is, with serverless version 1.64, and then install a higher serverless version and deploy again, you will see it tries to create the role again and run into the described issue. I was hoping this would be enough information. My guess is that in this situation, other resources that depend on the role trigger a `create` instead of an `update`.

**Comment by medikoo** [comment]
> I'm no serverless super expert but if you deploy the sample project as is, with serverless version 1.64, and then install a higher serverless version and deploy again, you will see it tries to create the role again and run into the described issue

@xalvarez that's not the case. Name of the resources didn't change. The only thing that changed is role name and only for some corner case scenarios, and even if that is the case the update should run smoothly.

You've stated that you've approached the collision, where new stack generated role name that already existed. It's not clear why that was the case. Framework definitely is not configured to do that.

Ideally if you prepare a minimal (no plugins involved) test case, where with two consecutive deployments (using two different SLS version) we can reproduce the issue. That'll help me understand where the eventual source of the issue is.

**Comment by xalvarez** [comment]
I've removed the plugin `serverless-pseudo-parameters`, although that has absolutely nothing to do with roles, and simplified the sample project even more. So there are no plugins now, you have a minimal test case where with two consecutive deployments you can reproduce the issue, exactly as I described in my previous messages.

In the second deployment, with a higher sls version you'll see:

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service slsV165BreakingChange.zip file to S3 (7.28 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - SlsV165BreakingChange-test-stage
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_FAILED - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - SlsV165BreakingChange-test-stage
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - SlsV165BreakingChange-test-stage
CloudFormation - DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - SlsV165BreakingChange-test-stage
Serverless: Operation failed!
```

**Comment by medikoo** [comment]
@xalvarez thanks for that. I can reproduce it now, and it seems it happens only when you override the `stackName` with same value as would be generated by the framework but with different casing (this is the reason, why it was not straigthforward to reproduce)

e.g. in service case in your example. you've overriden stack name of `slsV165BreakingChange-test-stage` with `SlsV165BreakingChange-test-stage` (note that only case of first letter have changed).

For some reason CloudFormation has problems in handling changes where role name is just changed by case. It fails to convert from `slsV165BreakingChange-test-stage-eu-central-1-lambdaRole` to `SlsV165BreakingChange-test-stage-eu-central-1-lambdaRole` (note that if it won't be just case that's changed there won't be an issue).

--- 

Anyway, I'll accept the PR, that reverts from using `this.getStackName()` for role name generation.

When taking this in I was not perfectly aware, that this method is used purely to generate the CloudFormation stack name, and should not be used to name resources.

That will also fix an issue on your side

**Comment by arkasai** [comment]
Hi guys, 

there is an additional edge case you need to consider with this ticket. Yesterday we upgraded our Serverless version to the latest one from 1.62.0 which leads to an complete downtime of our development infrastructure. 

Lets recap what happend:
We have a CloudFront distribution which gets additional security headers injected by a Lambda@Edge. This Lambda was deployed and working without any issue. After upgrading the Serverless version the change discussed here triggered an update for that Stack and replacing the former IAM role with a new role with new name schema. The old IAM role got deleted and was gone. As there was no code change within the Lambda function itself no new deployment to Lambda@Edge was triggered which make CloudFront use the last version with old IAM role reference which was not available anymore.

After some research we stumbled on that ticket and did some research in our CloudFormation logs which pointed us in the right direction to solve the issue. A simple redeploy of the latest Lambda@Edge version solved our issue.

Maybe there is any change to handle this edge case or at least add a "Breaking Change" section for Lambda@Edge users.

Cheers.

**Comment by medikoo** [comment]
@arkasai thanks for sharing that. Indeed that looks troublesome, still it looks as bug on AWS side, in how Lambda@Edge was handled. Technically by CF template role for lambda have changed while AWS didn't apply that change while stating that deployment went successful.

Have you contacted AWS support about that?

**Comment by arkasai** [comment]
@medikoo sure thing.

I'm just opening a ticket to AWS letting them know the behavior that this might be an issue with their implementation on IAM role change with CloudFormation at a Lambda@Edge deployment. I'll keep you updated what they answer.

**Comment by arkasai** [comment]
@medikoo I'm back again with some new information from AWS support crew. They've analyzed the issue and found out that the CloudFormation behavior is correct, which I agree with after some research on the Lambda@Edge topic. 

That's really a edge case with this issue here as I might explain:

CloudFront will reference Lambda function not by directly reference the $LATEST or a special ALIAS of a function but by creation a so called Lambda:Version (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-version.html), so the CloudFront distribution will only change if you update that version. This version can be referenced by a SHA256 hash within the CloudFormation template which Serverless actually does. This means the SHA256 hash code, which is optional, filled by Serverless prevented my function from being updated (because my code did not change) but my IAM role being removed and added because of the name change.

From my point of view adding the "CodeSha256" hash in the background by Serverless makes the deployment towards CloudFront and Lambda@Edge a little bit less chatty but a little bit more dangerous in case of IAM role changes.

**Comment by medikoo** [comment]
@arkasai so reasuming, IAM role resource configuration should also be included in lambda version hash generation. Having that changed role name will incur a different hash.
PR that implements that is definitely welcome.

However I've just prepared a PR which partially reverts this change, and role name be resolved before. See #7694

**Comment by simonkarman** [comment]
This is a breaking change. Where I work we use the role name of the lambda in other policies in other CloudFormation stack, this change caused these policies to break. Please take this into consideration. We are rolling back to a serverless version before this.

**Comment by medikoo** [comment]
@simonkarman this will be reverted with next version

**Comment by thomaschaaf** [comment]
@medikoo I just wanted to upgrade and saw that this was reverted.. I dont understand why though..

**Comment by medikoo** [comment]
@thomaschaaf it was reverted partially. 

What was reverted is `this.getStackName()` usage, as that one should not be used for resource naming (it takes into account `stackName` customization, which is meant to influence only name of CloudFormation stack and no its resource naming)

**Comment by thomaschaaf** [comment]
This is extremely frustrating as we are prefixing our resources with our team names. Until now we were able to do it like this: ```
stackName: tx-${self:service.name}-${self:provider.stage}
```

Can we create something new so all resources are prefixed correctly? Or have a way to set the name dynamically?

**Comment by medikoo** [comment]
@thomaschaaf why not prefixing service names directly?

Also note, that Framework never leaked customized `stackName` into resource names before v1.70.1, and fact that it started to do so, is considered to be a bug.

Technically you're relying on side effect, never documented feature that's outcome of a bug.

See also bug reports that this issue created.

**Comment by thomaschaaf** [comment]
We are allowing all developers in a team to access the "test" stage and only a limited amount of people are allowed to change "live" stages. This way we were able to restrict access with resource names (as tagging is still a second class citizen at amazon).

But I guess then I have to change the service name dynamically somehow with bash before deployment.

**Comment by medikoo** [comment]
> We are allowing all developers in a team to access the "test" stage and only a limited amount of people are allowed to change "live" stages. 

Ok, but technically what you're after is ability to customize role name right?

**Pull request merged**
