### PR TITLE
improve aws cloudwatchlog filter #4569

### LINKED ISSUE #4569: Filter pattern improvement for cloudwatchLog events (aws)
# This is a Feature Proposal (Improvement)

## Description

For feature proposals:
* When adding a cloudwatchLog event, as mentioned by AWS document `Metric filter terms that include characters other than alphanumeric or underscore must be placed inside double quotes ("")`, if we want to add a filter like `"Total amount" - "level=DEBUG"`, we need to write it like this:

```yaml
events:
      - cloudwatchLog:
          logGroup: "/aws/lambda/my-lambda-log-group"
          filter: "\\\"Total amount\\\" -\\\"level=DEBUG\\\""
```
It is not straightforward and it is not obvious to users. I only found out that I need to write like above when I check the [source code](https://github.com/serverless/serverless/blob/v1.24.1/lib/plugins/aws/package/compile/events/cloudWatchLog/index.js#L87).

* Do you think it necessary to modify it and let it accept format like below:
```yaml
events:
      - cloudwatchLog:
          logGroup: "/aws/lambda/my-lambda-log-group"
          filter: '"Total amount" -"level=DEBUG"'
```

* Need to consider backwards compatible
* I can try to implement the improvement if you agree to make this change

Similar or dependent issues:
* None

## Additional Data

* ***Serverless Framework Version you're using***: v1.24.1
* ***Operating System***: Mac OSX, Linux, AWS AIM
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by willwhy**
## What did you implement:

Closes #4569

Use JSON.stringify(FilterPattern) to avoid massive quotes in serverless.yml config.

## How did you implement it:

Use `JSON.stringify(FilterPattern)` instead of `"${FilterPattern}"`.

## How can we verify it:
Instead of using:
```yaml
events:
      - cloudwatchLog:
          logGroup: "/aws/lambda/my-lambda-log-group"
          filter: "\\\"Total amount\\\" -\\\"level=DEBUG\\\""
```
we can now use:
```yaml
events:
      - cloudwatchLog:
          logGroup: "/aws/lambda/my-lambda-log-group"
          filter: '"Total amount" -"level=DEBUG"'
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources (refer to `How can we verify it` above)
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by HyperBrain** [comment]
For users that already use the filters, this migt be a breaking change, because the stringify will now double encode the backslashes. Is that right, or does it continue to work without changing the old notation?

**Comment by willwhy** [comment]
Hi @HyperBrain, yes. It will break some existing filters which already use encoded backslashes. e.g for filter like `filter: "\\\"Total amount\\\" -\\\"level=DEBUG\\\""` needs to be changed to `filter: '"Total amount" -"level=DEBUG"'`. But for JSON formated filters like `filter: '{$.userIdentity.type = Root}'` or plain text filters without quote like `filter: 'LOG_EVENT_FLAG'` will continue to work without any changes.

For those filters already use backslashes, it hard to tell if they use backslashes to escape quotes or use backslashes themselves. From this point, it might not easy to be backwards compatible.

Do you have any suggestions @HyperBrain ?

**Comment by HyperBrain** [comment]
We could try to detect uses of the "old" patterns with one or more a proper regexes.
`\\".*?\\"` should match if any escaped quote pairs are detected. There are additional rules that might be useful.

Then we can try to detect any (now) incompatible filter strings and either bail out, or try to correct them silently but emit a warning, so that it is not breaking anymore.

**Comment by willwhy** [comment]
Cool, thanks, @HyperBrain . I'll try and update this PR.

**Comment by willwhy** [comment]
Hi @HyperBrain I've updated the PR and tested on following patterns:

- oldFormat => newFormat
- single quote: `"\\\"'\\\""` => `"\"'\""`
- double quote: `'\"\\\"\"'` => `'"\""'`
- multiple term: `'\" RequestId: \" -\"END\"'` OR `"\\\" RequestId: \\\" -\\\"END\\\""` => `'" RequestId: " -"END"'`
- simple single term: `'REPORT'`
- quotes inside double quotes: `'\"\\\"Example of \\\\\\"double quotes\\\\\\" inside double quotes\\\"\"'` => `'"\"Example of \\\"double quotes\\\" inside double quotes\""'`
- quotes inside single quotes: `"\\\"'Example of \\\\\\\"double quotes\\\\\\\" inside single quotes'\\\""` => `"\"'Example of \\\"double quotes\\\" inside single quotes'\""`
- JSON formated message: `"{ $.data = \"\\\"abc\\\"abc\" && $.value = \"def\" }"` OR `'{ $.messageType = "\"abc\"DATA_MESSAGE" && $.value = "def" }'`

Hi @noahmedling, as you mentioned in your issue #4577, you can try the double quote listed above. Because you need to include `"` inside `""` according to [the AWS document](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html).

**Comment by willwhy** [comment]
hmm, seems like one of the Travis builds failed because of Github connection issue.

**Comment by willwhy** [comment]
Thanks, @horike37 .
I'll add the test case and update this PR later.

**Comment by willwhy** [comment]
Hi @horike37,

I added a test case for escaped quotes.

Because double quotes string breach ESLint so I can only use the equivalent single quoted string version like `'\" RequestId: \" -\"END\"'`. And correct me if I'm wrong, in the js code (not in the yml file), `'\" RequestId: \" -\"END\"'` should be actually `'\\" RequestId: \\" -\\"END\\"'`.

**Comment by HyperBrain** [comment]
@willwhy You can add `// eslint-disable quotes` to the top of the test file (or with `// eslint-disable-line quotes`) immediately after the test code in the same line. This is better, as we have all needed tests in the file.

**Comment by horike37** [comment]
@willwhy 
Thank you for the update :smile: 
As @HyperBrain said, you can avoid the breach by using `// eslint-disable-line quotes`.

**Comment by willwhy** [comment]
Hi @horike37  @HyperBrain, cool, `// eslint-disable-line quotes` works, thanks.

**Pull request merged**
