### PR TITLE
Fixes bug with sns-cross-region definition using psuedo params

### LINKED ISSUE #6760: SNS cross region trigger breaks pseudo parameters
# Bug Report

For reference, see the bug report here: https://github.com/svdgraaf/serverless-pseudo-parameters/issues/38

Also for reference, currently the plugin uses `after:aws:package:finalize:mergeCustomProviderResources` to trigger, perhaps this needs to run at a different stage in the process, but I'm not sure about that.

I'm happy to create a PR with a fix, but I'd like to discuss here what we want it to do.

## Description
**1. What did you do?**
Since 1.48.0 and up, when creating an sns event, the value no longer works with a pseudo parameter.

**2. What happened?**
Since this PR: https://github.com/serverless/serverless/pull/6366 was merged, the sns event tries to be smart, and detect if a cross-region sns topic is referenced. If so, it creates a cross-region event trigger.
However, when this value is set with a `!Ref` or `!Sub` parameter, this breaks the logic, as noted by @bzemms in the actual PR: https://github.com/serverless/serverless/pull/6366#pullrequestreview-275160827
If the logic doesn't see the same region in the value, as the script is running from, it tries to fetch the region from the value. Which of course doesn't work when using a reference value, as there is no actual region in there at all.

**3. What should've happened?**
It shouldn't break on a valid arn  😅 

**4. What's the content of your `serverless.yml` file?**

Here's an example setup which breaks:
```
plugins:
  - serverless-pseudo-parameters
functions:
  alert:
    handler: src/foo.bar
    events:
      - sns:
          topicName: foobar
          arn: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:foobar
```

**Similar or dependent issues:**

- #6444 
- #6445 

## Proposed solution
I think a valid solution would be to perhaps check if the found region adheres to a list of valid regions from the `aws-sdk`, or we could do a quick regex match. If it doesn't match, the region should not be set and be left alone. Perhaps issue a warning or info log when this occurs.

Not sure what is preferred. Let's discuss and I can provide a PR

### PR DESCRIPTION
**Pull request by master-of-null**
Fixes the split of of arn for sns topic, when using pseudo params.

Closes #6760 

## How can we verify it

Tests updated.

## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test-ci` --> Run all validation checks on proposed changes
- `npm run lint-updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check-updated` --> Check if updated files adhere to Prettier config
- `npm run prettify-updated` --> Prettify all the updated files

</details>

- [x] Write and run all tests
- [x] Write documentation
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by pmuens** [comment]
Here's a `serverless.yml` we should use to validate this fix:

```yaml
service: test-${self:custom.idx}

provider:
  name: aws
  runtime: nodejs10.x

custom:
  idx: 0

plugins:
  - serverless-pseudo-parameters

functions:
  alert:
    handler: src/foo.bar
    events:
      - sns:
          topicName: foobar
          arn: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:foobar
```

**Comment by master-of-null** [comment]
> Here's a `serverless.yml` we should use to validate this fix:
> 
> ```yaml
> service: test-${self:custom.idx}
> 
> provider:
>   name: aws
>   runtime: nodejs10.x
> 
> custom:
>   idx: 0
> 
> plugins:
>   - serverless-pseudo-parameters
> 
> functions:
>   alert:
>     handler: src/foo.bar
>     events:
>       - sns:
>           topicName: foobar
>           arn: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:foobar
> ```

Thanks for the feedback, is there a standard way I should be adding the `serverless.yml` you provided to the project and testing?

**Comment by pmuens** [comment]
Thanks for getting back @master-of-null :+1:

> Thanks for the feedback, is there a standard way I should be adding the serverless.yml you provided to the project and testing?

I think having this `serverless.yml` as a comment in this thread is enough. Usually this is part of the PR itself, but it only matters that we have a `serverless.yml` we can use to test. It doesn't matter where it's written down. :+1:

**Comment by master-of-null** [comment]
> Thanks for getting back @master-of-null 👍
> 
> > Thanks for the feedback, is there a standard way I should be adding the serverless.yml you provided to the project and testing?
> 
> I think having this `serverless.yml` as a comment in this thread is enough. Usually this is part of the PR description itself, but it only matters that we have a `serverless.yml` we can use to test manually. It doesn't matter where it's written down. 👍

Do you know the timeline for moving off of node 6? We can do some really weird `.replace().split().map(s => s.replace)` in the mean time on the topicArn string

**Comment by pmuens** [comment]
> Do you know the timeline for moving off of node 6? We can do some really weird .replace(/::/g, '@@').split(':').map(s => s.replace(/@@/g, '::')) in the mean time on the topicArn string

Unfortunately there's no ETA for Node.js 6 removal (I'm eagerly waiting for that day!).

If we could re-write the code so that it doesn't require regex lookbehind that would be ideal since we can merge the PR right away in that case. We should just leave a comment with a link to the discussion in this PR so that people who read the current implementation can educate themselves why it's done the way it's done.

**Comment by master-of-null** [comment]
> Thanks again for working on this @master-of-null 👍
> 
> I just tested this today and it works as expected. LGTM :shipit:

Awesome. Thank you for going ahead and doing that. I've been swamped the past week

**Pull request merged**
