### PR TITLE
Support form requests for APIG in v1

### PR DESCRIPTION
**Pull request by oriolgual**
##### Status:

In Development

##### Description:

Adds a default velocity template to handle application/www-form-urlencoded requests and transform in a very similar way as a JSON request. Comes from #1593.

##### Todos:

- [X] Form template
- [ ] Write tests
- [ ] DRY code

### CODE REVIEW

**Comment by ac360** [comment]
This looks AWESOME @oriolgual

**Comment by bijoutrouvaille** [comment]
In the past I've had trouble with some mapping templates, so I'm posting an example raw form post that might fail because it includes ascii 10 char. The content type should be `application/x-www-form-urlencoded` and request body:

    abc=xyz%2BCg%3D%3D%0A

I'm not sure if your template can handle this, but one I've used in that past gave me the following error message `"Could not parse request body into json: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value\n at [Source: [B@417f22f1; line: 9, column: 22]"`. It took me some time to track it down.

This particular example comes from Braintree's webhook payloads.

**Comment by oriolgual** [comment]
Thanks for the example @bijoutrouvaille, I'll have some time this Friday to work on this and I'll try if it also fails.

**Comment by flomotlik** [comment]
@oriolgual this looks great. I'm currently not sure if and how we should test those templates really, apart from making sure that a template for a particular content-type is set and its not empty. Other than that I don't think we can do a lot of things on the unit test level. We should definitely add some more tests to this for the integration test repo we've planned

**Comment by flomotlik** [comment]
@oriolgual could you reopen against master? We'll get to look into this more over the next week, sorry for the delay here

**Comment by oriolgual** [comment]
Done @flomotlik (I was on vacation, sorry for the late update!)

**Pull request closed without merging**
