### PR TITLE
Add notificationArns AWS parameter to enable Cloudformation notifications

### LINKED ISSUE #3998: Allow to set NotificationARNs parameter for AWS provider
# This is a Feature Proposal

## Description

Cloudformation provides a [NotificationARNs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-notificationarns) property to be able to send Cloudformation events to one or more SNS topics.

This is useful for custom integrations, i.e.: a Slack bot that listens to the SNS topic and send the events to a Slack channel.

The initial idea is to add a new provider parameter ``notificationArns``, for example:

```
provider:
  name: aws
  runtime: python3.6
  notificationArns:
    - 'arn:aws:sns:us-west-2:1234567890:deploy-events'

```

### PR DESCRIPTION
**Pull request by rmax**
## What did you implement:

Added a new AWS provider's property ``notificationArns`` to enable deploy events notification. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-notificationarns

Closes #3998

## How did you implement it:

Set the ``NotificationARNs`` parameter if the ``notificationArns`` provider property is set.

## How can we verify it:

1. Create a SNS topic and grab its ARN (i.e.: `arn:aws:sns:us-west-2:1234567890:mytopic`). Optionally you can set up a subscriber to read the messages from the topic and publish them somewhere (i.e. to a [slack channel](https://github.com/robbwagoner/aws-lambda-sns-to-slack)).
2. Add the `notificationArns` property to a `serverless.yml`:

```
provider:
  name: aws
  region: us-west-2
  ...
  notificationArns:
    - arn:aws:sns:us-west-2:1234567890:mytopic
```

3. Run `serverless deploy` and stack events will be sent to the SNS topic.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by eahefnawy** [comment]
Hey @rmax ... thanks for getting started on this. It's a been a month though since you marked this PR as WIP. Any updates here? 😊

**Comment by rmax** [comment]
Hey @eahefnawy. Thanks for the reminder. Functionality-wise there is no more changes to be done. We have been using this feature without any issues at all.

I would need a little guidance to write the tests as I'm mainly a python dev rather than a js dev. Do you have any pointers?

**Comment by eahefnawy** [comment]
you could add couple of tests in the `createStack.test.js` and `updateStack.test.js` files ... I think the logic would look something like this:

https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/createStack.test.js#L60

Hope this helps ✨

**Comment by eahefnawy** [comment]
Also, don't forget to add this new property to the docs! 😊

**Comment by rmax** [comment]
@eahefnawy Thanks for the pointers! I will get back to this by the end of this week.

**Comment by rmax** [comment]
@eahefnawy @pmuens This is ready for review 🎉

**Comment by pmuens** [comment]
> @eahefnawy @pmuens This is ready for review 🎉

Thanks for pinging @rmax 👍. We'll look into it ASAP!

**Comment by rmax** [comment]
:tada:

**Comment by horike37** [comment]
Thank @rmax for your effort and sorry for taking long time :sweat_smile: 
This functionality will be shipped in the next release :tada:

**Comment by SeaGuy** [comment]
Hello @rmax ... Thank you very much for providing this feature -  great for software to know when the stack is created, so that other work might begin.

It seems like the ARN must be a string literal of a pre-existing SNS Topic (created previously outside the stack)?  Is it possible to reference an SNS Topic being created in the same stack?  Thanks.

**Pull request merged**
