### PR TITLE
Added Support for Cloud Components

### PR DESCRIPTION
**Pull request by eahefnawy**
## What did you implement

Added support for cloud component to work alongside the first component's version.

## How can we verify it

Try running `serverless deploy` in a directory containing:

- components v1
- components v2
- framework v1

They should all work with their respective experiences.

## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test:ci` --> Run all validation checks on proposed changes
- `npm run lint:updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check:updated` --> Check if updated files adhere to Prettier config
- `npm run prettify:updated` --> Prettify all the updated files

</details>

- [x] Write and run all tests
- [x] Write documentation
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by eahefnawy** [comment]
@medikoo hmm I'm not sure about that 🤔 ... did @ac360 mention we're gonna bump the version soon?!

**Comment by medikoo** [comment]
> @medikoo hmm I'm not sure about that 🤔 ... did @ac360 mention we're gonna bump the version soon?!

Yes, I was told we're very close. So I assumed it's about that.

Is this change breaking for current components users?

**Comment by mnapoli** [comment]
👀  is there any resource talking about those "components v2"?

If it is too early/not documented yet no problem, I'm just curious ;)

**Comment by ac360** [comment]
@mnapoli Coming soon!  Looking forward to chatting more about this on our call.

**Pull request merged**
