### PR TITLE
Added profile option for deployment

### PR DESCRIPTION
**Pull request by kevinaud**
##### Status:

Ready

##### Description:

Adds `--profile` option to deploy command which allows for easy profile switching. I implemented this in a similar way to how profile switching with environment variables was implemented, by setting the 'profile' attribute of the credentials object to the name of the desired profile in the getCredentials() function. This is my first time doing open source so sorry if I made any noob mistakes!

### CODE REVIEW

**Comment by kevinaud** [comment]
hmm looks like the build is failing... I'll try to figure out what's going on

**Comment by kevinaud** [comment]
I only have basic experience with git and while trying to get my fork synced with the upstream and squash my commits I kind of screwed up my commit history to the point that I don't know how to fix it... That's why there are some other peoples commits in my pull request

**Comment by pmuens** [comment]
Hey @kevinaud thank you for this PR 🎉 

We'll review it soon.

Just wanted to leave a note here that it might slightly conflict with https://github.com/serverless/serverless/pull/1906 as the deployment process is refined there.

**Comment by josephfinlayson** [comment]
This is would be very useful, it describes a feature which is mentioned in the docs:

https://github.com/serverless/serverless/blob/master/docs/guide/provider-account-setup.md#advanced--longer-term-setup

**Comment by andymac4182** [comment]
I believe this can be implemented using the new variables feature and https://github.com/serverless/serverless/pull/2015

**Comment by flomotlik** [comment]
Sorry for the long delay on this @kevinaud , as @andymac4182 said this can now be implemented thorught he new variable system and the provider->profile option.

Sorry for not communicating this earlier that we're going in a different direction (or more specifically changing our mind). Very much appreciate your work on it and it definitely pointed me towards what we eventually implemented!

**Pull request closed without merging**
