### PR TITLE
Add print command to generate output of computed serverless.yml file with all resolved Serverless Variables

### LINKED ISSUE #3224: DX: Add ability to preview populated serverless.yml
The variable system is ultra powerful and amazing!

However it is super confusing to people unfamiliar with a given project and the [variable syntax](https://serverless.com/framework/docs/providers/aws/guide/variables/)

image

Additionally working with nested variables is really cool but hard to get right.

**It would be a huge UX/DX win if you could preview the output of the `serverless.yml` file populated with it's final variables before deploying.**

Something like `serverless deploy --dry-run` or `serverless info variables`

Then you could preview what exactly your config files (or CLI options) are actually resolving to in the final `serverless.yml`

---

I felt this first hand with creating https://github.com/serverless/scope/blob/master/backend/serverless.yml and would have freaking loved a preview option to see what was going with the final serverless.yml that was being deployed.

### PR DESCRIPTION
**Pull request by alexdebrie**
## What did you implement:

Adds an `sls print` command that compiles your config file, resolves all variable references, and prints it to the console.

Closes #3224

Would also assist in debugging reported issues such as #4161.

## How did you implement it:

Use the `getServerlessConfigFile()` utility function to read the config file, then use the `populateObject()` method to resolve all references.

## How can we verify it:

_Edited August 31 to use CLI options_

Create a Serverless service with the following files:

```yml
# serverless.yml

service: print-test

custom:
  region: ${opt:region}
  bucketName: mySpecialBucket
  fileValue: ${file(./config.yml):secretValue}

provider:
  name: aws
  runtime: python3.6

package:
  include:
    - include-me.py
    - include-me-dir/**

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
```

```yml
#config.yml

secretValue: ohsosecret
```

Then check that it works:

```bash
$ sls print --region us-east-1
service: lint-test
frameworkVersion: =X.X.X
custom:
  region: us-east-1
  bucketName: mySpecialBucket
  fileValue: ohsosecret <-- Resolved!!
provider:
  name: aws
  runtime: python3.6
package:
  include:
    - include-me.py
    - include-me-dir/**
functions:
  hello:
    handler: handler.hello
resources:
  Resources:
    NewResource:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: mySpecialBucket <--- Resolved!!
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by eahefnawy** [comment]
Thanks for this PR @alexdebrie 😊 ... I wish it was that simple though! :D ... options references complicates things a little. So If you're referencing options, you need to make sure you provide it to the print command as well.

So, what you'll need to do is use `populateService` and pass it the options object instead of using `populateObject`.

**Comment by alexdebrie** [comment]
Thanks for that note @eahefnawy! I rarely use CLI options so didn't think to test it 😁.

Can you check the latest commit? I just set the `options` property in the variables class before running populateObject. I don't love populateService because it returns a ton of other information in the return object.

**Comment by alexdebrie** [comment]
@dschep I'm not understanding there, can you elaborate? What would you be passing in on the command line with `-f`?

If you're asking if it would resolve variables in the function environment variables section, it would. It resolves the entire config file.

**Comment by dschep** [comment]
Doh, I misunderstood what this outputs, this outputs `serverless.yml` with vars resolved, not the environment with config variables resolved.

ignoreme

**Comment by eahefnawy** [comment]
Alright! sounds good @alexdebrie 🙌 I've tried it out with the extensive variable config mentioned in #4144 and it's working with all cases 👏 

So in terms of functionality, this is good to go. @alexdebrie could you add tests and docs for this new command 😊 ... then it should be G2M!

**Comment by alexdebrie** [comment]
@eahefnawy Will do!

Also, do you know why CI is failing? For older Node versions, it's having trouble with the Plugins.json file. Not sure why.

**Comment by eahefnawy** [comment]
@alexdebrie I don't think this is the real issue. I've seen this error many times masking the real cause of the error. I think it's an issue in our codebase where this error swallows the actual error. We need to fix that.

I was able to reproduce this error after switching to Node 4, I'll try to debug the real issue here with you and let you know what's going on if I find something

**Comment by eahefnawy** [comment]
@alexdebrie I figured it out. You need to add `'use strict';` at the beginning of the file 😅 ... freakin' Node!

**Comment by eahefnawy** [comment]
I just added it and pushed it to the branch

**Comment by eahefnawy** [comment]
It's interesting to note that this little issue in the print plugin broke **all** plugins in Node 4/5 ... This is a fundamental issue in our plugin system where we actually load the logic of all the plugins even when we're using only one plugin. So a syntax error or something in one plugin would break the entire framework. Even more bad that it's masked by this misleading error.

**Comment by HyperBrain** [comment]
@eahefnawy I'm not sure if the plugin loading algorithm is really an issue. On the other hand it shows errors immediately. If you'd only load a few of them (the needed ones), you might release without even noticing that something's wrong.

Additionally the forgotten 'use strict' is a major issue in my opinion, because it can f*** up the whole app. The only way to improve the quality checks that I see is, to run all unit tests with Node 4, because Node 6+ won't show them.

**Comment by mvayngrib** [comment]
@alexdebrie i've wanted this one for a while! 

it seems to choke if a different variableSyntax is specified

**Comment by eahefnawy** [comment]
@mvayngrib really nice catch! @alexdebrie that's another reason to use `populateService` 😊

**Comment by alexdebrie** [comment]
Thanks @mvayngrib! I'll get that fixed.

@eahefnawy I'd like to stay away from `populateService` because it adds a bunch of other crud that's not directly relevant here -- I'd like to have a easy, clear way to understand what my config files. I'll need to do some additional looking on this, but it seems like there should be a pure function that says "Here's my config file, return the fully resolved config object" without relying on a bunch of separate state.

**Comment by eahefnawy** [comment]
@alexdebrie sounds good! however you see fit. We def need pure functions! Converting our codebase to be more functional is a big task that I wanted to do for so long already!

**Comment by pmuens** [comment]
@alexdebrie Any updates on this one?

Let us know if you need any help here! I really like this feature and it would be great if we could introduce that in one of the upcoming versions 🎉 👍.

**Comment by alexdebrie** [comment]
@pmuens @eahefnawy I've got the fix for the variable syntax issue. I've also pushed up docs for every provider that has a `Variables` section in their guide with some actual variable examples.

There's a super basic test suite similar to the base [`info`](https://github.com/serverless/serverless/blob/master/lib/plugins/info/info.test.js) plugin, but it doesn't do much more than check to make sure it can load the plugin correctly. Still poking around to test actual functionality but may need some pointers from those with more JS knowledge 😄

**Comment by pmuens** [comment]
Great! Thanks for taking the time to push some updates @alexdebrie 👍 💯

We'll take another look at it soon and can jump in and help with the remaining fixes!

**Comment by alexdebrie** [comment]
Ok, I think this is working thanks to a lot of direct help from @pmuens 🎉 👏. 

Open to any feedback or changes :)

**Comment by pmuens** [comment]
> Ok, I think this is working thanks to a lot of direct help from @pmuens 🎉 👏.

> Open to any feedback or changes :)

Awesome! This is great 🎉. Thanks for taking the time to update this @alexdebrie 👍 🙏

**Comment by ozbillwang** [comment]
@alexdebrie 

Does this feature do `serverless.yml` lint check as well?

**Comment by alexdebrie** [comment]
@ozbillwang It doesn't right now, but I was thinking about adding that! I was thinking the linter could be a separate tool that you could pipe the resolved output to -- `sls print | sls-linter`.

What linting items would be most helpful -- CloudFormation linting in the `resources` section? Or making sure your keys are in the right levels for different areas, e.g. that `environment` is under the `provider` block?

**Comment by mvayngrib** [comment]
it would be good to be able to pipe a serverless.yml to `sls print`, like you can pipe an event json to `sls invoke`. I have a preprocessing step, so i'd be doing something like this:

```sh
{
  "scripts": {
    "build:slsyml": "cat serverless-raw.yml | ./scripts/preprocess.sh | sls print > serverless.yml"
  }
}
```

**Comment by mvayngrib** [comment]
@alexdebrie deleting the variableSyntax actually breaks stuff for me in the long run. I use variables like this: `${{myVar}}` to differentiate them from CF variables like `${AWS::AccountId}` and runtime variables like `${aws:userid}` and `${iot:ClientId}`. With the variableSyntax stripped, `sls package` run on the output of `sls print` fails because it uses the default syntax and misinterprets `${AWS::AccountId}` and the like

**Comment by alexdebrie** [comment]
Good point @mvayngrib. I've updated and tested with my custom variableSyntax setup. Can you confirm it works with yours?

**Comment by mvayngrib** [comment]
@alexdebrie yep!

**Comment by ozbillwang** [comment]
@alexdebrie 

Got your points. Let the tool to do the job only suitable for it. 

I search `Cloudformation lint` in google and found this tool https://github.com/martysweet/cfn-lint,  `serverless.yml` is something like a superset of cloudformation templates. If we don't have `sls lint` feature currently, maybe we need to think to develop a serverless-lint plugin separately base on `cfn-lint`.

**Comment by alexdebrie** [comment]
I'm good on this PR if maintainers are happy with it. Let me know if there any other changes I can make. 😄 

@serverless/framework-maintainers

**Comment by dschep** [comment]
@HyperBrain isn't the current out put be a valid `serverless.yml` config? Adding `**` would break that.

**Comment by HyperBrain** [comment]
Hmmm... yes, but doesn't the output of a print command have necessarily to be a valid yaml? The main reason for that is imo to verify that everything is set correctly, but not to use it subsequently as replacement for the original yaml.

**Comment by alexdebrie** [comment]
Yea, my thoughts are more with @dschep here. I'd like to eventually make a linter that uses this as input, so I'd need a valid yml file.

**Comment by mvayngrib** [comment]
i'm actually using this plugin as a build step, and then later running deploy with the interpolated yaml. Not sure if that's the intended use, just saying :)

**Comment by dschep** [comment]
I was just playing with this branch because `sls print` is super useful :+1:, but it seem to choke a little when using yaml references, this it is a functional&correct config, it wasn't what I expected.

Here's a sample `serverless.yml`:
```yaml
service: test

custom:
  corsOrigin: '*'
  httpEventOptions: &httpEventOptions
    private: true
    cors:
      origin: ${self:custom.corsOrigin}
      headers: [x-api-key]

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  test:
    handler: handler.test
    events:
      - http:
          <<: *httpEventOptions
          path: test
          method: get
```

And here's the output of `sls print`:
```yaml
service: test
custom:
  corsOrigin: '*'
  httpEventOptions:
    private: true
    cors: &ref_0
      origin: '*'
      headers:
        - x-api-key
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
functions:
  test:
    handler: handler.test
    events:
      - http:
          private: true
          cors: *ref_0
          path: test
          method: get
```

**Comment by mvayngrib** [comment]
@dschep whoa, are those tricks with &, * and << documented somewhere?

**Comment by dschep** [comment]
@mvayngrib yup. The YAML spec :wink: http://yaml.org/type/merge.html

**Comment by mvayngrib** [comment]
@dschep haha, thanks! If you remember where u saw the others, let me know

**Comment by HyperBrain** [comment]
You can find the other ones in http://www.yaml.org/spec/1.2/spec.html

Anchors (&) and aliases (*)
**6.9.2 Node Anchors**
**7.1. Alias Nodes**

BTW: I assume our YAML parser also supports the tons of other nifty stuff in there 😄

**Comment by alexdebrie** [comment]
Nice catch, @dschep! I just added a new option for `dump()` that should handle this.

**Comment by dschep** [comment]
Awesome @alexdebrie, works as expected now! :smile: :tada:

**Comment by RafalWilinski** [comment]
Thanks @alexdebrie for contribution! 💪 

I confirm that it works as expected. Besides a small eslint bug that I've just fixed, everything seems great from my perspective.

LGTM ✅ 

Merging as soon as CI pass...

**Comment by horike37** [comment]
Hey, @alexdebrie :+1:  Thank you for the great PR :100: 
Could you please rebase this PR since the error on CI has been resolved on the top of master?
Thanks in advance!

**Comment by alexdebrie** [comment]
@RafalWilinski Thanks for fixing the eslint bug.

@horike37 Thanks for rebasing and for the other comments. It looks like the integration tests were just flaky, as I reran them and they have passed.

Re: Webtasks, I only added documentation for providers that have a `Variables` section in their documentation with actual variables examples. Some of the providers are more straight-forward in their config and don't use much resolved variables.

Good to merge on my end 😄

**Comment by horike37** [comment]
Thank you for commenting @alexdebrie :+1: 
LGTM :100:  merging...

**Comment by benswinburne** [comment]
What version of Serverless will this be published in? It doesn't appear to be in 1.23.0 unless i'm mistaken?

**Comment by alexdebrie** [comment]
@benswinburne This will be in the 1.24 release. If you'd like this feature now, you can install the master branch of this repo with:

```
npm install -g serverless/serverless
```

**Comment by benswinburne** [comment]
I've checked out `97d80b3` to play around with it as it stands. Don't suppose you know when 1.24 is likely/planned to release do?

**Comment by ozbillwang** [comment]
@alexdebrie 

I have tested with latest sls review 1.24, print works very well. 

Thanks a lot to add this feature in sls.

**Comment by alexdebrie** [comment]
Great to hear, @ozbillwang ! I'd love to do a linter with this eventually, but it's on my backlog 😄

**Comment by HyperBrain** [comment]
@alexdebrie @horike37 @RafalWilinski Did we ever think about creating an ESLint plugin for serverless, that will analyze the serverless.yml and report errors in there in real-time? Just had that idea and it should eliminate lots of issues that exist due to configuration errors. It might be a bit complex, but in the end very helpful.
@pmuens If we ever decide to create such a plugin, it would be good to have it hosted as serverless repo.

Any comments?

**Comment by alexdebrie** [comment]
@HyperBrain I definitely like the idea. There could be a few difficulties:

1) If it were separate from the `serverless` core, it would have to do a lot of work to emulate the Serverless variable system. If the `serverless.yml` has something like `${self:custom.foo.${opt:stage}}`, it has to know how to resolve all of that.

2) The config often relies on command like options like `--stage`, so we'd need to think about sane defaults for the linter.

3) Would need to think about how to handle variables that take a while to resolve (S3, SSM, other CloudFormation stacks, JS files). This could also cause rate-limit issues with CloudFormation / SSM.

For these reasons, I was thinking a good first step would be to write a linter where you could do `sls print --stage prod | sls-lint`. This would handle the three problems above, with the downside that you need to manually kick off a compile + lint step.

**Comment by HyperBrain** [comment]
I agree with the on-demand first step approach. That makes sense.

For an ESLint plugin I would go for pure syntax checking in the first step. That means that it checks for correct root nodes in the serverless.yml, variable reference syntax, missing mandatory properties on nodes, deprecated definitions, etc.

> The config often relies on command like options like --stage, so we'd need to think about sane defaults for the linter.
> Would need to think about how to handle variables that take a while to resolve (S3, SSM, other CloudFormation stacks, JS files). This could also cause rate-limit issues with CloudFormation / SSM.

For these semantical checks I'm not really sure if an ESLint plugin is the right place to do that, because most likely it is run within an editor and any external calls (especially to AWS) are rate limited and slow. Of course a proper request queuing can prevent issues there.
So I see these as a further evolution - if not completely unnecessary and replaced by your approach.

**Comment by RafalWilinski** [comment]
Great idea @HyperBrain, I make a lot of mistakes when writing `serverless.yml` file so such thing would be really useful. Actually, in past I thought about adding a "Language Support" for VS Code or Atom so we could have IntelliSense autosuggestions in realtime when typing but that's quite complex.

**Pull request merged**
