### PR TITLE
fixes serverless/serverless#1638

### PR DESCRIPTION
**Pull request by activescott**
Pull Request Template ------------------------
* Check out our Pull Request Guidelines here: https://github.com/serverless/serverless/blob/v1.0/CONTRIBUTING.md

##### Status:
Ready

##### Description:
#1638 describes the detail

### CODE REVIEW

**Comment by eahefnawy** [comment]
Wooo! Thanks a lot for that :tada: ... @pmuens what you think?

**Comment by pmuens** [comment]
Thanks a lot @activescott!
That's a really nifty fix! GTM from my side! 🎉

**Comment by activescott** [comment]
When the stack gets into that state there are no outputs. Not in AWS console and not in the result, but the resources are there and it appears to be the right value. This at least gives an actionable error message. I've since fixed my stack (deleted everything and redeployed) and used this code for several hours without any problem on a working stack.

**Comment by pmuens** [comment]
Alright. Thanks for the explanation (and of course the contribution). Let's do this! 👍

**Pull request merged**
