### PR TITLE
Use nodejs18 in custom-resources

### PR DESCRIPTION
**Pull request by svoychik**
Closes: #12133
similar to #11359
As NodeJS 16 security support recently ended all internal lambda functions have to be migrated to the latest LTS nodejs18 
I made changes in the same way they were done in https://github.com/serverless/serverless/pull/11367/files

### CODE REVIEW

**Comment by Mmarzex** [comment]
@svoychik Thanks for looking at this. However we can't just increment the runtime version. These custom resource handlers use `aws-sdk` v2 which is not bundled with node18 lambda functions. In order to change this, you'd need to update the custom resource handlers to use v3 of the AWS SDK.

**Comment by svoychik** [comment]
> @svoychik Thanks for looking at this. However we can't just increment the runtime version. These custom resource handlers use `aws-sdk` v2 which is not bundled with node18 lambda functions. In order to change this, you'd need to update the custom resource handlers to use v3 of the AWS SDK.

Thanks for the response. I can take a look on the adjustments required for aws-sdk3, and the changes in this PR If you don’t mind

**Comment by Mmarzex** [comment]
Go for it @svoychik 👍

**Comment by svoychik** [comment]
@Mmarzex I went through the repo to find the code that is used by those custom lambda functions. Please, take a look at my code and whether my changes make sense. 
awsRequest function and its util file were a bit tricky. I believe that eventually the function can be replaced with retry mechanisms available on aws-sdk client level ([link](https://github.com/aws/aws-sdk-js-v3/issues/3611))

**Comment by svoychik** [comment]
@Mmarzex Hi, Could you give me some feedback on this, please?

**Comment by Destructrix** [comment]
Hey guys, 

is there any ETA when this will be merged?

**Comment by CodeByTwo** [comment]
Can someone please action this ASAP. Node16 is now end of life

**Comment by Destructrix** [comment]
@svoychik 

can you please resolve the conflicts ? 😄

**Comment by gupta-abhi26** [comment]
> @svoychik
> 
> can you please resolve the conflicts ? 😄

Any updates, guys ?

**Comment by mikeprimm** [comment]
Just got notices from AWS on end-of-support for node 16 runtime - end of standard support is 11 Mar 2024 (deprecated support ending 11 Apr 2024). I'd suggest move fixed value to nodejs 20.x (now latest runtime) (or use the runtime from the provider->runtime setting)

**Comment by kris8889** [comment]
Please resolve this ASAP.  node 16.x  AWS end-of-support for node 16 runtime is very near.

**Comment by svoychik** [comment]
Since there hasn't been any activity from the serverless team on this issue, I suggest removing the custom serverless lambda. Here's a guide for eliminating the api-gw lambda, shortly speaking you have 2 options:
1. Disable those logs for API GW 
2. Enable the `roleManagedExternally` flag, and manage api-gw permissions by yourself. More info on roleManagedExternally [here](https://www.serverless.com/framework/docs/providers/aws/events/apigateway#logs)

Guidance on the second option:
Why this lambda was needed overall? Custom lambda grants API-GW `serverlessApiGatewayCloudWatchRole`  to write logs to the Cloudwatch. https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html

In your serverless.yml, set 'roleManagedExternally' to true, like this:

```
provider:
  logs:
    restApi:
      level: INFO
      fullExecutionData: false
      roleManagedExternally: true

```

From now on, you will need to manage those permissions yourself. However, keep in mind that the permissions granted by the custom API Gateway Lambda earlier will not disappear. This means that the API Gateway will continue to send logs until you clean up the AWS environment. To explicitly grant these permissions, you can implement a custom script using CloudFormation, Terraform, or AWS CDK.

**Comment by mikeprimm** [comment]
The lambda is also used for S3 and for Cognito User Pool - anyone work out a similar workaround to avoid them as @svoychik nicely outlined for API GW?

**Comment by tonivdv** [comment]
@Mmarzex  are you waiting for @svoychik to resolve the merge conflicts?

**Comment by smiley717** [comment]
Good to read here, any updates for this issue? @Mmarzex

**Comment by phongvuhyuet** [comment]
any update on this? Node.js 16 support in Lambda will end on June 12, 2024

**Comment by Mmarzex** [comment]
Hi everyone, this is now available in the [v4.0 alpha](https://github.com/serverless/serverless/tree/v4.0)

**Comment by Trav55555** [comment]
@Mmarzex will this be available in 3.x?

**Comment by jonasduever** [comment]
As of now, we cannot migrate to sls v4 (which is still in **alpha**!) until Jul 15, 2024. Probably others also have to see if they get "approval" for the sls v4 licensing changes or not, evaluate alternatives, adapt their code to v4 and test it, and so on.

_Not_ merging this to v3 would shorten the deadline for all those decisions drastically, from "end of 2024" to "mid of July", and would force people to upgrade earlier than they actually can or should.

Please let us know what you plan to do with this PR - thanks!

**Comment by Trav55555** [comment]
> As of now, we cannot migrate to sls v4 (which is still in **alpha**!) until Jul 15, 2024. Probably others also have to see if they get "approval" for the sls v4 licensing changes or not, evaluate alternatives, adapt their code to v4 and test it, and so on.
> 
> _Not_ merging this to v3 would shorten the deadline for all those decisions drastically, from "end of 2024" to "mid of July", and would force people to upgrade earlier than they actually can or should.
> 
> Please let us know what you plan to do with this PR - thanks!

Same issue here

**Comment by sergioissi** [comment]
Are there any updates on this PR @Mmarzex @medikoo @eahefnawy ? we are 2 months away from the deadline on Aws. since v4 is still in alpha it would be useful to have it on v3

thank you guys for all!

**Comment by medikoo** [comment]
@sergioissi thanks for asking. I'm personally no longer with Serverless Inc. and I don't have the necessary rights to approve and push any work here. I believe @eahefnawy @ac360 and @Mmarzex are the right contacts for that

**Comment by wesyoung** [comment]
FYSA- https://github.com/serverless/serverless/issues/12133#issuecomment-2070902296

(local plugins style work-around)

**Comment by jonasduever** [comment]
[Update from AWS](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy):
> **Runtime deprecation for Node.js 16**
> In response to customer feedback, AWS is **delaying the deprecation of the Node.js 16 runtime** until 9 months after the end of community LTS. The Node.js 16 runtime will be deprecated on the date provided in the Supported Runtimes table. As stated in the preceding note, between the end of LTS on September 11, 2023 and the deprecation date, Lambda will only apply OS patches to the runtime. No security patches for the language runtime will be applied during this period.
>
> Delaying the deprecation of Node.js 16 gives customers using this runtime the opportunity to migrate their functions directly to Node.js 20, skipping Node.js 18.

image

(Don't get me wrong - this is **not** a reason not to include this PR into v3! There won't be any Node.js security patches for example. Just wanted to let you know about the update.)

**Comment by roland-pep** [comment]
we're still waiting for this

**Comment by xoapit** [comment]
Are there any plans to merge this PR? @Mmarzex

**Comment by pd-alex** [comment]
+1

**Comment by xoapit** [comment]
Because @svoychik is not available to resolve conflicts so I have recreated a new PR, pls review and merge it https://github.com/serverless/serverless/pull/12445 @Mmarzex @eahefnawy @ac360

**Comment by mdchrist** [comment]
Can we get an update on this?

**Comment by ValeryP** [comment]
Any updates, guys @eahefnawy @ac360 and @Mmarzex?

**Comment by pd-alex** [comment]
Hey serverless guys (@eahefnawy @Mmarzex),

is there any update on this?

It seems that Serverless wants to push its users to v4 (which is still an alpha AFAIU) to earn money, which is fine.
What is not fine is the way Serverless is doing so.

Actually, we will be considering dropping Serverless since such behavior is simply irresponsible.

**Comment by JaroVDH** [comment]
They responded in a related issue:
> Our commitment to maintaining V3 for critical security and bug fixes through 2024 stands. We'll upgrade this next week.
https://github.com/serverless/serverless/issues/12133#issuecomment-2143045350

**Comment by pd-alex** [comment]
Great to hear that, thank you!

**Comment by Mmarzex** [comment]
Hi everyone, thank you for your patience, this is now supported in a new v3 release, specifically [v3.39.0](https://www.npmjs.com/package/serverless/v/3.39.0), it is available on NPM now.

**Comment by AEsmerio** [comment]
I'm using the v.3.39 with NodeJs 20.
The Cognito Triggers are still deploying Node 16.x

=/

**Pull request closed without merging**
