### PR TITLE
feat: add UAE Spain and Zurich to the AWS regions

### PR DESCRIPTION
**Pull request by umutuzgur**
Closes: #11522

### CODE REVIEW

**Comment by umutuzgur** [comment]
Although pushing changes like this make me feel like an opensource contributor again 😂 , it would be great to automate this 😬

**Review by medikoo — APPROVED** [review]
Thank you @umutuzgur !

How do you think, it can be automated?

**Comment by umutuzgur** [comment]
I was thinking about a github actions cron job that runs everyday, parses an endpoints where the DCs are located from AWS which I assume they have something for this, compares it with the ones in this file and creates a new PR if it detects a drift

**Comment by medikoo** [comment]
@umutuzgur do you think creating such PR and involved maintenance work of auto-update logic is worth it in comparison to manual update of the list we practise currently?

**Comment by medikoo** [comment]
@umutuzgur if you're into, you may prepare a PR that will automate that, but I assume it's complexity will be big, and I would be reluctant to take it assuming. we have to do such update as today maybe once a year. 

It seems that less cost and friction is when this is handled manually

**Pull request merged**
