### PR TITLE
Set permissions for GitHub actions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
As it is mentioned in the docs. The default is write permissions and this reduces to necessary permissions. 

So it reduces the attack vector. 

Obviously the docs explain better than I can. 😀

**Review by medikoo — COMMENTED** [review]
@naveensrinivasan I don't think we will need that, as I've just set access rights to "read" for `GITHUB_TOKEN` in repository settings.

Note that in a place where we push a tag (and need a write access) we do not rely on `GITHUB_TOKEN` but on custom token we pass through with secrets.

**Comment by naveensrinivasan** [comment]
I understand. The whole idea is that if another PR gets merged with another token this will address that. 

I'll let you decide. Thanks

**Comment by medikoo** [comment]
> The whole idea is that if another PR gets merged with another token this will address that.

Tokens are configured through secrets, they're not part of CI file.

In CI we just refer to environment variables. Settings you've added refer to `GITHUB_TOKEN` environment variable which is provided by GitHub internally. In our settings it's set that any token that's injected via `GITHUB_TOKEN` has just read access (it's equivalent to change you proposed here).

**Comment by naveensrinivasan** [comment]
Closing this for now. Thanks

**Pull request closed without merging**
