### PR TITLE
DRY on validate 

### PR DESCRIPTION
**Pull request by bennybauer**
Pull Request Template ------------------------
* Check out our Pull Request Guidelines here: https://github.com/serverless/serverless/blob/v1.0/CONTRIBUTING.md

##### Status:

Ready

##### Description:
As part of the work on #1590 I've noticed that the `validate` code of plugin calls repeats itself in all AWS plugins. I think it makes sense to refactor it and create a `lib` folder under `lib/plugins/aws` that will have the common logic. So now we have only one `validate.js` there, that all plugins use. 

Only one plugin, `invoke`, had additional validations, so it first calls the generic validate and then its custom checks.

##### Todos:

- [X] Write tests

### CODE REVIEW

**Comment by eahefnawy** [comment]
hmmm @bennybauer you're right! The thing is we wanted each plugin to be completely separate (although all plugins are using the aws/index.js file still). hmm maybe validate should be its own plugin that runs beforehand?

@flomotlik @pmuens what you think?

**Comment by flomotlik** [comment]
Yeah in general imho this validation logic should be in a more general place, so that plugins can define specific either config items or other stuff that gets checked without having to reimplement it everywhere. Imho our plugin system should have that built in.

With that said its just not a huge pain right now and we got other stuff to do imho. So from my perspective this is a great first step in at least DRYing this code until we clean this up in a larger way.

@pmuens @eahefnawy if you guys are ok from a Code perspective imho we can merge this to clean up the code a bit.

thanks @bennybauer for getting this up!

**Comment by pmuens** [comment]
Thanks again @bennybauer Great job and great thinking 🎉 

Would merge this into a separate branch and do some code cleanup before merging it into v1.

**Comment by flomotlik** [comment]
@pmuens what did you want to clean up before merging?

**Comment by pmuens** [comment]
I think I mixed this up with another PR by @bennybauer (he's doing so many awesome things here)

Will merge it now. :shipit: Great addition @bennybauer

**Pull request merged**
