### PR TITLE
aws schemas auto generation script

### PR DESCRIPTION
**Pull request by thewizarodofoz**
This is not a PR per se, more like an anecdote.

I found these [json files](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) which have all CloudFormation specs.

I wrote a naive script which transforms those specs into Json schema format.
It currently lacks all the nuances like `minLength` or `pattern`. But I think it could be a nice starting point when writing schemas for AJV.

If you create a folder named `schemas` and run `cloudFormationResourceSpecificationToJsonSchema.js` you will get the Json schema files for all resources.

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
@thewizarodofoz thanks for sharing.

If you have some concrete idea on how we can benefit from that, for the sake of discussion it's way bettter to open an issue with proposal (eventual code snippets can be shared in gist).

One possible use case I see is that this could be used for offline validation of  generated CloudFormation template, which could be useful to do with `sls package` (which is offline in most cases).

But then I can hardly see how we can do it reliably offline. As ideally we should download current version of JSON file from AWS servers (to ensure we have it up to date), and reasoning further I think AWS SDK has CloudFormation validation method which we could use without downloading this schema.

_As a side note (to ensure that's clear), JSON schema validation that we have baked into Framework is for validation of service configuration files and not result CloudFormation template eventually generated when Framework is used with AWS provider._

**Comment by thewizarodofoz** [comment]
I was actually excited about this just for the benefit of my work on some PR which requires writing a schema for a lot of CF specs (the aws provider s3 section).

But your point is interesting.
AFAIK the SDK only has a [validate template](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/validate-template.html) method, and even that only fails on invalid json/yaml.

Regarding having the latest version, I would argue that the framework is always coupled to a certain version of CF spec because it builds resources according to the spec. If the spec changes, probably some code will change too. So maybe the final validations schemas could be generated as a version-release step.

**Comment by medikoo** [comment]
> I was actually excited about this just for the benefit of my work on some PR which requires writing a schema for a lot of CF specs (the aws provider s3 section).

If that's helpful we may generate schema for those properties which we pass as is, and copy paste result in our schema.

We may even bake in script helper that helps generating schema to be used (but I would still download the reference JSON, as hosting it in will significantly size of a Framework)

> AFAIK the SDK only has a validate template method, and even that only fails on invalid json/yaml.

As I check it does full template validation per CF schema rules:

```
$  aws cloudformation validate-template --region us-east-1 --template-body "{ Resources: { Foo: {} } }"

An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: Every Resources object must contain a Type member.
```

**Comment by thewizarodofoz** [comment]
> As I check it does full template validation per CF schema rules:

Yeah, it validates some basic structure, but not the actual property types, for example this invalid s3 resource definition will not yield an error validation:
```json
{
  "Resources" : {
    "S3Bucket" : {
      "Type" : "AWS::S3::Bucket",
      "Properties" : {
        "BucketName" : 3
      }
    }
  }
}
```

> If that's helpful we may generate schema for those properties which we pass as is, and copy paste result in our schema.

Currently my script creates a basic schema which requires quite a lot of manual handling. I can probably improve it, but I think I will close this PR for now, and if needed I will get back to it in the future.

**Pull request closed without merging**
