### PR TITLE
Adding aws-nodejs-typescript template

### LINKED ISSUE #4057: Adding template for AWS Nodejs using Typescript
# This is a Feature Proposal

## Description
Add the ability to create function template for aws nodejs using typescript:
`serverless create --template aws-nodejs-typescript --path awesome-typescript-project`

### PR DESCRIPTION
**Pull request by franciscocpg**
## What did you implement:

Closes #4057

## How did you implement it:
Adding templates in `lib/plugins/create/templates/aws-nodejs-typescript`

## How can we verify it:
Checkout and install this PR branch and then
`bin/serverless create --template aws-nodejs-typescript --path awesome-typescript-project`

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by eahefnawy** [comment]
@franciscocpg thanks for that 👍 ... could you add this template to the list of supported templates in the create command docs?

also, I don't know much about TypeScript, but is webpack a requirement? We try to keep all the core template focused and minimal 😊

**Comment by franciscocpg** [comment]
@eahefnawy 
Webpack isn't strictly required for typescript to work, but IMO using `serverless-webpack` plugin is the best way to go right now because this plugin is mature and well integrated with development and deploy phases of serverless framework.

Development: `sls webpack invoke` works great. BTW: [will be integrated](https://github.com/serverless/serverless/pull/4056#discussion_r131877625) with `sls invoke local` in v3.
Deploy: `sls deploy` bundles correctly the generated output `js` files so deployed functions works seamless.

IMO, there are a plenty of solutions out there that integrates `typescript` with serverless framework but none of them as mature as `serverless-webpack` plugin.

@HyperBrain 
Do you have something to add?

**Comment by HyperBrain** [comment]
@franciscocpg Perfectly said 👍 😄 . Cannot add anything more.

**Comment by pmuens** [comment]
Thanks for getting back @franciscocpg 👍

Just posting the comment from your other template PR here:

> Yes, correct! That section should be update. Best would be if you could do a global search for `aws-python3` (that's another template). This should show you all the places where the template should be added.

Thanks again! And feel free to ping here if you need any additional help here!

**Comment by franciscocpg** [comment]
Done @pmuens

**Comment by pmuens** [comment]
Travis is hanging here (but build is green on the Travis website). Merging...

**Pull request merged**
