### PR TITLE
Improve serverless typescript template

### PR DESCRIPTION
**Pull request by fredericbarthelet**
Closes: #7933

### CODE REVIEW

**Comment by harrycollin** [comment]
Where can I find the documentation for serverless.ts? Thanks!

**Comment by medikoo** [comment]
@harrycollin for service config reference check this: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/ and TS file is simply expected to return object that reflects the service config

**Comment by harrycollin** [comment]
@medikoo of course, but what about self references etc.

**Comment by sanrita** [comment]
@medikoo Please can you show us an example of using the self reference in typescript with this example: ${self:provider.region}?

**Comment by fredericbarthelet** [comment]
@sanrita you can use it as usual, making sure to provide string JS notation. You can as well make use of JS string interpolation features :

```ts
profile: '${self:provider.stage}',
stage: `\${opt:stage, '${DEFAULT_STAGE}'}`,
```

@medikoo I'm working on enhancing documentation regarding serverless configuration file in other formats than yaml. Would you like to open a separate issue to handle this ?

**Comment by medikoo** [comment]
> @medikoo I'm working on enhancing documentation regarding serverless configuration file in other formats than yaml. Would you like to open a separate issue to handle this ?

@fredericbarthelet if it's just documentation, I think you can go straight to PR. Great thanks for working on that!

**Comment by fredericbarthelet** [comment]
@sanrita @harrycollin would this documentation update help ?
https://github.com/serverless/serverless/pull/8003

What are the missing point you'd like to see specifically in the documentation regarding `serverless.ts` ?

**Comment by sanrita** [comment]
@fredericbarthelet thanks for the documentation, I'm fairly new and I don't know how indepth you need to go for the example. The example you had documented seem fine, it's simple. As a beginner to serverless, the self references is something I struggled with, and I'm currently trying to figure out where I'm going wrong with the code below:
` iamRoleStatements: [
      {
        Effect: 'Allow',
        Action: [
          {
            dynamodb: 'Scan'
          }          
        ],
        Resource: `arn:aws:dynamodb:\${self:provider.region}:*:table/\${self:provider.environment.GROUPS_TABLE}`
      }]`

Maybe an example with the self references will be useful to others.

**Comment by harrycollin** [comment]
@fredericbarthelet That's great! It wasn't too clear on how it differed from yaml initially. I think for new people this will be a bit confusing though, an example where you demonstrate the similarities and differences in syntax might be useful.

**Comment by brazilianbytes** [comment]
> @sanrita you can use it as usual, making sure to provide string JS notation. You can as well make use of JS string interpolation features :
> 
> ```ts
> profile: '${self:provider.stage}',
> stage: `\${opt:stage, '${DEFAULT_STAGE}'}`,
> ```
> 
> @medikoo I'm working on enhancing documentation regarding serverless configuration file in other formats than yaml. Would you like to open a separate issue to handle this ?

I just end up here looking for better documentation to how config my service using serverless.ts. I think the self-reference presented should have a better approach than mimetic the yaml approach? What about something like this...

<pre>
<code>
import { Serverless } from 'serverless/aws';

const self: Serverless = {
 
...
<b>
  custom: {
    information: {
      apiKey: 1234,
      secret: 4321
    }
  },
</b>
...

  functions: {
    hello: {
      handler: 'src/handler.service',
      environment: {
<b>
        API_KEY: () => self.custom.information.apiKey,
        API_SECRET: () => self.custom.information.secretKey
</b>
      },
      events: [
        {
          httpApi: {
            method: 'ANY',
            path: '/',
          },
        },
        {
          httpApi: {
            method: 'ANY',
            path: '{proxy+}',
          }
        }
      ]
    }
  }
};

module.exports = self;
</code>
</pre>

I think this is a better approach because you can avoid in time of coding you put a wrong reference.

**Comment by alexvdvalk** [comment]
Anyone advise on a cron expression in the TS file? rate works but I would prefer to use a cron expression.
```
schedule: {
             rate: "30 minutes",
 },
```

**Comment by mblpz** [comment]
> Anyone advise on a cron expression in the TS file? rate works but I would prefer to use a cron expression.
> 
> ```
> schedule: {
>             rate: "rate(30 minutes)",
>           },
> ```

well is it this what you are looking for? e.g.
```
            rate: 'cron(42 * * * ? *)',
```
just upstream schedule expression as referenced here https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions

be aware of the special handling of the question mark :)

**Comment by simonotter** [comment]
I'm following a tutorial on using serverless framework with the aws-nodejs-typescript template
`sls create --template aws-nodejs-typescript --path myproject`
I was expecting a serverless.yml for the configuration, but it seems that I get a serverless.ts and the configuration is in JSON instead of YAML, making it much more difficult to write accurately and follow the tutorial. 

The serverless docs still seem to suggest that it would be YAML [https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/ ](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/ )

Is there a way to work in YAML, please?

**Comment by fredericbarthelet** [comment]
Hi @simonotter, thanks for reporting this.
The Serverless framework accept 4 different file type for its definition: `serverless.yml`, `serverless.json`, `serverless.js` and `serverless.ts`. This is described in details in the [Service section of the intro documentation](https://www.serverless.com/framework/docs/providers/aws/guide/intro#services).

If you feel more comfortable using YAML, feel free to replace the `serverless.ts` generated by the aws-nodejs-typescript template with its `serverless.yml` counterpart. Everything will still work the same.

Let me know if you face any additional issue.

**Comment by medikoo** [comment]
> I'm following a tutorial on using serverless framework with the aws-nodejs-typescript template

@simonotter what's the tutorial exactly? I guess it's targetted at TypeScript developers (?)

**Comment by simonotter** [comment]
Thanks @fredericbarthelet. I've swapped to a YAML configuration file so that I can follow the course/tutorial more closely.

@medikoo the course is [Udacity's Cloud Developer Nanodegree](https://www.udacity.com/course/cloud-developer-nanodegree--nd9990). It's not focused on typescript, but in the Serverless framework module, the instructor uses typescript.

**Comment by medikoo** [comment]
> @medikoo the course is Udacity's Cloud Developer Nanodegree. It's not focused on typescript, but in the Serverless framework module, the instructor uses typescript.

Thanks for info. Note that _default_ template to start with a Framework is [aws-nodejs](https://github.com/serverless/serverless/tree/master/lib/plugins/create/templates/aws-nodejs) it's also first option as proposed by an interactive setup (which could be started simply by `serverless` command)

**Pull request merged**
