### PR TITLE
Use chai as promised

### PR DESCRIPTION
**Pull request by HyperBrain**
## What did you implement:

Relates to #3529 

## How did you implement it:

Added `chai-as-promised` to devDependencies.

Updated some unit test files that expect promised results as reference.

## How can we verify it:

Run the unit tests. Check the coverage.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by HyperBrain** [comment]
I checked some of the unit tests (plugin/deploy, plugin/package(/lib), classes/Service, classes/YamlParser) and updated them where appropriate as reference. Error output especially on mismatched promised expectations should be much better there now. The other unit tests should be checked too and can be updated iteratively.

**Comment by HyperBrain** [comment]
`sinon-chai` could be added as well. It offers better integration of chai with sinon ->
```
expect(myStub).to.have.been.calledWithExactly(...)
```
instead of
```
expect(myStub.calledWithExactly(...)).to.be.equal(true)
```

**Comment by HyperBrain** [comment]
@pmuens @eahefnawy Any update here? In the meantime there are already conflicts as tests in master evolve.... We should merge this in the near future - after I resolved the conflicts. But I will not update the PR each and every week if tests in master are changed.

**Comment by pmuens** [comment]
@HyperBrain thanks for the follow-up and sorry for the slow response on our end (totally understand that resolving conflicts every few weeks is not an option).

Do those updates cover the whole test-codebase or are those examples and other tests are not ported yet? Sorry, I'm not 100% updated on that.

**Comment by HyperBrain** [comment]
@pmuens It is as we initially discussed a selection of test files that resemble the capabilities of chai+sinon+promises with chai-as-promised and sinon-chai.

The full test optimization should be distributed - that's a whole bunch of stuff :-D

**Comment by pmuens** [comment]
> The full test optimization should be distributed - that's a whole bunch of stuff :-D

Gotcha! yes, that's what I understood as well! Thanks for the clarification 👍 

/cc @eahefnawy 🔝

**Comment by HyperBrain** [comment]
Just rebased to current master to resolve the conflicts.

**Comment by eahefnawy** [comment]
@HyperBrain Sorry for the late response, you're totally right about conflicts!

G2M 😊

**Comment by eahefnawy** [comment]
Sorry, I just deleted/restored the branch on your fork 😅 out of habit! You might want to revoke my access to avoid such issues 😊

**Comment by HyperBrain** [comment]
@eahefnawy If it is merged - I do not need the branch anymore, so you're explicitly allowed to delete after merginging hereby 😃

**Comment by pmuens** [comment]
Looool I've just deleted the branch right before reading your comments guys 🤣 

Sorry @HyperBrain. Seems like I'm also following this habit

**Comment by HyperBrain** [comment]
If you delete my branches after merging it really saves my time - otherwise I have to clean up my repo myself ;-)

**Pull request merged**
