### PR TITLE
[openwhisk] Doc Update: Adding new API Gateway access token instructions

### PR DESCRIPTION
**Pull request by jthomas**
## What did you implement:

Adding instructions about new API Gateway integration available in OpenWhisk. 
This will be available when I release the 0.7 version of the plugin.
https://github.com/serverless/serverless-openwhisk/milestone/3

## How did you implement it:

Simple doc updates, no code changes.

## How can we verify it:

N/A

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by ilanc** [comment]
Hi @jthomas I'm getting deployment failures when trying to expose an API Gateway with openwhisk:
```
Failed to deploy API Gateway route (/hello) due to error: POST https://openwhisk.ng.bluemix.net/api/v1/experimental/web/whisk.system/routemgmt/createApi.json Returned HTTP 400 (Bad Request) --> "Response is not valid 'application/json'."
```
I take it I need to follow the instructions in the new [credentials.md](https://github.com/serverless/serverless/pull/3675/files)?

**Comment by pmuens** [comment]
Hey @ilanc 👋 

have you looked at our examples repo where you can find some OpenWhisk code examples? You can find it here: https://github.com/serverless/examples

Here's an example for a Swift HTTP service: https://github.com/serverless/examples/tree/master/openwhisk-swift-simple-http-endpoint

Maybe you could try to deploy this service to see if it's a configuration problem.

**Comment by ilanc** [comment]
Hi Phil I got what I needed yesterday. Thanks - serverless is fantastic.

**Comment by pmuens** [comment]
Great @ilanc 👍 Great to hear that an thanks for the feedback!

Really appreciate it! Let us know if you need any additional help.

**Comment by jthomas** [comment]
Hello @ilanc, sounds like @pmuens helped you out? Is everything working now?

**Comment by ilanc** [comment]
Yup thanks @jthomas. Whilst I have you on the line - can I check a few things with you about the openwhisk implementation? I'm experimenting with custom docker images (i.e. using wsk manually not via serverless, i.e. not injecting a .zip into a standard openwhisk supplied docker image) and it looks like:
1. on cold start IBM pulls the docker image directly from hub.docker.com (it's not cached anywhere on IBM's cloud)
2. there's currently no way to use private docker repos see [here](https://developer.ibm.com/answers/questions/307961/does-bluemix-openwhisk-support-a-docker-action-pul.html)

Is this correct?

**Comment by jthomas** [comment]
That's correct for 1 & 2.

Are you having issues using the `openwhisk/dockerskeleton` image with a zip file for your application?

**Comment by ilanc** [comment]
the trouble was with creating the gateway (i.e. exposing http endpoints) on bluemix not with creating the action. I didn't realise that I had do additional bx/wsk setup (`bx login -a https://api.eu-gb.bluemix.net` & `wsk bluemix login ...`), but I've sorted that out now and i can create gateways using `serverless` & `serverless.yml`

**Pull request merged**
