### PR TITLE
docs: Reorganize plugin documentation and document new v3 plugin API

### PR DESCRIPTION
**Pull request by mnapoli**
This PR:

- reorganizes the plugin documentation into separated articles, for better navigation
- the index is about _using_ plugins, where the other articles are about _creating_ plugins
- new page that documents plugin API introduced in v3 (writing to the CLI output)
- review and improve existing plugin documentation and examples

By merging we would be publishing that new documentation immediately (in v2). As such, I have added a paragraph to explain that the new API is available in v3 only.

By making that documentation available right now, it lets us point plugin authors to that documentation online.

The menu should (hopefully) render like this:

image

TODO after merging:

- Create redirects from older pages to the new pages

### CODE REVIEW

**Comment by mnapoli** [comment]
@pgrzesik I agree with you that having a small screenshot of the `success()` API could be useful. I'm currently trying to find a way to host the screenshot online. I don't want to block this PR any further, I'll add the screenshot later if that's fine with you.

**Comment by pgrzesik** [comment]
> @pgrzesik I agree with you that having a small screenshot of the `success()` API could be useful. I'm currently trying to find a way to host the screenshot online. I don't want to block this PR any further, I'll add the screenshot later if that's fine with you.

Sure thing, let's move forward with this one :100:

**Comment by mnapoli** [comment]
@medikoo are we good to merge, or is there anything else we need to update here before merging?

**Review by medikoo — APPROVED** [review]
Looks great 👍

**Pull request merged**
