### PR TITLE
Fix `deploy function` command by normalizing role 

### PR DESCRIPTION
**Pull request by RafalWilinski**
## What did you implement:

Closes https://github.com/serverless/serverless/issues/4318

## How did you implement it:

Previous change introduced regression which broke uploading functions with `deploy function` command if `role` wasn't ARN-based string. 

## How can we verify it:

```yml
service: iam-function-fix
provider:
  name: aws
  runtime: nodejs6.10

resources:
  Resources:
    RoleOne:
      Type: AWS::IAM::Role
      Properties:
        Path: /somepath/a/
        RoleName: RoleOneTest
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyNameOne
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - '*'
                  Resource:
                    - '*'
    RoleTwo:
      Type: AWS::IAM::Role
      Properties:
        Path: /my/default/path/
        RoleName: RoleTwo
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyNameTwo
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - '*'
                  Resource:
                    - '*'

functions:
  helloOne:
    handler: handler.hello
    role: RoleOne
  helloTwo:
    handler: handler.hello
    role:
      Fn::GetAtt:
       - RoleTwo
       - Arn
  helloThree:
    handler: handler.hello
    role: arn:aws:iam::085108115628:role/aws-kotlin-jvm-dev-us-east-1-lambdaRole # Replace with one working for you
```

```bash
sls deploy        # Creates resources
sls deploy function -f helloOne
sls deploy function -f helloTwo
sls deploy function -f helloThree
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by horike37** [comment]
@RafalWilinski 
Is this ready for the review?

**Comment by RafalWilinski** [comment]
@horike37 Yes.

**Comment by RafalWilinski** [comment]
@horike37 I've added minor improvement. Can you check it now?

**Comment by horike37** [comment]
Thank @RafalWilinski for updating :+1: 
That has worked like a charm with all situation :heart: The problem which I pointed out above the comment has been resolved :tada: 
merging..

**Pull request merged**
