### PR TITLE
fix(aws): allow false values in aws provider configuration

### PR DESCRIPTION
**Pull request by fargito**
Hello ! Thanks for the hard work.

In aws provider, is currently not possible to put falsy values for some configuration keys. This PR will enable per-stage configuration that is currently not possible

### CODE REVIEW

**Review by fredericbarthelet — DISMISSED** [review]

**Review by medikoo — CHANGES_REQUESTED** [review]
@fargito thanks for taking an action for that. Still most of those properties were intentionally defined that way.

They are about migration from deprecated properties, and we allow only `true` values, as only `true` will be supported in v3 (and these properties will be deprecated as meaningless in v3).

The only exceptions are:
-  `shouldStartNameWithService`  for both `http` and `httpApi`, we wanted to force that setting, but we've resigned from doing that, so I think we can indeed relax it to `true/false`
- `disableRollback` - I believe it's a bug that this property was configured as `const: true`, from a start it should be boolen.

Summarizing, let's update schema only for the above properties, and PR will be good to merge

**Comment by fargito** [comment]
Hello @medikoo I restricted the changes to the forementionned :wink:

**Review by medikoo — APPROVED** [review]
Thank you @fargito !

**Comment by medikoo** [comment]
Taken via three distinct commits.

**Pull request closed without merging**
