### PR TITLE
Add support for vpc link integration discussed as part of #5025

### LINKED ISSUE #5025: Support VPC - Link
For feature proposals:
This feature makes it possible to restrict access to api-gateway and make the solution only internally available.

https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-api-gateway-supports-endpoint-integrations-with-private-vpcs/?nc1=h_ls

Advantage: Security Enhancement 

-> no public access
-> internal microservices not accessible
-> internal enterprise solutions possible - no webapplication firewall needed -> lower costs and less senseless work

### PR DESCRIPTION
**Pull request by imsatyam**
…hub.com/serverless/serverless/issues/5025

## What did you implement:

Closes #5025 
Big thanks to @guice for this implementation. 

## How did you implement it:

Added support for `http.connectionType` and `http.connectionId` attributes.
If integration type is selected as HTTP or HTTP_PROXY, one can also add connectionType and connectionType attributes. 

Accepted value for connectionType attribute is VPC_LINK only at this point in time.
Validation is added to ensure that if VPC_LINK is present as connectionType then, connectionId cannot be null.

## How can we verify it:

We can use following configuration to have http-proxy integration with VPC_LINK as connection type.
```yml
   - http:
          path: v1/repo
          method: get
          integration: http-proxy
          connectionType: vpc-link
          connectionId: "{your-vpc-link-id}"
          cors: true
          request:
            uri: http://github.com/v1/repo
            method: get
```

deployment_log

## Todos:

- [X] Write tests
- [X] Write documentation
- [X] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by imsatyam** [comment]
@pmuens - Any pointers as to which release this feature is being targeted for? We have a need for this and we can plan accordingly.

**Comment by imsatyam** [comment]
@pmuens - let me try to put the desired resources where steps are given clearly:

1. VPC Creation with public subnet: https://docs.aws.amazon.com/directoryservice/latest/admin-guide/gsg_create_vpc.html

2. To create security group please refer to https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#CreatingSecurityGroups
For testing purpose, you can configure inbound rules to allow all traffic and not just traffic from within VPC. https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html

3. I am assuming that you'll deploy with a user having access to create IAM Roles. So in screenshot above, you may not require **role** attribute after handler. If you absolutely need to create IAM role, please refer https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-service.html.

Hope this was of some help! :)
Please let me know if there is anything specific that you are looking at.

**Comment by pmuens** [comment]
Hey @imsatyam thanks for the instructions! 👌

I just setup a VPC with subnets and security groups according to the docs. Furthermore I allowed all inbound traffic.

I tried to deploy a serverless service according to your `serverless.yml`. However I get the error that the VPC Link was not found. Is the `connectionId` the VPC id? 🤔

Futhermore after deployment what can I do to test that the API Gateway invokes the Lamdba function (according to your example)?

**Comment by jplock** [comment]
@pmuens @imsatyam if it's of any use, I created https://github.com/smoketurner/serverless-vpc-plugin which can provision a VPC, routes and subnets for you (optionally with bastion hosts, NAT Gateways or NAT instances, NACL's, etc.) and VPC Endpoints.

**Comment by imsatyam** [comment]
Yes, connectionId is VPC Link Id. 
We create VPC Link from the API Gateway Console. It needs an NLB which points to the service.

About testing:

Say the internal service endpoint v1/status returns an output **{"status": "ok"}**. Ideally this should not be accessible over internet i.e. accessible only within VPC or within corporate network.
**Service url:** https://abcservice.xyz.com/v1/status

After we create the API Gateway with resource v1/status and link this v1/status to the aforementioned micro-service using VPC Link (let us say vpc link id is _abcdpqrs_), we can test it.
**Gateway url:** https://{restapi_id}.execute-api.{region}.amazonaws.com/{stage_name}/


If we call https://{restapi_id}.execute-api.{region}.amazonaws.com/{stage_name}/v1/status, it should return the same output **{"status": "ok"}**.

Configuration for this test would be
```yml
- http:
          path: v1/status
          method: get
          integration: http-proxy
          connectionType: vpc-link
          connectionId: "abcdpqrs"
          cors: true
          request:
            uri: https://abcservice.xyz.com/v1/status
            method: get
```

For simplicity you can once try this whole process  [deploying service, creating NLB, creating VPC Link, creating Gateway and configuring VPC link integration] using AWS Console.

**Comment by imsatyam** [comment]
@guice - if you have any other suggestions that can help @pmuens  with testing of VPC Link integration, please feel free to share.

**Comment by imsatyam** [comment]
@pmuens any luck with this?
Apologies for following up on this one so many times. We want to avoid writing custom script around it.

**Comment by guice** [comment]
@imsatyam I saw your request. Unfortunately, I don't have much to add there. All these things are configured by our infra team, and, as you mentioned, can be a little complex. 🤯

**Comment by imsatyam** [comment]
@pmuens  I can see the tag for 1.43.0 milestone. Can you please share any tentative timelines around the release?

**Comment by pmuens** [comment]
> @pmuens I can see the tag for 1.43.0 milestone. Can you please share any tentative timelines around the release?

Hey @imsatyam thanks for following-up here and sorry for the slow response on my end. Yes, we're definitely interested in getting this into a mergeable state soon! TBH it's rather hard to test this PR thoroughly due to the manual processes to get a test environment up- and running.

@medikoo will take a second look at this and I believe we should be good on that front soon. Not sure if it'll land in v1.45.0. But it's definitely slated for the v1.46.0 release.

**Comment by imsatyam** [comment]
Thanks @pmuens and @medikoo. Eagerly waiting for this feature to be available!

**Comment by medikoo** [comment]
@imsatyam we would love to accompany it with some integration test.

Do you think you can patch one up? You may add one to [tests/integration-all/api-gateway/tests.js](https://github.com/serverless/serverless/blob/master/tests/integration-all/api-gateway/tests.js) or create a new service for testing somewhere in [tests/integration-all/api-gateway](https://github.com/serverless/serverless/tree/master/tests/integration-all/api-gateway).

Let us know.

**Comment by imsatyam** [comment]
Sure. Will try to add it asap.

**Comment by imsatyam** [comment]
@medikoo Looks like I'll have to setup things all over again. I am now unable to run the serverless tests either. Keep on getting error:

```
Error: Cannot find module 'process-utils/override-env'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```
Any suggestions?

In the meantime, for integration test, this is what I'll have to add to tests/integration-all/api-gateway/service/serverless.yml.

```yml
vpclink:
    handler: core.minimal  // It can be any handler. Looks like an enforcement from serverless.
    events:
      - http:
          path: /vpc-link-path
          method: get
          integration: http-proxy
          connectionType: vpc-link
          connectionId: vpc-id-1001   // It needs to be the id of a vpc link created from API gateway console.
          request:
            uri: https://github.com  // ideally this will be uri of a microservice endpoint only accessible within a vpc
            method: get
```

and in tests.js
```
describe('VPC Link Setup', () => {
    it('should expose an accessible GET HTTP endpoint', () => {
      const testEndpoint = `${endpoint}/vpc-link-path`;

      return fetch(testEndpoint, { method: 'GET' })
        .then(response => expect(response.status).to.equal(200));
    });
  });
```

Idea is that when /vpc-link-path is called, gateway would call http.request.uri.

**Comment by medikoo** [comment]
>I am now unable to run the serverless tests either. Keep on getting error:

@imsatyam you need to have all dependendies (including `devDependencies`) installed.
So just run `npm i` in context of repository and all should be fine.

> Wondering how to set up the infrastructure before integration test runs. Any suggestions?

In case of integration tests, we assume some bare (or test purpose) account, and that all setup is made in context of integration tests and that it follows with full teardown (so there's no need for setup steps that are needed to be done externally).

So here we need to create some microservice behind VPC to test it. Do you think its' doable to set this up via AWS SDK programmatically, and then tear this down? Or are there any notable implications that make this difficult?

**Comment by imsatyam** [comment]
> just run npm i in context of repository and all should be fine.
@medikoo Thanks for suggestion.

> Do you think its' doable to set this up via AWS SDK programmatically, and then tear this down?
Now, that is a difficult question :) Must be possible, however that would perhaps need deeper understanding of SDK itself. AWS does provide sample app[https://aws.amazon.com/getting-started/tutorials/deploy-docker-containers/] on ECS. 

What's challenging is that there are just so many infra pieces to be created - VPC, SG, EC2/ECS setup, NLB, VPC Link - wherein one piece may use the details of one or more pieces in the list. To me it looks so much more than the setup for an integration test. Please let me know if you think otherwise.

**Comment by medikoo** [comment]
> What's challenging is that there are just so many infra pieces to be created - VPC, SG, EC2/ECS setup, NLB, VPC Link - wherein one piece may use the details of one or more pieces in the list. To me it looks so much more than the setup for an integration test. Please let me know if you think otherwise.

I think to have it covered by maintainable integration tests, we need to either have this setup done in integration test, or provide some side script/documentation that clearly setups or explains what exactly needs to be provided for integration test to be successfully run.

I think programmatic setup would be better, as with documentation there's always risk some important details will be omitted, and developers will struggle to reproduce the test successfully.

Other question is maintenance. Do you think it involves some prone to change variables on AWS side, that will make this test challenging to maintain?

If you feel that for some reason that's not a valid approach to test this case, then it probably doesn't make sense to push too much for it.
Still integration test is the only way to ensure we won't have any accidental regression in that area (and recently after having few regressions, we agreed to cover all new bugs and features with them - of course where it makes sense)

**Comment by medikoo** [comment]
@imsatyam we've just merged [Prettier](https://prettier.io/) integration, and it may raise some conflicts with already existing changes. 

If you approach some issues in handling them, we'll be happy to help.

Also now prettier formatting is validated in CI. Therefore if you don't have an editor integrated with Prettier, you may fix all eventual style differences with `npm run prettify-updated` command.

**Comment by imsatyam** [comment]
@medikoo - Thanks for the pointer on conflict. I have rebased it.

As far as integration test is required, it is a huge ask to setup the entire infrastructure including vpc, sg, ec2/ecs, nlb and vpc link. Having said that, we do need this feature and are waiting for it to pick couple of our stories. Can you please help me understand what is the minimum that is required to get this PR merged? A documentation? Specific commands for infrastructure setup? or a complete script to setup (seems difficult considering time and complexity)?

**Comment by medikoo** [comment]
> Can you please help me understand what is the minimum that is required to get this PR merged? 

Technically, what you provided here is good enough. Still we would prefer to test it on our side locally before merging, and that's the only constraint.

So far we struggled with a setup of needed VPC infra on our side, we thought that  receiving a help with setup of integration test (which we will anyway want to introduce), will help us to sort that out.

Anyway let us give it another try.

**Comment by imsatyam** [comment]
@pmuens I can check with Infra team at my end to know if there is a way to come up with a simple document around it. However, not sure how timely would that help be. Looks like PR has been moved to  further release :)

**Comment by pmuens** [comment]
> @pmuens I can check with Infra team at my end to know if there is a way to come up with a simple document around it. However, not sure how timely would that help be. Looks like PR has been moved to further release :)

Hey @imsatyam thanks a ton for keeping the ball rolling! That would be super helpful. We'd love to get this into `master` soon, but having an integration test / an automated way to validate that it works would be thing a whole lot easier. Thanks again for following-up here 💯

**Comment by pmuens** [comment]
Hey @imsatyam I just wanted to check-in with you again to see if you had some time to talk to the infra team regarding the documentation.

Would love to get this into `master`. Let us know if you need any help here.

**Comment by dr-robert** [comment]
👍 for getting this merged. Would benefit my teams greatly.

**Comment by pmuens** [comment]
> 👍 for getting this merged. Would benefit my teams greatly.

@dr-robert thanks for chiming in! Do you have a simple step-by-step guide handy we could use to thoroughly test this feature? We'd love to merge this in ASAP, however apparently it's not that straightforward to test.

**Comment by dweeban** [comment]
> 
> 
> 👍 for getting this merged. Would benefit my teams greatly.

Same, this feature would solve a big problem for my team

**Comment by pmuens** [comment]
> @pmuens What do you need for us to help with the testing. We are in the same boat as others in that our enterprise creates and manages our VPC for us.

@dr-robert thanks for following-up. The best artifact would be a `serverless.yml` or CloudFormation `.json` file we can "just deploy" to test this PR thoroughly.

A clear step-by-step guide would work as well.

The main issues thus far has been that VPC setups are inherently complex, hence an automated test setup would be awesome.

Thanks in advance an let us know if there's anything else we can help you with.

**Comment by fablanglet** [comment]
@pmuens I created a CloudFormation Template (yml not json), to setup a test env:

1. Create private Subnet + Cluster
2. Create NLB
3. Create VPC Links in API Gateway

I hope it will be helpful to test the PR. 

[VPC Link - API Gateway.yml.txt](https://github.com/serverless/serverless/files/3790171/VPC.Link.-.API.Gateway.yml.txt)

**Comment by pmuens** [comment]
Thanks a lot for that @fablanglet ! 🙏

We'll update this PR soon (there are some conflicts) and then we'll use your template to validate it.

**Pull request merged**
