### PR TITLE
Event Source Mapping

### PR DESCRIPTION
**Pull request by dekz**
awsm-org/awsm#11

Supported Events should just work are translated directly into CF Event Source Mappings.
Unsupported Events are a special case and are handled with `aws-sdk`

Supported: `DynamoDB, Kinesis`
Unsupported: `S3, SNS, API Gateway, SQS, everything else...`

Added a new field to `awsm.json`, `eventSource`:

```diff
"lambda": {
    "enVars": [],
    "package": {},
    "excludePatterns": {},
    "cloudFormation": {
        "Description": "",
        "MemorySize": 1024,
        "Runtime": "nodejs",
        "Timeout": 6
    }
},
"apiGateway": {
     "cloudFormation": {}
+},
+"eventSource": {
+  "kinesisAbcd": {
+   "type": "kinesis",
+    "cloudFormation": {
+      "EventSourceArn": "abcd:dev:stage:123"
+    }
+    // Can use AWS::Lambda::EventSourceMapping
+  },
+}
+}
```

This will result in a new cloudformation entry of:

```diff
"Resources": {
  "ltest1": {
    "Type": "AWS::Lambda::Function",
    "Properties": {...}
  },
+  "esKinesisAbcd": {
+    "Type": "AWS::Lambda::EventSourceMapping",
+    "Properties": {
+      "EventSourceArn": "abcd:dev:stage:123"
+    },
+    "DependsOn": "ltest1"
+  }
}

```
API Gateway can eventually be migrated into the eventSource object but this will require a deprecation on a version change.

This PR also refactors the CF generate lambda out of the command as that file was getting massive.

#### TODO 
* [x] supported Event Source Mappings work
* [x] unsupported Event Sources need to be implemented with `aws-sdk` commands.

### CODE REVIEW

**Comment by dekz** [comment]
screen shot 2015-10-11 at 10 50 00 pm

SNS is now supported in this PR while we wait on CF.

**Comment by ac360** [comment]
:+1: @dekz you rock, as always!!!  I will dig into this today/tomorrow.  Really excited that you've started this :)

**Comment by dekz** [comment]
Any updates on getting this functionality merged in? We're trying to start work on a project and require a number of topics being subscribed to.

Happy to make modifications to this PR if required.

**Comment by doapp-ryanp** [comment]
Can't give a specific timeline as we are in the midst of a massive re-factor.  What I can tell you is we are committed to adding `EventSourceMapping` support.  IMO however, I think we need to nail down a solid flow to handle versioning and aliases, because everything else we build will depend on it.

So IMO the current work priority is:
1.  ES6 re-factor (almost complete) 
2.  Architect and implement versioning and aliases (this include fix issue 192)
3.  JAWS plug-in extension model design and implementation
4.  lambda permissions & event source mappings

**Comment by ac360** [comment]
We're working hard so we can merge this in soon @dekz.  We totally appreciate you and your work here.  I also just sent an email to the Lambda team asking if they could tell the CloudFormation team to move more quickly on adding more Event Source Mappings.

**Comment by ac360** [comment]
Thanks @dekz.  V0.4 and greater have event support built in.  Thanks for your great work @dekz and we miss you!

**Pull request closed without merging**
