### PR TITLE
Update AWS tag value pattern

### PR DESCRIPTION
**Pull request by mvanzoest-rcd**
Closes: #8390

Inspired by [this PR](https://github.com/serverless/serverless/pull/8314/files#diff-271ef5d492727880dcac1b94a86c878dR359), which also does not include test modifications, but I would be happy to write a couple tests if given guidance on the best place for those tests.

### CODE REVIEW

**Comment by medikoo** [comment]
Thanks for opening but issue in question was already fixed with https://github.com/serverless/serverless/pull/8314. 

And it's in since v2.5.0 (ensure to use latest version!)

**Comment by mvanzoest-rcd** [comment]
> Thanks for opening but issue in question was already fixed with #8314.
> 
> And it's in since v2.5.0 (ensure to use latest version!)

What are you talking about? I added an underscore and an at-sign...

**Comment by medikoo** [comment]
> What are you talking about? I added an underscore and an at-sign...

Have you checked whether you observe same issue with latest version of a Framework? 

Note that what you've updated is pattern for tag name (which is correct) and not tag value

**Comment by mvanzoest-rcd** [comment]
> Have you checked whether you observe same issue with latest version of a Framework?
> 
> Note that what you've updated is pattern for tag name (which is correct) and not tag value

Ahh gotcha.  Yes, you are right, 2.5.0+ does not give the warnings.  Thanks for the clarifications!

**Pull request closed without merging**
