### PR TITLE
fix loading of asynchronous credentials.

### PR DESCRIPTION
**Pull request by rkistner**
## What did you implement:

**_Implementing Issue:**_ #2355 

The issue is that if a `role_arn` is defined in the profile, the actual `accessKeyId`, `secretAccessKey` and  `sessionToken` are load asynchronously. By the time these are copied into the `credentials` object, these haven't been loaded yet.
## How did you implement it:

There are two main solutions to this:
1. Call `refresh()` on the `SharedIniFileCredentials` object, and only copy the credentials after it has loaded.
2. Keep it as a `SharedIniFileCredentials` object, and let the AWS SDK handle the details. It's unlikely that you'll want to override any of the details if you're using a profile anyway.

I went with option 2.
## How can we verify it:

You need an account with roles setup: http://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html

Then a `~/.aws/credentials` file with something like this:

``` ini
[main]
aws_access_key_id = ...
aws_secret_access_key = ...

[subaccount]
role_arn = arn:aws:iam::<my-account>:role/Admin
source_profile = main
```

Then test with `AWS_PROFILE=subaccount serverless info`, or by specifying `profile: subaccount` in `serverless.yml`.
## Todos:
- [x] Properly design the implementation
- [x] Write tests
- [x] Write documentation - N/A
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config/commands/resources - N/A
- [x] Change ready for review message below

**_Is this ready for review?:**_ YES

### CODE REVIEW

**Comment by rkistner** [comment]
I re-implemented this from scratch on the current master.

The change is now less invasive, and only affects the case where:
1. A profile is defined (via `process.env.AWS_PROFILE` or `serverless.yml`).
2. No access key is defined by any method.

Without this change, there is no scenario in which the above would work, as there are effectively no credentials loaded. This change uses `AWS.SharedIniFileCredentials` for the above case, letting the AWS library load the temporary credentials.

**Comment by kddeisz** [comment]
Bumping this because it's important for our use case as well. Just switched over to the branch and confirmed it works. Thanks for the great work @rkistner!

**Comment by stevecaldwell77** [comment]
NOTE: I didn't notice this PR and ended up doing a duplicate PR - #2687.  I've closed mine because this implementation is better.  However, I did provide more details in my PR description on how to set up an assume-role profile - whoever is reviewing this PR might find those instructions useful.

**Comment by stevecaldwell77** [comment]
@rkistner - I've successfully resolved the conflicts with master on my copy of your branch:

  https://github.com/stevecaldwell77/serverless/commits/fix-async-credentials

No need for you to duplicate work :)

**Comment by rkistner** [comment]
@stevecaldwell77 Thanks! I updated the PR to your copy.

**Comment by pmuens** [comment]
@rkistner thank you very much for this PR! 👍 

Looks good from a "code design" perspective for me.
Would like to invite @eahefnawy and @erikerikson to take a look at this and provide feedback!

**Comment by erikerikson** [comment]
Thanks @rkistner, 🎉 , I'll be taking a look.  Thanks @stevecaldwell77 for the extra docs. 👍 

I was unaware of this feature when I implemented the existing code.  It definitely assumes that everything is available synchronously.  Reading into what is going on here but with the holiday my response may not be immediate.  Thanks again!

**Comment by erikerikson** [comment]
@rkistner I ended up tanking here a bit after all.  Thanks again for these changes and especially for bringing up the circumstance that I missed!

I think I understand the approach you are taking and it brings to light a failure in my thinking within the initial implementation (1) but I also think you've made these changes at the wrong location in the code (2).  I think I know how to untangle this (3).

1. My failure in thinking was believing that there is a relatively standard response (The [docs here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html) only mention the case that was coded to) but as you've demonstrated that was wrong and the returned blob should be treated like a blob.  I originally went for a positive detection of successfully loaded credentials.  The reason for positive, specific detection was to avoid an error case that resulted from null credentials being returned from these calls under certain circumstances (and thereafter, in some cases, the attempt to use those.

2. To be specific, the location of the code that inspects the credential blob and acts appropriately is the `addCredentials` method.  That function contains the code that is intended (at least in the original design as written) to be responsible for codifying the knowledge of what forms credentials can take when loaded from any of the multitude of sources.  This form of credentials was not explicitly coded for (again because of the positive detection of the expected credentials form).

3. All that background and explanation given, I suspect that the solution comprises either:
A. shifting from positive credential loading detection to detecting the null credentials loading case.
B. adding the detection of this new credential form into the positive credentials loaded detection and assignment logic.
Taking approach B seems like it could work but may consist of playing a relatively endless form of whack-a-mole as the imperfectly documented form of credentials return morphs over the years.  Similarly taking approach A seems like it could work but may consist of playing a relatively endless form of whack-a-mole as the not-yet-documented form of null credentials return values morphs over the years.
Between these two, A seems to engender a lower probability of change risk.

Doing research in the [awssdk's SharedIniFileCredentials docs](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/shared_ini_file_credentials.js) to see about any other cases that may have been missed.

**Comment by erikerikson** [comment]
Relevant docs bug issue that brings in a potential future shift in implementation:
https://github.com/aws/aws-sdk-js/issues/993

**Comment by erikerikson** [comment]
looks like there's a bug in here that the `profile` attribute is not reset if profile-loaded credentials are overridden.  this could create a bug in consuming code.  I also don't recall where the requirement for that attribute came from.  seems that consumers should be ambivalent as to the providence of the credentials.

**Comment by rkistner** [comment]
@erikerikson Thanks for looking at this. I just went with the simplest approach I could find to solve my specific case, without risking breaking other existing cases. There may be other cases that are still not handled, but that's a little out of my depth. There are also some cases where it's not even clear what the intended behaviour should be. For example, what should happen if a `secretAccessKey` is specified in addition to the profile? I'm assuming this won't actually be common in practice though.

> Relevant docs bug issue that brings in a potential future shift in implementation:
aws/aws-sdk-js#993

So it seems like e.g. the AWS CLI uses the `~/.aws/config` file to store this profile info. The JS SDK currently uses `~/.aws/credentials`, but may use `~/.aws/config` in the future. I'm happy with using either, as long as there is some way to specify the `source_profile` and `role_arn`.

**Comment by erikerikson** [comment]
@rkistner Mostly with that link, I was hoping to note that they were discussing potential shifts in the implementation.  As much as possible, I have been relying on the `aws-sdk` classes to implement the know-how of loading credentials.  This because I'm lazy and try to avoid duplication.  As noted in the linked PR, I'm working on merging this with #2695 and writing tests.

**Comment by erikerikson** [comment]
Please correct me if I am wrong but the crux of this fix is that the same sdk object used to load the credentials file needs to be the returned credentials attribute because the temporary STS credentials will be delivered to that object.  Is that right?

**Comment by erikerikson** [comment]
I believe that I've incorporated the spirit of these changes but I can't seem to properly test the capability.  I don't have that setup.  As a result, I apologize but I am going to go ahead and open the PR and ask that you investigate whether it has sufficiently resolved your issue.

Thanks for bringing attention to this fix.  It has forced me to face some failures and by so doing, you enabled an improved implementation to the credentials loading codebase.  Many thanks!  🎉

**Comment by rkistner** [comment]
> Please correct me if I am wrong but the crux of this fix is that the same sdk object used to load the credentials file needs to be the returned credentials attribute because the temporary STS credentials will be delivered to that object. Is that right?

Yes, that's the crux.

Let me know if you have a something that I need to test.

**Comment by erikerikson** [comment]
Thanks for confirming!  PR is https://github.com/serverless/serverless/pull/2820

**Comment by pmuens** [comment]
Thank you @rkistner for working on this! 👍 

I'll close this one as @erikerikson started to merge these changes into #2820.

**Pull request closed without merging**
