### PR TITLE
refactor(CLI): Improve progress for CloudFormation updates

### PR DESCRIPTION
**Pull request by pgrzesik**
Reported internally, take advantage of ChangeSet implementation to improve the way we show progress for deploy command

### CODE REVIEW

**Comment by mnapoli** [comment]
That is AWESOME!

I tried this on a small project: I deployed changes + added a Lambda function. The CloudFormation deployment was very very long. Having the update really made the difference between "is it stuck? is there a problem?" and "cloudformation is slow…"

One thing to note: there was a looong time before the count even showed up (75 seconds): is there anything we can do about that? I would imagine it's the time for CloudFormation to create the changeset? I guess we have to live with it?

Here is a rough timeline:

Screen 2022-01-05 16-38

Finally some resources show up:

Screen 2022-01-05 16-14

Then it updates nicely:

Screen 2022-01-05 16-25 2
Screen 2022-01-05 16-32

And all of a sudden the deployment is done. I guess the last changes are resource deletions, which may be super quick. Anyway, not a big deal, but surprising:

Screen 2022-01-05 16-44

**Comment by pgrzesik** [comment]
Thanks a lot for checking that out @mnapoli 🙇 

As for the question about the count showing up - you're right, this is time when we wait for changeset to be created - you can see what's happening under the hood better with `--verbose` flag. What we could potentially do here is changing the messaging a little bit - we can present information that ChangeSet is being created instead of showing current message and only when the changeset is being executed then we switch to message - in such situation we should quickly see the number of resources. 

As for the situation where the deployment "is gone" - this is situation where during update cycle we see that all resources finished their deployment and the message is changed as we move forward with processing. Not sure what we could do here as the change to new message is pretty fast.

**Comment by mnapoli** [comment]
Got it, thanks. Let's stay with this simple approach for now, it's already a great improvement!

**Comment by pgrzesik** [comment]
@mnapoli So we should keep it as-is without any additional adjustments? We definitely can consider adjusting the progress message to inform that change set is being created

**Comment by mnapoli** [comment]
The thing is that "CloudFormation change set" is a low-level detail, it may not speak to all users. Having a counter "(5/10)" is useful because even if you don't know what is actually being deployed (what at those 10 things), it tells you a bit of progress and how long you'll probably need to keep waiting.

Since our goal with v3 is to simplify and make Serverless Framework more approachable, speaking about CloudFormation changesets may be a bit too much. We could write something like "Preparing CloudFormation deployment" but that risks also confusing experienced AWS users ^^

That's why I wouldn't change the message, unless we can think of something both "high level" yet still "accurate" that it won't confuse beginners and experienced users.

**Review by medikoo — APPROVED** [review]
Looks great 👍

**Pull request merged**
