### PR TITLE
Set stdin to a TTY in invoke.py to allow PDB use

### PR DESCRIPTION
**Pull request by dschep**
Setting `sys.stdin` to a TTY prevents `pdb.set_trace()` from immediatly throwing
`BdbQuit`. I am unsure if there is a way to make this work in Windows

## What did you implement:

PDB support in Python Invoke Local, which didn't work because it requires a TTY.

## How did you implement it:
Set `sys.stdin` to a TTY in `invoke.py` after the JSON event is read from it.

## How can we verify it:
1. create a new python project: `sls create -t aws-python3`
2. add `import pdb;pdb.set_trace()` in the sample handler, ie:
```python
def hello(event, context):
    body = {
        "message": "Go Serverless v1.0! Your function executed successfully!",
        "input": event
    }

    response = {
        "statusCode": 200,
        "body": json.dumps(body)
    }
    import pdb;pdb.set_trace()


    return response
```
3. run `sls invoke local -f hello` You should get a PDB prompt rather than a `BdbExit` error. (type `c` and Enter to continue execution)

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by RafalWilinski** [comment]
Thanks for this small improvement @dschep 👍 

Merging...

**Comment by dschep** [comment]
Cool. I assume there is something wrong with unit tests on master, not my branch specifically, yes?

**Comment by RafalWilinski** [comment]
It's related to master: https://github.com/serverless/serverless/pull/4363

**Comment by dschep** [comment]
Updated. Still fails on node 4, but AFAICT so does the master branch.

**Pull request merged**
