### PR TITLE
[feature] Universal json request template

### PR DESCRIPTION
**Pull request by rma4ok**
http://kennbrodhagen.net/2015/12/06/how-to-create-a-request-object-for-your-lambda-event-from-api-gateway/

@ac360 
[AWS GW docs](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html)
I've implemented a template that grabs all data from AWS GW `$input` and passes it as objects within lambda event.
Do we also want to grab by default all the params from `$context` like
```
{
"stage" : "$context.stage",
"request_id" : "$context.requestId",
"api_id" : "$context.apiId",
"resource_path" : "$context.resourcePath",
"resource_id" : "$context.resourceId",
"http_method" : "$context.httpMethod",
"source_ip" : "$context.identity.sourceIp",
"user-agent" : "$context.identity.userAgent",
"account_id" : "$context.identity.accountId",
"api_key" : "$context.identity.apiKey",
"caller" : "$context.identity.caller",
"user" : "$context.identity.user",
"user_arn" : "$context.identity.userArn"
}
```
and also `$stageVariables`

### CODE REVIEW

**Comment by rma4ok** [comment]
@ac360 I've added `$context` and `$stageVariables` to the template

**Comment by HyperBrain** [comment]
@rma4ok @ac360 I would suggest also to add `$context.identity.cognitoId` to the event object. If you use Cognito and do not want to call your lambda within the Cognito user's role (because it's just too restricted) but let the lambda know who called, this would be needed to be passed to the lambda.

**Comment by rma4ok** [comment]
@HyperBrain it provides `{body, method, path, querystring, header, context, stageVariables} = event`

**Comment by ac360** [comment]
@minibikini @eahefnawy Could you review this and let me know your opinion?  It looks like a big UX gain.

**Comment by ac360** [comment]
ping @minibikini @eahefnawy

**Comment by minibikini** [comment]
@ac360 it looks awesome! 

It'd be great to have `{body, method, headers, query, path, identity, stageVariables} = event` by default.

**Comment by eahefnawy** [comment]
Oops, sorry I missed this one in my Github notifications. This is looking great, and I definitely find it very useful. The only concern I have is that maybe it's a bit too much for `s-function.json`? `s-function.json` is already complex and this makes it a bit worse.

Maybe it should be included in a default template instead? we've also been discussing adding default error codes in a default template as well. What you guys think?

**Comment by ac360** [comment]
Ok, here's an idea.  Inspired by @minibikini @eahefnawy.  Could we create something like a `requestAll: true` option which tells Serverless to automatically use this template when deploying.  This way, the user does not have to include this template it every endpoint, just `requestAll: true`.

**Comment by ac360** [comment]
Or do we need that option?  Perhaps if `requestTemplate` is empty we go with @minibikini's suggestion and just add the above default requestTemplate.

**Comment by eahefnawy** [comment]
@ac360 Love it! This way the user doesn't have to keep it in s-function nor s-template. I say we go this way.

**Comment by mwawrusch** [comment]
I don't think this should be hardcoded in serverless, it's very individual to each usecase. However I think that serverless should provide guidance and reasonable defaults that can be used. E.g. when doing a project create the template should be created using this (or a modified form of it) and a default set in the project file which is used when not overridden by the s-function file.

**Comment by doapp-ryanp** [comment]
I really like this, however I don't think this metadata should be at the top level of the `event` object.  I think these attrs should be put in their own namespace. For ex: `event.slsContext` or `event.slsReq`

**Comment by flomotlik** [comment]
Agreed with @mwawrusch and @doapp-ryanp here. This should be an optional (maybe even default) part of the deployment, but not forced upon everyone. I think we should ship with this in V1 as its a feature that should be very commonly used by people. Put it into the V1 milestone.

**Comment by flomotlik** [comment]
@rma4ok we've implemented this now in V1 of the service: https://github.com/serverless/serverless/blob/v1.0/lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js#L49

Therefore I'm closing this issue here. Thanks for proposing this and starting the discussion!

**Pull request closed without merging**
