### PR TITLE
Update AWS Lambda runtime to nodejs18.x

### PR DESCRIPTION
**Pull request by tampueroc**
AWS notified about Node.js v16  deprecation on AWS Lambda runtime. This PR upgrades AWS Lambda runtime to Node.js v18
Closes: #12310

### CODE REVIEW

**Comment by jmoe** [comment]
Waiting for this.

**Review by cbolivar-neostella — APPROVED** [review]

**Review by mvalencia-neostella — APPROVED** [review]

**Comment by fnerdrum** [comment]
Lambda upgraded from v2 to v3 of AWS SDK, so I think this is a bit more work. https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/

Also maybe do directly to nodejs20.x while we're at it?

**Review by gavinjohnson-crowdcube — APPROVED** [review]

**Comment by tschumann** [comment]
Looks like discussion about the AWS Javascript SDK v3 at https://github.com/serverless/serverless/issues/11920 is ongoing.

In relation to this, it looks like https://github.com/serverless/serverless/blob/main/lib/plugins/aws/custom-resources/resources/s3/handler.js is the file that gets deployed and run and I think https://github.com/serverless/serverless/blob/main/lib/plugins/aws/custom-resources/resources/utils.js is the only file that it references (indirectly at that) that uses the AWS Javascript SDK v2.

**Review by jrdnrc — APPROVED** [review]

**Comment by tonivdv** [comment]
The correct fix is here => https://github.com/serverless/serverless/pull/12146

**Comment by malcyL** [comment]
I inadvertently created a duplicate of this, which I have now closed: #12334 

Testing of this change is working in our staging environments. We obviously need this before the node 16 runtime reaches it's end of life at AWS. 

I notice someone else has just asked for this on the issue: https://github.com/serverless/serverless/issues/12310#issuecomment-1915169898

I'm not clear what else needs to be done here?

**Comment by malcyL** [comment]
I'm also looking at the comment above re AWS Javascript SDK v3 and I'm wondering if that is relevant for the v2 branch this PR is targeting?

**Comment by tonivdv** [comment]
> I'm also looking at the comment above re AWS Javascript SDK v3 and I'm wondering if that is relevant for the v2 branch this PR is targeting?

@malcyL afaik it is ... whether it is v2 or v3, if it runs on the node engine >=18 then it requires aws sdk v3

**Comment by marslan02** [comment]
Is there an estimated timeline for when this change will be available?

**Review by reecebenson — APPROVED** [review]

**Comment by tampueroc** [comment]
Updated AWS SDK v3 dependencies accordingly

**Comment by vSkoryk** [comment]
Will this one be merged?

**Comment by j0k3r** [comment]
Can be close as it was added in https://github.com/serverless/serverless/releases/tag/v3.39.0

**Comment by tampueroc** [comment]
@j0k3r It targets a different version (v3), this PR aims to solve the issue on v2.

**Comment by malcyL** [comment]
@j0k3r Can I reiterate @tampueroc's comment above. 

This issue is not fixed by https://github.com/serverless/serverless/releases/tag/v3.39.0

This issue is about the deprecation of the NodeJS v16 runtime in  AWS and whether this is going to be fixed in v2 of Serverless.

The previous node version deprecation was fixed in v2 here: https://github.com/serverless/serverless/pull/12055 which was merged into the `[serverless:v2](https://github.com/serverless/serverless/tree/v2)` branch - not main.

This issue was raised in multiple places which have all been closed pointing to this issue as the solution, a few but maybe not all are: 

- https://github.com/serverless/serverless/pull/12334
- https://github.com/serverless/serverless/issues/12310#issuecomment-1915169898

While v2 is obviously old and upgrading to v3 is the obvious solution - this PR is important for people who are unable to do so immediately and are facing the AWS EOL of Node 16.

If the serverless framework is not going to fix this for the v2 branch - this needs to be communicated

**Comment by reecebenson** [comment]
@malcyL It was confirmed in discussions that no minor fixes or new features will come to v2, [see here](https://github.com/serverless/serverless/discussions/10934). v2 hasn't been updated since July 10th, so I wouldn't assume they would backport this Node v18 change to v2.

**Comment by malcyL** [comment]
@reecebenson Thank you.

The link you reference was made on 6th April 2022. 

The previous PR to bump this, https://github.com/serverless/serverless/pull/12055, was merged on 10th July 2023 - after this statement. Obviously there is more of a change here with the need to bump the SDK.

But I guess people were hoping that this would be similar and would get merged.

Obviously not - so this does seem to mean that v2 will stop working with AWS's EOL of NodeJS 16.

**Comment by tampueroc** [comment]
@Danwakeem Asking you also since you merged the last maintance PR to v2 last year (#12055). Didn't found any discussions or announcment after #12055 got merged.

**Comment by Mmarzex** [comment]
Hi @tampueroc we are not planning further releases of v2. V3 has been GA and stable for a few years at this point and now V4 is available. Both V3 and V4 have this fix in place. I'd recommend upgrading to more recent version.

**Pull request closed without merging**
