### PR TITLE
Fix end of failed deletion discovery in AWS stack monitor

### PR DESCRIPTION
**Pull request by medikoo**
## What did you implement:

Failed deletion is not discovered as expected by stack monitor, therefore it polls infinitely.

It looks as a regression introduced by: https://github.com/serverless/serverless/pull/2367/files#diff-3863240f31427c97202058562e09ec44R79 (the problem was already being fixed in a past -> https://github.com/serverless/serverless/issues/1367 )

## How did you implement it

I ensured `DELETE_FAILED` is picked as final status

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by medikoo** [comment]
@pmuens added tests, on the way discovered that bug affects only _verbose_ mode (I anyway introduced tests for both cases)

**Comment by pmuens** [comment]
> @pmuens added tests, on the way discovered that bug affects only verbose mode (I anyway introduced tests for both cases)

Great! Thanks for updating the PR @medikoo 👍

**Comment by eahefnawy** [comment]
while I wasn't able to test the DELETE_FAILED status, this PR works on my service without an issue as expected. Pretty straightforward 👏 

@medikoo what scenario would trigger this DELETE_FAILED status?

**Comment by medikoo** [comment]
> @medikoo what scenario would trigger this DELETE_FAILED status?

e.g.:

```
CloudFormation - DELETE_IN_PROGRESS - AWS::CloudFormation::Stack - maas-tsp-dev2
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - BookingDashhtdLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - BookingDashcitybikesLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - BookingDashvalopilkkuLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - BookingDashsixtLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - BookingDashhslLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - BookingDashgettLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - BookingDashnxLambdaFunction
CloudFormation - DELETE_FAILED - AWS::Lambda::Function - BookingDashhtdLambdaFunction
CloudFormation - DELETE_FAILED - AWS::Lambda::Function - BookingDashsixtLambdaFunction
CloudFormation - DELETE_FAILED - AWS::Lambda::Function - BookingDashcitybikesLambdaFunction
CloudFormation - DELETE_FAILED - AWS::Lambda::Function - BookingDashhslLambdaFunction
CloudFormation - DELETE_FAILED - AWS::Lambda::Function - BookingDashgettLambdaFunction
CloudFormation - DELETE_FAILED - AWS::Lambda::Function - BookingDashvalopilkkuLambdaFunction
CloudFormation - DELETE_FAILED - AWS::Lambda::Function - BookingDashnxLambdaFunction
CloudFormation - DELETE_FAILED - AWS::CloudFormation::Stack - maas-tsp-dev2
Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred while provisioning your stack: BookingDashhtdLambdaFunction - API: ec2:DescribeNetworkInterfaces You are not authorized to perform this operation..
```

**Comment by medikoo** [comment]
@pmuens good point. What do you think will work better? Best that comes to my mind:
- `Operation failed!`
- `An error occured: ..`

**Comment by pmuens** [comment]
> @pmuens good point. What do you think will work better? Best that comes to my mind:

> Operation failed!
> An error occured: ..

@medikoo That looks good. I like that 👍

**Comment by medikoo** [comment]
@pmuens Thanks, updated

**Comment by medikoo** [comment]
> I fixed the tests (they were failing because of the new error message).

Thanks! Sorry didn't notice (it's long known problem of Travis CI, that notifications for failed builds are not send to PR authors)

**Comment by pmuens** [comment]
> Thanks! Sorry didn't notice (it's long known problem of Travis CI, that notifications for failed builds are not send to PR authors)

No worries! Those fixes were no-brainers 😄!

**Pull request merged**
