### PR TITLE
added support for VPC with tests and docs

### PR DESCRIPTION
**Pull request by eahefnawy**
This PR adds support for providing VPC configuration for functions as described in issue #1489 . It also includes tests and docs.

### CODE REVIEW

**Comment by flomotlik** [comment]
@svdgraaf apparently @eahefnawy was already on this :D. Would be great to get your opinion on it.

**Comment by svdgraaf** [comment]
This looks perfect. Would it be possible to use a Ref() on the values for the SG/VPC? So someone would be able to create the VPC and SG's directly in the Resources section?

**Comment by flomotlik** [comment]
@svdgraaf @eahefnawy how about a Regex that checks if the value is an arn, if it is use it directly, if it isn't use a Ref?

**Comment by eahefnawy** [comment]
@svdgraaf Since `securityGroupIds` & `subnetIds` are arrays of strings, I think you can either use Ref directly or with `Fn::Join` like [we're doing with APIG Methods](https://github.com/serverless/serverless/blob/v1.0/lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js#L90-L100).

@flomotlik I don't think ARN would work because the configurations are expecting Ids not ARNs, which you can set directly or with Ref.

**Comment by flomotlik** [comment]
@eahefnawy so users could simply do

```
securityGroupIds:
      - "{ "Ref" : "MyEC2Instance" }"
      - securityGroupId2
```

and this would work right away. That would be neat :D

**Comment by eahefnawy** [comment]
Yep, but I think without the quotes around Ref in yaml:

```
securityGroupIds:
      - Ref: MyEC2Instance
      - securityGroupId2
```

What we're basically telling AWS here is that the first array element is an object containing the Ref key with `MyEC2Instance` value. AWS will then replace that Ref with the logical id of MyEC2Instance.

**Comment by flomotlik** [comment]
GTM

**Comment by flomotlik** [comment]
@svdgraaf this is merged now, could you check if this works well with your Ref setup too, then we'll update the docs to include the Ref config option

**Pull request merged**
