### PR TITLE
Layers

### PR DESCRIPTION
**Pull request by dschep**
## What did you implement:

Implemented Layers support!

## How did you implement it:
the layers option on functions is passed through to the function's CFN object since the syntax is simply a list of ARNs

Publication adds a new package/compile/upload step.

## How can we verify it:
```
git clone git@github.com/serverless/serverless
cd serverless
git checkout layers
npm i -g .
cd ..
git clone git@github.com:serverless/sqlite-lambda-layer
cd sqlite-lambda-layer
./build.sh
sls deploy
cd example
# Update sls yaml with the ARN printed out in the deploy above
sls deploy
sls invoke -f hello
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by hotgazpacho** [comment]
@dashmug Serverless is a launch partner for Layers on Lambda ;)

**Comment by dashmug** [comment]
Does this support specifying a layer for specific functions only and not to all functions in the `serverless.yml`?

**Comment by hotgazpacho** [comment]
@dashmug check out the docs: https://github.com/serverless/serverless/blob/1231edc2b071f8d95d50fb1c62077717636a5252/docs/providers/aws/guide/functions.md

**Comment by dschep** [comment]
What @hotgazpacho said. or a deep link straight to the relevant part of the docs: https://serverless.com/framework/docs/providers/aws/guide/functions/#layers

**Comment by dschep** [comment]
Gonna leave some extra tips here for folks...

If you publish your layer & the function using the layer in the same service, you can use refs to avoid specifying an ARN. The name is your layer name camelCased then adding `LambdaLayer`. You can always check your `.serverless/*update*.json` after `sls package` to double check the name:
```yaml
service: layer-ref-example
provider:
  name: aws
  runtime: nodejs8.10
functions:
  hello:
    handler: handler.hello
    layers:
      - {Ref: HelloLambdaLayer}
layers:
  hello:
    path: layer
```

Or, if you manage your layer and lambda in a different service (this is useful if your layer contents change way less often than your function contents. alas cloudformation will ALWAYS update a layer in a cfn stack  AFAICT):
in the layer service's `serverless.yml`:
```
service: foobar-layer
provider:
  name: aws
layers:
  foobar:
    path: layer
resources:
  Outputs:
    FoobarLayerExport:
        Value:
          Ref: FoobarLambdaLayer
        Export:
          Name: FoobarLambdaLayer
```
the function containing service's `serverless.yml`
```yaml
service: foobar
provider:
  name: aws
  language: python3.6
functions:
  hello:
    handler: handler.hello
    layers:
      - ${cf:foobar-layer-dev.FoobarLayerExport}
```

note, I use `${cf:...}` instead of `Fn::ImportValue: FoobarLambdaLayer` here because that would block the layer publishing service from pushing a new version.

**Pull request merged**
