### PR TITLE
Introduces provider.iamRoleName param.

### LINKED ISSUE #8887: Cannot specify name of default AWS IAM Role
### Use case description

Currently the default AWS IAM Role is named with a static naming convention that cannot be customized,

https://github.com/serverless/serverless/blob/61dd3bde8d17cdd995fdd27259a689d12bee1e42/lib/plugins/aws/lib/naming.js#L93-L105

It would be beneficial to many projects to provide a name (e.g. the service name and/or stage name combine to a long string, opening potential issues with the AWS Role name length limit of 64 characters. 

Allowing the name to be customized would solve the issue as reported in #4918, #2856.

Similar solutions appear to have been proposed and either disagreed on or otherwise abandoned (#7821).

### Proposed solution

Introduce a **new** configuration item `provider.iamRoleName` to allow for specifying a name other than the default generated one.

The new item would should be backwards-compatibile as it will be optional and continue to default to the existing name scheme.

### PR DESCRIPTION
**Pull request by matthewpoer**
Fixes #8887
Closes: #8887

Simple, small change introduces a new configuration parameter to address #8887 and similar issues reporting/complaining about the inability to customize the name of the default AWS IAM Role.

### CODE REVIEW

**Comment by pgrzesik** [comment]
Hello @matthewpoer, at the moment we're in the process of migrating `iam` related configuration to be grouped in `provider.role` instead of defining them directly on `provider`. Due to that, I believe it would be better to wait with this PR until this one gets merged: https://github.com/serverless/serverless/pull/8701 to avoid adding functionality that will have to be migrated to different notation very soon

**Comment by matthewpoer** [comment]
Per comment in #8887 I've rebased from master and I believe this is ready for testing and merge.

**Comment by matthewpoer** [comment]
Or, is it that `this.provider.iamRoleName` is no longer the appropriate placement of this param?

**Comment by pgrzesik** [comment]
Hello @matthewpoer - as we've migrated to grouping all `iam` related properties on `provider`, we should continue that trend with all newly introduced properties as well - in this case it seems like `provider.iam.role.name` looks like the best place - what is your opinion?

**Comment by pgrzesik** [comment]
Hello @matthewpoer - are you still interested in working on this one? As discussed above, we've migrated all IAM-related properties to be scoped under `provider.iam` - PR in current form adds a top-level property to `provider` which we would like to avoid.

**Comment by Enase** [comment]
@pgrzesik job finished here: https://github.com/serverless/serverless/pull/9166

**Comment by medikoo** [comment]
I believe it was addressed at #9166

**Pull request closed without merging**
