### PR TITLE
Persist self references with "${self:}" and restore it correctly

### LINKED ISSUE #3509: Converting circular structure to JSON when using package command with self reference
# This is a Bug Report

Refs #3344 and #3467

/cc @HyperBrain @eahefnawy 

## Description

The `serverless package` command is currently broken when using the `${self:}` serverless variable.

Use the following `serverless.yml` file to reproduce the issue with `master` by running `serverless package`

(The example is taken from https://github.com/serverless/serverless/pull/3208#pullrequestreview-24424693)

```yml
service: self-reference

provider:
  name: aws
  runtime: nodejs4.3

custom:
  newService: ${self:}
  exportName: ${self:custom.newService.service}-export

functions:
  hello:
    handler: handler.hello

resources:
  Outputs:
    selfExport:
      Value: 'A Value To Export'
      Export:
        Name: ${self:custom.exportName}
    OptExport:
      Value: 'Exported option variable'
      Export:
        Name: ${opt:}
    EnvExport:
      Value: 'Exported env variable'
      Export:
        Name: ${env:}
```

Here's the stack trace:

```
root@14c148d98242:/app/self# ../../../bin/serverless package
Serverless: Packaging service...
 
  Type Error ---------------------------------------------
 
     Converting circular structure to JSON
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Utils.writeFileSync (/app/lib/classes/Utils.js:51:23)
    at AwsPackage.saveServiceState (/app/lib/plugins/aws/package/lib/saveServiceState.js:32:27)
From previous event:
    at Object.aws:package:finalize:saveServiceState [as hook] (/app/lib/plugins/aws/package/index.js:81:10)
    at BbPromise.reduce (/app/lib/classes/PluginManager.js:234:55)
From previous event:
    at PluginManager.invoke (/app/lib/classes/PluginManager.js:234:22)
    at PluginManager.spawn (/app/lib/classes/PluginManager.js:246:17)
    at AwsPackage.BbPromise.bind.then (/app/lib/plugins/aws/package/index.js:69:51)
From previous event:
    at Object.package:finalize [as hook] (/app/lib/plugins/aws/package/index.js:69:10)
    at BbPromise.reduce (/app/lib/classes/PluginManager.js:234:55)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at PluginManager.invoke (/app/lib/classes/PluginManager.js:234:22)
    at PluginManager.run (/app/lib/classes/PluginManager.js:253:17)
    at Serverless.run (/app/lib/Serverless.js:97:31)
    at serverless.init.then (/app/bin/serverless:23:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       7.9.0
     Serverless Version: 1.11.0
```

### PR DESCRIPTION
**Pull request by HyperBrain**
## What did you implement:

This is work-in-progress!

Closes #3509

Self references created with `${self:}` are now persisted as `${self:}` and will be restored properly on state restoration.

## How did you implement it:

In `saveServiceState()` a deep search for self references is done now (the FQ property paths are extracted) and all refs are replaced with "${self:}".

## How can we verify it:

Create a service that contains

```
...
custom:
  newService: ${self:}
  ...
```

Run a package and then a deploy.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by HyperBrain** [comment]
@erikerikson The pure implementation is finished. Can you verify that it works as expected?
I will finish the PR as soon as I finished the unit tests.

**Comment by erikerikson** [comment]
@gwsii can look into this

**Comment by HyperBrain** [comment]
PR finalized
/cc @pmuens @eahefnawy

**Comment by eahefnawy** [comment]
@HyperBrain ❤️ ❤️ ❤️ ❤️

**Comment by eahefnawy** [comment]
@pmuens @HyperBrain @erikerikson I just published a patch release (v1.12.1) that includes this fix. @erikerikson please confirm that everything is now ok on your end 😊

**Comment by erikerikson** [comment]
Confirmed!  Thank you @HyperBrain @eahefnawy @pmuens!!!  You guys rock!  🎸

**Comment by pmuens** [comment]
Thanks for confirming and the warm words @erikerikson 💯

**Pull request merged**
