### PR TITLE
998 variables support stage vars

### LINKED ISSUE #998: sls variables command uses region-specific files and meta sync does not
When I use the `sls variables` command to list or set variables, it uses the file **s-variables-dev-euwest1.json** and ignores the contents of file **s-variables-dev.json**. --all does not seem to affect this, it just shows all the stages but still uses the region-specific files.

This is problematic, because `sls meta sync` only seems to synchronize the file **s-variables-dev.json** to S3.

Overall I'm confused about which files I should be using for my variables, which files should be excluded from Git, and which files `sls meta sync` is intended to synchronize.

The way that I'm currently using these files is that I exclude **s-variables-dev.json** from Git, put my secrets in it, and synchronize it with `sls meta sync`. However, that requires new team members to first create dummy files with {} as their contents, because otherwise `sls meta sync` won't recognize the stage existing.

If there is a better way to do all this, I would be very happy to hear it.

(Discussed with @HyperBrain in #985 )

### PR DESCRIPTION
**Pull request by HyperBrain**
Fixes #998 
The `sls variables xxx` type commands now support the Serverless variable hierarchy (common, stage and region). You can now easily set a variable within the specified scope.

### CODE REVIEW

**Comment by ac360** [comment]
@eahefnawy How does this look?

**Comment by eahefnawy** [comment]
It's better UX for sure for the `sls variables` commands ... I like it! Thanks tons @HyperBrain 😊 

It's also a pretty safe change since it's only dealing with the variables action files

**Comment by HyperBrain** [comment]
A further improvement would be to disallow deletion of critical variables from common, like the project name, the stack name or the Lambda role name. We could create an additional issue (enhancement) for that.

**Comment by eahefnawy** [comment]
yeah, but some people like to hack around and change that stuff, which is cool...I think @erikerikson likes to do that 😄

**Comment by erikerikson** [comment]
That's right @eahefnawy.  :)

We could ignore those variables in the project output (not sure how they would be created in the first place) but this decision appears to proxy whether SLS will prescribe the shape of resources and their creation.  The problem is that if guaranteed to be there, the system will be increasingly built around those assumptions and that will make its value more narrow over time.  I think it is better that the "default happy path" that enables project onboarding is only an instance implementation of the generalized provisioning pattern instead of an enforced implementation.

In the case of https://github.com/serverless/serverless/issues/910 we are actually blocked from being able to use the SLS resource commands.  Hmm... maybe that's only true with a no really crufty cruftiness constraint (I may have just dreamed up an untested workaround).  Don't really want to take that course.

**Pull request merged**
