### PR TITLE
fix(Packaging): Avoid duplicated includes when using non-normalized p…

### PR DESCRIPTION
**Pull request by juanjoDiaz**
…aths

Closes: #6164
Closes: https://github.com/UnitedIncome/serverless-python-requirements/issues/365

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
@juanjoDiaz Thanks for looking into that. Still I think we already ensure to package normalized paths (free of duplicates). It was covered with https://github.com/serverless/serverless/pull/6705

And https://github.com/serverless/serverless/issues/6164 simply was overlooked and left open (I've just closed it). Sorry for confusion it raised

**Comment by juanjoDiaz** [comment]
Damn!

I still think that removing duplicated when resolving the path is more correct than doing it when zipping.

So I'd keep it here and remove it from zipService.
Or even keep it in both if you wanna be extra-safe.

Let me know what you think. Feel free to close if you disagree 🙂

**Comment by medikoo** [comment]
> I still think that removing duplicated when resolving the path is more correct than doing it when zipping.

To be honest, I think it's solved the right way now. Ensuring no duplicates right before feeding zip archive seems most solid approach.

Now, introducing deduplication in other places, with above in place, brings no changes, and just adds maintenance cost

**Comment by medikoo** [comment]
@juanjoDiaz great thanks for looking into that! Still as discussed I believe there's currently no issue in a Framework that this PR was attempting to solve

**Pull request closed without merging**
