### PR TITLE
Download templates from a Bitbucket Server

### PR DESCRIPTION
**Pull request by taktakpeops**
## What did you implement:

Allow the usage of templates hosted in a Bitbucket Server for creating a new Serverless service.
The authentication is managed using Basic Authentication as what was done for GitHub.

## How did you implement it:

In case a given URL do not refer to the already defined providers (GitHub, (public) Bitbucket, Gitlab), we try to fetch `/rest/api/1.0/application-properties` from the server. This endpoint in the Bitbucket Server Rest-API do not require any authentication. In case the response contains a property called `displayName` set to `Bitbucket`, we fulfill `repoInformation` with the data extracted from the URL for the Bitbucket Server. 

## How can we verify it:

Run unit-tests
Locally, check-out this branch. Create a repository with a Serverless template in a repository on your Bitbucket Server then run `serverless create -p test --template-url https://myname:mypass@myserver.com/rest/api/latest/projects/MY-PROJECT/repos/MY-REPO/archive?at=refs%2Fheads%2FsomeBranch

## Todos:

_**Note: Run `npm run test-ci` to run all validation checks on proposed changes**_

- [X] Write tests and confirm existing functionality is not broken.  
       **Validate via `npm test`**
- [ ] Write documentation
- [X] Ensure there are no lint errors.  
       **Validate via `npm run lint-updated`**  
       _Note: Some reported issues can be automatically fixed by running `npm run lint:fix`_
- [x] Ensure introduced changes match Prettier formatting.  
       **Validate via `npm run prettier-check-updated`**  
       _Note: All reported issues can be automatically fixed by running `npm run prettify-updated`_
- [ ] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

**_Is this ready for review?:_** NO  
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by taktakpeops** [comment]
Hello,

I will add the documentation soon.

**Comment by pmuens** [comment]
> I will add the documentation soon.

Thanks! Let us know if you need any help here :+1:

**Comment by taktakpeops** [comment]
I added the documentation in the `create.md` file. Is it the right place?

Also, I noticed that currently in the `create` command we specify only `GitHub, BitBucket` as providers but Gitlab is also supported.

Last one, in the `downloadTemplateFromRepo.js` file, the function `parseGitlabURL` calls `validateUrl` with `Bitbucket` as third parameter - is it normal?

**Comment by taktakpeops** [comment]
Hello @pmuens - thank you for the update of the PR. Regarding a public Bitbucket URL, I don't have that unfortunately.

**Comment by taktakpeops** [comment]
Hello @pmuens - thank you for the approval and the merge. When will the 1.52 be released?

**Pull request merged**
