### PR TITLE
Remove postinstall completely

### LINKED ISSUE #4069: Add separate command for completion install/uninstall (was: npm install mucks with preferences silently)
I've got my home directory in git so I noticed something that I perceived to be wildly bad manners. When I `npm install -g serverless` it makes global changes to my `.zshrc` without asking. My rc file is configured for multiple machines and tailored to my needs, as I think it is for many people -- having things haphazardly add themselves to it without my control feels invasive, IMHO\*

The culprit lines of code that caused this are:
https://github.com/serverless/serverless/blob/66f019b1f36af41dd067ac598244e97f98e1ead8/scripts/postinstall.js#L30-L31

The use of tabtab's `--auto` flag is what I think is damaging. In auto mode, tabtab doesn't place a standalone file in the completions folder for bash/zsh, it just haphazardly dumps code into the rc file.

Maybe I'm being overly sensitive about packages changing files outside of their scope in stateful manners and convenience is king. I just wanted to start a discussion about this to see if this was a valid concern or if I should continue "being weird" and write protecting my zshrc so that `npm install` doesn't mess with it.

### PR DESCRIPTION
**Pull request by axelson**
## What did you implement:

Closes #4069

## How did you implement it:

Removed the postinstall hook and all references to it

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** Yes
***Is it a breaking change?:*** No

### CODE REVIEW

**Comment by Gerst20051** [comment]
Thanks for taking the time to create a pull request! Hope to see some progress on this issue soon!

**Comment by cornfeedhobo** [comment]
You, sir, are a gentleman, and a scholar. Thank you for taking this on!

**Comment by pmuens** [comment]
Hey @axelson thanks again for taking the time to work on this 👍

Are there any updates? Do you need any help here?

**Comment by cornfeedhobo** [comment]
I hope this doesn't get lost in time. It's almost been a year waiting on this.

**Pull request closed without merging**
