### PR TITLE
Added ability to add S3 deployment resource tags

### PR DESCRIPTION
**Pull request by Vol4Life27**
## What did you implement:
Ability to add tags to the AWS S3 deployment resources created by serverless
for https://github.com/serverless/serverless/issues/3817

## How did you implement it:
Added function to uploadArtifacts.js to check for existence of `tags` key on `deploymentBucket` object, and if so, loop through all the tags and create a url encoded string to add to S3 upload object that will be added to each deployed resource item

## How can we verify it:
Add the `tags` key to `deploymentBucket` as shown in the updated docs, then run the deploy command, and check if deployed resources have the specified tags in S3

## Todos:

- [X] Write tests
- [X] Write documentation
- [X] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by mrrobot-anonymous** [comment]
Looks like something stalled on last step of the build. It needs to be reran and should be good to go

**Comment by str3tch** [comment]
looking forward to getting this in. I'm getting nasty emails about s3 tagging on sls buckets from the policy enforcers in the enterprise I am working in.

**Comment by rts-cwalker** [comment]
Sure. Ill go and try to make it match. Considering its been a while since i submitted this, ill have to refresh myself on what i did so i can make the changes and get tests to pass. But ill try to get this done in the next few days

**Comment by Vol4Life27** [comment]
Sorry. posted from wrong account. :) 

But ill try to get to this in the next few days. Will have to refresh myself on a few things which make add  a little extra time. :)

**Comment by pmuens** [comment]
Hey @Vol4Life27 👋

Hope you're doing good! Just want to follow-up here. Do you need any help? Should I move forward with your PR so that we can merge it soon?

**Comment by Vol4Life27** [comment]
@pmuens I think i have gotten the builds passing with new updated structure. Let me know if anything else needs to be updated

**Comment by pmuens** [comment]
> @pmuens I think i have gotten the builds passing with new updated structure. Let me know if anything else needs to be updated

Great! Thanks for the updates and taking the time to work on this @Vol4Life27 👍

I'll review it ASAP!

**Pull request merged**
