### PR TITLE
Provider property can be an object

### PR DESCRIPTION
**Pull request by eahefnawy**
Allows for `provider` property to be an object to hold provider specific config as discussed in [Issue 1567](https://github.com/serverless/serverless/issues/1567)

### CODE REVIEW

**Comment by flomotlik** [comment]
LGTM from my side. @pmuens if ok for you please merge

**Comment by pmuens** [comment]
Looks good so far bit isn't there a need to update the templates as well?

**Comment by eahefnawy** [comment]
@pmuens we still support string syntax for provider property `provider: aws`. So the templates work as they are.

**Comment by pmuens** [comment]
Awesome! 🎉

**Comment by eahefnawy** [comment]
hahaha yep

**Pull request merged**
