### PR TITLE
Update event-sources.md

### PR DESCRIPTION
**Pull request by jobechoi**
Pull Request Template ------------------------
* Check out our Pull Request Guidelines here: https://github.com/serverless/serverless/blob/v1.0/CONTRIBUTING.md

##### Status:

Ready/In Development/Hold

##### Todos:

- [ ] Write tests

- added process steps required for AWS API Gateway

### CODE REVIEW

**Comment by jobechoi** [comment]
Now that I'm reviewing other sections of the guide, I'm unsure if my edits were required because of skipping the VPC object definition prior to deploying.

**Comment by eahefnawy** [comment]
@jobechoi one of the advantages of the framework is to create the APIG for you and not having to do it manually. Any reason why you're doing it manually?

Either way, putting docs on how to create APIG manually is beyond the scope of our docs imo :)

**Comment by jobechoi** [comment]
Chalk it up to 1) being a noob, and 2) learning by doing. 

Does that mean had I defined the vpc object in serverless.yaml first, when I called serverless deploy, the API gateway would have been created by that command?

**Comment by jobechoi** [comment]
@eahefnawy the main reason I added the section on creating the API gateway on AWS is because the section "Calling our HTTP endpoint" does not present as written for AWS accounts that have no current gateways defined.

**Comment by pmuens** [comment]
Hey @jobechoi thanks for your feedback! You could simply use the `events` definition for your function as shown here: https://github.com/serverless/serverless/blob/master/docs/guide/event-sources.md#adding-a-http-event

There's no need to set this up manually.

**Comment by jobechoi** [comment]
@pmuens thanks. Checked that more than once. 
Here's my serverless.yaml that I'm deploying:
serverless

and here's what I see when I go to the API Gateway in AWS:
aws api gateway

**Comment by pmuens** [comment]
Aaah. Thanks @jobechoi 

The problem is the YAML indentation in this case (mixture of 4 level indentation and 2 level indentation).

```yml
functions:
    hello:
        handler: handler.hello
        events:
          - http:
            path: greet
            method: get
```

translates to:

``json
{
  "functions": {
    "hello": {
      "handler": "handler.hello",
      "events": [
        {
          "http": null,
          "path": "greet",
          "method": "get"
        }
      ]
    }
  }
}
```

But if you use this:

```yml
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: greet
          method: get
```

you'll get this:

```json
{
  "functions": {
    "hello": {
      "handler": "handler.hello",
      "events": [
        {
          "http": {
            "path": "greet",
            "method": "get"
          }
        }
      ]
    }
  }
}
```

We've recently switched to 2 level deep indentation which is kind of an industry standard...

**Comment by pmuens** [comment]
@jobechoi could you remove the hash in the URL in your console window (maybe there's something like `#getting-started` or `#welcome`) and refresh the page with the URL without the hash?

Your syntax definition looks correct...

**Comment by jobechoi** [comment]
@pmuens Thanks for clearing that up. 

Is that really 2-space indents?
Seems there are 4 spaces from the `-` on the line following `- http:`

**Comment by pmuens** [comment]
@jobechoi yep looked into it. My first comment (which I've removed right after posting it) was wrong. The indentation is correct (although I'd use 2 spaces from now on as we've also switched to 2 spaces recently).

Have you tried to remove the hash in the URL and reloaded the page?

**Comment by flomotlik** [comment]
I looked over the PR and at the moment I don't want to add additional configuration for creating API Gateways manually. If people set up API Gateway manually and want to connect it to Serverless they would have already gone through setting it up beforehand, if they don't have APIG deployed they can use our integrated API Gateway support.

Thanks for bringing this up @jobechoi

**Pull request closed without merging**
