### PR TITLE
Add Tests for resolveFilePathsFromPatterns()

### PR DESCRIPTION
**Pull request by kdnakt**
## What did you implement

Added some tests for packageService#resolveFilePathsFromPatterns().

## How can we verify it

Just `$(npm bin)/mocha ./lib/plugins/package/lib/packageService.test.js`

or `npm test` would do.

## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test-ci` --> Run all validation checks on proposed changes
- `npm run lint-updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check-updated` --> Check if updated files adhere to Prettier config
- `npm run prettify-updated` --> Prettify all the updated files

</details>

- [x] Write and run all tests
- [x] Write documentation
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by medikoo** [comment]
> Most of our other tests create such an isolated service directory in tmp. What do you think @medikoo ?

I'm honestly a bit on the fence, as yes it's true that in many test files the convention is to setup playground in provisioned temp directory, an it'll be good to follow that convention.

But on the other note, I see value  fixtures committed into repo, as then it's probably a bit easier to reason about tests (we can easily inspect the fixture, while it's not as straightforward when we look into code which generates it).

We also already have some fixtures made e.g. in interactive CLI case: https://github.com/serverless/serverless/tree/3fcd05e4a78e258ceab9d75718e9099becb7f23e/lib/plugins/interactiveCli/test/fixtures

In case of this PR, I would either align to @pmuens  suggestion (so work with temp dir), or create a fixture that matches convention of other fixtures we already have (So it's in `test/fixtures/service` folder)

_A side note: one problem with fixtures right now is, that they'd be published with a package (it might be good to consider moving out all tests to dedicated `test` directory, but it's ofc not in a scope of this PR)._

Other important note @kdnakt, recently we put more value into integration tests, and we have one that should cover what you're after here: https://github.com/serverless/serverless/blob/master/tests/integration-package/lambda-files.tests.js (if they do not cover such cases, it'll be good that update is done there).
Integration tests allow us to focus more on the real outcome, than how our internals are constructed (which is always subject to changes, e.g. packaging is scheduled to have a significant refactor with: https://github.com/serverless/serverless/issues/6580 - and it might be that with that `resolveFilePathsFromPatterns()` function will be gone)

**Comment by kdnakt** [comment]
Thanks for the review, I'll fix this as suggested, with temp dir or using existing fixture to match the convention.

But before moving on, is it better to close this PR because significant refactoring might remove the tested function?

**Comment by pmuens** [comment]
> Thanks for the review, I'll fix this as suggested, with temp dir or using existing fixture to match the convention.

Thanks for taking the time to continue the work on this PR @kdnakt 👍

> But before moving on, is it better to close this PR because significant refactoring might remove the tested function?

I think it should be ok to use this PR. Just add your commits and we should be good as we see the diff and therefore the changes you made. Let us know if you need any help here.

**Comment by kdnakt** [comment]
Hi, sorry for being late. I removed the dummy files and used temporary files for test.

**Comment by pmuens** [comment]
> It appears new tests fail on Windows.

That happened right after I updated the RP with [this commit](https://github.com/serverless/serverless/pull/6825/commits/f76a2d83648473cc2c53a6ea36a3b01c681d7308). Apparently we change the file paths back again if we are on Windows (see [here](https://github.com/serverless/serverless/blob/9501e6556fb2433b068f80de3dcdeb50b3c7c1b0/lib/plugins/package/lib/packageService.js#L256)). I've pushed a fix for the tests via [this commit](https://github.com/serverless/serverless/pull/6825/commits/5372117607ccb4bafe1069643a3b0da55fd31f60).

**Pull request merged**
