### PR TITLE
allow to define custom variables from within the endpoint template. T…

### PR DESCRIPTION
**Pull request by olado**
…his allows to insert custom parameters into reusable mapping templates

For example, i am reusing the same lambda function for multiple endpoints.
In AWS Gateway in my body mapping template I define a property that gets different values for each endpoint that goes to the same Lambda.

To have this logic with serverless, I need a way to define these custom variables from inside of the s-function. This is what this PR implements.

Example:
```
"endpoints": [
 {  ....
      "customVars": {
        "myparam": "myvalue"
      },
      "requestTemplates": "$${apiRequestTemplate}",
}]
```

In the template s-templates.yaml:
```
"params": {
    "type": "${myparam}",
    #foreach($param in $input.params().path.keySet())
    "$param": "$util.escapeJavaScript($input.params().path.get($param))"
    #if($foreach.hasNext),#end
    #end
}
```

### CODE REVIEW

**Comment by ac360** [comment]
Thanks @olado!  We'll review this shortly :)

**Comment by eahefnawy** [comment]
@olado Thanks for putting this together. However, I'm sort of on the fence with merging this one. For these two reasons:

- You're defining the value of your variable in `s-function.json`, this is something we highly discourage since the whole point of our variable system is to protect sensitive information and to be hidden from version control. Config reuse is a second priority for variables and we recommend using templates instead.
- I think this won't only affect endpoint data, but rather *any* data that we we try to populate. We'll have the `customVars` property reserved for any data we pass even if the user don't need it.

Generally what you're trying to accomplish can still be accomplished with the current variables system, however I do realize it'll be a bit messy since you'll have to define a new variable for each of your endpoints. But I'd go that route over exposing my variables publicly.

Just my two cents 😊

**Comment by HyperBrain** [comment]
I think the idea of having the possibility to define endpoint variables in general is useful. If you implement your lambdas as _micro routers_ that are bound to multiple endpoints and select their sub functionality by a special property, but use all other input parameters in common, this save you a lot of time copy-pasting templates.
However, Including it directly into endpoint definitions and `s-function.json` doesn't seem an optimal solution to me, for the reasons @eahefnawy mentioned above.

I'd rather see that as an additional *variables sub-scope* functionality that could be added to the `serverless variables` command by specifying `--type endpoint` as additional variable type (whether it would be stored in common or stage had to be discussed). Then the concerns about sensitive data would be obsolete.

We even could let the variables command add an `endpoints` object to the variables, where the variables defined per endpoint would be stored:
```
  ...
  "endpoints": {
    "myEndpoint1~POST": [ { "var1": "val1" }, ... ],
    "myEndpoint1~GET": [ ... ]
    "myEndpoint2~*": [ ... ]      // * would apply to all methods
  }
  ...
```

What do you think?

**Comment by olado** [comment]
Thanks for the review. Answering to the points:
1. The variables do not have to be sensitive, these are more like parameters to the templates.
For sensitive values, you could use your sensitive variables in customVars: { "mySenstiiveKey": "{$smthSentisitve}" } instead of defining them right in there.
Alternatively,  you could have parameterized templates (for example my doT supports passing parameters into the template).
2. I don't see how this can be achieved without defining multiple templates, could you please provide an example?

**Comment by olado** [comment]
@HyperBrain thanks for validating the use case!
I do not know all the details about current variable system but from my understanding these are global variables (per project/stage) and are excluded from source control.
Most of endpoint use cases would not have sensitive info and would be local in nature. It would be better to have endpoint definition contained in one place. For sensitive info these parameters could use variables instead of defining them in place like I mentioned in the previous post.
Unrelated to this PR, but maybe it would be good to have separate global variable sets, sensitive variables set that is excluded from source control and non-sensitive variables set that is included.

**Comment by eahefnawy** [comment]
@olado The non sensitive variables are what we call templates. You can have a single template file which contains a separate template for each endpoint. This is of course a lot of duplication and it can get messy really easy.

I do understand your issue though, and it is indeed worth investigating, just not sure the way we're solving it right now is the best way.

**Comment by olado** [comment]
Thanks, is there a solution for this use case in the repo? 
I am still using my custom code and would like to use the official serverless.

**Comment by flomotlik** [comment]
Hi, thanks for the contribution, but we've stopped working on 0.5 of Serverless at this point to fully focus on the next release with V1 that we're currently working on. Therefore we're not taking any commits for 0.5 and do not plan any future releases at this point and I'm closing this PR. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Pull request closed without merging**
