### PR TITLE
V0.5 ProviderAws test class & credential loading tests

### PR DESCRIPTION
**Pull request by erikerikson**
1. Add missing test class for the ProviderAws class.
2. Add that test class to the "all" tests script
3. Added unit tests for verifying all the credential loading mechanisms recently added to ProviderAws.  Currently, this doesn't test the cases where session_token is not defined in profiles, the overriding of credentials from those sources, or any of the other ProviderAws functionality.

### CODE REVIEW

**Comment by erikerikson** [comment]
@ac360 these are unit tests I failed to add with the credential clean up branch.

**Comment by ac360** [comment]
:+1: Awesome work, @erikerikson!!

**Comment by erikerikson** [comment]
Thanks @ac360.  In that case, it might be worth merging!  ;)

Let me know if you'd like any problems you'd like addressed.

**Comment by ac360** [comment]
Going to merge this in soon!  Distracted by a few other things ATM.

**Comment by erikerikson** [comment]
:)

**Comment by erikerikson** [comment]
Hmm...  You didn't want tests for the provider?

**Comment by erikerikson** [comment]
@ac360 did you really mean to close this without merging?  Do you want it to retarget master?  Something else?

**Comment by ac360** [comment]
@erikerikson Thanks for looking out.  This was not intended to be closed.  Not sure what I was doing when I accidentally closed it :\

**Comment by erikerikson** [comment]
@ac360 it can be merged once more.  Note that this is still on the v0.5 branch.  Shall I open a separate PR to add it to master?

**Comment by ac360** [comment]
@erikerikson Yes please.  Could you retarget this to the master branch?

**Comment by erikerikson** [comment]
This PR has been retargeted to master in PR https://github.com/serverless/serverless/pull/933.

**Pull request closed without merging**
