### PR TITLE
Document that variable refs aren't resolved at plugin constructor exe…

### PR DESCRIPTION
**Pull request by dschep**
…cution time

## What did you implement:

Documented some plugin API behavior that surprised me (it changed in v1.13 IIRC) and [another user](http://forum.serverless.com/t/serverless-plugin-resolving-variable-references/2233)

## How did you implement it:
I wrote some docs.

## How can we verify it:
n/a?

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by tommedema** [comment]
@dschep @pmuens this doesn't work for cloudformation references. For example, my plugin:

```
const util = require('util')

class Test {
  constructor(serverless) {
    // members
    this.serverless = serverless
    this.provider = this.serverless.getProvider('aws')
    
    // bindings
    this.log = this.log.bind(this)
    this.main = this.main.bind(this)
    
    // hooks
    this.hooks = {
      'after:aws:package:finalize:mergeCustomProviderResources': this.main
    }
  }
  
  main() {
    this.log(util.inspect(this.serverless.service.custom))
  }
  
  log(msg) {
    this.serverless.cli.log(`!!! TEST: ${msg}`)
  }
}

module.exports = Test
```

And serverless.yml:

```
custom:
  someVar:
    Ref: CognitoUserPool
```

it outputs:

```
Serverless: !!! TEST: { someVar: { Ref: 'CognitoUserPool' },
```

**Comment by HyperBrain** [comment]
@tommedema What exactly do you expect to happen here? Imo the output is correct, as it prints the content of custom.someVar correctly.
The `Ref:` inside the variable is a native CF reference and will be dereferenced by CloudFormation at deployment time. If you wanted to get the logical id of the user pool contained in the stack, there is currently no way to achieve that, but by inspecting the CF template in `.serverless` after a ` serverless package`. That problem is addressed by #4542 .

**Comment by tommedema** [comment]
@HyperBrain then why doesn't this print the content "correctly"?

_serverless.yml_
```
provider:
  environment:
    someVar:
      Ref: CognitoUserPool
```

This prints the ID of the CognitoUserPool; as expected.

The codebase should be consistent. If `Ref:` is looked up here and passed as an environment variable (the value, not the `Ref` statement itself), this should also happen elsewhere, such as in `custom`.

**Comment by HyperBrain** [comment]
The environment is resolved _during_ deployment by CloudFormation, so in your deployed function the variable is present. This is standard CF behavior. Ref and GetAtt are never resolved locally, because they are CF functions. These references behave exactly as documented on AWS. Even if someone is new to serverless, he should have a basic understanding of AWS and CloudFormation - maybe that could be added to the docs somewhere, so that one first knows how CloudFormation works.

If you want to resolve CF references, you should do that in a plugin. This resolution is not trivial, if not impossible. In the case, the service has not been deployed yet, you won't be to resolve them at all. If the service is deployed already, you only can be sure about the final resolved values after deploying it - you can hardly predict, what the value will be - only for the most trivial lookups.

Yes, #4542 is about using the logical ids within the service. This is helpful, because some of the logical ids have to be created with random names, because CloudFormation demands that it is changed from deployment to deployment for some resources (e.g. AWS::ApiGateway::Deployment or AWS::Lambda::Version) - otherwise nothing will happen.

**Comment by HyperBrain** [comment]
An approach to have ids resolved locally is, to put service resources into a separated stack (e.g. dynamo tables, etc.) and expose their dereferenced attributes via output variables.

Then you can use `${cf:the-resource-stack.the-output-var}` to do a local resolution. In contrast to CF's `Fn::ImportValue` this does not create a dependency nor does it protect the other stack from being removed.

In case you have your service already deployed there are plugins like the `serverless-export-env` plugin which can retrieve and resolve the actual CF variables, so that they are available in a `serverless invoke local` or `serverless offline` call - that makes testing a bit easier with CF references.

**Pull request merged**
