### PR TITLE
Fix #7149 <WSS> Use AWS partition pseudo param

### LINKED ISSUE #7149: Please do not hard code ARN partition for websocket
# Bug Report

## Description

I am using aws china, where I set iamRoleStatement as 
```
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws-cn:execute-api:*:*:**/@connections/*"
```
 however, serverless always add an extra policy as
```
{
  "Effect": "Allow",
  "Action": [
    "execute-api:ManageConnections"
  ],
  "Resource": [
    "arn:aws:execute-api:*:*:*/@connections/*"
  ]
}
```
when I do the deployment, it reports
`ServerlessError: Stack:arn:aws-cn:cloudformation:cn-northwest-1:xxxx is in ROLLBACK_COMPLETE state and can not be updated.`

as I can search in the repository, this line may the cause
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/websockets/lib/api.js#L42

- #12345

### PR DESCRIPTION
**Pull request by austinjalexander**
## What did you implement?

During [`compileApi`](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/websockets/lib/api.js#L7), the websockets AWS policy generated currently assumes the standard 'aws' partition (see [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/websockets/lib/api.js#L42)). This PR replaces 'aws' with the `AWS::Partition` pseudo parameter.

Closes #7149

## How can we verify it?

A new websockets service using a non-standard region; for example:
```yml
service: api
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

  stage: production
  region: us-gov-west-1
...
```

Will result in something like the following error:
```shell
Serverless: Packaging service...
Serverless: Excluding development dependencies...
...
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_FAILED - AWS::IAM::Role - IamRoleLambdaExecution
...
Serverless: Operation failed!
...
An error occurred: IamRoleLambdaExecution - Partition "aws" is not valid for resource "arn:aws:execute-api:*:*:*/@connections/*". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument...
...
```

Using the changes in this PR, while deploying in a non-standard partition (e.g., 'aws-us-gov'), will result in success!  :)

## Prior Art

- https://github.com/serverless/serverless/pull/7175

## Resources

- [AWS::Partition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-partition)

## Todos

- [x] Write and run all tests
- [ ] Write documentation
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by austinjalexander** [comment]
@medikoo It looks like Travis errored out; would you mind re-running, please?

**Comment by medikoo** [comment]
@austinjalexander thanks for update. It looks way better!

Concerning CI fails, it looks that npm went nuts (issue we didn't see before got exposed).

To have that fixed I needed to update our CI configuration in master, therefore when you update your branch with master issue will be resolved.

**Comment by austinjalexander** [comment]
Fantastic! Thank you, @medikoo!  😄

**Comment by medikoo** [comment]
@austinjalexander I've updated your branch automatically with master, and still one CI issue got exposed. 
Can you ensure changes follow Prettier formatting? You can easily fix it by running `npm run prettify:updated`

**Comment by austinjalexander** [comment]
@medikoo All set!  :)

**Comment by austinjalexander** [comment]
Thank you for taking such swift action, @medikoo!

**Pull request merged**
