### PR TITLE
Release v3.18.2

### PR DESCRIPTION
**Pull request by pgrzesik**

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
@pgrzesik is there a chance we can also take: https://github.com/serverless/serverless/pull/11106 ?

**Comment by pgrzesik** [comment]
Sure @medikoo - is it ready for a review?

**Comment by medikoo** [comment]
> Sure @medikoo - is it ready for a review?

Yes (sorry just assigned you)

**Review by medikoo — APPROVED** [review]
👍

**Pull request merged**
