### PR TITLE
Add apig resource policy

### LINKED ISSUE #4926: API Gateway Resource Policy Support Feature
# This is a Feature Proposal

## Description
Recently API Gateway (April 2nd, 2018) started providing resource policy to handle each API. Which includes blacklisting IP or allowing denying IP.

This is currently only supported by the API Gateway API, AWS console, AWS SDK and not yet by CloudFormation, which I'm guessing is why it is not yet supported by Serverless. 

[Announcement](https://aws.amazon.com/about-aws/whats-new/2018/04/amazon-api-gateway-supports-resource-policies/)

[Blog for console-based setup](https://lobster1234.github.io/2018/04/14/amazon-api-gateway-ip-whitelisting/)

Probably best to wait for CloudFormation to catch up on this so I'm just registering for a future task.

For feature proposals:
* IP Blacklisting or allowing a certain type of method. Basically IAM type policy but without creating IAM role/policy.
* Json input or parameter based information can be set up.  

Note
** [Forum Question in relation](https://forum.serverless.com/t/api-gateway-resource-policy/4215
)

### PR DESCRIPTION
**Pull request by laardee**
## What did you implement:

Closes #4926

## How did you implement it:

Resource policy document is added to the provider block of the serverless.yml.

## How can we verify it:

Example provider block in serverless.yml that whitelists IP 123.123.123.123, replace the dummy IP address with yours to test.

```yml
service: aws-nodejs-1 # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10

  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        IpAddress:
          aws:SourceIp:
            - "123.123.123.123"
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by dailyherold** [comment]
Greetings @laardee  and others, I added a [comment](https://github.com/serverless/serverless/issues/4926#issuecomment-400895899) to #4926 and thought about the following requirement from AWS regarding attachment of resource policies:
> If you attach a resource policy to a deployed API, or if you update an existing resource policy, you'll need to redeploy the API for the changes to take effect. ([doc](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-resource-policies-create-attach.html))

Should/can serverless _know_ whether a resource policy has been applied to an existing stack or not? If so should serverless know to redeploy?

**Comment by laardee** [comment]
@dailyherold  Hi, good question. Serverless creates an `AWS::ApiGateway::Deployment`  resource with a different logical id every time the CloudFormation stack is generated, which means that new deployment is done on every `serverless deploy`. 
However, If you have an existing API Gateway that you are using ([share-api-gateway-and-api-resources](https://serverless.com/framework/docs/providers/aws/events/apigateway/#share-api-gateway-and-api-resources)), settings like this, and for example, `endpointType` won't affect at all. They need to be set in the original API Gateway configuration.

**Comment by densbozz** [comment]
hello,
good day. we are getting this error when 1.28 was released.

An error occurred: ApiGatewayDeployment1530701418990 - No integration defined for method (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: d70a7552-7f78-11e8-b9db-1b2e839033ef).

Anyone have resolution? we tried specifying in our buildspec.yml to specific version 1.27. but still getting the error.

**Comment by rahulmparikh** [comment]
I tried. But it doesn't work. 

I am basically trying to create an api to invoke lambda function over http and I would like to restrict my api to my personal public ip. I am still new to CF. Any help would be highly appreciated. 

`  IAMAwsInfoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName:  XXXXX
      Handler: handler.main
      AutoPublishAlias: !Ref aliasName
      Runtime: python3.6
      CodeUri: XXXXXXXX
      Role: !GetAtt LambdaIAMRole.Arn
      Timeout: 30
      Events:
          GetApi:
              Type: Api 
              Properties:
                  Path: /get
                  Method: get
                  RestApiId: 
                    Ref: TestApi
      DeploymentPreference:
        Type: AllAtOnce

TestApi:
    Type: AWS::Serverless::Api
    Properties:  
        StageName: nonprod
        DefinitionBody:
            swagger: 2.0
            info:
              title:
                Ref: AWS::StackName
            paths:
              "/get":
                get:
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IAMAwsInfoLambda.Arn}/invocations
                  responses: {}`

**Comment by rojosnow** [comment]
@laardee First, thanks for adding this functionality! 

While your example above is technically accurate, there is another situation that people need to understand.

Let's say I have an endpoint with the following methods: `GET`, `POST`, `PUT`, `DELETE`, and `OPTIONS`. It would be accurate to write a resource policy like the following to restrict all state changes on the endpoint by IP address.

```
provider:
  name: aws
  runtime: nodejs8.10
  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/POST/*
        - execute-api:/*/PUT/*
        - execute-api:/*/DELETE/*
      Condition:
        IpAddress:
          aws:SourceIp:
            - "123.123.123.123"
```

You might assume that the`GET` and `OPTIONS` methods continue to work as normal while the other methods are restricted by IP address. Not so. you will get `"Message": "User: anonymous is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:us-east-1:********5212:lb10q2lyn8/dev/GET/contracts"` for every method.

In my testing, it appears that once you specify any `Resource` with a `Condition`, you then need to specify the remaining `Resource`s without a `Condition`. It feels like once the `Condition` engine turns on, it actually applies to everything unless you specify which methods you don't want it to apply to. This is not documented. It might have something to do with the overall `Effect` functionality too. I didn't have time to check.

Also, it's tempting to start to look for an IAM solution due to the message. It's not the issue and it adds complexity where none is needed. After all, I don't care who reads...I only care who (what) writes. What I found to work, by trial and error, was the following:

```
provider:
  name: aws
  runtime: nodejs8.10
  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/GET/*
        - execute-api:/*/OPTIONS/*
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/POST/*
        - execute-api:/*/PUT/*
        - execute-api:/*/DELETE/*
      Condition:
        IpAddress:
          aws:SourceIp:
            - "123.123.123.123"
```

So, no `Condition` on the `Resource`s I want anybody to access and restrict the other `Resource`s with a `Condition` by IP address.

If anybody has another solution, I'd love to see it since my solution would be documented if this was the intended behavior. I searched high and low but could not find any solutions on this issue...other than people going down the IAM route.

**Pull request merged**
