### PR TITLE
Add support in Spotinst Functions

### PR DESCRIPTION
**Pull request by guyklainer**
added 2 new templates - spotinst-nodejs, spotinst-python

## What did you implement:
Add support for Spotinst Functions

## How did you implement it:
I've added 2 new templates: spotinst-nodejs, spotinst-python to the 'templates/' folders,
and updated the array in create.js

## How can we verify it:
tests/templates/integration-test-template spotinst-nodejs
tests/templates/integration-test-template spotinst-python

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by pmuens** [comment]
Great! Thanks for the update @guyklainer 👍

We'll review it again ASAP so that we can merge soon! 💯

**Comment by guyklainer** [comment]
Actually, I want to make few changes in the serverless.yml templates. 
So I need one more day. :)

**Comment by pmuens** [comment]
> Actually, I want to make few changes in the serverless.yml templates.
> So I need one more day. :)

Gotcha. Thanks for the update @guyklainer 👍

**Comment by pmuens** [comment]
Hey @guyklainer! Thanks for the recent updates 👍!

Is this ready for a review?

**Comment by guyklainer** [comment]
Yes, it's ready.
Thanks!

**Comment by pmuens** [comment]
> Yes, it's ready.
> Thanks!

Thanks for the update @guyklainer 👍

We'll take a final look at it ASAP!

**Comment by guyklainer** [comment]
Great!
💪 💪 
Thanks!!

**Pull request merged**
