### PR TITLE
Use common prefix for log groups permissions at Lambdas' execution roles

### LINKED ISSUE #2508: Maximum policy size of 10240 bytes exceeded for role
# This is a Bug Report
### What went wrong?

I tried to deploy a function that listens to 50+ DynamoDB streams. The deploy hung for around 5-10min before eventually failing.
### What did you expect should have happened?

The function should have deployed without any errors.
### What was the config you used?

``` yml
service: ddb-backup

provider:
  name: aws
  runtime: nodejs4.3

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource:
        - "arn:aws:s3:::my-bucket/backups/dynamodb/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:DescribeStream"
        - "dynamodb:ListStreams"
      Resource:
        - "*"

functions:

  backup:
    description: "Backs up DynamoDB records to S3 when modified."
    handler: handler.default
    events:
      - stream: arn:aws:dynamodb:us-east-1:***:table/table-1/stream/2016-01-01T00:00:00.000
      - stream: arn:aws:dynamodb:us-east-1:***:table/table-2/stream/2016-01-01T00:00:00.000
      # ... 50+ more stream events ...
```
### What stacktrace or error message from your provider did you see?

Console output:

```
CloudFormation - UPDATE_FAILED - AWS::IAM::Policy - IamPolicyLambdaExecution
```

CloudFormation output in AWS console:

```
Maximum policy size of 10240 bytes exceeded for role ddb-backup-prod-IamRoleLambdaExecution-ASDF1234
```
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.3
- **_Operating System**_: OSX 10.11.6

I was able to deploy the function after commenting out most of the event stream mappings. I then had a look at the IAM profile CloudFormation was complaining about. This is when I noticed that Serverless adds it's own policy statements... One for each event source mapping. The end result looks something like this:

``` json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:us-east-1:*:*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket/backups/dynamodb/*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator",
                "dynamodb:DescribeStream",
                "dynamodb:ListStreams"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator",
                "dynamodb:DescribeStream",
                "dynamodb:ListStreams"
            ],
            "Resource": "arn:aws:dynamodb:us-east-1:***:table/table-1/stream/2016-01-01T00:00:00.000",
            "Effect": "Allow"
        },
        {
            "Action": [
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator",
                "dynamodb:DescribeStream",
                "dynamodb:ListStreams"
            ],
            "Resource": "arn:aws:dynamodb:us-east-1:***:table/table-2/stream/2016-01-01T00:00:00.000",
            "Effect": "Allow"
        }
        // ... etc, etc, etc...
    ]
}
```

These individual policy statements are far too verbose to be scaleable given AWS' limit on policy size. Also, in my case they're totally redundant because I've already defined a catch-all statement that covers these actions.

IMO there are two solutions that would be helpful in solving the issue:
- 1. Serverless should create a single policy statement with all event stream ARNs added to a single `Resource: []` array. This would greatly cut down on the verbosity, allowing the policy to scale past ~50 events.
- 2. Allow some way in Serverless to disable this behaviour all together for those who want to manually define policy statements in `serverless.yml`. This would provide a way to bypass these potential scaling issues.

### LINKED ISSUE #4686: Feature Proposal: join logs permissions to allow for scaling
# This is a Feature Proposal

## Description
We have a very large serverless application that we're upgrading from sls 0.5 to sls 1. We've been hitting a lot of scaling issues; most recently an error `Maximum policy size of 10240 bytes exceeded for role`. Looking at the policy generated in `.serverless`, I realised we have a separate definition of permission for creating and putting to logs; that causes an issue with size when you have 50+ functions.

## Proposed solution
I tinkered a bit with serverless code and came up with this. 

1) Joining statement to allow creating log streams and putting log events for all functions
```
        "Policies": [
            {
                "PolicyName": "[TO BE REPLACED]",
                "PolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": ["logs:CreateLogStream", "logs:PutLogEvents"],
                            "Resource": []
                        }
                    ]
                }
            }
        ]
```

2) Simplify the piece of code that adds functions (resources) to this statement in `mergeIamTemplates.js`:

```
      this.serverless.service.provider.compiledCloudFormationTemplate
        .Resources[this.provider.naming.getRoleLogicalId()]
        .Properties
        .Policies[0]
        .PolicyDocument
        .Statement[0]
        .Resource
        .push({ 'Fn::Sub': 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}' +
          `:log-group:${this.provider.naming.getLogGroupName(functionObject.name)}:*` });

      // here the same code (with .Statement[1]) was deleted
```

## Concerns
1) I assume there has been a reason for these two statements to be separated?
2) I know that technically serverless framework isn't made for this scale and we'll keep hitting scaling issue. Long term, we'd like to separate our application into several stacks. But as we're only trying to upgrade serverless and not to change everything at once, this would be very useful for us.

## Similar or dependent issues:
* #2508 - Maximum policy size of 10240 bytes exceeded for role; this issue has been closed but there are still people experiencing this issue.
* https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/25 - closer description of the original issue that I originally believed to come from the split stacks plugin

### PR DESCRIPTION
**Pull request by rdsedmundo**
## What did you implement:

Closes #2508, Closes #4686 

Our team has started to hit limitations on some growing services regarding the maximum allowed size for an IAM role, which is 10240 bytes.
```
An error occurred: IamRoleLambdaExecutioncanary - Maximum policy size of 10240 bytes exceeded for role hello-world-service-prod-us-east-1-lambdaRole
```

Checking the CloudFormation's templates I realized that somewhere between 60%-70% of the role policy is this:
```
{
  "Action": [
    "logs:CreateLogStream"
  ],
  "Resource": [
    {
      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/hello-world-service-prod-helloWorld:*"
    }
   ...this repeats for every function on the project
  ]
}
```

and this:
```
{
  "Action": [
    "logs:LogPutEvents"
  ],
  "Resource": [
    {
      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/hello-world-service-prod-helloWorld:*"
    },
    ...this repeats for every function on the project
  ]
}
```

## How did you implement it:

Instead of adding a permission for each log group separately, I simply got their common prefix which is the service name + dash + the current stage and added a wildcard at the end.

On a service with 10 functions, I was able to see a reduction from 7100 bytes to 3100 bytes.

I hope this doesn't have extra complications... looking forward to hearing your thoughts.

## How can we verify it:

Simply package any service and verify that the iamRoleLambdaExecution now only has one entry for the log groups with a wildcard appended, rather than one for each function on the service.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by vlad-traceme** [comment]
This couldn't have come at a better time, just tested this out as we ran into this same issue and this fix seemed to work, thanks @rdsedmundo. Hoping this will get reviewed and pushed into a patch soon

**Comment by jplock** [comment]
Is it possible to also combine the `logs:LogPutEvents` and `logs:CreateLogStream` actions together as well?

**Comment by rdsedmundo** [comment]
@jplock this won't represent a big change in the size like the main edit, but that's fair enough. I'll make that change.

**Comment by rdsedmundo** [comment]
@pmuens I made those changes asked by @jplock, please check it again.

**Comment by smferguson** [comment]
@rdsedmundo thank you! we just ran into this. hope it's merged/released soon.

**Comment by rdsedmundo** [comment]
I just reverted the changes that @jplock had suggested. There's a difference yes. The ARN of the two actions are slightly different at the end:

logs:CreateLogStream
```
log-group:${logGroupsPrefix}*:*
```

logs:LogPutEvents
```
log-group:${logGroupsPrefix}*:*:*
```

Thanks to a coworker of mine who spotted this, otherwise we could almost have merged it and broken some builds.

**Comment by jplock** [comment]
Are the extra :*’s necessary since you are wildcarding the prefix?

**Comment by rdsedmundo** [comment]
They are. The wildcard on ARNs expands up to the next colon.

**Comment by rdsedmundo** [comment]
@pmuens @medikoo Sorry, but I need your review approval (and test) again. Since I pushed to the branch it was dismissed.

**Comment by lucasbastianik** [comment]
Nice job @rdsedmundo! 🔥

**Comment by mgresko** [comment]
Have found an issue where this breaks down... on 1.53.0.

Line 78 it is assumed that the functions are named service-stage.  We are using https://github.com/concon121/serverless-plugin-aws-resource-names and modifying the name so that it is stage-service...   What happens is this logic to consolidate the log groups in the iam policy is skipped and we hit the original problem this github issue fixes.  Because our convention does not match the hard coded values.

```
const canonicalFunctionNamePrefix = `${
      this.provider.serverless.service.service
    }-${this.provider.getStage()}`;
```

Is it possible to make the `canonicalFunctionNamePrefix` configurable or other alternatives?

**Comment by medikoo** [comment]
@mgresko function which do not follow default naming convention, are also ensured to have logs setup properly. See: https://github.com/serverless/serverless/blob/92514eea78b476d970bbad908a759ecc1791bf6f/lib/plugins/aws/package/lib/mergeIamTemplates.js#L89-L112

**Comment by mgresko** [comment]
@medikoo thanks for the reply.  

Since the name of our function does not match the hard coded formula that generates 'canonicalFunctionNamePrefix` we are now reliant on the `customFunctionNamelogGroupsPrefix` to populate the policy which will be `/aws/lambda/<full function name>`.  Then down below that creates a policy that is one line per function.  `customFunctionNamelogGroupsPrefix` is not a prefix as it is passing the entire function name to `getLogGroupName`

https://github.com/serverless/serverless/blob/92514eea78b476d970bbad908a759ecc1791bf6f/lib/plugins/aws/package/lib/mergeIamTemplates.js#L97

Based on the current logic there is no way for this code to determine what the prefix of a function is without making it configurable.  Please correct me if I am confused.  Thanks!

BTW, if I modify `canonicalFunctionNamePrefix` to match our convention of `$stage-$service` all works fine.

**Comment by medikoo** [comment]
> `customFunctionNamelogGroupsPrefix` is not a prefix as it is passing the entire function name to `getLogGroupName`

Yes, that's true, the var has logically incorrect name. Technically it's a complete log group name in that case.

> Based on the current logic there is no way for this code to determine what the prefix of a function is without making it configurable. 

Yes, internally prefixes are used only for functions which match default naming conventions. All other functions are addressed individually with dedicated logs group configuration

**Comment by craig-dae** [comment]
I've just started experiencing this issue. Shouldn't this merge have fixed it?

**Pull request merged**
