### PR TITLE
Introduce efficient packaging for dotnet projects

### PR DESCRIPTION
**Pull request by BryanCrotaz**
Closes: #7523
Addresses: #6580

### CODE REVIEW

**Comment by medikoo** [comment]
@BryanCrotaz great thanks for that initiatilve. Still can you propose this PR, when you believe work will be finalized (?)

To improve bug tracker maintance, we prefer to not host drafts coming from forks (they just add noise to open PR's list), See https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#when-you-propose-a-new-feature-or-bug-fix

**Comment by BryanCrotaz** [comment]
I've put it up so you can comment as I go rather than telling me at the end that you don't like the structure.

**Comment by BryanCrotaz** [comment]
It also lets others know that this is being worked on so they don't duplicate the work

**Comment by medikoo** [comment]
> I've put it up so you can comment as I go rather than telling me at the end that you don't like the structure.

Ideally we should discuss implementation spec first at #7523, after we agree on implementation over there, it's unlikely we will reject the PR that conforms to it.

**Comment by medikoo** [comment]
> It also lets others know that this is being worked on so they don't duplicate the work

Usually it's clearly indicated in an issue (in which case contributor is assigned to it)

**Comment by medikoo** [comment]
Additionally no PR's should be introduced to reports which are unclear (have "question" label)

**Comment by BryanCrotaz** [comment]
ok, well here it is. Native support for dotnet out of the box without breaking node.js

I need to add some documentation still, and some tests

**Comment by BryanCrotaz** [comment]
I've just run `prettier -c [files that it complained about] --write` and committed, but the validation is still failing on the same files. How do I find out what it's complaining about?

**Comment by medikoo** [comment]
> How do I find out what it's complaining about?

It's listed in CI:

```
lib/classes/CLI.js
lib/plugins/package/lib/packageService.js
Code style issues found in the above file(s). Forgot to run Prettier?
```

Note that also unit tests fail

**Comment by BryanCrotaz** [comment]
I know which files but not what the issue is. I've run prettier on those files and it still fails.

**Comment by BryanCrotaz** [comment]
Do the unit tests pass on main? I'm seeing failures on stuff I haven't touched.

**Comment by medikoo** [comment]
Closing as it doesn't respect contribution guidelines, and it's also not mergable in given state.

@BryanCrotaz if you still want to work on this, we will definitely appreciate it, still let's please first discuss and agree on implementation spec at #7523 (note it t touches very sensitive parts towards which significant refactor is planned to be done soon)

**Comment by BryanCrotaz** [comment]
It’s working in production for me. Takes ten minutes off the packaging
time, and generates valid dotnet packages, unlike the current code.

What do I need to change to have this accepted? It neither makes sense to
have a serverless system that will never support all the possibilities of
AWS (in terms of languages), not forks of serverless of serverless like
mine that diverge over time.

Bryan Crotaz
Silver Curve

On 24 Aug 2020, at 13:20, Mariusz Nowak <notifications@github.com> wrote:

﻿

Closing as it doesn't respect contribution guidelines, and it's also not
mergable in given state.

@BryanCrotaz <https://github.com/BryanCrotaz> if you still want to work on
this, we will definitely appreciate it, still let's please first discuss
and agree on implementation spec at #7523
<https://github.com/serverless/serverless/issues/7523> (note it touches
very sensitive parts towards which significant refactor is planned to be
done soon)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/serverless/serverless/pull/8043#issuecomment-679093291>,
or unsubscribe

**Comment by medikoo** [comment]
> What do I need to change to have this accepted?

As I mentioned in previous comment, please outline an implementation idea at #7523

Also please note that this PR contains a lot unrelated changes, which makes it hard to review and reason about

**Pull request closed without merging**
