### PR TITLE
SessionTokens + Contribution Notes

### PR DESCRIPTION
**Pull request by erikerikson**
Add AWS session token usage and handling (for NodeJs or Python). This is important to enable the use of temporary credentials, particularly for cases of credential federation (e.g. SAML) where end users are unable to establish permanent IAM credentials.

Credentials are obtained as follows
1. Will use ~/.aws/credentials defined credentials if SERVERLESS_ADMIN_AWS_PROFILE is set
2. Checks for environmentally defined credentials
3. Reads any duplicated credentials in admin.env.

If SERVERLESS_ADMIN_AWS_PROFILE exists but obtaining the credentials from ~/.aws/credentials fails, it falls back on using the environment or duplicated credentials. (as is the current logic, to avoid breaking existing behavior.)

The logic for obtaining credentials and preparing AWS SDK config has been consolidated.  As appropriate, where defaults are inappropriate, customization of the base default is necessary/implemented.

Also adding some comments from gitter to the contribution notes.  (I'd be happy to break that into a separate PR if desired)

### CODE REVIEW

**Comment by erikerikson** [comment]
For the record, I bulldozed over some of the listed commits (previously pushed for discussion purposes) to simplify what I am pushing.

This includes the following (that were not included in this pull request):
1. enable custom function name templating …
2. enable the use of a proxy …

There's a merge commit and a few cleanup commits but otherwise the only real commit is:

1. 	Add AWS session token usage and handling. This is important to enable …

**Comment by erikerikson** [comment]
This PR should address the following list of issues:
https://github.com/serverless/serverless/issues/516
https://github.com/serverless/serverless/issues/488

**Comment by ac360** [comment]
Sorry for the slowness on this PR @erikerikson.  Just wanted to let you know that we are talking internally about how we will be merging this and adding the multi-AWS account support with it.

**Comment by erikerikson** [comment]
Thanks for the heads up @ac360, I was wondering.  :)

If you want anything changed, do please let me know.

**Comment by davidcai** [comment]
+1 this PR. 
+1 multi AWS account support.

**Comment by andyday** [comment]
@erikerikson looks like this needs updated with the latest serverless:master.

**Comment by erikerikson** [comment]
Heh, indeed @andyday but I'm going to merge it into the v0.5 branch instead and close this one out.  Started that today but haven't quite finished.  I'm going to try and get it done tonight so that these changes get into the next release before the VPC release takes over.  :)

**Comment by erikerikson** [comment]
/sigh
Ran out of battery with the merge nearly done.  Will get this in tomorrow.

**Comment by ac360** [comment]
@erikerikson I will have time to work on this tomorrow.  We're going to get this in V0.5.

**Comment by pmuens** [comment]
:+1: Great! Also great to see that you started working on the `CONTRIBUTING.md` file (I think that we need this soon so that we have some conventions we can all stick to)!

**Comment by erikerikson** [comment]
running test and whatnot... should be in shortly

**Comment by erikerikson** [comment]
Superseded by https://github.com/serverless/serverless/pull/634

**Pull request closed without merging**
