### PR TITLE
add Node version and Serverless version in CLI errors

### PR DESCRIPTION
**Pull request by horike37**
## What did you implement:

***Implementing Issue:*** #2109

## How did you implement it:
I added Node version and Serverless version in `lib/Error.js`
## How can we verify it:
Please exec `$ serverless tracking e` in your serverless project, and show messege below

errors

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [ ] Provide verification config/commands/resources
- [x] Leave a comment that this is ready for review once you've finished the implementation

### CODE REVIEW

**Comment by andymac4182** [comment]
It would be great it this included the OS as well since there are some differences between the various OS's.

**Comment by flomotlik** [comment]
@horike37  You can ignore the Coveralls issue, its because error wasn't covered well yet, I'll create a separate issue for that. As @andymac4182 mentioned having in there as well would be great.

**Comment by flomotlik** [comment]
@horike37 could you add the Operating system as well?

**Comment by pmuens** [comment]
@horike37 thanks for this really useful PR!

Do you need any help with the operating system retrieval? `process.platform` should do the trick!

**Comment by horike37** [comment]
@pmuens @flomotlik 
I will send PR again and list the OS info as well.

**Comment by pmuens** [comment]
@horike37 awesome! Thank you very much!

**Comment by horike37** [comment]
@pmuens 
I added the OS info. Could you check it?

**Comment by pmuens** [comment]
@horike37 that's a really great and useful feature. Love it!

Thank you very much for updating it! Tested it and will merge it now 👯

**Comment by pmuens** [comment]
Damn. Just noticed one slightly typo (`environment`).

Would be great if you could fix this. Then I'll merge immediately!

**Comment by horike37** [comment]
@pmuens 
Oh.. I fixed it.

**Comment by pmuens** [comment]
Awesome! Thanks a lot!

**Comment by robertkowalski** [comment]
<3

**Pull request merged**
