### PR TITLE
Resolve #1470 - Possibility to specify template on service creation

### LINKED ISSUE #1470: Possibility to specify template on service creation
The user should be able to create a service based upon a template like this:
`serverless create --name my-service --template aws-java-maven` or this: `serverless create --name my-service --template aws-node43`.

**Note:** This also implies that Services are runtime bound (one service only supports one runtime)

The templates should live in our core framework (might be moved to somewhere else such as an own npm package later on).

Here's an example of the directory structure:
```
templates
  |__aws-node43
  |__aws-node
  |__aws-python
  ...
```

The syntax for subfolder is `PROVIDER-LANGUAGE-BUILDTOOL` (where BUILDTOOL isn’t necessary for each language, but e.g. necessary for java).

Each template folder also includes `serverless.yaml` and `serverless.env.yaml`.

**Aside:** Templates might also be "installed" with the help of a `gitUrl` later on so that users can point the template option to their repository when they don't want to go with core ones.
The serverless command name might change to something different like `serverless scaffold` or `serverless install`.

Related to: https://github.com/serverless/serverless/issues/1452

Corresponding PR is: https://github.com/serverless/serverless/issues/1470

### PR DESCRIPTION
**Pull request by license2e**
##### Status:

Ready

##### Description:

Resolve #1470 - Possibility to specify template on service creation

##### Todos:

- [√ ] Tests already checked for the presence of handler.js
- [√ ] Add test to check for package.json

### CODE REVIEW

**Comment by license2e** [comment]
@pmuens @flomotlik any status on this one? I would love to get to the next stage with the java templates once I hear back if this implementation is the way forward.

**Comment by pmuens** [comment]
@license2e thanks for this one! 🎉 

We'll look into it ASAP as it's on our plan as one of the next steps.

**Comment by eahefnawy** [comment]
@license2e Thanks for your work on this. This is a highly requested feature, so we discussed internally and it's now in progress. The exact implementation will be a bit more complex than this PR as we added even more ideas.

Here's where you can follow the [PR](https://github.com/serverless/serverless/pull/1537) & [Issue](https://github.com/serverless/serverless/issues/1470).

**Comment by flomotlik** [comment]
@license2e as this was resolved with #1537 I'm going to close this one. Thanks again for for your contribution, definitely influenced our discussion about the exact implementation. Looking forward to work on more stuff with you.

**Pull request closed without merging**
