### PR TITLE
document Condition in iamRoleStatements

### PR DESCRIPTION
**Pull request by isaacl**
this already works but isn't documented.

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
@isaacl thanks for update. Still you've put this into general config reference.

Do you want to indicate that we definitely support `Condition` property? 

Note that `iamRoleStatements` are passed as is to CF template, and this config is simply about providing basic example of a property (not a complex one, as it's about listing all)

**Comment by isaacl** [comment]
I'm not sure where you're suggesting I put that?

I've used both single conditions like the example above and compound such as:
```
    - Effect: Allow
      Action: ['ses:SendEmail']
      Resource: '*'
      Condition:
        StringEquals:
          'ses:FromAddress': ${file(conf/config_staged.yml):${self:provider.stage}.email.from}
        Bool:
          aws:SecureTransport: true
```

Condition key is already allowed by the configuration validation as well.

**Comment by medikoo** [comment]
> I'm not sure where you're suggesting I put that?

Documentation of this property lives here: https://github.com/serverless/serverless/blob/86b366a5d3b6b0bd00b73c71d0c1a0661ff27ce2/docs/providers/aws/guide/iam.md#the-default-iam-role

And I believe it's a best place where it eventually can be extended

**Comment by medikoo** [comment]
@isaacl I'm closing this due to lack of activity. Still if you want to work on this, just let us and we will happily reopen

**Pull request closed without merging**
