### PR TITLE
feat(AWS RabbitMQ): Support `maximumBatchingWindow`

### PR DESCRIPTION
**Pull request by rm-hull**
As per #10580, this PR adds maximumBatchingWindow property to serverless.yaml for RabbitMQ event sources

### CODE REVIEW

**Review by pgrzesik — APPROVED** [review]
Thanks @rm-hull 🙇

**Review by pgrzesik — CHANGES_REQUESTED** [review]
Oops, I accepted too fast - there's a small conflict - could you please resolve it?

**Comment by rm-hull** [comment]
@pgrzesik rebased from upstream .. this PR should be ok now

**Comment by rm-hull** [comment]
@pgrzesik many thanks for reviewing and merging the PRs  :clinking_glasses:

**Pull request merged**
