### PR TITLE
AWS Lambda: Remove `nodejs12.x` runtime

### PR DESCRIPTION
**Pull request by medikoo**
Support for the `node12.x` runtime was dropped on AWS side

### CODE REVIEW

**Comment by thetumper** [comment]
Is it the policy for Serverless to drop runtime support with the AWS "phase 1" deprecation?  Or not until "phase 2"?  The latter is when AWS will no longer allow to create or update functions on that runtime.  During "phase 1", it is allowed to update functions, including updating the runtime.  So, would it be more appropriate to drop when the runtime enters phase 2?

**Comment by medikoo** [comment]
@thetumper currently AWS shows the message that nodejs12.x runtime _is no longer supported for creating or updating AWS Lambda functions_ (you can see that e.g. in that CI failed build: https://github.com/serverless/console/actions/runs/5082650720/jobs/9132695168#step:10:100481)

So I take we're already in "phase 2". Or do you find it possible to update deployed `nodejs12.x` functions?

**Comment by thetumper** [comment]
@medikoo I was just going by this page:
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy

It's not impacting me - my functions are all on 16 right now.  So no urgency.  I was just asking because it surprised me that there was nothing on the above page for a phase 2 date for 12.  It may be that AWS have not kept that page updated?

**Comment by medikoo** [comment]
@thetumper yes, I've also noticed that AWS docs are silent about complete deprecation, yet it's what we're experiencing in builds, and that move is dictated by this experience

**Comment by thetumper** [comment]
@medikoo I've just submitted feedback to AWS on that page, so they can (hopefully) verify it and update as needed.  Thanks for the discussion!

**Pull request merged**
