### PR TITLE
Add npm-shrinkwrap.json creation to Travis publish process

### LINKED ISSUE #4096: npm-shrinkwrap.json should be published, not package-lock.json
# This is a Bug Report

## Description

As stated in the NPM docs https://docs.npmjs.com/files/shrinkwrap.json
> The recommended use-case for npm-shrinkwrap.json is applications deployed through the publishing process on the registry: for example, daemons and command-line tools intended as global installs or devDependencies

Serverless is clearly in the "command-line" tool category.

Also stated in the docs is that package-lock.json will be ignored if found anywhere other than the top level project and should not be published to npm. https://docs.npmjs.com/files/package-lock.json

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package. It shares a format with npm-shrinkwrap.json, which is essentially the same file, but allows publication.

Believe this issue was introduced in this PR https://github.com/serverless/serverless/pull/3690

### PR DESCRIPTION
**Pull request by pmuens**
Closes #4096 

Added a bash script which will create the `npm-shrinkwrap.json` file before the publishing process kicks in (it also removes the `package-lock.json` file).

Running `./scripts/shrinkwrap` should show that it works (or run `npm run prepublishOnly`).

### CODE REVIEW

**Comment by eahefnawy** [comment]
Thanks for that @pmuens 🙌 ... few comments:

- should be `npm prune --production`
- we should also completely remove the `package-lock.json` file before publishing, following the npm recommendation and the discusion in #4096 
- following previous discussion, we should use the `prepublishOnly` **npm** script rather than the Travis `before_deploy` script. This way if we do manual release for any reason, we won't forget this script.

Other than that, lots of ❤️

**Comment by pmuens** [comment]
Good stuff! Thanks for the review @eahefnawy 👍

That totally makes sense! I just updated the PR accordingly.

**Comment by eahefnawy** [comment]
Beautiful! One other concern, having two `prerelease` files is confusing. Maybe just call the script `shrinkwrap`?

I wish we can put them both in one file, but I understand it's bash vs Node 🤔

**Comment by pmuens** [comment]
> Beautiful! One other concern, having two prerelease files is confusing. Maybe just call the script shrinkwrap?

> I wish we can put them both in one file, but I understand it's bash vs Node 🤔

Haha. Yes, I 100% agree with that (`shrinkwrap` sounds like a nice name!). I wanted to write the logic in JavaScript, but boy I was immediately turned-off by `then()` and its friends...

**Comment by eahefnawy** [comment]
> then() and its friends...

😂

**Pull request merged**
