### PR TITLE
add PRIVATE endpointType

### LINKED ISSUE #5063: Support for new Endpoint type " PRIVATE"
# This is a  Feature Proposal

## Description

For feature proposals:
Using Amazon API Gateway, we can now create private REST APIs that can only be accessed from your Amazon Virtual Private Cloud (VPC) using an interface VPC endpoint. 

To do that we have to set up "Endpoint Type": PRIVATE. But Serverless framework does not allow to use this Endpoint Type (Only allow "REGIONAL" or "EDGE" ). Can you Include support for this new Endpoint type via Serverless framwork. 

For more details please refer this: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version ***: 1.27.3
* ***Operating System***: linux
* ***Stack Trace***:
* ***Provider Error messages***:   endpointType must be one of "REGIONAL" or "EDGE". You provided PRIVATE.

### PR DESCRIPTION
**Pull request by ijin**
## What did you implement:

Added `PRIVATE` [endpointType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html) for API Gateway

Closes #5063 #5052

## How did you implement it:

Added `PRIVATE` to `validEndpointTypes` const variable with more specific tests.

## How can we verify it:

```yaml:serverless.yml
service: private-endpoint-test
provider:
  name: aws
  runtime: nodejs6.10
  endpointType: private

functions:
  helloWorld:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
```

```shell
$ aws --region us-east-1 apigateway get-rest-apis 

{
    "items": [
        {
            "id": "gxq77iec19",
            "name": "dev-private-gw-test",
            "createdDate": 1530087544,
            "apiKeySource": "HEADER",
            "endpointConfiguration": {
                "types": [
                    "PRIVATE"
                ]
            }
        }
    ]
}
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by mcshiz** [comment]
After I deployed a private gateway, I still had to log into the console and set a resource policy for the endpoint. When I looked at the cloudformation template the endpoint was set to private
` "EndpointConfiguration": {
          "Types": [
            "PRIVATE"
          ]
        }`
but it appears that we have to also set the `policy` attribute which is a JSON Object of a Resource Policy.
For example this will allow anything within the VPC
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:##########",
            "Condition": {
                "StringEquals": {
                    "aws:sourceVpce": "##############"
                }
            }
        }
    ]
}
`

**Comment by BrandonEvansAsurion** [comment]
@mcshiz You may already be doing this, but you can set the resource policy within your serverless.yml like so:

```
provider:
    name: aws
    runtime: nodejs6.10
    endpointType: private
    resourcePolicy:
        - Effect: Allow
          Principal: '*'
          Action: execute-api:Invoke
          Resource: arn:aws:execute-api:##########
          Condition:
              StringEquals:
                 'aws:sourceVpce': ##############
```

**Comment by mcshiz** [comment]
Yea, thanks @BrandonEvansAsurion. I did end up writing that into my serverless.yml.
I have decided that I will also create the `com.amazonaws.us-west-2.execute-api` vpc endpoint in the resources section of my file.
I think it would be helpful to add some of this information to the documentation, I'll work on a PR

**Comment by ptrhck** [comment]
I get a cloudformation circular dependency error if I try the following:

`Resource: { "Fn::Join" : ["", [ "arn:aws:execute-api:${self:provider.region}:", { "Ref": "AWS::AccountId" }, ":", { "Ref": "ApiGatewayRestApi" }, "/*" ] ]  }`

I guess it does not work as it is the event that is being created? Can I solve this somehow such that I do not have to update in manually if redeploying?

What is the consequence if I set it to the following?

`arn:aws:execute-api:${self:provider.region}:*`

**Comment by dschep** [comment]
@ptrhck, since the name of the `ApiGatewayRestApi` instance is generated from your service name & region, you can infer it without using a `Ref`. So instead of:
```yaml
Resource:
  "Fn::Join":
    - ""
    -
      - "arn:aws:execute-api:${self:provider.region}:"
      - { "Ref": "AWS::AccountId" }
      - ":"
      - { "Ref": "ApiGatewayRestApi" }
      - "/*"
```

Use this:
```yaml
Resource:
  "Fn::Join":
    - ""
    -
      - "arn:aws:execute-api:${self:provider.region}:"
      - { "Ref": "AWS::AccountId" }
      - ":"
      - ${opt:stage, self:provider.stage}-${self:service}
      - "/*"
```

**Comment by luisamador** [comment]
I'm having exactly the same issue as @ptrhck.

@ptrhck I'm afraid your solution ends up throwing the same error message.

"Error -----------------------------------------
The CloudFormation template is invalid: Circular dependency between resources: blah..."

**Comment by dschep** [comment]
Oh. That's unfortunate @luisamador  😞

**Comment by luisamador** [comment]
I think I will deploy the API Gateway resource policy manually in the meantime.

**Comment by ptrhck** [comment]
> @ptrhck, since the name of the `ApiGatewayRestApi` instance is generated from your service name & stage, you can infer it without using a `Ref`. So instead of:
> 
> ```yaml
> Resource:
>   "Fn::Join":
>     - ""
>     -
>       - "arn:aws:execute-api:${self:provider.region}:"
>       - { "Ref": "AWS::AccountId" }
>       - ":"
>       - { "Ref": "ApiGatewayRestApi" }
>       - "/*"
> ```
> 
> Use this:
> 
> ```yaml
> Resource:
>   "Fn::Join":
>     - ""
>     -
>       - "arn:aws:execute-api:${self:provider.region}:"
>       - { "Ref": "AWS::AccountId" }
>       - ":"
>       - ${opt:stage, self:provider.stage}-${self:service}
>       - "/*"
> ```

This seems not to work anymore, right? Looks like you need `arn:aws:execute-api:REGION:ACCOUNTID:*/*`

**Comment by philipbarile** [comment]
I also have the same circular dependency issue with attempting to set the resource policy in serverless.yml.  There is most likely a better way/I'm possibly doing something wrong, but I worked around it by wrapping my serverless deploy command in a shell script that then updates the resource policy on the API that was deployed, and finally issues a "create-deployment" command through the CLI  (this last part is important or it won't work.  I found this out the hard way after several hours ha).

**Comment by andrhamm** [comment]
If you go to the API Gateway web console, on the Resource Policy page, if you click the button to add an example policy for "Source VPC Whitelist", it generates a policy stub like this (no need to Ref the ApiGatewayRestApi resource):

```
resourcePolicy:
    - Effect: Deny
      Principal: '*'
      Action: execute-api:Invoke
      Resource: "execute-api:/${self:provider.stage}/*/*"
      Condition:
        StringNotEquals:
          aws:sourceVpce: ${file(./config.vpc.${self:provider.stage}.yml):vpcId}
    - Effect: Allow
      Principal: '*'
      Action: execute-api:Invoke
      Resource: "execute-api:/${self:provider.stage}/*/*"
```

After deploying, the policy in the console looks like this (correctly expands the API Gateway ARN):

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Principal": "*",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:us-east-1:XXXXXXXXX:YYYYYYYYY/stage/*/*",
            "Condition": {
                "StringNotEquals": {
                    "aws:sourceVpce": "vpc-ZZZZZZZZ"
                }
            }
        },
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:us-east-1:XXXXXXXXX:YYYYYYYYY/stage/*/*"
        }
    ]
}
```

**Comment by jeffreysmooth** [comment]
This is not supporting to add VPCE list when we enabling private endpoint.In the AWS console ,we can add vpce list when we enable private in end point configuration

**Pull request merged**
