### PR TITLE
Issue #657: Condense CLI output to fit in a single screen

### PR DESCRIPTION
**Pull request by akalra**
Addressing #657 -- discussion and screenshots are in the referenced issue.

There are a few pieces of future work I intend to tackle next:

1. Referencing loaded plugins in the top-level version of this screen
2. Find some way to have the color scheme work across light and dark background terminals.

I didn't find much in the way of test infrastructure for the CLI, and to be honest, I'm not even sure what tests would be meaningful for something like this. Open to suggestions here, please do let me know if you have ideas.

I did notice that some action descriptions had embedded new-lines. Not sure how best to handle that -- thoughts? I can obviously strip out the embedded new-lines, but not sure if that's the right move here.

Thanks!

Ankur

### CODE REVIEW

**Comment by eahefnawy** [comment]
Awesome!!! for the embedded new lines, we can easily change that. Action descriptions generally needs some rework and if new lines gonna cause issues, we have control over that!

I can merge this PR right away @akalra but I understand it still needs some work? or is this version complete enough? (does it cover both main help and contextual help for each action as described in the issue?). 

Also can you make sure you style your code with ESLing/Airbnb style? just to make Travis happy :)

Thanks a lot for your hard work here @akalra 😊

**Comment by akalra** [comment]
Thanks @eahefnawy -- I consider this PR complete enough to be merged. I just listed future work as the items I think need to be tackled next in this space. It **does** handle both main and contextual help.

For the embedded new lines -- do you want me to strip out the new lines in the action descriptions as part of this PR, or should we just tackle that opportunistically as we re-write them? I could also have the code automatically strip out any newlines in text it's about to render, not sure if that'll make things unreadable.

For ESLint/AirBnB -- happy to do that, though most of the things it is complaining about are not in any code I wrote. Additionally, in some cases the rules actually detract from readability (space-in-parens, no-multi-spaces), and some rules don't apply for our usage (no-console is recommended for browser-based apps, not Node.js based apps http://eslint.org/docs/rules/no-console ).

If we want to apply all those rules nonetheless, I'd prefer to submit a separate PR that is behavior-preserving and lint-satisfying. And then re-base this branch off of that, so that this PR can be behavior-modifying and lint-preserving.

I'd prefer to avoid submitting a single PR with a whole bunch of whitespace changes as well as a few critical non-whitespace changes.

Thoughts?

Ankur

**Comment by eahefnawy** [comment]
Well said! You're right, let's forget about Linting for now (we have to do a lot of work in that front too anyway) ... for embedded lines, how about we replace new lines with spaces? I can merge right away after that 😉

**Comment by akalra** [comment]
Hi @eahefnawy -- stripped out all the newlines as you suggested. This PR should be complete and merge-ready.

Let me know if you need anything else from me,

Thanks!

Ankur

**Comment by eahefnawy** [comment]
Awesome stuff! 🎉  Thank you so much @akalra 😊

**Pull request merged**
