### PR TITLE
Parse yaml without changing cwd

### PR DESCRIPTION
**Pull request by xdissent**
## What did you implement:

Changed yaml parser to no longer change the current working directory.

## How did you implement it:

There's already a json-ref method that does it.

## How can we verify it:

The tests pass, and they parse yaml in directories other than the current.

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by HyperBrain** [comment]
Does this also work for included yamls that themselves include yamls from the included yaml's directory?
We should make sure that it does not harm any existing user configurations.

**Comment by xdissent** [comment]
How's that? =)

**Comment by xdissent** [comment]
This change revealed another problem with the yaml parser - although it wasn't caching the top-level file (because it was read every time before parsing), it *was* caching any file included via ref. So if a references b, any changes to b after the initial load are never present in the parsed output of a, for the lifetime of the process. The problem is json-refs's global cache, which is an all-or-nothing affair, and has no way to give a parser its own cache. I added a test that demonstrates the issue, and patched the new parser to clear the cache after each parse. Unfortunately it's not a perfect solution because parsing is async, and multiple concurrent calls could use/remove each other's caches. Ideally, json-refs would either a) use a per-parser cache or b) just rely on http's built-in caching mechanism for remote files and always read local files from disk, eliminating the global module state. Anyway, there ya go.

**Comment by pmuens** [comment]
Nice! Thanks for the investigation and fixing the issue with the cache @xdissent 👍 

🤔 any suggestion what solution you'd prefer to resolve the issue with async parsing?

> a) use a per-parser cache

> b) just rely on http's built-in caching mechanism for remote files and always read local files from disk, eliminating the global module state.

**Comment by xdissent** [comment]
Hey @pmuens, sorry this took so long, I was on vacation and somehow managed to stay off the computer! I looked at the two options I mentioned and both would require some big changes to json-refs, so I'll get the ball rolling on a PR over there soon. In the meantime, I just made the yaml parser use a promise queue to avoid the potential cache issues altogether. Of course queuing totally eliminates concurrency for multiple parser calls, but all the actual fetching/reading/ref resolving is still done concurrently within the individual run. Not ideal, but it was the only way I could think of to solve all the above problems given the current state of json-refs.

**Comment by pmuens** [comment]
> Hey @pmuens, sorry this took so long, I was on vacation and somehow managed to stay off the computer!

Nice! Hope you enjoyed your days off of the computer!

No worries @xdissent 👍 Thanks for taking the time to work on this!

I'm currently at a place where I have pretty spotty internet connectivity so it might take some time till I can take a deep dive into this.

> In the meantime, I just made the yaml parser use a promise queue to avoid the potential cache issues altogether. Of course queuing totally eliminates concurrency for multiple parser calls, but all the actual fetching/reading/ref resolving is still done concurrently within the individual run. Not ideal, but it was the only way I could think of to solve all the above problems given the current state of json-refs.

That sounds like a good implementation for now 👍 

BTW. Let us know if you need any help with your PRs and thanks again for your work on this 👍

**Comment by eahefnawy** [comment]
@xdissent First off, thanks a lot for contributing! 😊 ... Just one note, would be great if you open up and/or link to an issue discussing the problem you're trying to solve with this PR. I see that you don't want to change the cwd, **but why?**. This is how we see real value in PRs ☺️ 

This PR touches a very sensitive area of the codebase as @HyperBrain mentioned, so I just wanna make sure we test it thoroughly if we have a good use for this PR.

All the best 🙌

**Comment by xdissent** [comment]
@eahefnawy totally understood, I admit it may not be immediately obvious why not touching cwd is important. I believe the initial impetus behind this PR was a plugin I was using which needed to parse a yaml file that is distributed in the plugin. So that lives in `node_modules/serverless-plugin/something.yaml`. Now let's say I have a Makefile in my own project folder, and also have a plugin that just runs `make` in my project whenever I deploy, via hooks or whatever. The problems arise when the yaml parser changes the current working directory to parse a yaml file - if the plugin parses `node_modules/serverless-plugin/something.yaml` it will first chdir to `node_modules/serverless-plugin`. After that, my `make` command (and anything else) is run relative to that folder, so it can't find my make file - it's looking in `node_modules/serverless-plugin`. A seemingly simple fix is to just chdir back to the original directory after you parse the yaml file, but since it's async, there's a potential for my `make` command to still be run concurrently with the yaml parsing, yielding the same erroneous results.
But also consider two plugins that parse 2 different yaml files, both within their `node_modules/some-plugin` folders. If plugin A starts parsing and has a ref to a relative yaml file, like `./extra.yaml`, but for some reason the disk (or whatever transport) is being slow, and plugin B starts parsing immediately after plugin A, the yaml parser may end up looking for `./extra.yaml` in plugin B's folder. Because cwd is process-wide, and yaml parsing is async.
Sorry about the additional cache fixes being piled on here, I would have liked to put those in another PR but it is pretty tightly coupled to the same code. I discovered those bugs as I was trying to fix the cwd problem. Plus I was going on vacation!
Let me know if you need more info!

**Comment by horike37** [comment]
Closing this issue for now since it took for a long time without any activity.
Free feel to re-open if you want to restart working on this.

**Pull request closed without merging**
