### PR TITLE
Spotinst - Updated docs layout, added ruby template, added public/private support, and added chron documentation

### PR DESCRIPTION
**Pull request by jeffnoehren**
## What did you implement:

Updated the Spotinst Provider Documentation layout, added in a ruby template, and added to the yml file public/private support and chron functionality

## How did you implement it:

Edited documentation 

## How can we verify it:

View updated Spotinst provider docs

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by horike37** [comment]
Hey, @jeffnoehren Thank you for the great addition :+1: 
Can we start to review on this?

**Comment by jeffnoehren** [comment]
hey @horike37 thanks :) we are almost ready actually! I just want to change the images on the Spotinst Provider page really fast but after I push those changes it should be ready for review if thats cool with you!!

**Comment by jeffnoehren** [comment]
Hey @horike37! I finished updating the picture URLs but now I keep getting an error that I am not using a valid BitBucket URL with subdirectories, but I did not change any BitBucket URLs. Any idea why this is no longer passing?

**Comment by horike37** [comment]
Hey @jeffnoehren ! Thank you for updating the awesome Spotinst docs :100: 
The problem of BitBucket URLs test has been already resolved on the top of master branch, so I have rebased this PR on my end and passed the tests :+1: 

We will start to review !

**Comment by jeffnoehren** [comment]
Yay thanks so much @horike37 :)

**Pull request merged**
