### PR TITLE
Add status code support for API Gateway

### PR DESCRIPTION
**Pull request by pmuens**
***Implementing Issue:*** #608

## What did you implement:
Status code support for API Gateway (that you can e.g. return a 404 from within your lambda function).

## How did you implement it:
Added the `method responses` and `integration responses` to the `API Gateway compile method` method.

## How can we verify it:
Use this handler to raise a 404 error:

```
module.exports.hello = (event, context, cb) => {
  cb(new Error('[404] Not found'));
}
```

## Todos:
- [x] Write tests
- [x] Fix linting errors
- [x] Add docs
- [x] Provide verification config/commands/resources

## Notes / Things to be aware of:
- Uses the old resources logical Ids in test

/cc @eahefnawy @flomotlik

### CODE REVIEW

**Comment by flomotlik** [comment]
@pmuens please fix the conflicts

**Comment by pmuens** [comment]
@flomotlik rebased and fixed test to use new logical ids.

**Comment by pmuens** [comment]
@flomotlik Rebased and updated to the string representation usage 🏄

**Comment by wedgybo** [comment]
I have a few questions around this. I've been looking at adding a setup for a decent REST configuration. I like that this will have a default way of handling the error, but is there a plan to be able to change the response regex so we can have more details error responses. 

For instance we would like to return a JSON error code and for that, we would need to update the regex used to capture the correct error code.

I was thinking of putting together something for setting up the typical REST codes used and a standardised way of triggering them. So it would be an addition to this PR but wanted to discuss if it's something that should be in the main codebase or is more suited to a plugin?

I would have thought that providing a simple REST setup would be super helpful as AWS doesn't make it easy

**Comment by flomotlik** [comment]
@wedgybo could you open an issue describing how the HTTP responses should look in detail and what configuration options you want to have?

Generally having a way to add header mappings and body mappings for other statuses than 200 could be interesting, but would like to understand the use case better.

**Comment by wedgybo** [comment]
Will do. Will get something basic up soon to show the gist of what we're trying to do.

**Comment by JulienWeiler** [comment]
Is there a way or will there be one to extend the default status codes?

**Comment by wedgybo** [comment]
The PR I'm working on will allow it so you can have 201 for POST requests for example

**Comment by JulienWeiler** [comment]
Nice, thanks!

**Comment by wedgybo** [comment]
@JulienWeiler If you want to take a look and give us your thoughts on https://github.com/serverless/serverless/pull/2014 it would be appreciated

**Pull request merged**
