### PR TITLE
Fix broken shared API functionality

### LINKED ISSUE #4923: Shared API functionality has been broken on top of master
# This is a (Bug Report)

## Description
It seems that Shared API functionality has been broken on top of master with following error when sls deploy. maybe any one of PRs have introduced this after releasing v1.26.1

```
$sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (409 B)...
Serverless: Validating template...
 
  Error --------------------------------------------------
 
  The CloudFormation template is invalid: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.8.1
     Serverless Version:     1.26.0
```
Here is serverless.yml
```yml
service: shared-service

provider:
  name: aws
  runtime: nodejs6.10
  apiGateway:
    restApiId: [ID]
    restApiRootResourceId: [ID2]

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
```

## Additional Data

* ***Serverless Framework Version you're using***: top of master
* ***Operating System***: darwin
* ***Stack Trace***: above
* ***Provider Error messages***: above

### PR DESCRIPTION
**Pull request by horike37**
## What did you implement:

Closes #4923

## How did you implement it:
Used wrong function for generating CF, so I have fixed a correct one and added test case so as not to introduce this regression in the future.

## How can we verify it:
Run `sls deploy` with the following serverless.yml

``` yaml
service: shared-api

provider:
  name: aws
  runtime: nodejs6.10
  apiKeys:
    - myFirstKeyss
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100
  apiGateway:
    restApiId: xxxxxxxx # Specify your restApiId
    restApiRootResourceId: yyyyyyyyy # Specify your restApiRootResourceId

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get

```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by horike37** [comment]
@HyperBrain 
>Did you check for other places where naming.getRestApiLogicalId is still used instead of the new >getApiGatewayRestApiId that does the call internally?

Good point. will check it. If the old one is found in other places, I will fix those as well on this PR.

**Comment by mafrosis** [comment]
:+1: Just hit this one running `master`. Glad to see it's already fixed!

**Comment by horike37** [comment]
@HyperBrain 
I have done the check. In conclusion, we don't need to change it for other places :smile: 

On the other hand, I have found another bug about Shared API, which is that `sls remve` will fail if you specify usage plan in serverless.yml **on shared API side**. this bug has already existed when releasing this feature. However, this case would be a rare problem since AFAIK nobody has reported this one and personally don't think up a case which necessity to define it on Shared API side.

That being said, we can release v1.27.0 without waiting for the fix.

@mafrosis 
Thank you for commenting! Would be good if you can test it again after merging!
The more you test the better!

**Comment by HyperBrain** [comment]
@horike37 I agree that the bug is only very restricted and can be ignored for now (due to the missing real use case).
So we should be fine for the 1.27 release now 👍

**Comment by mafrosis** [comment]
I can confirm this works now in `master` for me

**Comment by horike37** [comment]
@mafrosis 
Awesome! Thank you for testing!

**Pull request merged**
