### PR TITLE
Add ES7+ support to aws-nodejs-ecma-script template

### PR DESCRIPTION
**Pull request by ffxsam**
Closes: #8060

### CODE REVIEW

**Comment by ffxsam** [comment]
Actually, hold off - need to test a couple more things.

**Comment by ffxsam** [comment]
Fixed, had to add some config to `@babel/preset-env` for things to work properly (no need to transpile to get async/await, for example, since we're using Node.js 12.x).

Someone please feel free to test this PR to double-check my work, but it seems to be fine!

**Review by medikoo — APPROVED** [review]
Thank you @ffxsam !

**Comment by ffxsam** [comment]
Happy to help!

**Pull request merged**
