### PR TITLE
Doc - Add AWS-only alternative for variableSyntax that is compatible with Serverless way

### PR DESCRIPTION
**Pull request by Vadorequest**
Add an alternative AWS-only variableSyntax in AWS doc, which is compatible with the current Serverless syntax `${stuff}`

Usage: `${AWS::stuff}`

(credits to @dschep)

### CODE REVIEW

**Comment by Vadorequest** [comment]
@alexdebrie Proposed change done :)

**Comment by lorengordon** [comment]
this is brilliant. been using `serverless-pseudo-parameters`, but i think this is even better.

**Comment by dschep** [comment]
@lorengordon, note that when using this, you still need to explicitly use `Fn::Sub` which `serverless-pseudo-parameters` does of for you automtically.

**Comment by lorengordon** [comment]
@dschep quite right, still brilliant, thanks!

**Comment by dougmoscrop** [comment]
Is there a non-user-action-required solution that would be compatible with the AWS notation? Can we just make the variables parser accept "aws:" but noop it?

**Comment by HyperBrain** [comment]
@dougmoscrop Interesting approach. We could indeed add a separate parser for the `aws:` namespace similarily to `cf:` or `ssm:` that just resolves the variable to its name (with `$` prepended).

Sample:
```
${aws:Region} => ${AWS::Region} (lit.)
```

@erikerikson Any thoughts?

**Comment by erikerikson** [comment]
This looks like a good change but it should not have been accepted in merged without accompanying test to validate the functionality.

@HyperBrain I think the noop approach would have been problematic and that this PR is implemented seems correct and straightforward.  How would one differentiate between the noop match and correct variable identification?  That said I offered what I think is a much more complete analysis of what ought to be recently at:
https://github.com/serverless/serverless/pull/3694#issuecomment-368126674

I don't expect there to be an issue resulting from this change.  If there would be an issue, I would expect it to have failed a number of the tests. Therefore I don't think that there's any issue and this is a good improvement.  Thank you @vadorequest for offering it.

**Comment by dougmoscrop** [comment]
I'm not sure I see a case where ${aws:Region} is valid other than being passed through to CloudFormation; I like the idea of provider-specific syntactic sugar, but as it stands, Serverless allows you to write CloudFormation in it's YML but only a subset -- _perfectly valid CloudFormation fails to work in Serverless_ -- as a user I would really prefer to have this fixed without having to wait for a cross-provider solution. And even **if** there is a cross-provider solution, I'm still pretty against Serverless "blocking" valid CF syntax.

The proposal here, to manipulate the variable syntax, feels hacky to me.

**Comment by erikerikson** [comment]
Hi @dougmoscrop.  I'm not sure I understand the concern here.  This fix causes exactly the behavior you state: "${AWS:Region} is [...] passed through to CloudFormation" (note that I altered the casing you provided for AWS).  It says "I know what AWS variables look like and I'm just going to ignore them".

The manipulation to the variable syntax causes all `${AWS::...}` values to be ignored using a negative look ahead so they are passed through to CloudFormation.  It seems safe to assume that other providers are not going to adopt AWS as the prefix to their variables so the seems a relatively safe cross provider solution. Perhaps you can help me understand something that I am missing?

I don't disagree that there is a better solution and attempted to offer what that might look like via my link.

**Comment by dougmoscrop** [comment]
Sorry - the concern is I have to maintain this regex in every serverless repo I have. At the very least it's just configuration noise. If the regex is good enough to document, make it the default one?

**Comment by erikerikson** [comment]
:facepalm:. Haha. Totally missed this is a docs change.  Sorry everyone!

Recommendation for doing this by default at given link.

**Comment by Vadorequest** [comment]
The decision to make it a doc change instead of changing the default behaviour is due to its incompatibility with other systems.

This is not like a universal regex that will fix every use case, it's more like a AWS workaround and should be used as it. If we make it the default behaviour, then other people will run into the same issue with other systems. I don't have a concrete example but that was our concern when discussing about it with @dschep on Slack.

That is also the reason why we only added it to the AWS documentation and not everywhere.

If we want to change the default behaviour, we need to improve the regex in order to become "universal/provider agnostic", IMHO.

**Comment by dougmoscrop** [comment]
That's why I would prefer the variable system just pass through aws
variables. It's pragmatic and compatible.

**Comment by HyperBrain** [comment]
What about keeping compatibility and solving this pragmatically in an elegant way?

We could introduce a provider based subsystem in the variable resolution, i.e. each provider plugin can define a variable mapping, that is run when the provider is detected. So the variable resolution would call `provider.resolveVariable(varString)` for variables not recognized by the Variable class'  `getValueFromSource()` function (last fallback).

The AWS plugin would define it's resolveVariable function to just pass the aws variables to their resolution. Then we can keep all doors open for other providers, and each provider can have its own special set of "standard" variable declarations and resolutions.

With the current deep resolution this should be possible and the provider resolution can be used as soon as the provider itself has been resolved (in case it is itself set by a variable).

**Comment by dougmoscrop** [comment]
I can't remember if variable resolution plays well with plug-in loading.  I'm all for whatever works!  Just adding AWS: variable felt like it was something that could be done in like 15 mins of work.

**Pull request merged**
