### PR TITLE
Improve configurability and performance of package plugin

### PR DESCRIPTION
**Pull request by medikoo**
Firstly, sorry for not opening an issue first, it came out as natural follow-up to  [reducer](https://github.com/medikoo/serverless-plugin-reducer) and [transpiler](https://github.com/medikoo/serverless-plugin-transpiler) plugins I developed recently.

Still, let me know if I'm on a right path, maybe there's a better way to approach it.

## What did you implement:

I secluded logic that's responsible for:
- Resolution of paths of all Lambda/Service files, to be included in final zip file ([`resolveFilePathsAll`](https://github.com/medikoo/serverless/blob/f4ee5481c6da0d61168bf1b2770958af6d571300/lib/plugins/package/lib/packageService.js#L109) and [`resolveFilePathsFunction`](https://github.com/medikoo/serverless/blob/f4ee5481c6da0d61168bf1b2770958af6d571300/lib/plugins/package/lib/packageService.js#L115))
- Resolution of content of individual files, to be piped into zip archive ([`getFileContent`](https://github.com/medikoo/serverless/blob/f4ee5481c6da0d61168bf1b2770958af6d571300/lib/plugins/package/lib/zipService.js#L99))

Having that not mixed into other methods as it's now, allows to tweak/replace functionalities in question in a more reliable way, e.g. it will allow to replace internal logic of [reducer](https://github.com/medikoo/serverless-plugin-reducer/blob/5a76f563daa9a31810bc36c2a1af102ed953f985/index.js#L37-L44) and [transpiler](https://github.com/medikoo/serverless-plugin-transpiler/blob/master/index.js#L27) with something more solid.

Additional smaller changes that came out naturally over the process:
- [globby is called an _async_ way, and directories are filtered on spot](https://github.com/medikoo/serverless/blob/f4ee5481c6da0d61168bf1b2770958af6d571300/lib/plugins/package/lib/packageService.js#L144-L150)
- [Content of files for zip archive is resolved _async_ way](https://github.com/medikoo/serverless/blob/f4ee5481c6da0d61168bf1b2770958af6d571300/lib/plugins/package/lib/zipService.js#L79-L94), that should speed up packaging process.
- Handle properly eventual [zip file write error](https://github.com/medikoo/serverless/blob/f4ee5481c6da0d61168bf1b2770958af6d571300/lib/plugins/package/lib/zipService.js#L72)
- In a current master version, packaging process starts after `.serverless` folder is created and zip archive file opened. That results with weird service/lambda packages where `.serverless` folder is included together with empty artifact `zip` file. This change fixed that, by enforcing file paths resolution to precede archive creation. Still tests had to be updated so [archive zip file is no longer counted as part of archive](https://github.com/serverless/serverless/compare/master...medikoo:improve-packaging-extensibility?expand=1#diff-13d632e1b3ff507c817556cdb0c65787)

### More reasoning notes
Current lambda packaging process, as implemented in master, may come out as highly inefficient for some service  cases:
- Even in [individual](https://serverless.com/framework/docs/providers/aws/guide/packaging#packaging-functions-separately) mode, lambda specific packages cover whole service codebase
- Invoked internally glob and npm commands are slow when comparing to more direct file resolution methods, and in certain scenarios may produce infinite stalls

In SLS project I work with (which consists of about 30 lambdas), each lambda package resulted with 6MB file, where on average lambda specific code covers 200KB.

Initially on our side, packaging of single lambda took over 1 minute, it was due to specific configuration where we had some internal versioned packages (folders with package.json outside of `node_modules`). It appeared that main issue lies in [`excludeNodeDevDependencies`](https://github.com/serverless/serverless/blob/f0b1474f1e49d69c39e27e3c8def929569e20bed/lib/plugins/package/lib/zipService.js#L116-L183) function, which does expensive [`globby`](https://github.com/serverless/serverless/blob/f0b1474f1e49d69c39e27e3c8def929569e20bed/lib/plugins/package/lib/zipService.js#L122-L131) call, and expensive [`npm ls`](https://github.com/serverless/serverless/blob/f0b1474f1e49d69c39e27e3c8def929569e20bed/lib/plugins/package/lib/zipService.js#L147-L149) call.

What's interesting in case someone had in setup some packages linked (via `npm link`) then deployment script totally hanged on that (most likely because following symlinks got globby into infinite recursion).

After removing internal packages it got cut to 25s per package, and I'd say it's still really bad file paths resolution time for single lambda.

I further cut it by taking in [reducer](https://github.com/medikoo/serverless-plugin-reducer) plugin, which by following require paths, resolves just needed files. It takes now 2s, but still may be improved if I would cut off the _glob_ step totally, but for that it would be better to have improvements I proposed with this PR.

I believe that it may be a good step for SLS, to provide such lambda files resolver (for Node.js case) out of a box, as an option. If you also feel it's a good idea, I'll be happy to provide it via other PR.

## How did you implement it:

I secluded mentioned logic in least invasive way and ensured that existing methods work as they did before.

## How can we verify it:

Run tests

## Todos:

- [x] Write tests
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped (there's a very minor drop, but only due to an extra [error handling improvement](https://github.com/medikoo/serverless/blob/f4ee5481c6da0d61168bf1b2770958af6d571300/lib/plugins/package/lib/zipService.js#L72), that can be a result of some very rare race condition or disk I/O error, therefore problematic to write test for)
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by medikoo** [comment]
@eahefnawy @pmuens what is the status of this PR exactly, is there a chance it'll be reviewed in next days? Great thanks!

**Comment by pmuens** [comment]
> @eahefnawy @pmuens what is the status of this PR exactly, is there a chance it'll be reviewed in next days? Great thanks!

Thanks for taking time to implement this change and for pinging @medikoo 👍!

We have this PR on our radar and will review it in the upcoming days!

**Comment by medikoo** [comment]
I ensured it's up to date with master. It'll be great to have that considered, as it'll significantly boost lambda packaging performance on our side.

**Comment by eahefnawy** [comment]
@medikoo Sorry for the delay. I've reviewed took this PR for a spin on a fresh service and found no issues. However I wasn't able to verify that it actually improves the performance.

Got any example service (maybe with some npm packages) with specific config that could illustrate how this PR improves performance? or maybe some benchmarks from your service? Otherwise this PR is G2M 😊

**Comment by medikoo** [comment]
@eahefnawy It depends on a setup, but pursuing _async_ parallel calls instead of consecutive _sync_ calls, seems more _right_ way to configure workflow within Node.js programs. It may bring noticeable performance difference for some extreme cases, still it's true that difference may be negligible for all others :)

However, it's not the reason I proposed those changes. What's more important in case of project I work with, is that those changes will allow to improve configuration and performance of following plugins, we rely on:

- https://github.com/medikoo/serverless-plugin-reducer - Here I will be able to directly resolve files for zip archive, and not be forced to rely on slow `glob` calls (as it's the case now). This noticeably improves performance of packaging in our serverless project (lambdas will be packaged near instantly, it's not the case now).
- https://github.com/medikoo/serverless-plugin-transpiler - Here I will be able to decorate _just_ logic responsible for retrieval of file content, and not rewrite whole [`zip`](https://github.com/medikoo/serverless-plugin-transpiler/blob/ae59157da627edbcab84041b4c87d31ebc3655cb/index.js#L27-L99) which takes place now, that doesn't seem future-proof.

**Comment by medikoo** [comment]
@eahefnawy Thank you!

**Comment by medikoo** [comment]
> throws an error  `ENFILE: file table overflow, open XYZ.js`

It's wide known issue, that may happen when large number of concurrent fs calls gets in. This can be fixed by using e.g. [graceful-fs](https://www.npmjs.com/package/graceful-fs). Generally it's good to have it in scripts that operate on indefinite number fs resources


I can propose a PR that loads [graceful-fs](https://www.npmjs.com/package/graceful-fs) it in `bin/serverless`.  let me know

**Comment by HyperBrain** [comment]
Regarding graceful-fs, I think it is important to use V4 (which does not monkey-patch fs by default) and do not activate the patch functionality as this affects the whole serverless process. Patching it process-wide will have side-effects on all plugins *AND* all user code run with `invoke local` as it runs within the Serverless process.

**Comment by medikoo** [comment]
> Regarding graceful-fs, I think it is important to use V4

Yes, this one doesn't patch. Still it's not as easy. I personally prefer to rely on patching in projects I work with, as then I know problem is solved across all dependencies I work with, and it's really seamless.

While non-patching solution requires that every entity that may open descriptors internally uses `graceful-fs` instead of `fs` which can hardly be the case.

However maybe in that single case of lambda packaging, this could  indeed be fixed on spot with `graceful-fs` v4. I'll look into it shortly

**Comment by HyperBrain** [comment]
The problem with invoke local is, that a patched fs silently hides issue in the user code (where it would fail without patching in a version deployed to AWS). The same is true for plugin development.

**Comment by medikoo** [comment]
> The problem with invoke local is, that a patched fs silently hides issue in the user code

Assuming we see an `EMFILE` as an issue in user code. To me it's more a design issue, that can be transparently _fixed_ by monkey patching. It's also important to note, that issue is not _hidden_ it's __fixed__ (error is just workaround by given call being postponed, not aborted, which is seamless when we speak of async calls) :)

But I agree if monkey patching can be avoided here, it's way better to avoid it.

**Comment by medikoo** [comment]
@pmuens @HyperBrain I've published PR at #4145 

There were two obvious _hot_ places for fs concurrency, and after applying `graceful-fs` there should be no more EMFILE/ENFILE issues, @pmuens please confim it fixes problem on your side.

**Comment by pmuens** [comment]
Thanks for PRing that @medikoo 👍. Great to see the fix that fast 💯!

I'll take a deep dive into this today!

**Comment by aterreno** [comment]
We started to notice few random loading issues with v1.21. 

And we currently ended up going back to 1.20. 

I wonder if anyone else is having issues and if this is a regression from this change. 

All I can see on our cloudwatch logs is `Unable to import module ‘handler’: Error at Function.Module._load`

**Comment by medikoo** [comment]
> All I can see on our cloudwatch logs is Unable to import module ‘handler’: Error at Function.Module._load

@aterreno can you prepare some (as small as possible) reproducible test case, so we can look into it?

Technically changes included in this PR shouldn't alter the outcome in anyway

**Comment by pmuens** [comment]
Thanks for your comment @aterreno and thanks for jumping in @medikoo 👍

I'm pretty sure that this is the bug where binary files were not packaged correctly. We've fixed that in `v1.21.1` so updating should resolve the issue. Furthermore we've just release Serverless `v1.22` a few hours ago.

@aterreno let us know if you still face the same issues after updating!

**Comment by aterreno** [comment]
Cool, I will report back, thanks everyone

**Pull request merged**
