### PR TITLE
refactor: Cleanup mergeIamTemplates module

### PR DESCRIPTION
**Pull request by runk**
As discussed in #8701 moving related by independent refactors into separate PR

### CODE REVIEW

**Comment by runk** [comment]
@medikoo Not sure I should be looking to increase coverage given no new business logic introduced?

**Comment by medikoo** [comment]
> @medikoo Not sure I should be looking to increase coverage given no new business logic introduced?

Yes, please ignore codecov status. I think it reports regression only because we've shortened used code removing some useless expressions (so technically we have now less of them covered)

**Comment by runk** [comment]
@medikoo can you please review this one when you get chance?

**Review by pgrzesik — APPROVED** [review]
Looks good, thank you @runk

**Pull request merged**
