### PR TITLE
Consolidate multiple beforeEach methods in test

### PR DESCRIPTION
**Pull request by alexdebrie**
## What did you implement:

There were multiple `beforeEach()` methods in a test module which was causing issues. cc @HyperBrain 

## How did you implement it:

Consolidated them

## How can we verify it:

Pray that the tests pass

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by alexdebrie** [comment]
@HyperBrain Yea, it's the same error as before. Trying to dig in further and see what the real issue is here.

**Comment by horike37** [comment]
That multiple `beforeEach()` was caused by my mistake :sweat_smile: Thanks @alexdebrie for the fix.

Recently, the original error sometimes occurs on only Travis, so we can't get the root cause so far since not sure the step to reproduce :thinking: 

That is a blocker to review PRs and makes us confusing. so we want to fix early though...

By re-building, the tests have been passed. 
merging for now.

**Comment by HyperBrain** [comment]
I will try if I can get some time at the weekend to have a look at the remaining errors (maybe I can reproduce them on one of my systems).

**Comment by alexdebrie** [comment]
Thanks, @horike37. I tested around on my machine and it looks like both `beforeEach()` methods were called. This is cleaner though 😄 

Did some digging on the errors but can't find it. I'm wondering if something is stubbing out the `request` method in the `AwsProvider` and then not restoring it. Hard to figure out where it is though...

**Pull request merged**
