### PR TITLE
Using 'paths-ignore' to not execute the validate pipeline always

### PR DESCRIPTION
**Pull request by sjortiz**
# Description
This pr uses `paths-ignore` to not execute the validate pipeline when the only changes are `.md` files or files inside the `docs` folder

Closes: #2699

### CODE REVIEW

**Comment by sjortiz** [comment]
hey @medikoo , yeah no probs I think this can be achieved with `jobs.<job_id>.if`, something like this:
```
steps:
  - uses: actions/hello-world-javascript-action@master
    if: ${{ <expression> }}
```
It'll look a lot more like the travis solution, so I assume that's ok. LMK

**Comment by medikoo** [comment]
> It'll look a lot more like the travis solution, so I assume that's ok. LMK

Yes that'll be totally fine, and I think it's the only way to achieve it

**Comment by medikoo** [comment]
@sjortiz what is the status of that?

**Comment by sjortiz** [comment]
this one has become tricky, in fact the ci  doesn't build this branch anymore, I'll withdraw from this one, maybe someone else can knock this one out.

**Pull request closed without merging**
