### PR TITLE
Add Ability to Run CLI in Parallel

### PR DESCRIPTION
**Pull request by saucoin**
This change allows the CLI to be run in parallel when running
'package' and 'deploy'.

## What did you implement:
The ability to run 'package' and 'deploy' cli commands in parallel to support building and deploying to multiple regions.

## How did you implement it:
When --package is passed on the command line with the package command, the cli uses this directory to create the supporting files necessary for deployment.
When --package is passed on the command line with the deploy command, the cli uses the artifacts in this directory to deploy.
When --package is passed on the command line, the .serverless directory is no longer used as a staging directory.

## How can we verify it:

./node_modules/serverless/bin/serverless package --package location/us-east-1 --region us-east-1 --stage development &
./node_modules/serverless/bin/serverless package --package location/us-east-2 --region us-east-2 --stage development &
./node_modules/serverless/bin/serverless package --package location//us-west-1 --region us-west-1 --stage development &
./node_modules/serverless/bin/serverless package --package location/us-west-2 --region us-west-2 --stage development &

wait

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by pontusab** [comment]
Whats the status on this?

**Comment by m-reka** [comment]
Nice 😍 !! At the right time, I needed that. Thanks !
This should definitely accepted and merged into master for the next release.

**Comment by exoego** [comment]
@saucoin 
Could you merge latest `master` branch then resolve conflicts?

**Comment by saucoin** [comment]
I'll take a look at it over the next couple of weeks and see what the options are.

I agree that it's sat out there too long at this point.  The merge may be worse than a refactor at this point.


Thanks,

Shawn Aucoin
shawn_aucoin@hotmail.com

________________________________

**Comment by pmuens** [comment]
> I'll take a look at it over the next couple of weeks and see what the options are.

Thanks a lot for looking into that @saucoin :+1:

> I agree that it's sat out there too long at this point.  The merge may be worse than a refactor at this point.

I know, it's been a while. Maybe we can start with a discussion around the implementation in an issue, get some feedback from e.g. @serverless/framework-maintainers and take it from there. There are a couple of different ways to implement this and there could be something (especially when things run in parallel) we might miss.

**Comment by pmuens** [comment]
Given that we'll start with a fresh, new Issue where we'll discuss certain potential implementations I'll close this PR for now. We can reference or re-open it later on (if necessary).

@saucoin thanks again for taking the first stab at this 👍 💯 🥇

**Pull request closed without merging**
