### PR TITLE
feat(Telemetry): Check DO_NOT_TRACK env variable

### PR DESCRIPTION
**Pull request by isaacl**
See: https://consoledonottrack.com

### CODE REVIEW

**Review by medikoo — DISMISSED** [review]
That looks good to me.

@mnapoli what do you think?

**Comment by isaacl** [comment]
Updated ✅

**Comment by mnapoli** [comment]
Thanks @isaacl for the PR.

We've been reviewing the linked website but it seems like it isn't used by any major project. We are open to adding support for existing standards, but it seems like this isn't a standard yet. Let's revisit this when the situation has changed 👍

**Comment by isaacl** [comment]
Yeah I noticed that as well. I saw this supported by the stripe cli and thought it was more widespread. But stripe is the only tool I've seen w the support

**Pull request closed without merging**
