### PR TITLE
Add CAPABILITY_NAMED_IAM to initial stack creation. Fix for #2826

### PR DESCRIPTION
**Pull request by surfacedstudio**
Closes https://github.com/serverless/serverless/issues/2826

### CODE REVIEW

**Comment by nicka** [comment]
Ahh run against this one as well!

**Comment by nicka** [comment]
@pmuens Not sure but maybe here https://github.com/serverless/serverless/blob/3b58ec3332563c7a2b6848edf61de528df3dbc07/lib/plugins/aws/lib/updateStack.js#L27

**Comment by pmuens** [comment]
@nicka thanks for the pointer!
Isn't this the file which is updated in this PR?

**Comment by nicka** [comment]
Aah yes haha sorry (getting some coffee now)! Should be good then 👍

**Pull request merged**
