### PR TITLE
- fixed the topic format

### PR DESCRIPTION
**Pull request by danielkoo**
## What did you implement:

***Implementing Issue:*** 

Fixed documentation on the SNS event source

## How did you implement it:

Updated doco.

## How can we verify it:

Create an SNS topic and specify it in serverless.yml as an event source.

## Todos:

- [x] Write documentation

- corrected the documentation

### CODE REVIEW

**Comment by flomotlik** [comment]
@danielkoo I updated the docs structure today and this file is now in `docs/02-providers/aws/events/04-sns.md`

Could you rebase and update your PR, then I'll merge. Thanks for bringing this up!

**Comment by danielkoo** [comment]
Hi @flomotlik 

Cheers for the heads up, will rebase now :)

**Comment by danielkoo** [comment]
It's done; let me know if there's anything else I missed.

**Comment by flomotlik** [comment]
Great, thanks!

**Pull request merged**
