### PR TITLE
feat: Remove support for Node v10

### PR DESCRIPTION
**Pull request by pgrzesik**
BREAKING CHANGE: Node in versions lower than 12 is no longer supported

The Node10 builds are no longer running based on `*-v3` Github Actions config files. I did not change the original ones as I assume we will just switch these files at the end.

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
> I did not change the original ones as I assume we will just switch these files at the end.

It actually be good to update CI in context of this branch.

We should not test v3 against Node.js v10, and we should be free in v3 branch to use syntax  that doesn't work in Node.js v10.

We should also update linter, let me prepare major upgrade in our `eslint-config`

**Review by medikoo — COMMENTED** [review]
@pgrzesik I've rebased v3 against master, can you rebase this branch against v3?

**Comment by pgrzesik** [comment]
sure, rebased :+1:

**Review by medikoo — COMMENTED** [review]
Looks great.

Let's also update eslint config to rely on default `node` configuration (and not `node/10`)

**Review by medikoo — APPROVED** [review]
👍

**Pull request merged**
