### PR TITLE
refactor: Use standalone `ServerlessError`.

### PR DESCRIPTION
**Pull request by juanjoDiaz**
Closes: #8783

There is still the `lib/classes/Error` module that is a proxy to the serverless-error and also includes a `logWarning` function.
That module is exposed in the `serverless.classes` property.
Should it be removed from there at some point?

### CODE REVIEW

**Comment by juanjoDiaz** [comment]
The linting error has nothing to do with my changes.
Not sure how it got into master.

**Review by pgrzesik — CHANGES_REQUESTED** [review]
Thanks @juanjoDiaz, tremendous job getting all of these instances refactored :clap: As for the `That module is exposed in the serverless.classes property.` - I believe at this point, that module is no longer exposed via `classes` property as `classes.Error` is configured to be `ServerlessError` - am I missing something? As for the original `lib/classes/Error` that still has `logWarning` and and `logInfo` exported - I believe it should also be removed at some point, but not as a part of this PR. @medikoo what is your opinion here?

As for the linting changes, could you please rebase on top of latest master, make sure to install fresh dependencies and run prettier once again? Thanks in advance :bow:

**Comment by medikoo** [comment]
>  As for the original lib/classes/Error that still has logWarning and and logInfo exported - I believe it should also be removed at some point, but not as a part of this PR. @medikoo what is your opinion here?

They will be naturally removed when addressing https://github.com/serverless/serverless/issues/1720, but also without breaking anything (so at first we will remove all it's internal usage, and with major shift we will remove utils (and this class file) completely.

**Comment by juanjoDiaz** [comment]
Got it.

I didn't modify the offending line, but I did modify the function content. Because it doesn't use the keyword `this`, eslint wants it to be an arrow function.

**Review by pgrzesik — APPROVED** [review]
Thank you @juanjoDiaz :bow: Awesome job :100:

**Pull request merged**
