### PR TITLE
refactor: add `async` to promise-returning functions in `Variables`

### PR DESCRIPTION
**Pull request by G-Rath**
Relates to #8368

I was toying with an implementation for #8071 to get a sense of how much work it'd be, and fell into this rabbit hole 😅 
If it's ok with the team, I'd be happy to follow up this with refactoring it to use native promises, as these changes will mean less work for the PR for #8071.

### CODE REVIEW

**Comment by G-Rath** [comment]
I found that #8680 contains most of these changes, but will keep this open since that PR is a bit out of date and landing this one shouldn't cause a major conflict.

I've compared the two to confirm that I've not missed any functions :)

**Comment by G-Rath** [comment]
Hmm I'm not sure if my change is whats causing the test failure:

```
2021-02-14T22:42:11.286Z × mocha test fail Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/serverless/serverless/test/unit/lib/classes/ConfigSchemaHandler/index.test.js)
2021-02-14T22:42:11.286Z i mocha flushing previously gathered logs...
2021-02-14T22:41:41.283Z * mocha ConfigSchemaHandler
2021-02-14T22:41:41.283Z * mocha ConfigSchemaHandler > #constructor
2021-02-14T22:41:41.284Z * mocha ConfigSchemaHandler > #constructor > should freeze parts of schema for service
2021-02-14T22:41:41.286Z i serverless:test setup configSchemaExtensions fixture at /tmp/tmpdirs-serverless/1d53/a57004
```

🤔

**Comment by pgrzesik** [comment]
Thank you @G-Rath :bow: Before moving forward with review, I have a question to @medikoo as I know you're currently heavily invested into refactoring that part of the codebase - should we currently refactor changes to `Variables.js`? I'm guessing it's going to substantially change as a part of refactoring you're working on in: https://github.com/serverless/serverless/issues/8364

**Comment by medikoo** [comment]
> @medikoo as I know you're currently heavily invested into refactoring that part of the codebase - should we currently refactor changes to Variables.js

@pgrzesik good point. We definitely should not welcome any enhancements to it. Marking functions as `async` if it doesn't raise any implications I think it's fine, but if it requires some more work (patching tests etc) I would rather avoid it.

New variables parser will be introduced shortly, still the old one will serve as fallback until v3, so it's not that it will be immediately replaced. Ideally if it also doesn't stand as blocker for e.g. dropping `bluebird` dependency

**Comment by G-Rath** [comment]
> Ideally if it also doesn't stand as blocker for e.g. dropping bluebird dependency

I'm unclear what you mean here - are you saying that you'd welcome refactoring away bluebird in this file while it's still serving as a fallback?

**Comment by medikoo** [comment]
> I'm unclear what you mean here - are you saying that you'd welcome refactoring away bluebird in this file while it's still serving as a fallback?

Yes, exactly.

**Comment by pgrzesik** [comment]
Hello @G-Rath - as I've seen the work on the https://github.com/serverless/serverless/issues/8071 is currently paused, do you plan to work on this one? As for the tests and the timeout - I would recommend checking one-by-one which change introduces it, I don't see anything obvious after review. PS - there's also another related PR which touches the same files: https://github.com/serverless/serverless/pull/8943

**Comment by G-Rath** [comment]
@pgrzesik I have no problem continuing with this, but I think that @juanjoDiaz has already beaten me to the punch with #8943, so it probably makes sense to just let them continue with their PR since theirs is already passing the tests 😅

**Comment by pgrzesik** [comment]
Thanks @G-Rath and sorry for the duplication with other PR - as you've noted, the #8943 is almost finished and I think it makes sense to wrap that refactor as a part of it. Are you okay with closing this one at this point?

**Pull request closed without merging**
