### PR TITLE
#6017 Allow to load plugin from path

### LINKED ISSUE #6017: Load plugin from path
# This is a Feature Proposal

## Description

At the moment we can load plugins like this:

```yaml
plugins:
  - plugin1
  - plugin2
```

or in a specific directory:

```yaml
plugins:
  localPath: './custom_serverless_plugins'
  modules:
    - plugin1
    - plugin2
```

However this changes the directory for all plugins.

It would be very useful to be able to include a module using a relative path:

```yaml
plugins:
  - plugin1
  - plugin2
  - src/foo/bar/plugin3
```

## Use case

My use case is that I want to distribute my plugin without NPM (it is a plugin for a serverless PHP framework, so the plugin will be distributed with the rest of the PHP source code). Because of that I want users to be able to include the plugin, yet don't mess up their "localPath" just for this specific plugin.

### PR DESCRIPTION
**Pull request by mnapoli**
## What did you implement:

Closes #6017 

The list of plugins can now contain relative paths.

For example:

```yaml
plugins:
    # will load myfirstplugin/plugin.js or myfirstplugin/plugin/index.js
    - 'myfirstplugin/plugin'
    # will load mysecondplugin/plugin.js or mysecondplugin/plugin/index.js
    - 'mysecondplugin/plugin'
```

## How did you implement it:

I added the service path (the one containing `serverless.yml`) to the list of path in which Node can load modules. That way relative paths work.

## How can we verify it:

- in a directory with a `serverless.yml` file, create a sub-directory `foo`
- create a `bar.js` plugin in there, for example:

```js
'use strict';

class ServerlessPlugin {
    constructor(serverless, options) {
    }
}

module.exports = ServerlessPlugin;
```
- in `serverless.yml` import the plugin:

```yaml
plugins:
    - 'foo/bar'
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by mnapoli** [comment]
> I'm in for merging it (one a test and docs are added).

Awesome. I'll look into where the documentation is at.

Regarding the tests as far as I understood there isn't much functional test (i.e. the existing behavior isn't really tested as of now). I'll give it a try but I'm not sure of how it will go.

**Comment by medikoo** [comment]
I'm a bit reluctant on this specific way of addressing that, for following reasons:

- It further changes `module.paths`, and that's not widely recognized standard, and raises problems (as e.g. one we had [recently](https://github.com/serverless/serverless/pull/6183)).
In general I think we should aim into direction where `module.paths` hacking is removed (and I have it somewhere on TODO list)
- Currently what we have, provides quite clear separation. Plugin either need to be placed in `node_modules` or in `./.serverless_plugins` dir, While this change allows us to mix plugins with _service_ codebase, and that can raise surprising conflicts. e.g. I can imagine situations where some user has local plugin `.serverless_plugins/config.js`, and after we take that in, it starts to interfere with e.g. with some service local file named as `./config.json`.

Solution I would propose instead, is that we embrace (wide known) convention that Node.js uses for loading modules. So support `./` prefixed paths as relative plugin paths.

Having that, this particular use case can be addressed with configuration as:

```yaml
plugins:
  - ./vendor/bref/bref
```

**Comment by mnapoli** [comment]
I have pushed the documentation. I tried but I am having a lot of trouble coming up with relevant tests. Currently, the `localPath` feature is not tested as well (to give you an idea).

This:

```yaml
plugins:
  - ./vendor/bref/bref
```

is perfect, even clearer, more standard, less confusing. I am all for it!

Now to go and implement that would I need to parse the path (e.g. recognize that it starts with `./`) and then apply specific behavior? Or is there a magic "one-liner" that could make it work?

To be honest, as I was reading about the behavior of `require()` in Node, I thought that this would work out of the box. The only explanation I can think of as to why it doesn't work is that `./vendor/bref/bref` is evaluated relative to the `serverless` binary, not the current directory. But maybe I'm completely wrong.

**Comment by medikoo** [comment]
> Now to go and implement that would I need to parse the path (e.g. recognize that it starts with ./) and then apply specific behavior? Or is there a magic "one-liner" that could make it work?

I believe this should be handled here: https://github.com/serverless/serverless/blob/b954fa4a17bdf99e0a1bef502fc8b37c288d2923/lib/classes/PluginManager.js#L103

Simply as:

```javascript
const Plugin = plugin.startsWith('./') ? require(path.join(this.serverless.config.servicePath, plugin) : require(plugin);
```

**Comment by mnapoli** [comment]
@medikoo thank you for your help this is awesome! I've pushed an update with your suggestion (I had to split the line because eslint was complaining).

I was now also able to add tests, the PR looks much better now! It should be ready for review.

**Comment by mnapoli** [comment]
:+1:

I'm not seeing the comment regarding the documentation. I have updated it and force-pushed just before your comment so maybe that's why? (I forgot to update the documentation to add the `./` prefix).

**Comment by medikoo** [comment]
> (I forgot to update the documentation to add the ./ prefix).

Yes it was about that. Fixed now :)

**Comment by pmuens** [comment]
Thanks for approving @medikoo :+1:

**Comment by jurajseffer** [comment]
I'd just like to note that it's not obvious from the documentation that I have to use `./../`format instead of being able to use just `../` if I want to include from a directory above the project.

**Comment by medikoo** [comment]
@jurajseffer we consider main service folder a root of a project.

Using absolute or relative paths that go out of root in requires, is generally considered not as best practice (can bite back in certain scenarios, e.g. SLS won't package such outer modules for lambdas even if lambda requires them)

What exactly is your use case? Not sure if you've considered that, but now we have also a `config` option that allows to host multiple service configurations in root of same project

**Comment by jurajseffer** [comment]
My case is that we have a monolithic repo and I'm loading a simple plugin (from a common location) which, curiously, has to massage rendered Cloudformation template to remove logs group because SLS hardcodes the creation of a logs group (we do it outside because SLS/CF don't support KMS).
While we keep the services in the same repo, we want the separation and want all service specific stuff in their respective folders.

**Comment by medikoo** [comment]
@jurajseffer as we don't have written in stone anywhere that service root should be also an package root, I think it's totally ok for us to update it, so it works better for you

We're open for PR

**Pull request merged**
