### PR TITLE
Print message that an update is available if user runs Serverless command with an outdated version

### PR DESCRIPTION
**Pull request by RafalWilinski**
## What did you implement:

Closes https://github.com/serverless/serverless/issues/2118

## How did you implement it:

Added https://www.npmjs.com/package/update-notifier module.

## How can we verify it:

```
# Modify package.json version to something like 0.23.0
serverless info
serverless logs   # Message should be shown at the end of command
```

You can also remove `~/.config/configstore/update-notifier-serverless.json` and then try again.

screen shot 2017-09-21 at 22 53 46

Tests coverage is likely to drop but I think there's nothing to test here.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by RafalWilinski** [comment]
Unfortunately, AFAIK it's not possible to change the path.

**Comment by pmuens** [comment]
Thanks for the update @RafalWilinski 👍

> Unfortunately, AFAIK it's not possible to change the path.

🤔 I guess that's not a big deal for the time being.

Just a quick question: Why are you adding it to the `Utils` class rather than the [`Serverless` Class](https://github.com/serverless/serverless/blob/master/lib/Serverless.js) which will always be instantiated, no matter what?

**Comment by RafalWilinski** [comment]
Dismissing your review @pmuens as I've addressed your concern 😝

**Comment by pmuens** [comment]
Hehe 😅. Thanks for updating @RafalWilinski 👍

**Comment by RafalWilinski** [comment]
@horike37 It doesn't work for me on the first try neither. However, It works on 2nd or 3rd try. Looks like it needs some time to perform a request and save a file.

**Comment by horike37** [comment]
@RafalWilinski 
Umm, Still not working..

`~/.config/configstore/update-notifier-serverless.json` is generated, but I've tried it over and over again but I couldn't work it :cry: 

@pmuens 
Could you test it on your end?
I'm not sure whether missing any configs on my end or go wrong the code..

**Comment by horike37** [comment]
Hey, @RafalWilinski :+1: Could you please rebase this PR so that Appveyor tests have passed.
I think it would be OK since works fine on your end. If there would be a bug, the addition will not have serious side effect.

After you do rebasing, I will push the merge button :smile:

**Comment by RafalWilinski** [comment]
Actually, I'm pretty sure that this message does not appear because the process exits before response from this plugin is received so the message couldn't be printed. 

Rebasing...

**Comment by horike37** [comment]
Thanks @RafalWilinski :+1: 

>Actually, I'm pretty sure that this message does not appear because the process exits before >response from this plugin is received so the message couldn't be printed.
Ah, that makes sense :+1: 
merging..

**Pull request merged**
