### PR TITLE
feat(Variables): Accept case-insensitive strings in `strToBool`

### PR DESCRIPTION
**Pull request by whardier**
This change simply adds toLowerCase() when assigning stringValue to allow enable a case-insensitive input (True, TRUE, False, False)

Q1: No link.. no traction in slack either when attempting to discuss this.

### CODE REVIEW

**Review by pgrzesik — CHANGES_REQUESTED** [review]
Thanks @whardier :bow: 

I think it's worth considering, but there would be some changes needed if we were to accept this PR. 
1. We should document that change here: https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/variables.md#read-string-variable-values-as-boolean-values
2. We should test that introduced logic works correctly and properly converts e.g. `TRUE` 

@medikoo What do you think about this change?

**Review by medikoo — COMMENTED** [review]
>  @medikoo What do you think about this change?

I have mixed feelings but it doesn't look harmful.

@whardier can you explain what problem on your side does it solve?

**Comment by whardier** [comment]
Given an environment like this:

```shell
CI=FALSE
prettyLogging=True
```

I've needed to enlist tools like this:

```yaml
custom:
  helpers:
    NEGATE_true: false
    NEGATE_false: true
    BOOL_0: false
    BOOL_1: true
    BOOL_true: true
    BOOL_True: true
    BOOL_TRUE: true
    BOOL_false: false
    BOOL_False: false
    BOOL_FALSE: false
  pythonRequirements:
    dockerizePip: ${self:custom.helpers.NEGATE_${self:custom.helpers.BOOL_${env:CI, 'false'}}}
```

Simply because some foundational utilities are just plain missing.  Like having the ability to negate a bool or lowercase/uppercase a string.

**Comment by medikoo** [comment]
@whardier so if I understand correctly, you have such mixed case env vars injected by sources you do not control but you depend on. (e.g. `CI` and `prettyLogging` are as such). Is that correct?

In such case, it feels as a valid use case to address.

**Comment by pgrzesik** [comment]
Thanks a lot for additional explanation @whardier :bow: Please let me know what do you think about my previous comments, after they're addressed we should be good to go I believe

**Comment by whardier** [comment]
I've added docs/tests to PR branch

**Comment by pgrzesik** [comment]
Thank you @whardier - the changes look good in general, but I see that the linter is failing - could you please address that?

**Comment by whardier** [comment]
> Thank you @whardier - the changes look good in general, but I see that the linter is failing - could you please address that?

@pgrzesik  It is potentially prettier now (passes lint/prettier-check) and was automatically prettified using prettier.  I don't have that enabled by default for my work.

**Review by pgrzesik — APPROVED** [review]
Thanks @whardier - it's all looking good now :raised_hands:

**Pull request merged**
