### PR TITLE
Exclude dev dependency .bin executables

### LINKED ISSUE #4359: Dev dep exclusion does not exclude bins
# This is a Bug Report

## Description

I am using `lumo-cljs` in my `devDependencies` and expecting it to be completely excluded. However, it seems that my zip still contains the binary file.

```
 unzip -lf .serverless/my.zip  | grep lumo
      543  1980-01-01 00:00   node_modules/.bin/lumo
```

The package correctly [sets](https://github.com/anmonteiro/lumo/blob/master/packages/lumo/package.json#L28) the `"bin"` key in `package.json`

## Additional Data

* ***Serverless Framework Version you're using***: `1.23.0`

### PR DESCRIPTION
**Pull request by daviskoh**
## What did you implement:

Closes #4359 

## How did you implement it:

The `bin` properly `package.json` files of dev deps are read to check the name of the executable(s). If they exist, they are added to the glob exclude patterns.

Existing tests were updated w/ appropriate `readFileAsync` call counts & resolve values. 2 new tests were added handling executable exclusion.

NOTE: `readFileAsync` is being used to read `package.json` files & loading them into memory to access the `.bin` property which is not ideal, but this seems to be the safest way to know the name of the executables. For ex. a lib may be named `lumo-cljs`, but the executable specified in `package.json` could be named `lumo` w/o reading the file, there would be no way to know that. Also, there could be multiple executables include in the [bin](https://docs.npmjs.com/files/package.json#bin) section such as

package.json

```
{
  "bin": {
    "executable1", "executable1.js",
    "executable2", "executable2.js"
  }
}
```

Any feedback would be helpful as this is my first contrib to this project!

## How can we verify it:

Run `yarn test` or pull these changes and try installing as a package locally then running `sls package`

Pull these changes and create a new project, `yarn init` and add a few dev & prod packages:

package.json

```
{
  "name": "sample-project",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "sls": "sls"
  },
  "dependencies": {
    "lodash": "^4.17.4",
    "lokka": "^1.7.0",
    "lokka-transport-http": "^1.6.1"
  },
  "devDependencies": {
    "serverless": "file:path-to-local-serverless",
    "lumo-cljs": "^1.8.0-beta",
  }
}
```

Run

```
$ sls create -t aws-nodejs
$ sls package
$ unzip .serverless/aws-nodejs.zip -lf | grep lumo
```

Should not print anything

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by daviskoh** [comment]
ahh...looks like `readFileAsync` is failing on Windows...

**Comment by daviskoh** [comment]
ah god sorry...i clearly dont understand `path`...will look over it in a bit

**Comment by daviskoh** [comment]
hmm not sure why it would be failing on just node 5.11 when its passing on mine...any ideas?

image

**Comment by daviskoh** [comment]
😍  I think I fixed everything and it should be fully ready for review!

**Comment by horike37** [comment]
Great @daviskoh :+1:  Thank you for fixing the bug :100: 
We will review that :smile:

**Comment by arichiardi** [comment]
I tried this patch locally and it works like a charm.

**Comment by horike37** [comment]
Thank you for testing @arichiardi :+1:  Great help :100: 
merging...

**Comment by daviskoh** [comment]
glad i could be useful! ✌️

**Pull request merged**
