### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DavidWells**
Update doc links

### CODE REVIEW

**Comment by DavidWells** [comment]
Moving support and stuff to forums.serverless.com. 

Gitter is/might be slowely phased out

**Comment by rupakg** [comment]
@DavidWells not sure why travis is failing.

**Comment by HyperBrain** [comment]
@rupakg I restarted it. Let's see if that works.

**Comment by HyperBrain** [comment]
It looks like the integration tests stopped working. @horike37 The merge of #4854 seems to have broken the integration tests, but the PR showed everything working (so I was able to merge it). But the merged code in master now breaks them.
@rupakg This is completely independent but we have to fix it to be able to merge this.

**Comment by horike37** [comment]
Umm :thinking: intersting.
I will investigate it on the master.

**Comment by horike37** [comment]
@HyperBrain @rupakg @DavidWells 
Turned all green and just merged.
This bug was introduced by #4677, but the PR author has fixed it on #4861 :+1: 
Thanks again @franciscocpg :smile:

**Comment by rupakg** [comment]
@HyperBrain @horike37 Thanks for fixing and taking care of it.

**Pull request merged**
