### PR TITLE
Improve default variable syntax

### LINKED ISSUE #3693: Default variable syntax detection conflicts with variable syntax used by AWS
# This is a Bug Report

## Description

There are a number of places where AWS uses `${stuff}`, `${aws:stuff}`, and `${iot:stuff}` syntax for variables (see https://docs.aws.amazon.com/iot/latest/developerguide/iot-substitution-templates.html and https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html for examples). This is problematic as the existing default regex used for variable syntax detection cannot distinguish these AWS variables from Serverless variables.

Similar or dependent issues:
* #3565 talks about an escape syntax which is unnecessary if the regex is improved

### PR DESCRIPTION
**Pull request by azurelogic**
## What did you implement:

Closes #3693 

## How did you implement it:

I simply replaced the default regex with `\${((env|self|opt|file|cf|s3)[:\(][ :a-zA-Z0-9._,\-\/\(\)]*?)}` (with double slashes to make it friendly with JS strings)

## How can we verify it:

It passes the existing test suite (there were a few tests with typos that I fixed as well). In addition, I have added a test that checks that various similar syntaxes are not picked up. Just run `npm test`.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by azurelogic** [comment]
Thanks for the feedback, @pmuens!

We (people at Trek10) considered the additional maintainability issues, but we felt that it was necessary to allow for AWS's (and maybe other future providers') variable syntax.

A suggestion toward improving the maintainability of this syntax would be to move the default variable syntax declarations from `lib/classes/Utils.js` and `lib/classes/Service.js` to a static getter in `lib/classes/Variables.js`. This would remove the duplicated constant and put the variable syntax in close proximity to the variable processing code.

Thoughts?

**Comment by brianneisler** [comment]
The only problem I see with this is that it introduces potentially bad DX for users where variables with typos are undetected. I like the escape syntax because it forces the user to indicate to the framework that a variable is not meant to be processed. 

Internally we discussed introducing a feature that would alert users when a bad variable was detected to help improve DX. I'm not sure that this change would allow us to accomplish that...

**Comment by eahefnawy** [comment]
Agreed with @brianneisler ... on top of that, if someone wants to use a custom variable syntax, he has make sure all those prefixes are within the regex, currently they only need to specify a much simpler syntax that is irrelevant to the source.

Sorry didn't see your issue earlier @azurelogic 😊 , but what you're facing in the issue can be solved by using a custom variable syntax:
https://serverless.com/framework/docs/providers/aws/guide/variables/#using-custom-variable-syntax

**Comment by shortjared** [comment]
@eahefnawy @brianneisler As a counter point, from experience it is actually a **_very confusing experience_** for our clients when native [AWS pseudo-params](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html) simply do not work as they are used to and find in AWS docs. We have to regularly explain that the framework isn't able to handle well known vendor variables without a workaround.

We have applied this custom variable fix to at least 30 different projects and have to maintain it across all of those clients / projects.

So I guess we are asking for an improvement to at least handle AWS pseudo-params, we offered one solution but are open to anything that alleviates the pain point!

**Comment by shortjared** [comment]
In addition, this actually prevents the very useful and common Fn::Sub syntax from working by default.

**Comment by azurelogic** [comment]
Sorry for the delayed reply. I had assumed that there was no serious issue here until it was closed today.

@brianneisler, it would be great to be able to warn of typos. However, it is a confusing DX when Serverless has conflicts between internal and vendor variables.

@eahefnawy, our team has been using this custom syntax for some time, and we found that it allowed us to do much more powerful things than the current default. We decided to suggest it because it solves a critical problem. Also, nothing actually stops someone from using a less rigid custom variable syntax than our proposed one.

We did have an alternative proposal, but it is even more work for you to maintain. The alternative uses negative lookahead to fail matches on things that start with `aws:` or `iot:`. The currently proposed syntax at least can be maintained without knowledge of any provider syntaxes.

Either way, you may want to at least grab the other fixes that I provided to your test suite.

**Comment by brianneisler** [comment]
Thanks for the follow ups @azurelogic and @shortjared 

> However, it is a confusing DX when Serverless has conflicts between internal and vendor variables

To me, this is the heart of the issue. Unfortunately the framework and AWS have conflicting variable syntaxes. I'm honestly not sure that there's a clean solution here but want to work with you all to find a solution that offers both a good DX and helps alleviate this issue.

From a DX perspective I feel strongly that trying to magically support both by "sometimes" processing variables and "sometimes not" is only going to lead us down a path of confusion and further issues. I'd rather enforce a stronger policy that helps users understand that there's a difference between AWS's variables and serverless's.

Given that the framework is heading in a multi provider direction this leads me to further feel it is important to enforce a separation between the `serverless.yml` variable definitions and the AWS variable definitions. Having full support for variable detection in one provider and partial support in another creates a pretty bad developer experience when switching between providers.

That being said, I do think this is an issue and there are a few things we can do to help here.

1) Provide a simple escape syntax 
2) Introduce new `${aws:}` and `${iot:}` variables, which are basically just a pass throughs but we could offer some light validation.
3) Log warnings or throw errors when an unsupported variable is detected and offer helpful suggestions on how to fix.

What else?

**Comment by brianneisler** [comment]
@azurelogic and @shortjared it would also be extremely helpful if we had some simple use case examples where this is falling apart so we could think through it a bit more clearly.

**Comment by hauboldj** [comment]
If you want a clear distinction between Serverless variables and AWS variables you could change the Serverless variable syntax to `$<>` or `$[]`

Here is an example where the Serverless variable syntax collides in a couple ways with AWS.
```
IOTTopicRuleIncrementImageSets:
      Type: AWS::IoT::TopicRule
      Properties:
        RuleName: $<self:custom.iotTopicRuleNames.incrementImageSets>
        TopicRulePayload:
          RuleDisabled: false
          AwsIotSqlVersion: "2016-03-23"
          Description: Increments uploaded image sets total in device shadows
          Sql:
            Fn::Sub: >
              SELECT get_thing_shadow(topic(1), '${IAMRoleGetPublishThingShadow.Arn}').state.reported.imageSets + 1
              AS state.reported.imageSets FROM '+/increment/imageSets'
          Actions:
            - Republish:
                Topic: $$aws/things/${topic(1)}/shadow/update
                RoleArn: { "Fn::GetAtt": [ "IAMRoleGetPublishThingShadow", "Arn" ]}
```
For the above project we used `$<>` as the customVariable syntax for Serverless. Otherwise it would collide with `${IAMRoleGetPublishThingShadow.Arn}` in `Fn::Sub` and in the `${topic(1)}` substitution in the Republish Topic. Notice that new Serverless variables `${iot:}` and `${AWS:}` won't help with the substitution in the topic Republish Topic.

Another example, this time a policy document.
```
    IOTPolicyAllowShadow:
      Type: AWS::IoT::Policy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: iot:Publish
              Resource:
                - { "Fn::Sub": "arn:aws:iot:us-east-1:${AWS::AccountId}:topic/$aws/things/${!iot:Connection.Thing.ThingName}/shadow/update" }
                - { "Fn::Sub": "arn:aws:iot:us-east-1:${AWS::AccountId}:topic/$aws/things/${!iot:Connection.Thing.ThingName}/shadow/get" }
                - { "Fn::Sub": "arn:aws:iot:us-east-1:${AWS::AccountId}:topic/${!iot:Connection.Thing.ThingName}/*" }
            - Effect: Allow
              Action: iot:Receive
              Resource: { "Fn::Sub": "arn:aws:iot:us-east-1:${AWS::AccountId}:topic/$aws/things/${!iot:Connection.Thing.ThingName}/shadow/*" }
            - Effect: Allow
              Action: iot:Subscribe
              Resource: { "Fn::Sub": "arn:aws:iot:us-east-1:${AWS::AccountId}:topicfilter/$aws/things/${!iot:Connection.Thing.ThingName}/shadow/*" }
```
Here the `!` in the `${!iot:...}` is Cloudformation's way of escaping the substitutions in the `Fn::Sub` string. Other valid strings in policy documents include escaping a `*` by using `${*}` and a escaping a `$` by using `${$}`.
Any solution should not interfere with any of the above.

**Comment by eahefnawy** [comment]
@shortjared @azurelogic thanks a lot for your thorough input into this! 😊 

> So I guess we are asking for an improvement to at least handle AWS pseudo-params, we offered one solution but are open to anything that alleviates the pain point!

This is **exactly** why we added support for custom variable syntax, to solve this exact pain point. To give users complete flexibility when conflicts like that happen.

> We have applied this custom variable fix to at least 30 different projects and have to maintain it across all of those clients / projects.

I feel like this is the real issue you guys are facing, and I can see why having it in core would make things easier. However like @brianneisler said, that wouldn't be provider agnostic and would be too specific to aws. Do you have a common `varaibles.json/yml/js` file that is you often reuse in your projects? maybe this kind of organization would help there?

I just wrote a blog post about this recently, but I'm sure you're already familiar with that practice 😊 
https://serverless.com/blog/devops-serverless-variables/

**Comment by azurelogic** [comment]
Sorry again for the delay. I finally had a chance to circle back on this and discuss with @hauboldj.

@eahefnawy, we are familiar with the various tricks and techniques with the variables, but that still doesn't solve the problem of Serverless picking up variables that are not meant for it. As for the custom variable syntax, we're glad that it exists given the current issue, but anyone using Serverless and CloudFormation to do anything sufficiently advanced is going to hit this issue and have to solve the same problem all over again. That makes this an important problem to solve.

As we see it, there are 4 options that could resolve this:
1) Use and maintain our suggested syntax
2) Stop erroring on unrecognized variables. Instead, log the detected regex match and leave the variable intact
3) Switch to `$[...]` or `$<...>` style for Serverless variables
4) Add an escape syntax

Options 1 and 2 are the only ones that solve the problem *without breaking changes* for *currently working* Serverless projects. However, option 2 could cause disasters when users make mistakes.

Option 3 is massively breaking, but would be a very definitive fix. It would break every project so badly that I'd expect a major version number bump to accompany the change for sure.

Option 4, the escape syntax, seems potentially problematic. Existing Serverless projects could already contain the escape sequence, which would have unintended consequences when devs upgrade. Plus there are likely large implementation challenges. The default syntax would have to change so that it did not recognize the escape sequence. You would have to add a second phase where you strip the escape sequence. Also, you'd have to have a way to escape the escape sequence in case the escape character was needed right in front of a Serverless variable.

@shortjared, @hauboldj, any other thoughts?

**Comment by azurelogic** [comment]
As I was writing that last comment, I had an idea. @brianneisler, you mentioned this:

> Internally we discussed introducing a feature that would alert users when a bad variable was detected to help improve DX. I'm not sure that this change would allow us to accomplish that...

I'm not sure how you would want to implement this, but what if you had 2 regular expressions. One to detect actual variables and one to detect things that are "variable-like". Example:
variable syntax: `\${((env|self|opt|file|cf|s3)[:\(][ :a-zA-Z0-9._,\-\/\(\)]*?)}`
variable-like syntax: `\${.+}`
If a match is found on the variable-like syntax but not the variable syntax, you would notify the user. This could be added along side the custom variable syntax even, allowing users to add a custom "variable-like" syntax. You could also allow the user to decide whether to consider these types of mismatches are errors or just things to log.

That might be more complex than what you want to present to your users, but it still might be easier than trying to manage the escape syntax.

**Comment by horike37** [comment]
Closing this issue for now since it took for a long time without any activity.
Feel free to re-open if you want to restart working on this.

**Comment by erikerikson** [comment]
This is an old issue but as I was working on the variables system recently and the matter came up [on slack](https://serverless-contrib.slack.com/archives/C6ETEFWDT/p1518834603000091).

The use of custom `variableSyntax`es represents an ongoing risk and cost for users, their clients, and/or maintainers by creating a breaking change risk in the variables subsystem.

For example:
`variableSyntax: "\\${((opt|env|self|file)[ ~:a-zA-Z0-9._'\",\\-\\/\\(\\)]+?)}"`
Fails to identify the new `deep` variable type that allows the avoidance of deadlocks.

More broadly, any detection of existing internally known variable types has the problem that @brianneisler mentioned about typo detection.

However, there is a known set of variables that ought to be excluded.  For example, the list of AWS' [Pseudo Parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html).  As [dschep mentions](https://serverless-contrib.slack.com/archives/C6ETEFWDT/p1518882628000102) we could use a negative look ahead to avoid this but its problematic to do so in the generic context of the variables system because of the specificity and potential conflicts of providers.  Instead, we could query the provider for a RegEx that can identify variable strings to ignore (e.g. `/^AWS::.+$/`) and add a filter [to the results of this `map` call in the refactored Variables class](https://github.com/serverless/serverless/blob/bf5a8c9fd4a90946f1862e1837e6899b542d4cb2/lib/classes/Variables.js#L289).  This type of a fix would allow typo detection while enabling iterative discovery and fixing of additional scenarios where ignoring a variable is appropriate as each provider ecosystem evolves.  In the least it could reduce the surface area where a custom `variableSyntax` is necessary.

Anyway... seems like a potential solution to the constellation of concerns here, so here I am sharing it.

**Comment by DavidWells** [comment]
+1000 for supporting native AWS Pseudo Parameters without plugins

This was a design flaw that should be addressed by core framework

**Comment by erikerikson** [comment]
Heh.  Over the longer term, provider specific variables should probably end up being rendered by the provider implementation itself.  That is to say the proximal, `getValueFromCf`, `getValueFromS3`, and `getValueFromSsm` should migrate/be refactored into the AWS provider plugin.  Perhaps the addendum to my above would be that the "filtered" variables would have their values rendered/populated by the provider plugin.

**Pull request closed without merging**
