### PR TITLE
Fix packaging with files that contain dots as part of the name

### PR DESCRIPTION
**Pull request by crash7**
This ports a fix introduced to serverless-components: https://github.com/serverless-components/aws-lambda/pull/26 but given some changes in the test, it probably needs to be flagged as a breaking change.

Closes: #8125

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
> but given some changes in the test, it probably needs to be flagged as a breaking change.

@crash7 change looks good to me, still I don't think it's breaking. I believe files with dots in name were expected to be included, and it was a bug they weren't

Did you have any other concern in mind pointing that it should be marked as breaking?

**Comment by crash7** [comment]
> Did you have any other concern in mind pointing that it should be marked as breaking?

Just pointed that because codebases using just `**` to exclude all files won't work the same way after this change:

```
package:
  exclude:
    - '**'
  include:
    - src/handle.js
```

This fill include files with dots and also the handler file.

Those codebases will need to change the "exclude all" rule to `**/*` to make sure those dotted files are not included.

However I see what you mean, those files should have been included initially and they doesn't due to this bug, so maybe it's fine.

Thanks!

**Comment by medikoo** [comment]
@crash7 thanks for explanation.

Do you understand why handling of `**` and `**/*` differs? Is it `globby` package resolution quirk, or is this how global pattern handling is specified (if there's any specification) ?

**Comment by crash7** [comment]
@medikoo while trying to found a good answer to your question, I ended in doing a lot of digging and finding something else.

**Short version:** 
Let's try to upgrade to [`globby@v11`](https://github.com/sindresorhus/globby/releases/tag/v11.0.1), seems that one of its dependencies ([`picomatch`](https://github.com/micromatch/picomatch)) follows the globstar spec correctly.


**Long version:**
This problem affects `globby@v9.2.0`, which is the version `serverless` uses right now. Upgrading to `globby@>v10` seems to solve the problem (need to run all the tests)

That version of `globby` upgraded the lib that uses under the hood: `fast-glob` to v3. Testing this library in particular confirms that lower versions (specifically `fast-glob@v2.2.7`, which is the one that `globby@v9.2.0` uses) produces the same error with `**` but works fine with `**/*`.

In fact, `fast-glob@v3` introduced a lot of [breaking changes](https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0), one of them being the upgrade of `micromatch@v3` to `micromatch@v4`. Testing `micromatch@v3` produces the same behavior.

Unfortunately, the [changelog](https://github.com/micromatch/micromatch/blob/master/CHANGELOG.md#400---2019-03-20) for `micromatch@v4` doesn't tell me nothing.

On the other hand, `micromatch@v2` works fine too, so the problem was introduced in v3 and then solved again in v4. Checking the code closely, v3 added `nanomatch` but v4 removed it (and yes, nanomatch@latest produces the same behavior) and [switched to `picomatch`](https://github.com/micromatch/micromatch/commit/52df06d08c2cd41b8ded6f30a1d7e69dde89b8ca#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) witch is the one that apparently implements globstar correctly and works correctly just using `**`.

Hope you are not bored after reading all of this :joy:

**Comment by crash7** [comment]
@medikoo I updated the code to use latest version of globby, the breaking changes introduced in both v10 and v11 are related with libraries or other changes that doesn't have an impact in the API. I also found the we use `nanomatch` directly, which based in my previous investigation has a bug with files with dots, I replaced it with `micromatch`, which is the same library that `globby` is using right now. The API is the same as `nanomatch`, so the only change is the name of the function.

Also found that one of the tests in my initial commit was wrong, so I fixed that too.

Let me know what you think, thanks!

**Comment by medikoo** [comment]
@crash7 if you feel that upgrading `globby` to v11 will fix it. Feel free to do it, and rebase the PR against [`v2`](https://github.com/serverless/serverless/tree/v2) branch.

We're planning to release v2 next week.

That'll probably be best approach to that (as anyway with v2 we plan to upgrade all dependencies)

**Comment by crash7** [comment]
@medikoo upgrading globby and replacing nanomatch fixed it (https://github.com/serverless/serverless/pull/8130/commits/e297d829b3c3c091c1e28587ac097bf000ef20bf) but the CI check for node6 failed, that's why I reverted the changes.

I don't mind rebasing this against v2 if you are planning to release the stable version soon, as long as I can use a `next` version in my project, I don't care for now.

**Comment by medikoo** [comment]
> @medikoo upgrading globby and replacing nanomatch fixed it (e297d82) but the CI check for node6 failed, that's why I reverted the changes.

That's clear. In v1 we need to maintain support for Node.js v6, so it's a no go. With v2 we drop support for Node.js v6 and v8 and branch has already a CI update to test against those versions.

> I don't mind rebasing this against v2 if you are planning to release the stable version soon, as long as I can use a next version in my project, I don't care for now.

It'll be released next week, and it contains few minor (but breaking changes). Check the milestone that outlines them: https://github.com/serverless/serverless/milestone/82

If you do not see any deprecation logs during deployment it means you'll be able to upgrade right away

**Comment by crash7** [comment]
@medikoo just rebased with `v2` and changed the base for this PR - all node tests passed :)

>It'll be released next week, and it contains few minor (but breaking changes). Check the milestone that outlines them: https://github.com/serverless/serverless/milestone/82

Let me know if you need a hand with something from that milestone.

**Review by medikoo — APPROVED** [review]
Thank you!

**Comment by medikoo** [comment]
> Let me know if you need a hand with something from that milestone.

@crash7 We appreciate help with any marked by _help wanted_ label, here: https://github.com/serverless/serverless/milestone/82

**Pull request merged**
