### PR TITLE
CosmosDB documentation: Show how to set http out

### PR DESCRIPTION
**Pull request by kereslas**
If you follow the example, requests to http endpoints always returns "204 No Content", independently of the status you set in "context.res". This is because the function.json generated doesn't has the output binding:

   {
      "type": "http",
      "direction": "out",
      "name": "res"
    }

This only happens if you combine http and cosmosDB events. Only with http and without cosmosDB, it works fine (only setting the first event without the http out event). Maybe is a bug, because with cosmosdb event, http event works in a different way than without.

It is necessary to set the http out event explicitly to work. This way you can return 201, 400, or whatever you need (and with the resulting json in the body if you want).

This occurs with other endpoints like GET too.

## What did you implement

Event and code added to the example

## How can we verify it

Create a function with the example code

## Todos

<details>
<summary>Useful Scripts</summary>

- `npm run test:ci` --> Run all validation checks on proposed changes
- `npm run lint:updated` --> Lint all the updated files
- `npm run lint:fix` --> Automatically fix lint problems (if possible)
- `npm run prettier-check:updated` --> Check if updated files adhere to Prettier config
- `npm run prettify:updated` --> Prettify all the updated files

</details>

- [ ] Write and run all tests
- [ ] Write documentation
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by medikoo** [comment]
@kereslas what is the status of this? Can you please fix Prettier issues, and re-assign me for review when you feel it's ready. Thank you!

**Comment by A-5ingh** [comment]
@medikoo I can help with this, what is pending in it ?

**Comment by medikoo** [comment]
@A-5ingh I believe it was purely about styling issues (so proposed changes match Prettier formatting).

Still now it also needs to be merged with master. 

Can you prepare updated version? If you cannot push to @kereslas branch it's fine if you propose another PR

**Comment by A-5ingh** [comment]
> @A-5ingh I believe it was purely about styling issues (so proposed changes match Prettier formatting).
> 
> Still now it also needs to be merged with master.
> 
> Can you prepare updated version? If you cannot push to @kereslas branch it's fine if you propose another PR

Hey @medikoo even after using the same prettier configuration settings mentioned in the eslint-config\prettier.config.js file. The formatting is getting failed in CI.
```
{
  endOfLine: 'lf',
  printWidth: 100,
  quoteProps: 'consistent',
  singleQuote: true,
  trailingComma: 'es5',
}
```
Can you please suggest to resolve it ?

**Comment by medikoo** [comment]
@A-5ingh please ensure that branch is up to date with https://github.com/serverless/serverless master. Note that you're using very old version with an old CI/CD setup. There's no way CI/CD will pass in such case

**Comment by A-5ingh** [comment]
@medikoo I forked it from serverless repository only and was working on master branch. But anyways, I have created a new PR - #8452. Please review it and let me know if it requires any further changes. Thanks :)

**Comment by medikoo** [comment]
Closing, as it was apparently well solved with https://github.com/serverless/serverless/pull/7765

I'm very sorry for confusion @A-5ingh

**Pull request closed without merging**
