### PR TITLE
AWS Lambda destinations support

### LINKED ISSUE #7007: AWS Lambda Destination
# AWS Lambda Destination

## Description

[AWS Lambda Destinations](https://aws.amazon.com/fr/blogs/compute/introducing-aws-lambda-destinations/) for asynchronous invocations. This is a feature that provides visibility into Lambda function invocations and routes the execution results to AWS services, simplifying event-driven applications and reducing code complexity.

I have already simply tried to add a cloudformation resource: 

```
functions:
  hello:
    handler: src/hello.handler
    events:
      - sqs:
          batchSize: 1
          arn: ${arn}

resources: # CloudFormation template syntax
  Resources:
    HelloLambdaFunction:
      Type: AWS::Lambda::EventInvokeConfig
      Properties:
          FunctionName: "hello"
          Qualifier: "$LATEST"
          MaximumEventAgeInSeconds: 600
          MaximumRetryAttempts: 0
          DestinationConfig:
              OnSuccess:
                  Destination: ${arn}
              OnFailure:
                  Destination: ${arn}
```

But i got this error: `Update of resource type is not permitted. The new template modifies resource type of the following resources: [HelloLambdaFunction]`

Yours sincerely.

### PR DESCRIPTION
**Pull request by medikoo**
Closes #7007 

Implements support of AWS Lambda destinations via `destinations` function property

### CODE REVIEW

**Comment by nicu-chiciuc** [comment]
@medikoo Great job on starting to implement this. Do you have any ETA or do you maybe need some help (I don't know the codebase but might try to take a look). Also in the interim, do you know if there's any way (even hacky way, or by using cloudformation directly) to add a destination to a function?

**Comment by medikoo** [comment]
@nicu-chiciuc I should follow with it shortly. Current estimate is, that it should be ready next week.

For now you can configure destination by extending `resources`, follow example in description of this issue: https://github.com/serverless/serverless/issues/7007

**Comment by fernando-mc** [comment]
@medikoo Tested this out, config options look solid and it worked great.

**Comment by medikoo** [comment]
> @medikoo Tested this out, config options look solid and it worked great.

Thanks @fernando-mc ! To have it really approved (and github status green) I need an actuall review approve :)

**Pull request merged**
